module Stripe.CustomerSession.Types.AccountUnificationAccountController where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_unification_account_controller
instance Show Account_unification_account_controller
instance Eq Account_unification_account_controller
instance Data.Aeson.FromJSON Account_unification_account_controller
instance Data.Aeson.ToJSON Account_unification_account_controller
data Account_unification_account_controllerRequirement_collection
instance Show Account_unification_account_controllerRequirement_collection
instance Eq Account_unification_account_controllerRequirement_collection
instance Data.Aeson.FromJSON Account_unification_account_controllerRequirement_collection
instance Data.Aeson.ToJSON Account_unification_account_controllerRequirement_collection
data Account_unification_account_controllerType
instance Show Account_unification_account_controllerType
instance Eq Account_unification_account_controllerType
instance Data.Aeson.FromJSON Account_unification_account_controllerType
instance Data.Aeson.ToJSON Account_unification_account_controllerType
