module Stripe.CustomerSession.Types.AccountUnificationAccountControllerStripeDashboard where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_unification_account_controller_stripe_dashboard
instance Show Account_unification_account_controller_stripe_dashboard
instance Eq Account_unification_account_controller_stripe_dashboard
instance Data.Aeson.FromJSON Account_unification_account_controller_stripe_dashboard
instance Data.Aeson.ToJSON Account_unification_account_controller_stripe_dashboard
data Account_unification_account_controller_stripe_dashboardType
instance Show Account_unification_account_controller_stripe_dashboardType
instance Eq Account_unification_account_controller_stripe_dashboardType
instance Data.Aeson.FromJSON Account_unification_account_controller_stripe_dashboardType
instance Data.Aeson.ToJSON Account_unification_account_controller_stripe_dashboardType
