module Stripe.CustomerSession.Types.AccountUnificationAccountControllerLosses where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_unification_account_controller_losses
instance Show Account_unification_account_controller_losses
instance Eq Account_unification_account_controller_losses
instance Data.Aeson.FromJSON Account_unification_account_controller_losses
instance Data.Aeson.ToJSON Account_unification_account_controller_losses
data Account_unification_account_controller_lossesPayments
instance Show Account_unification_account_controller_lossesPayments
instance Eq Account_unification_account_controller_lossesPayments
instance Data.Aeson.FromJSON Account_unification_account_controller_lossesPayments
instance Data.Aeson.ToJSON Account_unification_account_controller_lossesPayments
