module Stripe.CustomerSession.Types.AccountBusinessProfile where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_business_profile
instance Show Account_business_profile
instance Eq Account_business_profile
instance Data.Aeson.FromJSON Account_business_profile
instance Data.Aeson.ToJSON Account_business_profile
data Account_business_profileAnnual_revenueNonNullable
instance Show Account_business_profileAnnual_revenueNonNullable
instance Eq Account_business_profileAnnual_revenueNonNullable
instance Data.Aeson.FromJSON Account_business_profileAnnual_revenueNonNullable
instance Data.Aeson.ToJSON Account_business_profileAnnual_revenueNonNullable
data Account_business_profileMinority_owned_business_designationNonNullable
instance Show Account_business_profileMinority_owned_business_designationNonNullable
instance Eq Account_business_profileMinority_owned_business_designationNonNullable
instance Data.Aeson.FromJSON Account_business_profileMinority_owned_business_designationNonNullable
instance Data.Aeson.ToJSON Account_business_profileMinority_owned_business_designationNonNullable
data Account_business_profileSupport_addressNonNullable
instance Show Account_business_profileSupport_addressNonNullable
instance Eq Account_business_profileSupport_addressNonNullable
instance Data.Aeson.FromJSON Account_business_profileSupport_addressNonNullable
instance Data.Aeson.ToJSON Account_business_profileSupport_addressNonNullable
