module Stripe.CustomerSession.Types.AccountBacsDebitPaymentsSettings where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_bacs_debit_payments_settings
instance Show Account_bacs_debit_payments_settings
instance Eq Account_bacs_debit_payments_settings
instance Data.Aeson.FromJSON Account_bacs_debit_payments_settings
instance Data.Aeson.ToJSON Account_bacs_debit_payments_settings
