module Stripe.CustomerSession.Types.AccountBrandingSettings where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_branding_settings
instance Show Account_branding_settings
instance Eq Account_branding_settings
instance Data.Aeson.FromJSON Account_branding_settings
instance Data.Aeson.ToJSON Account_branding_settings
data Account_branding_settingsIconNonNullableVariants
instance Show Account_branding_settingsIconNonNullableVariants
instance Eq Account_branding_settingsIconNonNullableVariants
instance Data.Aeson.FromJSON Account_branding_settingsIconNonNullableVariants
instance Data.Aeson.ToJSON Account_branding_settingsIconNonNullableVariants
data Account_branding_settingsLogoNonNullableVariants
instance Show Account_branding_settingsLogoNonNullableVariants
instance Eq Account_branding_settingsLogoNonNullableVariants
instance Data.Aeson.FromJSON Account_branding_settingsLogoNonNullableVariants
instance Data.Aeson.ToJSON Account_branding_settingsLogoNonNullableVariants
