module Stripe.CustomerSession.Types.AccountUnificationAccountControllerFees where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_unification_account_controller_fees
instance Show Account_unification_account_controller_fees
instance Eq Account_unification_account_controller_fees
instance Data.Aeson.FromJSON Account_unification_account_controller_fees
instance Data.Aeson.ToJSON Account_unification_account_controller_fees
data Account_unification_account_controller_feesPayer
instance Show Account_unification_account_controller_feesPayer
instance Eq Account_unification_account_controller_feesPayer
instance Data.Aeson.FromJSON Account_unification_account_controller_feesPayer
instance Data.Aeson.ToJSON Account_unification_account_controller_feesPayer
