module Stripe.CustomerSession.Types.AccountBusinessProfile where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_business_profile
instance Show Account_business_profile
instance Eq Account_business_profile
instance Data.Aeson.FromJSON Account_business_profile
instance Data.Aeson.ToJSON Account_business_profile
data Account_business_profileAnnual_revenue
instance Show Account_business_profileAnnual_revenue
instance Eq Account_business_profileAnnual_revenue
instance Data.Aeson.FromJSON Account_business_profileAnnual_revenue
instance Data.Aeson.ToJSON Account_business_profileAnnual_revenue
data Account_business_profileSupport_address
instance Show Account_business_profileSupport_address
instance Eq Account_business_profileSupport_address
instance Data.Aeson.FromJSON Account_business_profileSupport_address
instance Data.Aeson.ToJSON Account_business_profileSupport_address
