module Stripe.CustomerSession.Types.AccountInvoicesSettings where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_invoices_settings
instance Show Account_invoices_settings
instance Eq Account_invoices_settings
instance Data.Aeson.FromJSON Account_invoices_settings
instance Data.Aeson.ToJSON Account_invoices_settings
data Account_invoices_settingsDefault_account_tax_idsVariants
instance Show Account_invoices_settingsDefault_account_tax_idsVariants
instance Eq Account_invoices_settingsDefault_account_tax_idsVariants
instance Data.Aeson.FromJSON Account_invoices_settingsDefault_account_tax_idsVariants
instance Data.Aeson.ToJSON Account_invoices_settingsDefault_account_tax_idsVariants
