module Stripe.CustomerSession.Types.AmazonPayUnderlyingPaymentMethodFundingDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Amazon_pay_underlying_payment_method_funding_details
instance Show Amazon_pay_underlying_payment_method_funding_details
instance Eq Amazon_pay_underlying_payment_method_funding_details
instance Data.Aeson.FromJSON Amazon_pay_underlying_payment_method_funding_details
instance Data.Aeson.ToJSON Amazon_pay_underlying_payment_method_funding_details
