module Stripe.CustomerSession.Types.AutomaticTax where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Automatic_tax
instance Show Automatic_tax
instance Eq Automatic_tax
instance Data.Aeson.FromJSON Automatic_tax
instance Data.Aeson.ToJSON Automatic_tax
data Automatic_taxDisabled_reasonNonNullable
instance Show Automatic_taxDisabled_reasonNonNullable
instance Eq Automatic_taxDisabled_reasonNonNullable
instance Data.Aeson.FromJSON Automatic_taxDisabled_reasonNonNullable
instance Data.Aeson.ToJSON Automatic_taxDisabled_reasonNonNullable
data Automatic_taxLiabilityNonNullable
instance Show Automatic_taxLiabilityNonNullable
instance Eq Automatic_taxLiabilityNonNullable
instance Data.Aeson.FromJSON Automatic_taxLiabilityNonNullable
instance Data.Aeson.ToJSON Automatic_taxLiabilityNonNullable
data Automatic_taxLiabilityNonNullableAccountVariants
instance Show Automatic_taxLiabilityNonNullableAccountVariants
instance Eq Automatic_taxLiabilityNonNullableAccountVariants
instance Data.Aeson.FromJSON Automatic_taxLiabilityNonNullableAccountVariants
instance Data.Aeson.ToJSON Automatic_taxLiabilityNonNullableAccountVariants
data Automatic_taxLiabilityNonNullableType
instance Show Automatic_taxLiabilityNonNullableType
instance Eq Automatic_taxLiabilityNonNullableType
instance Data.Aeson.FromJSON Automatic_taxLiabilityNonNullableType
instance Data.Aeson.ToJSON Automatic_taxLiabilityNonNullableType
data Automatic_taxStatusNonNullable
instance Show Automatic_taxStatusNonNullable
instance Eq Automatic_taxStatusNonNullable
instance Data.Aeson.FromJSON Automatic_taxStatusNonNullable
instance Data.Aeson.ToJSON Automatic_taxStatusNonNullable
