module Stripe.CustomerSession.Types.AutomaticTax where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Automatic_tax
instance Show Automatic_tax
instance Eq Automatic_tax
instance Data.Aeson.FromJSON Automatic_tax
instance Data.Aeson.ToJSON Automatic_tax
data Automatic_taxLiability
instance Show Automatic_taxLiability
instance Eq Automatic_taxLiability
instance Data.Aeson.FromJSON Automatic_taxLiability
instance Data.Aeson.ToJSON Automatic_taxLiability
data Automatic_taxLiabilityAccountVariants
instance Show Automatic_taxLiabilityAccountVariants
instance Eq Automatic_taxLiabilityAccountVariants
instance Data.Aeson.FromJSON Automatic_taxLiabilityAccountVariants
instance Data.Aeson.ToJSON Automatic_taxLiabilityAccountVariants
