module Stripe.CustomerSession.Types.BalanceTransaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Balance_transaction
instance Show Balance_transaction
instance Eq Balance_transaction
instance Data.Aeson.FromJSON Balance_transaction
instance Data.Aeson.ToJSON Balance_transaction
data Balance_transactionBalance_type
instance Show Balance_transactionBalance_type
instance Eq Balance_transactionBalance_type
instance Data.Aeson.FromJSON Balance_transactionBalance_type
instance Data.Aeson.ToJSON Balance_transactionBalance_type
data Balance_transactionSourceNonNullableVariants
instance Show Balance_transactionSourceNonNullableVariants
instance Eq Balance_transactionSourceNonNullableVariants
instance Data.Aeson.FromJSON Balance_transactionSourceNonNullableVariants
instance Data.Aeson.ToJSON Balance_transactionSourceNonNullableVariants
data Balance_transactionType
instance Show Balance_transactionType
instance Eq Balance_transactionType
instance Data.Aeson.FromJSON Balance_transactionType
instance Data.Aeson.ToJSON Balance_transactionType
