module Stripe.CustomerSession.Types.BankAccount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Bank_account
instance Show Bank_account
instance Eq Bank_account
instance Data.Aeson.FromJSON Bank_account
instance Data.Aeson.ToJSON Bank_account
data Bank_accountAccountNonNullableVariants
instance Show Bank_accountAccountNonNullableVariants
instance Eq Bank_accountAccountNonNullableVariants
instance Data.Aeson.FromJSON Bank_accountAccountNonNullableVariants
instance Data.Aeson.ToJSON Bank_accountAccountNonNullableVariants
data Bank_accountAvailable_payout_methodsNonNullable
instance Show Bank_accountAvailable_payout_methodsNonNullable
instance Eq Bank_accountAvailable_payout_methodsNonNullable
instance Data.Aeson.FromJSON Bank_accountAvailable_payout_methodsNonNullable
instance Data.Aeson.ToJSON Bank_accountAvailable_payout_methodsNonNullable
data Bank_accountCustomerNonNullableVariants
instance Show Bank_accountCustomerNonNullableVariants
instance Eq Bank_accountCustomerNonNullableVariants
instance Data.Aeson.FromJSON Bank_accountCustomerNonNullableVariants
instance Data.Aeson.ToJSON Bank_accountCustomerNonNullableVariants
data Bank_accountFuture_requirementsNonNullable
instance Show Bank_accountFuture_requirementsNonNullable
instance Eq Bank_accountFuture_requirementsNonNullable
instance Data.Aeson.FromJSON Bank_accountFuture_requirementsNonNullable
instance Data.Aeson.ToJSON Bank_accountFuture_requirementsNonNullable
data Bank_accountRequirementsNonNullable
instance Show Bank_accountRequirementsNonNullable
instance Eq Bank_accountRequirementsNonNullable
instance Data.Aeson.FromJSON Bank_accountRequirementsNonNullable
instance Data.Aeson.ToJSON Bank_accountRequirementsNonNullable
