module Stripe.CustomerSession.Types.BillingBillResourceInvoicingTaxesTaxRateDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_taxes_tax_rate_details
instance Show Billing_bill_resource_invoicing_taxes_tax_rate_details
instance Eq Billing_bill_resource_invoicing_taxes_tax_rate_details
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_taxes_tax_rate_details
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_taxes_tax_rate_details
