module Stripe.CustomerSession.Types.BillingBillResourceInvoicingLinesCommonProrationDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_lines_common_proration_details
instance Show Billing_bill_resource_invoicing_lines_common_proration_details
instance Eq Billing_bill_resource_invoicing_lines_common_proration_details
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_common_proration_details
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_common_proration_details
data Billing_bill_resource_invoicing_lines_common_proration_detailsCredited_itemsNonNullable
instance Show Billing_bill_resource_invoicing_lines_common_proration_detailsCredited_itemsNonNullable
instance Eq Billing_bill_resource_invoicing_lines_common_proration_detailsCredited_itemsNonNullable
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_common_proration_detailsCredited_itemsNonNullable
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_common_proration_detailsCredited_itemsNonNullable
