module Stripe.CustomerSession.Types.BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullable
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullable
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullable
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullable
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullable
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullableProration_detailsNonNullable
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullableProration_detailsNonNullable
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullableProration_detailsNonNullable
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullableProration_detailsNonNullable
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullableProration_detailsNonNullable
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullable
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullable
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullable
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullable
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullable
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullableProration_detailsNonNullable
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullableProration_detailsNonNullable
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullableProration_detailsNonNullable
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullableProration_detailsNonNullable
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullableProration_detailsNonNullable
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentType
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentType
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentType
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentType
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentType
