module Stripe.CustomerSession.Types.BillingBillResourceInvoicingTaxesTax where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_taxes_tax
instance Show Billing_bill_resource_invoicing_taxes_tax
instance Eq Billing_bill_resource_invoicing_taxes_tax
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_taxes_tax
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_taxes_tax
data Billing_bill_resource_invoicing_taxes_taxTax_behavior
instance Show Billing_bill_resource_invoicing_taxes_taxTax_behavior
instance Eq Billing_bill_resource_invoicing_taxes_taxTax_behavior
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_taxes_taxTax_behavior
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_taxes_taxTax_behavior
data Billing_bill_resource_invoicing_taxes_taxTax_rate_detailsNonNullable
instance Show Billing_bill_resource_invoicing_taxes_taxTax_rate_detailsNonNullable
instance Eq Billing_bill_resource_invoicing_taxes_taxTax_rate_detailsNonNullable
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_taxes_taxTax_rate_detailsNonNullable
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_taxes_taxTax_rate_detailsNonNullable
data Billing_bill_resource_invoicing_taxes_taxTaxability_reason
instance Show Billing_bill_resource_invoicing_taxes_taxTaxability_reason
instance Eq Billing_bill_resource_invoicing_taxes_taxTaxability_reason
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_taxes_taxTaxability_reason
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_taxes_taxTaxability_reason
