module Stripe.CustomerSession.Types.BillingCreditGrantsResourceBalanceDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_credit_grants_resource_balance_debit
instance Show Billing_credit_grants_resource_balance_debit
instance Eq Billing_credit_grants_resource_balance_debit
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_debit
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_debit
data Billing_credit_grants_resource_balance_debitCredits_appliedNonNullable
instance Show Billing_credit_grants_resource_balance_debitCredits_appliedNonNullable
instance Eq Billing_credit_grants_resource_balance_debitCredits_appliedNonNullable
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_debitCredits_appliedNonNullable
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_debitCredits_appliedNonNullable
data Billing_credit_grants_resource_balance_debitCredits_appliedNonNullableInvoiceVariants
instance Show Billing_credit_grants_resource_balance_debitCredits_appliedNonNullableInvoiceVariants
instance Eq Billing_credit_grants_resource_balance_debitCredits_appliedNonNullableInvoiceVariants
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_debitCredits_appliedNonNullableInvoiceVariants
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_debitCredits_appliedNonNullableInvoiceVariants
data Billing_credit_grants_resource_balance_debitType
instance Show Billing_credit_grants_resource_balance_debitType
instance Eq Billing_credit_grants_resource_balance_debitType
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_debitType
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_debitType
