module Stripe.CustomerSession.Types.BillingBillResourceInvoicingLinesParentsInvoiceLineItemSubscriptionItemParent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parent
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parent
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parent
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parent
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parent
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parentProration_details
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parentProration_details
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parentProration_details
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parentProration_details
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parentProration_details
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parentProration_detailsCredited_items
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parentProration_detailsCredited_items
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parentProration_detailsCredited_items
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parentProration_detailsCredited_items
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_subscription_item_parentProration_detailsCredited_items
