module Stripe.CustomerSession.Types.BillingBillResourceInvoicingLinesParentsInvoiceLineItemInvoiceItemParent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parent
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parent
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parent
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parent
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parent
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parentProration_detailsNonNullable
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parentProration_detailsNonNullable
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parentProration_detailsNonNullable
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parentProration_detailsNonNullable
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parentProration_detailsNonNullable
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parentProration_detailsNonNullableCredited_itemsNonNullable
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parentProration_detailsNonNullableCredited_itemsNonNullable
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parentProration_detailsNonNullableCredited_itemsNonNullable
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parentProration_detailsNonNullableCredited_itemsNonNullable
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_invoice_item_parentProration_detailsNonNullableCredited_itemsNonNullable
