module Stripe.CustomerSession.Types.BillingCreditGrantsResourceScope where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_credit_grants_resource_scope
instance Show Billing_credit_grants_resource_scope
instance Eq Billing_credit_grants_resource_scope
instance Data.Aeson.FromJSON Billing_credit_grants_resource_scope
instance Data.Aeson.ToJSON Billing_credit_grants_resource_scope
