module Stripe.CustomerSession.Types.BillingCreditGrantsResourceBalanceCreditsApplied where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_credit_grants_resource_balance_credits_applied
instance Show Billing_credit_grants_resource_balance_credits_applied
instance Eq Billing_credit_grants_resource_balance_credits_applied
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_credits_applied
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_credits_applied
data Billing_credit_grants_resource_balance_credits_appliedInvoiceVariants
instance Show Billing_credit_grants_resource_balance_credits_appliedInvoiceVariants
instance Eq Billing_credit_grants_resource_balance_credits_appliedInvoiceVariants
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_credits_appliedInvoiceVariants
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_credits_appliedInvoiceVariants
