module Stripe.CustomerSession.Types.BillingCreditGrantsResourceBalanceCredit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_credit_grants_resource_balance_credit
instance Show Billing_credit_grants_resource_balance_credit
instance Eq Billing_credit_grants_resource_balance_credit
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_credit
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_credit
data Billing_credit_grants_resource_balance_creditCredits_application_invoice_voided
instance Show Billing_credit_grants_resource_balance_creditCredits_application_invoice_voided
instance Eq Billing_credit_grants_resource_balance_creditCredits_application_invoice_voided
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_creditCredits_application_invoice_voided
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_creditCredits_application_invoice_voided
data Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedInvoiceVariants
instance Show Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedInvoiceVariants
instance Eq Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedInvoiceVariants
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedInvoiceVariants
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedInvoiceVariants
