module Stripe.CustomerSession.Types.BillingCreditGrantsResourceBalanceCredit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_credit_grants_resource_balance_credit
instance Show Billing_credit_grants_resource_balance_credit
instance Eq Billing_credit_grants_resource_balance_credit
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_credit
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_credit
data Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedNonNullable
instance Show Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedNonNullable
instance Eq Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedNonNullable
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedNonNullable
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedNonNullable
data Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedNonNullableInvoiceVariants
instance Show Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedNonNullableInvoiceVariants
instance Eq Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedNonNullableInvoiceVariants
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedNonNullableInvoiceVariants
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_creditCredits_application_invoice_voidedNonNullableInvoiceVariants
data Billing_credit_grants_resource_balance_creditType
instance Show Billing_credit_grants_resource_balance_creditType
instance Eq Billing_credit_grants_resource_balance_creditType
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_creditType
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_creditType
