module Stripe.CustomerSession.Types.BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_credit_grants_resource_balance_credits_application_invoice_voided
instance Show Billing_credit_grants_resource_balance_credits_application_invoice_voided
instance Eq Billing_credit_grants_resource_balance_credits_application_invoice_voided
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_credits_application_invoice_voided
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_credits_application_invoice_voided
data Billing_credit_grants_resource_balance_credits_application_invoice_voidedInvoiceVariants
instance Show Billing_credit_grants_resource_balance_credits_application_invoice_voidedInvoiceVariants
instance Eq Billing_credit_grants_resource_balance_credits_application_invoice_voidedInvoiceVariants
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_credits_application_invoice_voidedInvoiceVariants
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_credits_application_invoice_voidedInvoiceVariants
