module Stripe.CustomerSession.Types.BillingClocksResourceStatusDetailsStatusDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_clocks_resource_status_details_status_details
instance Show Billing_clocks_resource_status_details_status_details
instance Eq Billing_clocks_resource_status_details_status_details
instance Data.Aeson.FromJSON Billing_clocks_resource_status_details_status_details
instance Data.Aeson.ToJSON Billing_clocks_resource_status_details_status_details
