module Stripe.CustomerSession.Types.BillingCreditGrantsResourceApplicabilityConfig where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_credit_grants_resource_applicability_config
instance Show Billing_credit_grants_resource_applicability_config
instance Eq Billing_credit_grants_resource_applicability_config
instance Data.Aeson.FromJSON Billing_credit_grants_resource_applicability_config
instance Data.Aeson.ToJSON Billing_credit_grants_resource_applicability_config
