module Stripe.CustomerSession.Types.Billing_CreditBalanceTransaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing'credit_balance_transaction
instance Show Billing'credit_balance_transaction
instance Eq Billing'credit_balance_transaction
instance Data.Aeson.FromJSON Billing'credit_balance_transaction
instance Data.Aeson.ToJSON Billing'credit_balance_transaction
data Billing'credit_balance_transactionCreditNonNullable
instance Show Billing'credit_balance_transactionCreditNonNullable
instance Eq Billing'credit_balance_transactionCreditNonNullable
instance Data.Aeson.FromJSON Billing'credit_balance_transactionCreditNonNullable
instance Data.Aeson.ToJSON Billing'credit_balance_transactionCreditNonNullable
data Billing'credit_balance_transactionCreditNonNullableCredits_application_invoice_voidedNonNullable
instance Show Billing'credit_balance_transactionCreditNonNullableCredits_application_invoice_voidedNonNullable
instance Eq Billing'credit_balance_transactionCreditNonNullableCredits_application_invoice_voidedNonNullable
instance Data.Aeson.FromJSON Billing'credit_balance_transactionCreditNonNullableCredits_application_invoice_voidedNonNullable
instance Data.Aeson.ToJSON Billing'credit_balance_transactionCreditNonNullableCredits_application_invoice_voidedNonNullable
data Billing'credit_balance_transactionCreditNonNullableCredits_application_invoice_voidedNonNullableInvoiceVariants
instance Show Billing'credit_balance_transactionCreditNonNullableCredits_application_invoice_voidedNonNullableInvoiceVariants
instance Eq Billing'credit_balance_transactionCreditNonNullableCredits_application_invoice_voidedNonNullableInvoiceVariants
instance Data.Aeson.FromJSON Billing'credit_balance_transactionCreditNonNullableCredits_application_invoice_voidedNonNullableInvoiceVariants
instance Data.Aeson.ToJSON Billing'credit_balance_transactionCreditNonNullableCredits_application_invoice_voidedNonNullableInvoiceVariants
data Billing'credit_balance_transactionCreditNonNullableType
instance Show Billing'credit_balance_transactionCreditNonNullableType
instance Eq Billing'credit_balance_transactionCreditNonNullableType
instance Data.Aeson.FromJSON Billing'credit_balance_transactionCreditNonNullableType
instance Data.Aeson.ToJSON Billing'credit_balance_transactionCreditNonNullableType
data Billing'credit_balance_transactionCredit_grantVariants
instance Show Billing'credit_balance_transactionCredit_grantVariants
instance Eq Billing'credit_balance_transactionCredit_grantVariants
instance Data.Aeson.FromJSON Billing'credit_balance_transactionCredit_grantVariants
instance Data.Aeson.ToJSON Billing'credit_balance_transactionCredit_grantVariants
data Billing'credit_balance_transactionDebitNonNullable
instance Show Billing'credit_balance_transactionDebitNonNullable
instance Eq Billing'credit_balance_transactionDebitNonNullable
instance Data.Aeson.FromJSON Billing'credit_balance_transactionDebitNonNullable
instance Data.Aeson.ToJSON Billing'credit_balance_transactionDebitNonNullable
data Billing'credit_balance_transactionDebitNonNullableCredits_appliedNonNullable
instance Show Billing'credit_balance_transactionDebitNonNullableCredits_appliedNonNullable
instance Eq Billing'credit_balance_transactionDebitNonNullableCredits_appliedNonNullable
instance Data.Aeson.FromJSON Billing'credit_balance_transactionDebitNonNullableCredits_appliedNonNullable
instance Data.Aeson.ToJSON Billing'credit_balance_transactionDebitNonNullableCredits_appliedNonNullable
data Billing'credit_balance_transactionDebitNonNullableCredits_appliedNonNullableInvoiceVariants
instance Show Billing'credit_balance_transactionDebitNonNullableCredits_appliedNonNullableInvoiceVariants
instance Eq Billing'credit_balance_transactionDebitNonNullableCredits_appliedNonNullableInvoiceVariants
instance Data.Aeson.FromJSON Billing'credit_balance_transactionDebitNonNullableCredits_appliedNonNullableInvoiceVariants
instance Data.Aeson.ToJSON Billing'credit_balance_transactionDebitNonNullableCredits_appliedNonNullableInvoiceVariants
data Billing'credit_balance_transactionDebitNonNullableType
instance Show Billing'credit_balance_transactionDebitNonNullableType
instance Eq Billing'credit_balance_transactionDebitNonNullableType
instance Data.Aeson.FromJSON Billing'credit_balance_transactionDebitNonNullableType
instance Data.Aeson.ToJSON Billing'credit_balance_transactionDebitNonNullableType
data Billing'credit_balance_transactionTest_clockNonNullableVariants
instance Show Billing'credit_balance_transactionTest_clockNonNullableVariants
instance Eq Billing'credit_balance_transactionTest_clockNonNullableVariants
instance Data.Aeson.FromJSON Billing'credit_balance_transactionTest_clockNonNullableVariants
instance Data.Aeson.ToJSON Billing'credit_balance_transactionTest_clockNonNullableVariants
data Billing'credit_balance_transactionTypeNonNullable
instance Show Billing'credit_balance_transactionTypeNonNullable
instance Eq Billing'credit_balance_transactionTypeNonNullable
instance Data.Aeson.FromJSON Billing'credit_balance_transactionTypeNonNullable
instance Data.Aeson.ToJSON Billing'credit_balance_transactionTypeNonNullable
