module Stripe.CustomerSession.Types.CancellationDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Cancellation_details
instance Show Cancellation_details
instance Eq Cancellation_details
instance Data.Aeson.FromJSON Cancellation_details
instance Data.Aeson.ToJSON Cancellation_details
