module Stripe.CustomerSession.Types.Charge where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Charge
instance Show Charge
instance Eq Charge
instance Data.Aeson.FromJSON Charge
instance Data.Aeson.ToJSON Charge
data ChargeApplicationNonNullableVariants
instance Show ChargeApplicationNonNullableVariants
instance Eq ChargeApplicationNonNullableVariants
instance Data.Aeson.FromJSON ChargeApplicationNonNullableVariants
instance Data.Aeson.ToJSON ChargeApplicationNonNullableVariants
data ChargeApplication_feeNonNullableVariants
instance Show ChargeApplication_feeNonNullableVariants
instance Eq ChargeApplication_feeNonNullableVariants
instance Data.Aeson.FromJSON ChargeApplication_feeNonNullableVariants
instance Data.Aeson.ToJSON ChargeApplication_feeNonNullableVariants
data ChargeBalance_transactionNonNullableVariants
instance Show ChargeBalance_transactionNonNullableVariants
instance Eq ChargeBalance_transactionNonNullableVariants
instance Data.Aeson.FromJSON ChargeBalance_transactionNonNullableVariants
instance Data.Aeson.ToJSON ChargeBalance_transactionNonNullableVariants
data ChargeCustomerNonNullableVariants
instance Show ChargeCustomerNonNullableVariants
instance Eq ChargeCustomerNonNullableVariants
instance Data.Aeson.FromJSON ChargeCustomerNonNullableVariants
instance Data.Aeson.ToJSON ChargeCustomerNonNullableVariants
data ChargeFailure_balance_transactionNonNullableVariants
instance Show ChargeFailure_balance_transactionNonNullableVariants
instance Eq ChargeFailure_balance_transactionNonNullableVariants
instance Data.Aeson.FromJSON ChargeFailure_balance_transactionNonNullableVariants
instance Data.Aeson.ToJSON ChargeFailure_balance_transactionNonNullableVariants
data ChargeFraud_detailsNonNullable
instance Show ChargeFraud_detailsNonNullable
instance Eq ChargeFraud_detailsNonNullable
instance Data.Aeson.FromJSON ChargeFraud_detailsNonNullable
instance Data.Aeson.ToJSON ChargeFraud_detailsNonNullable
data ChargeOn_behalf_ofNonNullableVariants
instance Show ChargeOn_behalf_ofNonNullableVariants
instance Eq ChargeOn_behalf_ofNonNullableVariants
instance Data.Aeson.FromJSON ChargeOn_behalf_ofNonNullableVariants
instance Data.Aeson.ToJSON ChargeOn_behalf_ofNonNullableVariants
data ChargeOutcomeNonNullable
instance Show ChargeOutcomeNonNullable
instance Eq ChargeOutcomeNonNullable
instance Data.Aeson.FromJSON ChargeOutcomeNonNullable
instance Data.Aeson.ToJSON ChargeOutcomeNonNullable
data ChargeOutcomeNonNullableAdvice_codeNonNullable
instance Show ChargeOutcomeNonNullableAdvice_codeNonNullable
instance Eq ChargeOutcomeNonNullableAdvice_codeNonNullable
instance Data.Aeson.FromJSON ChargeOutcomeNonNullableAdvice_codeNonNullable
instance Data.Aeson.ToJSON ChargeOutcomeNonNullableAdvice_codeNonNullable
data ChargeOutcomeNonNullableRuleVariants
instance Show ChargeOutcomeNonNullableRuleVariants
instance Eq ChargeOutcomeNonNullableRuleVariants
instance Data.Aeson.FromJSON ChargeOutcomeNonNullableRuleVariants
instance Data.Aeson.ToJSON ChargeOutcomeNonNullableRuleVariants
data ChargePayment_intentNonNullableVariants
instance Show ChargePayment_intentNonNullableVariants
instance Eq ChargePayment_intentNonNullableVariants
instance Data.Aeson.FromJSON ChargePayment_intentNonNullableVariants
instance Data.Aeson.ToJSON ChargePayment_intentNonNullableVariants
data ChargePayment_method_detailsNonNullable
instance Show ChargePayment_method_detailsNonNullable
instance Eq ChargePayment_method_detailsNonNullable
instance Data.Aeson.FromJSON ChargePayment_method_detailsNonNullable
instance Data.Aeson.ToJSON ChargePayment_method_detailsNonNullable
data ChargeRefundsNonNullable
instance Show ChargeRefundsNonNullable
instance Eq ChargeRefundsNonNullable
instance Data.Aeson.FromJSON ChargeRefundsNonNullable
instance Data.Aeson.ToJSON ChargeRefundsNonNullable
data ChargeReviewNonNullableVariants
instance Show ChargeReviewNonNullableVariants
instance Eq ChargeReviewNonNullableVariants
instance Data.Aeson.FromJSON ChargeReviewNonNullableVariants
instance Data.Aeson.ToJSON ChargeReviewNonNullableVariants
data ChargeShippingNonNullable
instance Show ChargeShippingNonNullable
instance Eq ChargeShippingNonNullable
instance Data.Aeson.FromJSON ChargeShippingNonNullable
instance Data.Aeson.ToJSON ChargeShippingNonNullable
data ChargeSource_transferNonNullableVariants
instance Show ChargeSource_transferNonNullableVariants
instance Eq ChargeSource_transferNonNullableVariants
instance Data.Aeson.FromJSON ChargeSource_transferNonNullableVariants
instance Data.Aeson.ToJSON ChargeSource_transferNonNullableVariants
data ChargeStatus
instance Show ChargeStatus
instance Eq ChargeStatus
instance Data.Aeson.FromJSON ChargeStatus
instance Data.Aeson.ToJSON ChargeStatus
data ChargeTransferVariants
instance Show ChargeTransferVariants
instance Eq ChargeTransferVariants
instance Data.Aeson.FromJSON ChargeTransferVariants
instance Data.Aeson.ToJSON ChargeTransferVariants
data ChargeTransfer_dataNonNullable
instance Show ChargeTransfer_dataNonNullable
instance Eq ChargeTransfer_dataNonNullable
instance Data.Aeson.FromJSON ChargeTransfer_dataNonNullable
instance Data.Aeson.ToJSON ChargeTransfer_dataNonNullable
data ChargeTransfer_dataNonNullableDestinationVariants
instance Show ChargeTransfer_dataNonNullableDestinationVariants
instance Eq ChargeTransfer_dataNonNullableDestinationVariants
instance Data.Aeson.FromJSON ChargeTransfer_dataNonNullableDestinationVariants
instance Data.Aeson.ToJSON ChargeTransfer_dataNonNullableDestinationVariants
