module Stripe.CustomerSession.Types.CustomerBalanceCustomerBalanceSettings where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_balance_customer_balance_settings
instance Show Customer_balance_customer_balance_settings
instance Eq Customer_balance_customer_balance_settings
instance Data.Aeson.FromJSON Customer_balance_customer_balance_settings
instance Data.Aeson.ToJSON Customer_balance_customer_balance_settings
