module Stripe.CustomerSession.Types.CustomerBalanceResourceCashBalanceTransactionResourceFundedTransaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_balance_resource_cash_balance_transaction_resource_funded_transaction
instance Show Customer_balance_resource_cash_balance_transaction_resource_funded_transaction
instance Eq Customer_balance_resource_cash_balance_transaction_resource_funded_transaction
instance Data.Aeson.FromJSON Customer_balance_resource_cash_balance_transaction_resource_funded_transaction
instance Data.Aeson.ToJSON Customer_balance_resource_cash_balance_transaction_resource_funded_transaction
