module Stripe.CustomerSession.Types.CustomerTaxLocation where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_tax_location
instance Show Customer_tax_location
instance Eq Customer_tax_location
instance Data.Aeson.FromJSON Customer_tax_location
instance Data.Aeson.ToJSON Customer_tax_location
data Customer_tax_locationSource
instance Show Customer_tax_locationSource
instance Eq Customer_tax_locationSource
instance Data.Aeson.FromJSON Customer_tax_locationSource
instance Data.Aeson.ToJSON Customer_tax_locationSource
