module Stripe.CustomerSession.Types.CustomerBalanceResourceCashBalanceTransactionResourceUnappliedFromPaymentTransaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_balance_resource_cash_balance_transaction_resource_unapplied_from_payment_transaction
instance Show Customer_balance_resource_cash_balance_transaction_resource_unapplied_from_payment_transaction
instance Eq Customer_balance_resource_cash_balance_transaction_resource_unapplied_from_payment_transaction
instance Data.Aeson.FromJSON Customer_balance_resource_cash_balance_transaction_resource_unapplied_from_payment_transaction
instance Data.Aeson.ToJSON Customer_balance_resource_cash_balance_transaction_resource_unapplied_from_payment_transaction
data Customer_balance_resource_cash_balance_transaction_resource_unapplied_from_payment_transactionPayment_intentVariants
instance Show Customer_balance_resource_cash_balance_transaction_resource_unapplied_from_payment_transactionPayment_intentVariants
instance Eq Customer_balance_resource_cash_balance_transaction_resource_unapplied_from_payment_transactionPayment_intentVariants
instance Data.Aeson.FromJSON Customer_balance_resource_cash_balance_transaction_resource_unapplied_from_payment_transactionPayment_intentVariants
instance Data.Aeson.ToJSON Customer_balance_resource_cash_balance_transaction_resource_unapplied_from_payment_transactionPayment_intentVariants
