module Stripe.CustomerSession.Types.CustomerSessionResourceComponentsResourcePaymentElement where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_session_resource_components_resource_payment_element
instance Show Customer_session_resource_components_resource_payment_element
instance Eq Customer_session_resource_components_resource_payment_element
instance Data.Aeson.FromJSON Customer_session_resource_components_resource_payment_element
instance Data.Aeson.ToJSON Customer_session_resource_components_resource_payment_element
data Customer_session_resource_components_resource_payment_elementFeatures
instance Show Customer_session_resource_components_resource_payment_elementFeatures
instance Eq Customer_session_resource_components_resource_payment_elementFeatures
instance Data.Aeson.FromJSON Customer_session_resource_components_resource_payment_elementFeatures
instance Data.Aeson.ToJSON Customer_session_resource_components_resource_payment_elementFeatures
