module Stripe.CustomerSession.Types.CustomerBalanceResourceCashBalanceTransactionResourceRefundedFromPaymentTransaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_balance_resource_cash_balance_transaction_resource_refunded_from_payment_transaction
instance Show Customer_balance_resource_cash_balance_transaction_resource_refunded_from_payment_transaction
instance Eq Customer_balance_resource_cash_balance_transaction_resource_refunded_from_payment_transaction
instance Data.Aeson.FromJSON Customer_balance_resource_cash_balance_transaction_resource_refunded_from_payment_transaction
instance Data.Aeson.ToJSON Customer_balance_resource_cash_balance_transaction_resource_refunded_from_payment_transaction
data Customer_balance_resource_cash_balance_transaction_resource_refunded_from_payment_transactionRefundVariants
instance Show Customer_balance_resource_cash_balance_transaction_resource_refunded_from_payment_transactionRefundVariants
instance Eq Customer_balance_resource_cash_balance_transaction_resource_refunded_from_payment_transactionRefundVariants
instance Data.Aeson.FromJSON Customer_balance_resource_cash_balance_transaction_resource_refunded_from_payment_transactionRefundVariants
instance Data.Aeson.ToJSON Customer_balance_resource_cash_balance_transaction_resource_refunded_from_payment_transactionRefundVariants
