module Stripe.CustomerSession.Types.CustomerSessionResourceComponentsResourceCustomerSheetResourceFeatures where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_session_resource_components_resource_customer_sheet_resource_features
instance Show Customer_session_resource_components_resource_customer_sheet_resource_features
instance Eq Customer_session_resource_components_resource_customer_sheet_resource_features
instance Data.Aeson.FromJSON Customer_session_resource_components_resource_customer_sheet_resource_features
instance Data.Aeson.ToJSON Customer_session_resource_components_resource_customer_sheet_resource_features
