module Stripe.CustomerSession.Types.CustomerBalanceResourceCashBalanceTransactionResourceTransferredToBalance where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_balance_resource_cash_balance_transaction_resource_transferred_to_balance
instance Show Customer_balance_resource_cash_balance_transaction_resource_transferred_to_balance
instance Eq Customer_balance_resource_cash_balance_transaction_resource_transferred_to_balance
instance Data.Aeson.FromJSON Customer_balance_resource_cash_balance_transaction_resource_transferred_to_balance
instance Data.Aeson.ToJSON Customer_balance_resource_cash_balance_transaction_resource_transferred_to_balance
data Customer_balance_resource_cash_balance_transaction_resource_transferred_to_balanceBalance_transactionVariants
instance Show Customer_balance_resource_cash_balance_transaction_resource_transferred_to_balanceBalance_transactionVariants
instance Eq Customer_balance_resource_cash_balance_transaction_resource_transferred_to_balanceBalance_transactionVariants
instance Data.Aeson.FromJSON Customer_balance_resource_cash_balance_transaction_resource_transferred_to_balanceBalance_transactionVariants
instance Data.Aeson.ToJSON Customer_balance_resource_cash_balance_transaction_resource_transferred_to_balanceBalance_transactionVariants
