-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema CustomerSessionResourceComponentsResourcePaymentElement
module Stripe.CustomerSession.Types.CustomerSessionResourceComponentsResourcePaymentElement where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias
import {-# SOURCE #-} Stripe.CustomerSession.Types.CustomerSessionResourceComponentsResourcePaymentElementResourceFeatures

-- | Defines the object schema located at @components.schemas.customer_session_resource_components_resource_payment_element@ in the specification.
-- 
-- This hash contains whether the Payment Element is enabled and the features it supports.
data Customer_session_resource_components_resource_payment_element = Customer_session_resource_components_resource_payment_element {
  -- | enabled: Whether the Payment Element is enabled.
  customer_session_resource_components_resource_payment_elementEnabled :: GHC.Types.Bool
  -- | features: This hash defines whether the Payment Element supports certain features.
  , customer_session_resource_components_resource_payment_elementFeatures :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Customer_session_resource_components_resource_payment_elementFeaturesNonNullable))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Customer_session_resource_components_resource_payment_element
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["enabled" Data.Aeson.Types.ToJSON..= customer_session_resource_components_resource_payment_elementEnabled obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("features" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeatures obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["enabled" Data.Aeson.Types.ToJSON..= customer_session_resource_components_resource_payment_elementEnabled obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("features" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeatures obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Customer_session_resource_components_resource_payment_element
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Customer_session_resource_components_resource_payment_element" (\obj -> (GHC.Base.pure Customer_session_resource_components_resource_payment_element GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "enabled")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "features"))}
-- | Create a new 'Customer_session_resource_components_resource_payment_element' with all required fields.
mkCustomer_session_resource_components_resource_payment_element :: GHC.Types.Bool -- ^ 'customer_session_resource_components_resource_payment_elementEnabled'
  -> Customer_session_resource_components_resource_payment_element
mkCustomer_session_resource_components_resource_payment_element customer_session_resource_components_resource_payment_elementEnabled = Customer_session_resource_components_resource_payment_element{customer_session_resource_components_resource_payment_elementEnabled = customer_session_resource_components_resource_payment_elementEnabled,
                                                                                                                                                                                                     customer_session_resource_components_resource_payment_elementFeatures = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.customer_session_resource_components_resource_payment_element.properties.features.anyOf@ in the specification.
-- 
-- This hash defines whether the Payment Element supports certain features.
data Customer_session_resource_components_resource_payment_elementFeaturesNonNullable = Customer_session_resource_components_resource_payment_elementFeaturesNonNullable {
  -- | payment_method_allow_redisplay_filters: A list of [\`allow_redisplay\`](https:\/\/docs.stripe.com\/api\/payment_methods\/object\#payment_method_object-allow_redisplay) values that controls which saved payment methods the Payment Element displays by filtering to only show payment methods with an \`allow_redisplay\` value that is present in this list.
  -- 
  -- If not specified, defaults to [\"always\"]. In order to display all saved payment methods, specify [\"always\", \"limited\", \"unspecified\"].
  customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filters :: (GHC.Maybe.Maybe [Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filters])
  -- | payment_method_redisplay: Controls whether or not the Payment Element shows saved payment methods. This parameter defaults to \`disabled\`.
  , customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay :: (GHC.Maybe.Maybe Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay)
  -- | payment_method_redisplay_limit: Determines the max number of saved payment methods for the Payment Element to display. This parameter defaults to \`3\`. The maximum redisplay limit is \`10\`.
  , customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay_limit :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable GHC.Types.Int))
  -- | payment_method_remove: Controls whether the Payment Element displays the option to remove a saved payment method. This parameter defaults to \`disabled\`.
  -- 
  -- Allowing buyers to remove their saved payment methods impacts subscriptions that depend on that payment method. Removing the payment method detaches the [\`customer\` object](https:\/\/docs.stripe.com\/api\/payment_methods\/object\#payment_method_object-customer) from that [PaymentMethod](https:\/\/docs.stripe.com\/api\/payment_methods).
  , customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_remove :: (GHC.Maybe.Maybe Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_remove)
  -- | payment_method_save: Controls whether the Payment Element displays a checkbox offering to save a new payment method. This parameter defaults to \`disabled\`.
  -- 
  -- If a customer checks the box, the [\`allow_redisplay\`](https:\/\/docs.stripe.com\/api\/payment_methods\/object\#payment_method_object-allow_redisplay) value on the PaymentMethod is set to \`\'always\'\` at confirmation time. For PaymentIntents, the [\`setup_future_usage\`](https:\/\/docs.stripe.com\/api\/payment_intents\/object\#payment_intent_object-setup_future_usage) value is also set to the value defined in \`payment_method_save_usage\`.
  , customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save :: (GHC.Maybe.Maybe Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save)
  -- | payment_method_save_usage: When using PaymentIntents and the customer checks the save checkbox, this field determines the [\`setup_future_usage\`](https:\/\/docs.stripe.com\/api\/payment_intents\/object\#payment_intent_object-setup_future_usage) value used to confirm the PaymentIntent.
  -- 
  -- When using SetupIntents, directly configure the [\`usage\`](https:\/\/docs.stripe.com\/api\/setup_intents\/object\#setup_intent_object-usage) value on SetupIntent creation.
  , customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usage :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullable))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_allow_redisplay_filters" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filters obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_redisplay" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_redisplay_limit" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay_limit obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_remove" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_remove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_save" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_save_usage" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usage obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_allow_redisplay_filters" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filters obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_redisplay" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_redisplay_limit" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay_limit obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_remove" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_remove obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_save" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_save_usage" Data.Aeson.Types.ToJSON..=)) (customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usage obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Customer_session_resource_components_resource_payment_elementFeaturesNonNullable" (\obj -> (((((GHC.Base.pure Customer_session_resource_components_resource_payment_elementFeaturesNonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "payment_method_allow_redisplay_filters")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "payment_method_redisplay")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "payment_method_redisplay_limit")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "payment_method_remove")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "payment_method_save")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "payment_method_save_usage"))}
-- | Create a new 'Customer_session_resource_components_resource_payment_elementFeaturesNonNullable' with all required fields.
mkCustomer_session_resource_components_resource_payment_elementFeaturesNonNullable :: Customer_session_resource_components_resource_payment_elementFeaturesNonNullable
mkCustomer_session_resource_components_resource_payment_elementFeaturesNonNullable = Customer_session_resource_components_resource_payment_elementFeaturesNonNullable{customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filters = GHC.Maybe.Nothing,
                                                                                                                                                                      customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay = GHC.Maybe.Nothing,
                                                                                                                                                                      customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay_limit = GHC.Maybe.Nothing,
                                                                                                                                                                      customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_remove = GHC.Maybe.Nothing,
                                                                                                                                                                      customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save = GHC.Maybe.Nothing,
                                                                                                                                                                      customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usage = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.customer_session_resource_components_resource_payment_element.properties.features.anyOf.properties.payment_method_allow_redisplay_filters.items@ in the specification.
-- 
-- 
data Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filters =
   Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersEnumAlways -- ^ Represents the JSON value @"always"@
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersEnumLimited -- ^ Represents the JSON value @"limited"@
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersEnumUnspecified -- ^ Represents the JSON value @"unspecified"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filters
    where {toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersOther val) = val;
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersEnumAlways) = "always";
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersEnumLimited) = "limited";
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersEnumUnspecified) = "unspecified"}
instance Data.Aeson.Types.FromJSON.FromJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filters
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "always" -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersEnumAlways
                                             | val GHC.Classes.== "limited" -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersEnumLimited
                                             | val GHC.Classes.== "unspecified" -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersEnumUnspecified
                                             | GHC.Base.otherwise -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_allow_redisplay_filtersOther val)}
-- | Defines the enum schema located at @components.schemas.customer_session_resource_components_resource_payment_element.properties.features.anyOf.properties.payment_method_redisplay@ in the specification.
-- 
-- Controls whether or not the Payment Element shows saved payment methods. This parameter defaults to \`disabled\`.
data Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay =
   Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplayOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplayTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplayEnumDisabled -- ^ Represents the JSON value @"disabled"@
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplayEnumEnabled -- ^ Represents the JSON value @"enabled"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay
    where {toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplayOther val) = val;
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplayTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplayEnumDisabled) = "disabled";
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplayEnumEnabled) = "enabled"}
instance Data.Aeson.Types.FromJSON.FromJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplay
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "disabled" -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplayEnumDisabled
                                             | val GHC.Classes.== "enabled" -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplayEnumEnabled
                                             | GHC.Base.otherwise -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_redisplayOther val)}
-- | Defines the enum schema located at @components.schemas.customer_session_resource_components_resource_payment_element.properties.features.anyOf.properties.payment_method_remove@ in the specification.
-- 
-- Controls whether the Payment Element displays the option to remove a saved payment method. This parameter defaults to \`disabled\`.
-- 
-- Allowing buyers to remove their saved payment methods impacts subscriptions that depend on that payment method. Removing the payment method detaches the [\`customer\` object](https:\/\/docs.stripe.com\/api\/payment_methods\/object\#payment_method_object-customer) from that [PaymentMethod](https:\/\/docs.stripe.com\/api\/payment_methods).
data Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_remove =
   Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_removeOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_removeTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_removeEnumDisabled -- ^ Represents the JSON value @"disabled"@
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_removeEnumEnabled -- ^ Represents the JSON value @"enabled"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_remove
    where {toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_removeOther val) = val;
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_removeTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_removeEnumDisabled) = "disabled";
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_removeEnumEnabled) = "enabled"}
instance Data.Aeson.Types.FromJSON.FromJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_remove
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "disabled" -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_removeEnumDisabled
                                             | val GHC.Classes.== "enabled" -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_removeEnumEnabled
                                             | GHC.Base.otherwise -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_removeOther val)}
-- | Defines the enum schema located at @components.schemas.customer_session_resource_components_resource_payment_element.properties.features.anyOf.properties.payment_method_save@ in the specification.
-- 
-- Controls whether the Payment Element displays a checkbox offering to save a new payment method. This parameter defaults to \`disabled\`.
-- 
-- If a customer checks the box, the [\`allow_redisplay\`](https:\/\/docs.stripe.com\/api\/payment_methods\/object\#payment_method_object-allow_redisplay) value on the PaymentMethod is set to \`\'always\'\` at confirmation time. For PaymentIntents, the [\`setup_future_usage\`](https:\/\/docs.stripe.com\/api\/payment_intents\/object\#payment_intent_object-setup_future_usage) value is also set to the value defined in \`payment_method_save_usage\`.
data Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save =
   Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_saveOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_saveTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_saveEnumDisabled -- ^ Represents the JSON value @"disabled"@
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_saveEnumEnabled -- ^ Represents the JSON value @"enabled"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save
    where {toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_saveOther val) = val;
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_saveTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_saveEnumDisabled) = "disabled";
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_saveEnumEnabled) = "enabled"}
instance Data.Aeson.Types.FromJSON.FromJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "disabled" -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_saveEnumDisabled
                                             | val GHC.Classes.== "enabled" -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_saveEnumEnabled
                                             | GHC.Base.otherwise -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_saveOther val)}
-- | Defines the enum schema located at @components.schemas.customer_session_resource_components_resource_payment_element.properties.features.anyOf.properties.payment_method_save_usage@ in the specification.
-- 
-- When using PaymentIntents and the customer checks the save checkbox, this field determines the [\`setup_future_usage\`](https:\/\/docs.stripe.com\/api\/payment_intents\/object\#payment_intent_object-setup_future_usage) value used to confirm the PaymentIntent.
-- 
-- When using SetupIntents, directly configure the [\`usage\`](https:\/\/docs.stripe.com\/api\/setup_intents\/object\#setup_intent_object-usage) value on SetupIntent creation.
data Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullable =
   Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullableOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullableTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullableEnumOff_session -- ^ Represents the JSON value @"off_session"@
  | Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullableEnumOn_session -- ^ Represents the JSON value @"on_session"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullable
    where {toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullableOther val) = val;
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullableTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullableEnumOff_session) = "off_session";
           toJSON (Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullableEnumOn_session) = "on_session"}
instance Data.Aeson.Types.FromJSON.FromJSON Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullable
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "off_session" -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullableEnumOff_session
                                             | val GHC.Classes.== "on_session" -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullableEnumOn_session
                                             | GHC.Base.otherwise -> Customer_session_resource_components_resource_payment_elementFeaturesNonNullablePayment_method_save_usageNonNullableOther val)}
