module Stripe.CustomerSession.Types.DiscountsResourceStackableDiscountWithDiscountEnd where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Discounts_resource_stackable_discount_with_discount_end
instance Show Discounts_resource_stackable_discount_with_discount_end
instance Eq Discounts_resource_stackable_discount_with_discount_end
instance Data.Aeson.FromJSON Discounts_resource_stackable_discount_with_discount_end
instance Data.Aeson.ToJSON Discounts_resource_stackable_discount_with_discount_end
data Discounts_resource_stackable_discount_with_discount_endCouponNonNullableVariants
instance Show Discounts_resource_stackable_discount_with_discount_endCouponNonNullableVariants
instance Eq Discounts_resource_stackable_discount_with_discount_endCouponNonNullableVariants
instance Data.Aeson.FromJSON Discounts_resource_stackable_discount_with_discount_endCouponNonNullableVariants
instance Data.Aeson.ToJSON Discounts_resource_stackable_discount_with_discount_endCouponNonNullableVariants
data Discounts_resource_stackable_discount_with_discount_endDiscountNonNullableVariants
instance Show Discounts_resource_stackable_discount_with_discount_endDiscountNonNullableVariants
instance Eq Discounts_resource_stackable_discount_with_discount_endDiscountNonNullableVariants
instance Data.Aeson.FromJSON Discounts_resource_stackable_discount_with_discount_endDiscountNonNullableVariants
instance Data.Aeson.ToJSON Discounts_resource_stackable_discount_with_discount_endDiscountNonNullableVariants
data Discounts_resource_stackable_discount_with_discount_endPromotion_codeNonNullableVariants
instance Show Discounts_resource_stackable_discount_with_discount_endPromotion_codeNonNullableVariants
instance Eq Discounts_resource_stackable_discount_with_discount_endPromotion_codeNonNullableVariants
instance Data.Aeson.FromJSON Discounts_resource_stackable_discount_with_discount_endPromotion_codeNonNullableVariants
instance Data.Aeson.ToJSON Discounts_resource_stackable_discount_with_discount_endPromotion_codeNonNullableVariants
