module Stripe.CustomerSession.Types.DiscountsResourceStackableDiscountWithDiscountEnd where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Discounts_resource_stackable_discount_with_discount_end
instance Show Discounts_resource_stackable_discount_with_discount_end
instance Eq Discounts_resource_stackable_discount_with_discount_end
instance Data.Aeson.FromJSON Discounts_resource_stackable_discount_with_discount_end
instance Data.Aeson.ToJSON Discounts_resource_stackable_discount_with_discount_end
data Discounts_resource_stackable_discount_with_discount_endCouponVariants
instance Show Discounts_resource_stackable_discount_with_discount_endCouponVariants
instance Eq Discounts_resource_stackable_discount_with_discount_endCouponVariants
instance Data.Aeson.FromJSON Discounts_resource_stackable_discount_with_discount_endCouponVariants
instance Data.Aeson.ToJSON Discounts_resource_stackable_discount_with_discount_endCouponVariants
data Discounts_resource_stackable_discount_with_discount_endDiscountVariants
instance Show Discounts_resource_stackable_discount_with_discount_endDiscountVariants
instance Eq Discounts_resource_stackable_discount_with_discount_endDiscountVariants
instance Data.Aeson.FromJSON Discounts_resource_stackable_discount_with_discount_endDiscountVariants
instance Data.Aeson.ToJSON Discounts_resource_stackable_discount_with_discount_endDiscountVariants
data Discounts_resource_stackable_discount_with_discount_endPromotion_codeVariants
instance Show Discounts_resource_stackable_discount_with_discount_endPromotion_codeVariants
instance Eq Discounts_resource_stackable_discount_with_discount_endPromotion_codeVariants
instance Data.Aeson.FromJSON Discounts_resource_stackable_discount_with_discount_endPromotion_codeVariants
instance Data.Aeson.ToJSON Discounts_resource_stackable_discount_with_discount_endPromotion_codeVariants
