module Stripe.CustomerSession.Types.DiscountSource where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Discount_source
instance Show Discount_source
instance Eq Discount_source
instance Data.Aeson.FromJSON Discount_source
instance Data.Aeson.ToJSON Discount_source
data Discount_sourceCouponVariants
instance Show Discount_sourceCouponVariants
instance Eq Discount_sourceCouponVariants
instance Data.Aeson.FromJSON Discount_sourceCouponVariants
instance Data.Aeson.ToJSON Discount_sourceCouponVariants
