module Stripe.CustomerSession.Types.DisputeEnhancedEligibilityVisaCompellingEvidence3 where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Dispute_enhanced_eligibility_visa_compelling_evidence3
instance Show Dispute_enhanced_eligibility_visa_compelling_evidence3
instance Eq Dispute_enhanced_eligibility_visa_compelling_evidence3
instance Data.Aeson.FromJSON Dispute_enhanced_eligibility_visa_compelling_evidence3
instance Data.Aeson.ToJSON Dispute_enhanced_eligibility_visa_compelling_evidence3
data Dispute_enhanced_eligibility_visa_compelling_evidence3Required_actions
instance Show Dispute_enhanced_eligibility_visa_compelling_evidence3Required_actions
instance Eq Dispute_enhanced_eligibility_visa_compelling_evidence3Required_actions
instance Data.Aeson.FromJSON Dispute_enhanced_eligibility_visa_compelling_evidence3Required_actions
instance Data.Aeson.ToJSON Dispute_enhanced_eligibility_visa_compelling_evidence3Required_actions
data Dispute_enhanced_eligibility_visa_compelling_evidence3Status
instance Show Dispute_enhanced_eligibility_visa_compelling_evidence3Status
instance Eq Dispute_enhanced_eligibility_visa_compelling_evidence3Status
instance Data.Aeson.FromJSON Dispute_enhanced_eligibility_visa_compelling_evidence3Status
instance Data.Aeson.ToJSON Dispute_enhanced_eligibility_visa_compelling_evidence3Status
