module Stripe.CustomerSession.Types.DisputePaymentMethodDetailsAmazonPay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Dispute_payment_method_details_amazon_pay
instance Show Dispute_payment_method_details_amazon_pay
instance Eq Dispute_payment_method_details_amazon_pay
instance Data.Aeson.FromJSON Dispute_payment_method_details_amazon_pay
instance Data.Aeson.ToJSON Dispute_payment_method_details_amazon_pay
