module Stripe.CustomerSession.Types.DisputeVisaCompellingEvidence3PriorUndisputedTransaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Dispute_visa_compelling_evidence3_prior_undisputed_transaction
instance Show Dispute_visa_compelling_evidence3_prior_undisputed_transaction
instance Eq Dispute_visa_compelling_evidence3_prior_undisputed_transaction
instance Data.Aeson.FromJSON Dispute_visa_compelling_evidence3_prior_undisputed_transaction
instance Data.Aeson.ToJSON Dispute_visa_compelling_evidence3_prior_undisputed_transaction
data Dispute_visa_compelling_evidence3_prior_undisputed_transactionShipping_addressNonNullable
instance Show Dispute_visa_compelling_evidence3_prior_undisputed_transactionShipping_addressNonNullable
instance Eq Dispute_visa_compelling_evidence3_prior_undisputed_transactionShipping_addressNonNullable
instance Data.Aeson.FromJSON Dispute_visa_compelling_evidence3_prior_undisputed_transactionShipping_addressNonNullable
instance Data.Aeson.ToJSON Dispute_visa_compelling_evidence3_prior_undisputed_transactionShipping_addressNonNullable
