module Stripe.CustomerSession.Types.DisputeEnhancedEligibilityVisaCompliance where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Dispute_enhanced_eligibility_visa_compliance
instance Show Dispute_enhanced_eligibility_visa_compliance
instance Eq Dispute_enhanced_eligibility_visa_compliance
instance Data.Aeson.FromJSON Dispute_enhanced_eligibility_visa_compliance
instance Data.Aeson.ToJSON Dispute_enhanced_eligibility_visa_compliance
data Dispute_enhanced_eligibility_visa_complianceStatus
instance Show Dispute_enhanced_eligibility_visa_complianceStatus
instance Eq Dispute_enhanced_eligibility_visa_complianceStatus
instance Data.Aeson.FromJSON Dispute_enhanced_eligibility_visa_complianceStatus
instance Data.Aeson.ToJSON Dispute_enhanced_eligibility_visa_complianceStatus
