module Stripe.CustomerSession.Types.DisputeEnhancedEvidenceVisaCompellingEvidence3 where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Dispute_enhanced_evidence_visa_compelling_evidence3
instance Show Dispute_enhanced_evidence_visa_compelling_evidence3
instance Eq Dispute_enhanced_evidence_visa_compelling_evidence3
instance Data.Aeson.FromJSON Dispute_enhanced_evidence_visa_compelling_evidence3
instance Data.Aeson.ToJSON Dispute_enhanced_evidence_visa_compelling_evidence3
data Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullable
instance Show Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullable
instance Eq Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullable
instance Data.Aeson.FromJSON Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullable
instance Data.Aeson.ToJSON Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullable
data Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullableMerchandise_or_servicesNonNullable
instance Show Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullableMerchandise_or_servicesNonNullable
instance Eq Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullableMerchandise_or_servicesNonNullable
instance Data.Aeson.FromJSON Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullableMerchandise_or_servicesNonNullable
instance Data.Aeson.ToJSON Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullableMerchandise_or_servicesNonNullable
data Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullableShipping_addressNonNullable
instance Show Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullableShipping_addressNonNullable
instance Eq Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullableShipping_addressNonNullable
instance Data.Aeson.FromJSON Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullableShipping_addressNonNullable
instance Data.Aeson.ToJSON Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionNonNullableShipping_addressNonNullable
