module Stripe.CustomerSession.Types.DisputeVisaCompellingEvidence3DisputedTransaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Dispute_visa_compelling_evidence3_disputed_transaction
instance Show Dispute_visa_compelling_evidence3_disputed_transaction
instance Eq Dispute_visa_compelling_evidence3_disputed_transaction
instance Data.Aeson.FromJSON Dispute_visa_compelling_evidence3_disputed_transaction
instance Data.Aeson.ToJSON Dispute_visa_compelling_evidence3_disputed_transaction
data Dispute_visa_compelling_evidence3_disputed_transactionMerchandise_or_servicesNonNullable
instance Show Dispute_visa_compelling_evidence3_disputed_transactionMerchandise_or_servicesNonNullable
instance Eq Dispute_visa_compelling_evidence3_disputed_transactionMerchandise_or_servicesNonNullable
instance Data.Aeson.FromJSON Dispute_visa_compelling_evidence3_disputed_transactionMerchandise_or_servicesNonNullable
instance Data.Aeson.ToJSON Dispute_visa_compelling_evidence3_disputed_transactionMerchandise_or_servicesNonNullable
data Dispute_visa_compelling_evidence3_disputed_transactionShipping_addressNonNullable
instance Show Dispute_visa_compelling_evidence3_disputed_transactionShipping_addressNonNullable
instance Eq Dispute_visa_compelling_evidence3_disputed_transactionShipping_addressNonNullable
instance Data.Aeson.FromJSON Dispute_visa_compelling_evidence3_disputed_transactionShipping_addressNonNullable
instance Data.Aeson.ToJSON Dispute_visa_compelling_evidence3_disputed_transactionShipping_addressNonNullable
