module Stripe.CustomerSession.Types.DisputeEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Dispute_evidence
instance Show Dispute_evidence
instance Eq Dispute_evidence
instance Data.Aeson.FromJSON Dispute_evidence
instance Data.Aeson.ToJSON Dispute_evidence
data Dispute_evidenceCancellation_policyNonNullableVariants
instance Show Dispute_evidenceCancellation_policyNonNullableVariants
instance Eq Dispute_evidenceCancellation_policyNonNullableVariants
instance Data.Aeson.FromJSON Dispute_evidenceCancellation_policyNonNullableVariants
instance Data.Aeson.ToJSON Dispute_evidenceCancellation_policyNonNullableVariants
data Dispute_evidenceCustomer_communicationNonNullableVariants
instance Show Dispute_evidenceCustomer_communicationNonNullableVariants
instance Eq Dispute_evidenceCustomer_communicationNonNullableVariants
instance Data.Aeson.FromJSON Dispute_evidenceCustomer_communicationNonNullableVariants
instance Data.Aeson.ToJSON Dispute_evidenceCustomer_communicationNonNullableVariants
data Dispute_evidenceCustomer_signatureNonNullableVariants
instance Show Dispute_evidenceCustomer_signatureNonNullableVariants
instance Eq Dispute_evidenceCustomer_signatureNonNullableVariants
instance Data.Aeson.FromJSON Dispute_evidenceCustomer_signatureNonNullableVariants
instance Data.Aeson.ToJSON Dispute_evidenceCustomer_signatureNonNullableVariants
data Dispute_evidenceDuplicate_charge_documentationNonNullableVariants
instance Show Dispute_evidenceDuplicate_charge_documentationNonNullableVariants
instance Eq Dispute_evidenceDuplicate_charge_documentationNonNullableVariants
instance Data.Aeson.FromJSON Dispute_evidenceDuplicate_charge_documentationNonNullableVariants
instance Data.Aeson.ToJSON Dispute_evidenceDuplicate_charge_documentationNonNullableVariants
data Dispute_evidenceReceiptNonNullableVariants
instance Show Dispute_evidenceReceiptNonNullableVariants
instance Eq Dispute_evidenceReceiptNonNullableVariants
instance Data.Aeson.FromJSON Dispute_evidenceReceiptNonNullableVariants
instance Data.Aeson.ToJSON Dispute_evidenceReceiptNonNullableVariants
data Dispute_evidenceRefund_policyNonNullableVariants
instance Show Dispute_evidenceRefund_policyNonNullableVariants
instance Eq Dispute_evidenceRefund_policyNonNullableVariants
instance Data.Aeson.FromJSON Dispute_evidenceRefund_policyNonNullableVariants
instance Data.Aeson.ToJSON Dispute_evidenceRefund_policyNonNullableVariants
data Dispute_evidenceService_documentationNonNullableVariants
instance Show Dispute_evidenceService_documentationNonNullableVariants
instance Eq Dispute_evidenceService_documentationNonNullableVariants
instance Data.Aeson.FromJSON Dispute_evidenceService_documentationNonNullableVariants
instance Data.Aeson.ToJSON Dispute_evidenceService_documentationNonNullableVariants
data Dispute_evidenceShipping_documentationNonNullableVariants
instance Show Dispute_evidenceShipping_documentationNonNullableVariants
instance Eq Dispute_evidenceShipping_documentationNonNullableVariants
instance Data.Aeson.FromJSON Dispute_evidenceShipping_documentationNonNullableVariants
instance Data.Aeson.ToJSON Dispute_evidenceShipping_documentationNonNullableVariants
data Dispute_evidenceUncategorized_fileNonNullableVariants
instance Show Dispute_evidenceUncategorized_fileNonNullableVariants
instance Eq Dispute_evidenceUncategorized_fileNonNullableVariants
instance Data.Aeson.FromJSON Dispute_evidenceUncategorized_fileNonNullableVariants
instance Data.Aeson.ToJSON Dispute_evidenceUncategorized_fileNonNullableVariants
