module Stripe.CustomerSession.Types.DisputeEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Dispute_evidence
instance Show Dispute_evidence
instance Eq Dispute_evidence
instance Data.Aeson.FromJSON Dispute_evidence
instance Data.Aeson.ToJSON Dispute_evidence
data Dispute_evidenceCancellation_policyVariants
instance Show Dispute_evidenceCancellation_policyVariants
instance Eq Dispute_evidenceCancellation_policyVariants
instance Data.Aeson.FromJSON Dispute_evidenceCancellation_policyVariants
instance Data.Aeson.ToJSON Dispute_evidenceCancellation_policyVariants
data Dispute_evidenceCustomer_communicationVariants
instance Show Dispute_evidenceCustomer_communicationVariants
instance Eq Dispute_evidenceCustomer_communicationVariants
instance Data.Aeson.FromJSON Dispute_evidenceCustomer_communicationVariants
instance Data.Aeson.ToJSON Dispute_evidenceCustomer_communicationVariants
data Dispute_evidenceCustomer_signatureVariants
instance Show Dispute_evidenceCustomer_signatureVariants
instance Eq Dispute_evidenceCustomer_signatureVariants
instance Data.Aeson.FromJSON Dispute_evidenceCustomer_signatureVariants
instance Data.Aeson.ToJSON Dispute_evidenceCustomer_signatureVariants
data Dispute_evidenceDuplicate_charge_documentationVariants
instance Show Dispute_evidenceDuplicate_charge_documentationVariants
instance Eq Dispute_evidenceDuplicate_charge_documentationVariants
instance Data.Aeson.FromJSON Dispute_evidenceDuplicate_charge_documentationVariants
instance Data.Aeson.ToJSON Dispute_evidenceDuplicate_charge_documentationVariants
data Dispute_evidenceReceiptVariants
instance Show Dispute_evidenceReceiptVariants
instance Eq Dispute_evidenceReceiptVariants
instance Data.Aeson.FromJSON Dispute_evidenceReceiptVariants
instance Data.Aeson.ToJSON Dispute_evidenceReceiptVariants
data Dispute_evidenceRefund_policyVariants
instance Show Dispute_evidenceRefund_policyVariants
instance Eq Dispute_evidenceRefund_policyVariants
instance Data.Aeson.FromJSON Dispute_evidenceRefund_policyVariants
instance Data.Aeson.ToJSON Dispute_evidenceRefund_policyVariants
data Dispute_evidenceService_documentationVariants
instance Show Dispute_evidenceService_documentationVariants
instance Eq Dispute_evidenceService_documentationVariants
instance Data.Aeson.FromJSON Dispute_evidenceService_documentationVariants
instance Data.Aeson.ToJSON Dispute_evidenceService_documentationVariants
data Dispute_evidenceShipping_documentationVariants
instance Show Dispute_evidenceShipping_documentationVariants
instance Eq Dispute_evidenceShipping_documentationVariants
instance Data.Aeson.FromJSON Dispute_evidenceShipping_documentationVariants
instance Data.Aeson.ToJSON Dispute_evidenceShipping_documentationVariants
data Dispute_evidenceUncategorized_fileVariants
instance Show Dispute_evidenceUncategorized_fileVariants
instance Eq Dispute_evidenceUncategorized_fileVariants
instance Data.Aeson.FromJSON Dispute_evidenceUncategorized_fileVariants
instance Data.Aeson.ToJSON Dispute_evidenceUncategorized_fileVariants
