module Stripe.CustomerSession.Types.FundingInstructionsBankTransferFinancialAddress where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Funding_instructions_bank_transfer_financial_address
instance Show Funding_instructions_bank_transfer_financial_address
instance Eq Funding_instructions_bank_transfer_financial_address
instance Data.Aeson.FromJSON Funding_instructions_bank_transfer_financial_address
instance Data.Aeson.ToJSON Funding_instructions_bank_transfer_financial_address
data Funding_instructions_bank_transfer_financial_addressSupported_networks
instance Show Funding_instructions_bank_transfer_financial_addressSupported_networks
instance Eq Funding_instructions_bank_transfer_financial_addressSupported_networks
instance Data.Aeson.FromJSON Funding_instructions_bank_transfer_financial_addressSupported_networks
instance Data.Aeson.ToJSON Funding_instructions_bank_transfer_financial_addressSupported_networks
data Funding_instructions_bank_transfer_financial_addressType
instance Show Funding_instructions_bank_transfer_financial_addressType
instance Eq Funding_instructions_bank_transfer_financial_addressType
instance Data.Aeson.FromJSON Funding_instructions_bank_transfer_financial_addressType
instance Data.Aeson.ToJSON Funding_instructions_bank_transfer_financial_addressType
