module Stripe.CustomerSession.Types.InvoicePaymentMethodOptionsUsBankAccountLinkedAccountOptionsFilters where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_payment_method_options_us_bank_account_linked_account_options_filters
instance Show Invoice_payment_method_options_us_bank_account_linked_account_options_filters
instance Eq Invoice_payment_method_options_us_bank_account_linked_account_options_filters
instance Data.Aeson.FromJSON Invoice_payment_method_options_us_bank_account_linked_account_options_filters
instance Data.Aeson.ToJSON Invoice_payment_method_options_us_bank_account_linked_account_options_filters
