module Stripe.CustomerSession.Types.InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_payment_method_options_customer_balance_bank_transfer_eu_bank_transfer
instance Show Invoice_payment_method_options_customer_balance_bank_transfer_eu_bank_transfer
instance Eq Invoice_payment_method_options_customer_balance_bank_transfer_eu_bank_transfer
instance Data.Aeson.FromJSON Invoice_payment_method_options_customer_balance_bank_transfer_eu_bank_transfer
instance Data.Aeson.ToJSON Invoice_payment_method_options_customer_balance_bank_transfer_eu_bank_transfer
data Invoice_payment_method_options_customer_balance_bank_transfer_eu_bank_transferCountry
instance Show Invoice_payment_method_options_customer_balance_bank_transfer_eu_bank_transferCountry
instance Eq Invoice_payment_method_options_customer_balance_bank_transfer_eu_bank_transferCountry
instance Data.Aeson.FromJSON Invoice_payment_method_options_customer_balance_bank_transfer_eu_bank_transferCountry
instance Data.Aeson.ToJSON Invoice_payment_method_options_customer_balance_bank_transfer_eu_bank_transferCountry
