module Stripe.CustomerSession.Types.InvoiceSettingCustomerSetting where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_setting_customer_setting
instance Show Invoice_setting_customer_setting
instance Eq Invoice_setting_customer_setting
instance Data.Aeson.FromJSON Invoice_setting_customer_setting
instance Data.Aeson.ToJSON Invoice_setting_customer_setting
data Invoice_setting_customer_settingDefault_payment_methodNonNullableVariants
instance Show Invoice_setting_customer_settingDefault_payment_methodNonNullableVariants
instance Eq Invoice_setting_customer_settingDefault_payment_methodNonNullableVariants
instance Data.Aeson.FromJSON Invoice_setting_customer_settingDefault_payment_methodNonNullableVariants
instance Data.Aeson.ToJSON Invoice_setting_customer_settingDefault_payment_methodNonNullableVariants
data Invoice_setting_customer_settingRendering_optionsNonNullable
instance Show Invoice_setting_customer_settingRendering_optionsNonNullable
instance Eq Invoice_setting_customer_settingRendering_optionsNonNullable
instance Data.Aeson.FromJSON Invoice_setting_customer_settingRendering_optionsNonNullable
instance Data.Aeson.ToJSON Invoice_setting_customer_settingRendering_optionsNonNullable
