module Stripe.CustomerSession.Types.InvoicePaymentMethodOptionsBancontact where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_payment_method_options_bancontact
instance Show Invoice_payment_method_options_bancontact
instance Eq Invoice_payment_method_options_bancontact
instance Data.Aeson.FromJSON Invoice_payment_method_options_bancontact
instance Data.Aeson.ToJSON Invoice_payment_method_options_bancontact
data Invoice_payment_method_options_bancontactPreferred_language
instance Show Invoice_payment_method_options_bancontactPreferred_language
instance Eq Invoice_payment_method_options_bancontactPreferred_language
instance Data.Aeson.FromJSON Invoice_payment_method_options_bancontactPreferred_language
instance Data.Aeson.ToJSON Invoice_payment_method_options_bancontactPreferred_language
