module Stripe.CustomerSession.Types.InvoicePaymentMethodOptionsCustomerBalance where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_payment_method_options_customer_balance
instance Show Invoice_payment_method_options_customer_balance
instance Eq Invoice_payment_method_options_customer_balance
instance Data.Aeson.FromJSON Invoice_payment_method_options_customer_balance
instance Data.Aeson.ToJSON Invoice_payment_method_options_customer_balance
data Invoice_payment_method_options_customer_balanceFunding_typeNonNullable
instance Show Invoice_payment_method_options_customer_balanceFunding_typeNonNullable
instance Eq Invoice_payment_method_options_customer_balanceFunding_typeNonNullable
instance Data.Aeson.FromJSON Invoice_payment_method_options_customer_balanceFunding_typeNonNullable
instance Data.Aeson.ToJSON Invoice_payment_method_options_customer_balanceFunding_typeNonNullable
