module Stripe.CustomerSession.Types.InvoiceSettingSubscriptionScheduleSetting where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_setting_subscription_schedule_setting
instance Show Invoice_setting_subscription_schedule_setting
instance Eq Invoice_setting_subscription_schedule_setting
instance Data.Aeson.FromJSON Invoice_setting_subscription_schedule_setting
instance Data.Aeson.ToJSON Invoice_setting_subscription_schedule_setting
data Invoice_setting_subscription_schedule_settingAccount_tax_idsVariants
instance Show Invoice_setting_subscription_schedule_settingAccount_tax_idsVariants
instance Eq Invoice_setting_subscription_schedule_settingAccount_tax_idsVariants
instance Data.Aeson.FromJSON Invoice_setting_subscription_schedule_settingAccount_tax_idsVariants
instance Data.Aeson.ToJSON Invoice_setting_subscription_schedule_settingAccount_tax_idsVariants
