module Stripe.CustomerSession.Types.InvoicesResourcePretaxCreditAmount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoices_resource_pretax_credit_amount
instance Show Invoices_resource_pretax_credit_amount
instance Eq Invoices_resource_pretax_credit_amount
instance Data.Aeson.FromJSON Invoices_resource_pretax_credit_amount
instance Data.Aeson.ToJSON Invoices_resource_pretax_credit_amount
data Invoices_resource_pretax_credit_amountCredit_balance_transactionNonNullableVariants
instance Show Invoices_resource_pretax_credit_amountCredit_balance_transactionNonNullableVariants
instance Eq Invoices_resource_pretax_credit_amountCredit_balance_transactionNonNullableVariants
instance Data.Aeson.FromJSON Invoices_resource_pretax_credit_amountCredit_balance_transactionNonNullableVariants
instance Data.Aeson.ToJSON Invoices_resource_pretax_credit_amountCredit_balance_transactionNonNullableVariants
data Invoices_resource_pretax_credit_amountDiscountVariants
instance Show Invoices_resource_pretax_credit_amountDiscountVariants
instance Eq Invoices_resource_pretax_credit_amountDiscountVariants
instance Data.Aeson.FromJSON Invoices_resource_pretax_credit_amountDiscountVariants
instance Data.Aeson.ToJSON Invoices_resource_pretax_credit_amountDiscountVariants
data Invoices_resource_pretax_credit_amountType
instance Show Invoices_resource_pretax_credit_amountType
instance Eq Invoices_resource_pretax_credit_amountType
instance Data.Aeson.FromJSON Invoices_resource_pretax_credit_amountType
instance Data.Aeson.ToJSON Invoices_resource_pretax_credit_amountType
