module Stripe.CustomerSession.Types.InvoiceMandateOptionsPayto where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_mandate_options_payto
instance Show Invoice_mandate_options_payto
instance Eq Invoice_mandate_options_payto
instance Data.Aeson.FromJSON Invoice_mandate_options_payto
instance Data.Aeson.ToJSON Invoice_mandate_options_payto
data Invoice_mandate_options_paytoAmount_typeNonNullable
instance Show Invoice_mandate_options_paytoAmount_typeNonNullable
instance Eq Invoice_mandate_options_paytoAmount_typeNonNullable
instance Data.Aeson.FromJSON Invoice_mandate_options_paytoAmount_typeNonNullable
instance Data.Aeson.ToJSON Invoice_mandate_options_paytoAmount_typeNonNullable
data Invoice_mandate_options_paytoPurposeNonNullable
instance Show Invoice_mandate_options_paytoPurposeNonNullable
instance Eq Invoice_mandate_options_paytoPurposeNonNullable
instance Data.Aeson.FromJSON Invoice_mandate_options_paytoPurposeNonNullable
instance Data.Aeson.ToJSON Invoice_mandate_options_paytoPurposeNonNullable
