module Stripe.CustomerSession.Types.InvoicePaymentMethodOptionsUsBankAccount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_payment_method_options_us_bank_account
instance Show Invoice_payment_method_options_us_bank_account
instance Eq Invoice_payment_method_options_us_bank_account
instance Data.Aeson.FromJSON Invoice_payment_method_options_us_bank_account
instance Data.Aeson.ToJSON Invoice_payment_method_options_us_bank_account
data Invoice_payment_method_options_us_bank_accountVerification_method
instance Show Invoice_payment_method_options_us_bank_accountVerification_method
instance Eq Invoice_payment_method_options_us_bank_accountVerification_method
instance Data.Aeson.FromJSON Invoice_payment_method_options_us_bank_accountVerification_method
instance Data.Aeson.ToJSON Invoice_payment_method_options_us_bank_accountVerification_method
