module Stripe.CustomerSession.Types.InvoiceMandateOptionsPayto where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_mandate_options_payto
instance Show Invoice_mandate_options_payto
instance Eq Invoice_mandate_options_payto
instance Data.Aeson.FromJSON Invoice_mandate_options_payto
instance Data.Aeson.ToJSON Invoice_mandate_options_payto
