module Stripe.CustomerSession.Types.InvoicePaymentMethodOptionsCard where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_payment_method_options_card
instance Show Invoice_payment_method_options_card
instance Eq Invoice_payment_method_options_card
instance Data.Aeson.FromJSON Invoice_payment_method_options_card
instance Data.Aeson.ToJSON Invoice_payment_method_options_card
data Invoice_payment_method_options_cardRequest_three_d_secureNonNullable
instance Show Invoice_payment_method_options_cardRequest_three_d_secureNonNullable
instance Eq Invoice_payment_method_options_cardRequest_three_d_secureNonNullable
instance Data.Aeson.FromJSON Invoice_payment_method_options_cardRequest_three_d_secureNonNullable
instance Data.Aeson.ToJSON Invoice_payment_method_options_cardRequest_three_d_secureNonNullable
