-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema InvoicePayment
module Stripe.CustomerSession.Types.InvoicePayment where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias
import {-# SOURCE #-} Stripe.CustomerSession.Types.DeletedInvoice
import {-# SOURCE #-} Stripe.CustomerSession.Types.Invoice
import {-# SOURCE #-} Stripe.CustomerSession.Types.InvoicesPaymentsInvoicePaymentAssociatedPayment
import {-# SOURCE #-} Stripe.CustomerSession.Types.InvoicesPaymentsInvoicePaymentStatusTransitions

-- | Defines the object schema located at @components.schemas.invoice_payment@ in the specification.
-- 
-- Invoice Payments represent payments made against invoices. Invoice Payments can
-- be accessed in two ways:
-- 1. By expanding the \`payments\` field on the [Invoice](https:\/\/api.stripe.com\#invoice) resource.
-- 2. By using the Invoice Payment retrieve and list endpoints.
-- 
-- Invoice Payments include the mapping between payment objects, such as Payment Intent, and Invoices.
-- This resource and its endpoints allows you to easily track if a payment is associated with a specific invoice and
-- monitor the allocation details of the payments.
data Invoice_payment = Invoice_payment {
  -- | amount_paid: Amount that was actually paid for this invoice, in cents (or local equivalent). This field is null until the payment is \`paid\`. This amount can be less than the \`amount_requested\` if the PaymentIntent’s \`amount_received\` is not sufficient to pay all of the invoices that it is attached to.
  invoice_paymentAmount_paid :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable GHC.Types.Int))
  -- | amount_requested: Amount intended to be paid toward this invoice, in cents (or local equivalent)
  , invoice_paymentAmount_requested :: GHC.Types.Int
  -- | created: Time at which the object was created. Measured in seconds since the Unix epoch.
  , invoice_paymentCreated :: GHC.Types.Int
  -- | currency: Three-letter [ISO currency code](https:\/\/www.iso.org\/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https:\/\/stripe.com\/docs\/currencies).
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , invoice_paymentCurrency :: Data.Text.Internal.Text
  -- | id: Unique identifier for the object.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , invoice_paymentId :: Data.Text.Internal.Text
  -- | invoice: The invoice that was paid.
  , invoice_paymentInvoice :: Invoice_paymentInvoiceVariants
  -- | is_default: Stripe automatically creates a default InvoicePayment when the invoice is finalized, and keeps it synchronized with the invoice’s \`amount_remaining\`. The PaymentIntent associated with the default payment can’t be edited or canceled directly.
  , invoice_paymentIs_default :: GHC.Types.Bool
  -- | livemode: Has the value \`true\` if the object exists in live mode or the value \`false\` if the object exists in test mode.
  , invoice_paymentLivemode :: GHC.Types.Bool
  -- | payment: 
  , invoice_paymentPayment :: Invoices_payments_invoice_payment_associated_payment
  -- | status: The status of the payment, one of \`open\`, \`paid\`, or \`canceled\`.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , invoice_paymentStatus :: Data.Text.Internal.Text
  -- | status_transitions: 
  , invoice_paymentStatus_transitions :: Invoices_payments_invoice_payment_status_transitions
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Invoice_payment
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("amount_paid" Data.Aeson.Types.ToJSON..=)) (invoice_paymentAmount_paid obj) : ["amount_requested" Data.Aeson.Types.ToJSON..= invoice_paymentAmount_requested obj] : ["created" Data.Aeson.Types.ToJSON..= invoice_paymentCreated obj] : ["currency" Data.Aeson.Types.ToJSON..= invoice_paymentCurrency obj] : ["id" Data.Aeson.Types.ToJSON..= invoice_paymentId obj] : ["invoice" Data.Aeson.Types.ToJSON..= invoice_paymentInvoice obj] : ["is_default" Data.Aeson.Types.ToJSON..= invoice_paymentIs_default obj] : ["livemode" Data.Aeson.Types.ToJSON..= invoice_paymentLivemode obj] : ["payment" Data.Aeson.Types.ToJSON..= invoice_paymentPayment obj] : ["status" Data.Aeson.Types.ToJSON..= invoice_paymentStatus obj] : ["status_transitions" Data.Aeson.Types.ToJSON..= invoice_paymentStatus_transitions obj] : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "invoice_payment"] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("amount_paid" Data.Aeson.Types.ToJSON..=)) (invoice_paymentAmount_paid obj) : ["amount_requested" Data.Aeson.Types.ToJSON..= invoice_paymentAmount_requested obj] : ["created" Data.Aeson.Types.ToJSON..= invoice_paymentCreated obj] : ["currency" Data.Aeson.Types.ToJSON..= invoice_paymentCurrency obj] : ["id" Data.Aeson.Types.ToJSON..= invoice_paymentId obj] : ["invoice" Data.Aeson.Types.ToJSON..= invoice_paymentInvoice obj] : ["is_default" Data.Aeson.Types.ToJSON..= invoice_paymentIs_default obj] : ["livemode" Data.Aeson.Types.ToJSON..= invoice_paymentLivemode obj] : ["payment" Data.Aeson.Types.ToJSON..= invoice_paymentPayment obj] : ["status" Data.Aeson.Types.ToJSON..= invoice_paymentStatus obj] : ["status_transitions" Data.Aeson.Types.ToJSON..= invoice_paymentStatus_transitions obj] : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "invoice_payment"] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Invoice_payment
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Invoice_payment" (\obj -> ((((((((((GHC.Base.pure Invoice_payment GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "amount_paid")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "amount_requested")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "created")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "currency")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "invoice")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "is_default")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "livemode")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "payment")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "status")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "status_transitions"))}
-- | Create a new 'Invoice_payment' with all required fields.
mkInvoice_payment :: GHC.Types.Int -- ^ 'invoice_paymentAmount_requested'
  -> GHC.Types.Int -- ^ 'invoice_paymentCreated'
  -> Data.Text.Internal.Text -- ^ 'invoice_paymentCurrency'
  -> Data.Text.Internal.Text -- ^ 'invoice_paymentId'
  -> Invoice_paymentInvoiceVariants -- ^ 'invoice_paymentInvoice'
  -> GHC.Types.Bool -- ^ 'invoice_paymentIs_default'
  -> GHC.Types.Bool -- ^ 'invoice_paymentLivemode'
  -> Invoices_payments_invoice_payment_associated_payment -- ^ 'invoice_paymentPayment'
  -> Data.Text.Internal.Text -- ^ 'invoice_paymentStatus'
  -> Invoices_payments_invoice_payment_status_transitions -- ^ 'invoice_paymentStatus_transitions'
  -> Invoice_payment
mkInvoice_payment invoice_paymentAmount_requested invoice_paymentCreated invoice_paymentCurrency invoice_paymentId invoice_paymentInvoice invoice_paymentIs_default invoice_paymentLivemode invoice_paymentPayment invoice_paymentStatus invoice_paymentStatus_transitions = Invoice_payment{invoice_paymentAmount_paid = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                             invoice_paymentAmount_requested = invoice_paymentAmount_requested,
                                                                                                                                                                                                                                                                                             invoice_paymentCreated = invoice_paymentCreated,
                                                                                                                                                                                                                                                                                             invoice_paymentCurrency = invoice_paymentCurrency,
                                                                                                                                                                                                                                                                                             invoice_paymentId = invoice_paymentId,
                                                                                                                                                                                                                                                                                             invoice_paymentInvoice = invoice_paymentInvoice,
                                                                                                                                                                                                                                                                                             invoice_paymentIs_default = invoice_paymentIs_default,
                                                                                                                                                                                                                                                                                             invoice_paymentLivemode = invoice_paymentLivemode,
                                                                                                                                                                                                                                                                                             invoice_paymentPayment = invoice_paymentPayment,
                                                                                                                                                                                                                                                                                             invoice_paymentStatus = invoice_paymentStatus,
                                                                                                                                                                                                                                                                                             invoice_paymentStatus_transitions = invoice_paymentStatus_transitions}
-- | Defines the oneOf schema located at @components.schemas.invoice_payment.properties.invoice.anyOf@ in the specification.
-- 
-- The invoice that was paid.
data Invoice_paymentInvoiceVariants =
   Invoice_paymentInvoiceText Data.Text.Internal.Text
  | Invoice_paymentInvoiceInvoice Invoice
  | Invoice_paymentInvoiceDeleted_invoice Deleted_invoice
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Invoice_paymentInvoiceVariants
    where {toJSON (Invoice_paymentInvoiceText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Invoice_paymentInvoiceInvoice a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Invoice_paymentInvoiceDeleted_invoice a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON Invoice_paymentInvoiceVariants
    where {parseJSON val = case (Invoice_paymentInvoiceText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((Invoice_paymentInvoiceInvoice Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((Invoice_paymentInvoiceDeleted_invoice Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched")) of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
