module Stripe.CustomerSession.Types.InvoicePaymentMethodOptionsAcssDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_payment_method_options_acss_debit
instance Show Invoice_payment_method_options_acss_debit
instance Eq Invoice_payment_method_options_acss_debit
instance Data.Aeson.FromJSON Invoice_payment_method_options_acss_debit
instance Data.Aeson.ToJSON Invoice_payment_method_options_acss_debit
data Invoice_payment_method_options_acss_debitVerification_method
instance Show Invoice_payment_method_options_acss_debitVerification_method
instance Eq Invoice_payment_method_options_acss_debitVerification_method
instance Data.Aeson.FromJSON Invoice_payment_method_options_acss_debitVerification_method
instance Data.Aeson.ToJSON Invoice_payment_method_options_acss_debitVerification_method
