module Stripe.CustomerSession.Types.IssuingAuthorizationFleetReportedBreakdown where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_fleet_reported_breakdown
instance Show Issuing_authorization_fleet_reported_breakdown
instance Eq Issuing_authorization_fleet_reported_breakdown
instance Data.Aeson.FromJSON Issuing_authorization_fleet_reported_breakdown
instance Data.Aeson.ToJSON Issuing_authorization_fleet_reported_breakdown
data Issuing_authorization_fleet_reported_breakdownFuel
instance Show Issuing_authorization_fleet_reported_breakdownFuel
instance Eq Issuing_authorization_fleet_reported_breakdownFuel
instance Data.Aeson.FromJSON Issuing_authorization_fleet_reported_breakdownFuel
instance Data.Aeson.ToJSON Issuing_authorization_fleet_reported_breakdownFuel
data Issuing_authorization_fleet_reported_breakdownNon_fuel
instance Show Issuing_authorization_fleet_reported_breakdownNon_fuel
instance Eq Issuing_authorization_fleet_reported_breakdownNon_fuel
instance Data.Aeson.FromJSON Issuing_authorization_fleet_reported_breakdownNon_fuel
instance Data.Aeson.ToJSON Issuing_authorization_fleet_reported_breakdownNon_fuel
data Issuing_authorization_fleet_reported_breakdownTax
instance Show Issuing_authorization_fleet_reported_breakdownTax
instance Eq Issuing_authorization_fleet_reported_breakdownTax
instance Data.Aeson.FromJSON Issuing_authorization_fleet_reported_breakdownTax
instance Data.Aeson.ToJSON Issuing_authorization_fleet_reported_breakdownTax
