module Stripe.CustomerSession.Types.IssuingAuthorizationFraudChallenge where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_fraud_challenge
instance Show Issuing_authorization_fraud_challenge
instance Eq Issuing_authorization_fraud_challenge
instance Data.Aeson.FromJSON Issuing_authorization_fraud_challenge
instance Data.Aeson.ToJSON Issuing_authorization_fraud_challenge
data Issuing_authorization_fraud_challengeStatus
instance Show Issuing_authorization_fraud_challengeStatus
instance Eq Issuing_authorization_fraud_challengeStatus
instance Data.Aeson.FromJSON Issuing_authorization_fraud_challengeStatus
instance Data.Aeson.ToJSON Issuing_authorization_fraud_challengeStatus
data Issuing_authorization_fraud_challengeUndeliverable_reasonNonNullable
instance Show Issuing_authorization_fraud_challengeUndeliverable_reasonNonNullable
instance Eq Issuing_authorization_fraud_challengeUndeliverable_reasonNonNullable
instance Data.Aeson.FromJSON Issuing_authorization_fraud_challengeUndeliverable_reasonNonNullable
instance Data.Aeson.ToJSON Issuing_authorization_fraud_challengeUndeliverable_reasonNonNullable
