module Stripe.CustomerSession.Types.IssuingNetworkTokenWalletProvider where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_network_token_wallet_provider
instance Show Issuing_network_token_wallet_provider
instance Eq Issuing_network_token_wallet_provider
instance Data.Aeson.FromJSON Issuing_network_token_wallet_provider
instance Data.Aeson.ToJSON Issuing_network_token_wallet_provider
data Issuing_network_token_wallet_providerCard_number_source
instance Show Issuing_network_token_wallet_providerCard_number_source
instance Eq Issuing_network_token_wallet_providerCard_number_source
instance Data.Aeson.FromJSON Issuing_network_token_wallet_providerCard_number_source
instance Data.Aeson.ToJSON Issuing_network_token_wallet_providerCard_number_source
data Issuing_network_token_wallet_providerReason_codes
instance Show Issuing_network_token_wallet_providerReason_codes
instance Eq Issuing_network_token_wallet_providerReason_codes
instance Data.Aeson.FromJSON Issuing_network_token_wallet_providerReason_codes
instance Data.Aeson.ToJSON Issuing_network_token_wallet_providerReason_codes
data Issuing_network_token_wallet_providerSuggested_decision
instance Show Issuing_network_token_wallet_providerSuggested_decision
instance Eq Issuing_network_token_wallet_providerSuggested_decision
instance Data.Aeson.FromJSON Issuing_network_token_wallet_providerSuggested_decision
instance Data.Aeson.ToJSON Issuing_network_token_wallet_providerSuggested_decision
