-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema IssuingTransactionFlightData
module Stripe.CustomerSession.Types.IssuingTransactionFlightData where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingTransactionFlightDataLeg

-- | Defines the object schema located at @components.schemas.issuing_transaction_flight_data@ in the specification.
-- 
-- 
data Issuing_transaction_flight_data = Issuing_transaction_flight_data {
  -- | departure_at: The time that the flight departed.
  issuing_transaction_flight_dataDeparture_at :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | passenger_name: The name of the passenger.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , issuing_transaction_flight_dataPassenger_name :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | refundable: Whether the ticket is refundable.
  , issuing_transaction_flight_dataRefundable :: (GHC.Maybe.Maybe GHC.Types.Bool)
  -- | segments: The legs of the trip.
  , issuing_transaction_flight_dataSegments :: (GHC.Maybe.Maybe [Issuing_transaction_flight_data_leg])
  -- | travel_agency: The travel agency that issued the ticket.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , issuing_transaction_flight_dataTravel_agency :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing_transaction_flight_data
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("departure_at" Data.Aeson.Types.ToJSON..=)) (issuing_transaction_flight_dataDeparture_at obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("passenger_name" Data.Aeson.Types.ToJSON..=)) (issuing_transaction_flight_dataPassenger_name obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("refundable" Data.Aeson.Types.ToJSON..=)) (issuing_transaction_flight_dataRefundable obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("segments" Data.Aeson.Types.ToJSON..=)) (issuing_transaction_flight_dataSegments obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("travel_agency" Data.Aeson.Types.ToJSON..=)) (issuing_transaction_flight_dataTravel_agency obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("departure_at" Data.Aeson.Types.ToJSON..=)) (issuing_transaction_flight_dataDeparture_at obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("passenger_name" Data.Aeson.Types.ToJSON..=)) (issuing_transaction_flight_dataPassenger_name obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("refundable" Data.Aeson.Types.ToJSON..=)) (issuing_transaction_flight_dataRefundable obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("segments" Data.Aeson.Types.ToJSON..=)) (issuing_transaction_flight_dataSegments obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("travel_agency" Data.Aeson.Types.ToJSON..=)) (issuing_transaction_flight_dataTravel_agency obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing_transaction_flight_data
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing_transaction_flight_data" (\obj -> ((((GHC.Base.pure Issuing_transaction_flight_data GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "departure_at")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "passenger_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "refundable")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "segments")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "travel_agency"))}
-- | Create a new 'Issuing_transaction_flight_data' with all required fields.
mkIssuing_transaction_flight_data :: Issuing_transaction_flight_data
mkIssuing_transaction_flight_data = Issuing_transaction_flight_data{issuing_transaction_flight_dataDeparture_at = GHC.Maybe.Nothing,
                                                                    issuing_transaction_flight_dataPassenger_name = GHC.Maybe.Nothing,
                                                                    issuing_transaction_flight_dataRefundable = GHC.Maybe.Nothing,
                                                                    issuing_transaction_flight_dataSegments = GHC.Maybe.Nothing,
                                                                    issuing_transaction_flight_dataTravel_agency = GHC.Maybe.Nothing}
