module Stripe.CustomerSession.Types.IssuingCardShippingAddressValidation where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_card_shipping_address_validation
instance Show Issuing_card_shipping_address_validation
instance Eq Issuing_card_shipping_address_validation
instance Data.Aeson.FromJSON Issuing_card_shipping_address_validation
instance Data.Aeson.ToJSON Issuing_card_shipping_address_validation
data Issuing_card_shipping_address_validationMode
instance Show Issuing_card_shipping_address_validationMode
instance Eq Issuing_card_shipping_address_validationMode
instance Data.Aeson.FromJSON Issuing_card_shipping_address_validationMode
instance Data.Aeson.ToJSON Issuing_card_shipping_address_validationMode
data Issuing_card_shipping_address_validationNormalized_addressNonNullable
instance Show Issuing_card_shipping_address_validationNormalized_addressNonNullable
instance Eq Issuing_card_shipping_address_validationNormalized_addressNonNullable
instance Data.Aeson.FromJSON Issuing_card_shipping_address_validationNormalized_addressNonNullable
instance Data.Aeson.ToJSON Issuing_card_shipping_address_validationNormalized_addressNonNullable
data Issuing_card_shipping_address_validationResultNonNullable
instance Show Issuing_card_shipping_address_validationResultNonNullable
instance Eq Issuing_card_shipping_address_validationResultNonNullable
instance Data.Aeson.FromJSON Issuing_card_shipping_address_validationResultNonNullable
instance Data.Aeson.ToJSON Issuing_card_shipping_address_validationResultNonNullable
