module Stripe.CustomerSession.Types.IssuingCardholderIdDocument where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_cardholder_id_document
instance Show Issuing_cardholder_id_document
instance Eq Issuing_cardholder_id_document
instance Data.Aeson.FromJSON Issuing_cardholder_id_document
instance Data.Aeson.ToJSON Issuing_cardholder_id_document
data Issuing_cardholder_id_documentBackNonNullableVariants
instance Show Issuing_cardholder_id_documentBackNonNullableVariants
instance Eq Issuing_cardholder_id_documentBackNonNullableVariants
instance Data.Aeson.FromJSON Issuing_cardholder_id_documentBackNonNullableVariants
instance Data.Aeson.ToJSON Issuing_cardholder_id_documentBackNonNullableVariants
data Issuing_cardholder_id_documentFrontNonNullableVariants
instance Show Issuing_cardholder_id_documentFrontNonNullableVariants
instance Eq Issuing_cardholder_id_documentFrontNonNullableVariants
instance Data.Aeson.FromJSON Issuing_cardholder_id_documentFrontNonNullableVariants
instance Data.Aeson.ToJSON Issuing_cardholder_id_documentFrontNonNullableVariants
