module Stripe.CustomerSession.Types.IssuingCardholderAuthorizationControls where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_cardholder_authorization_controls
instance Show Issuing_cardholder_authorization_controls
instance Eq Issuing_cardholder_authorization_controls
instance Data.Aeson.FromJSON Issuing_cardholder_authorization_controls
instance Data.Aeson.ToJSON Issuing_cardholder_authorization_controls
data Issuing_cardholder_authorization_controlsAllowed_categoriesNonNullable
instance Show Issuing_cardholder_authorization_controlsAllowed_categoriesNonNullable
instance Eq Issuing_cardholder_authorization_controlsAllowed_categoriesNonNullable
instance Data.Aeson.FromJSON Issuing_cardholder_authorization_controlsAllowed_categoriesNonNullable
instance Data.Aeson.ToJSON Issuing_cardholder_authorization_controlsAllowed_categoriesNonNullable
data Issuing_cardholder_authorization_controlsBlocked_categoriesNonNullable
instance Show Issuing_cardholder_authorization_controlsBlocked_categoriesNonNullable
instance Eq Issuing_cardholder_authorization_controlsBlocked_categoriesNonNullable
instance Data.Aeson.FromJSON Issuing_cardholder_authorization_controlsBlocked_categoriesNonNullable
instance Data.Aeson.ToJSON Issuing_cardholder_authorization_controlsBlocked_categoriesNonNullable
