module Stripe.CustomerSession.Types.IssuingDisputeDuplicateEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_dispute_duplicate_evidence
instance Show Issuing_dispute_duplicate_evidence
instance Eq Issuing_dispute_duplicate_evidence
instance Data.Aeson.FromJSON Issuing_dispute_duplicate_evidence
instance Data.Aeson.ToJSON Issuing_dispute_duplicate_evidence
data Issuing_dispute_duplicate_evidenceAdditional_documentationNonNullableVariants
instance Show Issuing_dispute_duplicate_evidenceAdditional_documentationNonNullableVariants
instance Eq Issuing_dispute_duplicate_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.FromJSON Issuing_dispute_duplicate_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.ToJSON Issuing_dispute_duplicate_evidenceAdditional_documentationNonNullableVariants
data Issuing_dispute_duplicate_evidenceCard_statementNonNullableVariants
instance Show Issuing_dispute_duplicate_evidenceCard_statementNonNullableVariants
instance Eq Issuing_dispute_duplicate_evidenceCard_statementNonNullableVariants
instance Data.Aeson.FromJSON Issuing_dispute_duplicate_evidenceCard_statementNonNullableVariants
instance Data.Aeson.ToJSON Issuing_dispute_duplicate_evidenceCard_statementNonNullableVariants
data Issuing_dispute_duplicate_evidenceCash_receiptNonNullableVariants
instance Show Issuing_dispute_duplicate_evidenceCash_receiptNonNullableVariants
instance Eq Issuing_dispute_duplicate_evidenceCash_receiptNonNullableVariants
instance Data.Aeson.FromJSON Issuing_dispute_duplicate_evidenceCash_receiptNonNullableVariants
instance Data.Aeson.ToJSON Issuing_dispute_duplicate_evidenceCash_receiptNonNullableVariants
data Issuing_dispute_duplicate_evidenceCheck_imageNonNullableVariants
instance Show Issuing_dispute_duplicate_evidenceCheck_imageNonNullableVariants
instance Eq Issuing_dispute_duplicate_evidenceCheck_imageNonNullableVariants
instance Data.Aeson.FromJSON Issuing_dispute_duplicate_evidenceCheck_imageNonNullableVariants
instance Data.Aeson.ToJSON Issuing_dispute_duplicate_evidenceCheck_imageNonNullableVariants
