module Stripe.CustomerSession.Types.IssuingDisputeNotReceivedEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_dispute_not_received_evidence
instance Show Issuing_dispute_not_received_evidence
instance Eq Issuing_dispute_not_received_evidence
instance Data.Aeson.FromJSON Issuing_dispute_not_received_evidence
instance Data.Aeson.ToJSON Issuing_dispute_not_received_evidence
data Issuing_dispute_not_received_evidenceAdditional_documentationNonNullableVariants
instance Show Issuing_dispute_not_received_evidenceAdditional_documentationNonNullableVariants
instance Eq Issuing_dispute_not_received_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.FromJSON Issuing_dispute_not_received_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.ToJSON Issuing_dispute_not_received_evidenceAdditional_documentationNonNullableVariants
data Issuing_dispute_not_received_evidenceProduct_typeNonNullable
instance Show Issuing_dispute_not_received_evidenceProduct_typeNonNullable
instance Eq Issuing_dispute_not_received_evidenceProduct_typeNonNullable
instance Data.Aeson.FromJSON Issuing_dispute_not_received_evidenceProduct_typeNonNullable
instance Data.Aeson.ToJSON Issuing_dispute_not_received_evidenceProduct_typeNonNullable
