-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema IssuingPersonalizationDesignRejectionReasons
module Stripe.CustomerSession.Types.IssuingPersonalizationDesignRejectionReasons where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias

-- | Defines the object schema located at @components.schemas.issuing_personalization_design_rejection_reasons@ in the specification.
-- 
-- 
data Issuing_personalization_design_rejection_reasons = Issuing_personalization_design_rejection_reasons {
  -- | card_logo: The reason(s) the card logo was rejected.
  issuing_personalization_design_rejection_reasonsCard_logo :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable [Issuing_personalization_design_rejection_reasonsCard_logoNonNullable]))
  -- | carrier_text: The reason(s) the carrier text was rejected.
  , issuing_personalization_design_rejection_reasonsCarrier_text :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable [Issuing_personalization_design_rejection_reasonsCarrier_textNonNullable]))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing_personalization_design_rejection_reasons
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("card_logo" Data.Aeson.Types.ToJSON..=)) (issuing_personalization_design_rejection_reasonsCard_logo obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("carrier_text" Data.Aeson.Types.ToJSON..=)) (issuing_personalization_design_rejection_reasonsCarrier_text obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("card_logo" Data.Aeson.Types.ToJSON..=)) (issuing_personalization_design_rejection_reasonsCard_logo obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("carrier_text" Data.Aeson.Types.ToJSON..=)) (issuing_personalization_design_rejection_reasonsCarrier_text obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing_personalization_design_rejection_reasons
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing_personalization_design_rejection_reasons" (\obj -> (GHC.Base.pure Issuing_personalization_design_rejection_reasons GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "card_logo")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "carrier_text"))}
-- | Create a new 'Issuing_personalization_design_rejection_reasons' with all required fields.
mkIssuing_personalization_design_rejection_reasons :: Issuing_personalization_design_rejection_reasons
mkIssuing_personalization_design_rejection_reasons = Issuing_personalization_design_rejection_reasons{issuing_personalization_design_rejection_reasonsCard_logo = GHC.Maybe.Nothing,
                                                                                                      issuing_personalization_design_rejection_reasonsCarrier_text = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.issuing_personalization_design_rejection_reasons.properties.card_logo.items@ in the specification.
-- 
-- 
data Issuing_personalization_design_rejection_reasonsCard_logoNonNullable =
   Issuing_personalization_design_rejection_reasonsCard_logoNonNullableOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | Issuing_personalization_design_rejection_reasonsCard_logoNonNullableTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumGeographic_location -- ^ Represents the JSON value @"geographic_location"@
  | Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumInappropriate -- ^ Represents the JSON value @"inappropriate"@
  | Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumNetwork_name -- ^ Represents the JSON value @"network_name"@
  | Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumNon_binary_image -- ^ Represents the JSON value @"non_binary_image"@
  | Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumNon_fiat_currency -- ^ Represents the JSON value @"non_fiat_currency"@
  | Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumOther -- ^ Represents the JSON value @"other"@
  | Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumOther_entity -- ^ Represents the JSON value @"other_entity"@
  | Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumPromotional_material -- ^ Represents the JSON value @"promotional_material"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing_personalization_design_rejection_reasonsCard_logoNonNullable
    where {toJSON (Issuing_personalization_design_rejection_reasonsCard_logoNonNullableOther val) = val;
           toJSON (Issuing_personalization_design_rejection_reasonsCard_logoNonNullableTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumGeographic_location) = "geographic_location";
           toJSON (Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumInappropriate) = "inappropriate";
           toJSON (Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumNetwork_name) = "network_name";
           toJSON (Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumNon_binary_image) = "non_binary_image";
           toJSON (Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumNon_fiat_currency) = "non_fiat_currency";
           toJSON (Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumOther) = "other";
           toJSON (Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumOther_entity) = "other_entity";
           toJSON (Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumPromotional_material) = "promotional_material"}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing_personalization_design_rejection_reasonsCard_logoNonNullable
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "geographic_location" -> Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumGeographic_location
                                             | val GHC.Classes.== "inappropriate" -> Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumInappropriate
                                             | val GHC.Classes.== "network_name" -> Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumNetwork_name
                                             | val GHC.Classes.== "non_binary_image" -> Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumNon_binary_image
                                             | val GHC.Classes.== "non_fiat_currency" -> Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumNon_fiat_currency
                                             | val GHC.Classes.== "other" -> Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumOther
                                             | val GHC.Classes.== "other_entity" -> Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumOther_entity
                                             | val GHC.Classes.== "promotional_material" -> Issuing_personalization_design_rejection_reasonsCard_logoNonNullableEnumPromotional_material
                                             | GHC.Base.otherwise -> Issuing_personalization_design_rejection_reasonsCard_logoNonNullableOther val)}
-- | Defines the enum schema located at @components.schemas.issuing_personalization_design_rejection_reasons.properties.carrier_text.items@ in the specification.
-- 
-- 
data Issuing_personalization_design_rejection_reasonsCarrier_textNonNullable =
   Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumGeographic_location -- ^ Represents the JSON value @"geographic_location"@
  | Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumInappropriate -- ^ Represents the JSON value @"inappropriate"@
  | Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumNetwork_name -- ^ Represents the JSON value @"network_name"@
  | Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumNon_fiat_currency -- ^ Represents the JSON value @"non_fiat_currency"@
  | Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumOther -- ^ Represents the JSON value @"other"@
  | Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumOther_entity -- ^ Represents the JSON value @"other_entity"@
  | Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumPromotional_material -- ^ Represents the JSON value @"promotional_material"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing_personalization_design_rejection_reasonsCarrier_textNonNullable
    where {toJSON (Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableOther val) = val;
           toJSON (Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumGeographic_location) = "geographic_location";
           toJSON (Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumInappropriate) = "inappropriate";
           toJSON (Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumNetwork_name) = "network_name";
           toJSON (Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumNon_fiat_currency) = "non_fiat_currency";
           toJSON (Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumOther) = "other";
           toJSON (Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumOther_entity) = "other_entity";
           toJSON (Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumPromotional_material) = "promotional_material"}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing_personalization_design_rejection_reasonsCarrier_textNonNullable
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "geographic_location" -> Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumGeographic_location
                                             | val GHC.Classes.== "inappropriate" -> Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumInappropriate
                                             | val GHC.Classes.== "network_name" -> Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumNetwork_name
                                             | val GHC.Classes.== "non_fiat_currency" -> Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumNon_fiat_currency
                                             | val GHC.Classes.== "other" -> Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumOther
                                             | val GHC.Classes.== "other_entity" -> Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumOther_entity
                                             | val GHC.Classes.== "promotional_material" -> Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableEnumPromotional_material
                                             | GHC.Base.otherwise -> Issuing_personalization_design_rejection_reasonsCarrier_textNonNullableOther val)}
