module Stripe.CustomerSession.Types.IssuingAuthorizationAuthenticationExemption where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_authentication_exemption
instance Show Issuing_authorization_authentication_exemption
instance Eq Issuing_authorization_authentication_exemption
instance Data.Aeson.FromJSON Issuing_authorization_authentication_exemption
instance Data.Aeson.ToJSON Issuing_authorization_authentication_exemption
