module Stripe.CustomerSession.Types.IssuingAuthorizationFuelData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_fuel_data
instance Show Issuing_authorization_fuel_data
instance Eq Issuing_authorization_fuel_data
instance Data.Aeson.FromJSON Issuing_authorization_fuel_data
instance Data.Aeson.ToJSON Issuing_authorization_fuel_data
data Issuing_authorization_fuel_dataTypeNonNullable
instance Show Issuing_authorization_fuel_dataTypeNonNullable
instance Eq Issuing_authorization_fuel_dataTypeNonNullable
instance Data.Aeson.FromJSON Issuing_authorization_fuel_dataTypeNonNullable
instance Data.Aeson.ToJSON Issuing_authorization_fuel_dataTypeNonNullable
data Issuing_authorization_fuel_dataUnitNonNullable
instance Show Issuing_authorization_fuel_dataUnitNonNullable
instance Eq Issuing_authorization_fuel_dataUnitNonNullable
instance Data.Aeson.FromJSON Issuing_authorization_fuel_dataUnitNonNullable
instance Data.Aeson.ToJSON Issuing_authorization_fuel_dataUnitNonNullable
