module Stripe.CustomerSession.Types.IssuingAuthorizationFleetData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_fleet_data
instance Show Issuing_authorization_fleet_data
instance Eq Issuing_authorization_fleet_data
instance Data.Aeson.FromJSON Issuing_authorization_fleet_data
instance Data.Aeson.ToJSON Issuing_authorization_fleet_data
data Issuing_authorization_fleet_dataCardholder_prompt_dataNonNullable
instance Show Issuing_authorization_fleet_dataCardholder_prompt_dataNonNullable
instance Eq Issuing_authorization_fleet_dataCardholder_prompt_dataNonNullable
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataCardholder_prompt_dataNonNullable
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataCardholder_prompt_dataNonNullable
data Issuing_authorization_fleet_dataPurchase_typeNonNullable
instance Show Issuing_authorization_fleet_dataPurchase_typeNonNullable
instance Eq Issuing_authorization_fleet_dataPurchase_typeNonNullable
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataPurchase_typeNonNullable
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataPurchase_typeNonNullable
data Issuing_authorization_fleet_dataReported_breakdownNonNullable
instance Show Issuing_authorization_fleet_dataReported_breakdownNonNullable
instance Eq Issuing_authorization_fleet_dataReported_breakdownNonNullable
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataReported_breakdownNonNullable
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataReported_breakdownNonNullable
data Issuing_authorization_fleet_dataReported_breakdownNonNullableFuelNonNullable
instance Show Issuing_authorization_fleet_dataReported_breakdownNonNullableFuelNonNullable
instance Eq Issuing_authorization_fleet_dataReported_breakdownNonNullableFuelNonNullable
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataReported_breakdownNonNullableFuelNonNullable
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataReported_breakdownNonNullableFuelNonNullable
data Issuing_authorization_fleet_dataReported_breakdownNonNullableNon_fuelNonNullable
instance Show Issuing_authorization_fleet_dataReported_breakdownNonNullableNon_fuelNonNullable
instance Eq Issuing_authorization_fleet_dataReported_breakdownNonNullableNon_fuelNonNullable
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataReported_breakdownNonNullableNon_fuelNonNullable
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataReported_breakdownNonNullableNon_fuelNonNullable
data Issuing_authorization_fleet_dataReported_breakdownNonNullableTaxNonNullable
instance Show Issuing_authorization_fleet_dataReported_breakdownNonNullableTaxNonNullable
instance Eq Issuing_authorization_fleet_dataReported_breakdownNonNullableTaxNonNullable
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataReported_breakdownNonNullableTaxNonNullable
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataReported_breakdownNonNullableTaxNonNullable
data Issuing_authorization_fleet_dataService_typeNonNullable
instance Show Issuing_authorization_fleet_dataService_typeNonNullable
instance Eq Issuing_authorization_fleet_dataService_typeNonNullable
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataService_typeNonNullable
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataService_typeNonNullable
