-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema IssuingCardApplePay
module Stripe.CustomerSession.Types.IssuingCardApplePay where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias

-- | Defines the object schema located at @components.schemas.issuing_card_apple_pay@ in the specification.
-- 
-- 
data Issuing_card_apple_pay = Issuing_card_apple_pay {
  -- | eligible: Apple Pay Eligibility
  issuing_card_apple_payEligible :: GHC.Types.Bool
  -- | ineligible_reason: Reason the card is ineligible for Apple Pay
  , issuing_card_apple_payIneligible_reason :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Issuing_card_apple_payIneligible_reasonNonNullable))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing_card_apple_pay
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["eligible" Data.Aeson.Types.ToJSON..= issuing_card_apple_payEligible obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("ineligible_reason" Data.Aeson.Types.ToJSON..=)) (issuing_card_apple_payIneligible_reason obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["eligible" Data.Aeson.Types.ToJSON..= issuing_card_apple_payEligible obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("ineligible_reason" Data.Aeson.Types.ToJSON..=)) (issuing_card_apple_payIneligible_reason obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing_card_apple_pay
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing_card_apple_pay" (\obj -> (GHC.Base.pure Issuing_card_apple_pay GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "eligible")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "ineligible_reason"))}
-- | Create a new 'Issuing_card_apple_pay' with all required fields.
mkIssuing_card_apple_pay :: GHC.Types.Bool -- ^ 'issuing_card_apple_payEligible'
  -> Issuing_card_apple_pay
mkIssuing_card_apple_pay issuing_card_apple_payEligible = Issuing_card_apple_pay{issuing_card_apple_payEligible = issuing_card_apple_payEligible,
                                                                                 issuing_card_apple_payIneligible_reason = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.issuing_card_apple_pay.properties.ineligible_reason@ in the specification.
-- 
-- Reason the card is ineligible for Apple Pay
data Issuing_card_apple_payIneligible_reasonNonNullable =
   Issuing_card_apple_payIneligible_reasonNonNullableOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | Issuing_card_apple_payIneligible_reasonNonNullableTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | Issuing_card_apple_payIneligible_reasonNonNullableEnumMissing_agreement -- ^ Represents the JSON value @"missing_agreement"@
  | Issuing_card_apple_payIneligible_reasonNonNullableEnumMissing_cardholder_contact -- ^ Represents the JSON value @"missing_cardholder_contact"@
  | Issuing_card_apple_payIneligible_reasonNonNullableEnumUnsupported_region -- ^ Represents the JSON value @"unsupported_region"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing_card_apple_payIneligible_reasonNonNullable
    where {toJSON (Issuing_card_apple_payIneligible_reasonNonNullableOther val) = val;
           toJSON (Issuing_card_apple_payIneligible_reasonNonNullableTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (Issuing_card_apple_payIneligible_reasonNonNullableEnumMissing_agreement) = "missing_agreement";
           toJSON (Issuing_card_apple_payIneligible_reasonNonNullableEnumMissing_cardholder_contact) = "missing_cardholder_contact";
           toJSON (Issuing_card_apple_payIneligible_reasonNonNullableEnumUnsupported_region) = "unsupported_region"}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing_card_apple_payIneligible_reasonNonNullable
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "missing_agreement" -> Issuing_card_apple_payIneligible_reasonNonNullableEnumMissing_agreement
                                             | val GHC.Classes.== "missing_cardholder_contact" -> Issuing_card_apple_payIneligible_reasonNonNullableEnumMissing_cardholder_contact
                                             | val GHC.Classes.== "unsupported_region" -> Issuing_card_apple_payIneligible_reasonNonNullableEnumUnsupported_region
                                             | GHC.Base.otherwise -> Issuing_card_apple_payIneligible_reasonNonNullableOther val)}
