module Stripe.CustomerSession.Types.IssuingPersonalizationDesignRejectionReasons where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_personalization_design_rejection_reasons
instance Show Issuing_personalization_design_rejection_reasons
instance Eq Issuing_personalization_design_rejection_reasons
instance Data.Aeson.FromJSON Issuing_personalization_design_rejection_reasons
instance Data.Aeson.ToJSON Issuing_personalization_design_rejection_reasons
data Issuing_personalization_design_rejection_reasonsCard_logoNonNullable
instance Show Issuing_personalization_design_rejection_reasonsCard_logoNonNullable
instance Eq Issuing_personalization_design_rejection_reasonsCard_logoNonNullable
instance Data.Aeson.FromJSON Issuing_personalization_design_rejection_reasonsCard_logoNonNullable
instance Data.Aeson.ToJSON Issuing_personalization_design_rejection_reasonsCard_logoNonNullable
data Issuing_personalization_design_rejection_reasonsCarrier_textNonNullable
instance Show Issuing_personalization_design_rejection_reasonsCarrier_textNonNullable
instance Eq Issuing_personalization_design_rejection_reasonsCarrier_textNonNullable
instance Data.Aeson.FromJSON Issuing_personalization_design_rejection_reasonsCarrier_textNonNullable
instance Data.Aeson.ToJSON Issuing_personalization_design_rejection_reasonsCarrier_textNonNullable
