module Stripe.CustomerSession.Types.IssuingDisputeOtherEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_dispute_other_evidence
instance Show Issuing_dispute_other_evidence
instance Eq Issuing_dispute_other_evidence
instance Data.Aeson.FromJSON Issuing_dispute_other_evidence
instance Data.Aeson.ToJSON Issuing_dispute_other_evidence
data Issuing_dispute_other_evidenceAdditional_documentationNonNullableVariants
instance Show Issuing_dispute_other_evidenceAdditional_documentationNonNullableVariants
instance Eq Issuing_dispute_other_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.FromJSON Issuing_dispute_other_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.ToJSON Issuing_dispute_other_evidenceAdditional_documentationNonNullableVariants
data Issuing_dispute_other_evidenceProduct_typeNonNullable
instance Show Issuing_dispute_other_evidenceProduct_typeNonNullable
instance Eq Issuing_dispute_other_evidenceProduct_typeNonNullable
instance Data.Aeson.FromJSON Issuing_dispute_other_evidenceProduct_typeNonNullable
instance Data.Aeson.ToJSON Issuing_dispute_other_evidenceProduct_typeNonNullable
