module Stripe.CustomerSession.Types.IssuingDisputeDuplicateEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_dispute_duplicate_evidence
instance Show Issuing_dispute_duplicate_evidence
instance Eq Issuing_dispute_duplicate_evidence
instance Data.Aeson.FromJSON Issuing_dispute_duplicate_evidence
instance Data.Aeson.ToJSON Issuing_dispute_duplicate_evidence
data Issuing_dispute_duplicate_evidenceAdditional_documentationVariants
instance Show Issuing_dispute_duplicate_evidenceAdditional_documentationVariants
instance Eq Issuing_dispute_duplicate_evidenceAdditional_documentationVariants
instance Data.Aeson.FromJSON Issuing_dispute_duplicate_evidenceAdditional_documentationVariants
instance Data.Aeson.ToJSON Issuing_dispute_duplicate_evidenceAdditional_documentationVariants
data Issuing_dispute_duplicate_evidenceCard_statementVariants
instance Show Issuing_dispute_duplicate_evidenceCard_statementVariants
instance Eq Issuing_dispute_duplicate_evidenceCard_statementVariants
instance Data.Aeson.FromJSON Issuing_dispute_duplicate_evidenceCard_statementVariants
instance Data.Aeson.ToJSON Issuing_dispute_duplicate_evidenceCard_statementVariants
data Issuing_dispute_duplicate_evidenceCash_receiptVariants
instance Show Issuing_dispute_duplicate_evidenceCash_receiptVariants
instance Eq Issuing_dispute_duplicate_evidenceCash_receiptVariants
instance Data.Aeson.FromJSON Issuing_dispute_duplicate_evidenceCash_receiptVariants
instance Data.Aeson.ToJSON Issuing_dispute_duplicate_evidenceCash_receiptVariants
data Issuing_dispute_duplicate_evidenceCheck_imageVariants
instance Show Issuing_dispute_duplicate_evidenceCheck_imageVariants
instance Eq Issuing_dispute_duplicate_evidenceCheck_imageVariants
instance Data.Aeson.FromJSON Issuing_dispute_duplicate_evidenceCheck_imageVariants
instance Data.Aeson.ToJSON Issuing_dispute_duplicate_evidenceCheck_imageVariants
