module Stripe.CustomerSession.Types.Issuing_Transaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing'transaction
instance Show Issuing'transaction
instance Eq Issuing'transaction
instance Data.Aeson.FromJSON Issuing'transaction
instance Data.Aeson.ToJSON Issuing'transaction
data Issuing'transactionAmount_details
instance Show Issuing'transactionAmount_details
instance Eq Issuing'transactionAmount_details
instance Data.Aeson.FromJSON Issuing'transactionAmount_details
instance Data.Aeson.ToJSON Issuing'transactionAmount_details
data Issuing'transactionAuthorizationVariants
instance Show Issuing'transactionAuthorizationVariants
instance Eq Issuing'transactionAuthorizationVariants
instance Data.Aeson.FromJSON Issuing'transactionAuthorizationVariants
instance Data.Aeson.ToJSON Issuing'transactionAuthorizationVariants
data Issuing'transactionBalance_transactionVariants
instance Show Issuing'transactionBalance_transactionVariants
instance Eq Issuing'transactionBalance_transactionVariants
instance Data.Aeson.FromJSON Issuing'transactionBalance_transactionVariants
instance Data.Aeson.ToJSON Issuing'transactionBalance_transactionVariants
data Issuing'transactionCardVariants
instance Show Issuing'transactionCardVariants
instance Eq Issuing'transactionCardVariants
instance Data.Aeson.FromJSON Issuing'transactionCardVariants
instance Data.Aeson.ToJSON Issuing'transactionCardVariants
data Issuing'transactionCardholderVariants
instance Show Issuing'transactionCardholderVariants
instance Eq Issuing'transactionCardholderVariants
instance Data.Aeson.FromJSON Issuing'transactionCardholderVariants
instance Data.Aeson.ToJSON Issuing'transactionCardholderVariants
data Issuing'transactionDisputeVariants
instance Show Issuing'transactionDisputeVariants
instance Eq Issuing'transactionDisputeVariants
instance Data.Aeson.FromJSON Issuing'transactionDisputeVariants
instance Data.Aeson.ToJSON Issuing'transactionDisputeVariants
data Issuing'transactionNetwork_data
instance Show Issuing'transactionNetwork_data
instance Eq Issuing'transactionNetwork_data
instance Data.Aeson.FromJSON Issuing'transactionNetwork_data
instance Data.Aeson.ToJSON Issuing'transactionNetwork_data
data Issuing'transactionPurchase_details
instance Show Issuing'transactionPurchase_details
instance Eq Issuing'transactionPurchase_details
instance Data.Aeson.FromJSON Issuing'transactionPurchase_details
instance Data.Aeson.ToJSON Issuing'transactionPurchase_details
data Issuing'transactionPurchase_detailsFleet
instance Show Issuing'transactionPurchase_detailsFleet
instance Eq Issuing'transactionPurchase_detailsFleet
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsFleet
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsFleet
data Issuing'transactionPurchase_detailsFleetCardholder_prompt_data
instance Show Issuing'transactionPurchase_detailsFleetCardholder_prompt_data
instance Eq Issuing'transactionPurchase_detailsFleetCardholder_prompt_data
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsFleetCardholder_prompt_data
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsFleetCardholder_prompt_data
data Issuing'transactionPurchase_detailsFleetReported_breakdown
instance Show Issuing'transactionPurchase_detailsFleetReported_breakdown
instance Eq Issuing'transactionPurchase_detailsFleetReported_breakdown
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsFleetReported_breakdown
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsFleetReported_breakdown
data Issuing'transactionPurchase_detailsFleetReported_breakdownFuel
instance Show Issuing'transactionPurchase_detailsFleetReported_breakdownFuel
instance Eq Issuing'transactionPurchase_detailsFleetReported_breakdownFuel
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsFleetReported_breakdownFuel
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsFleetReported_breakdownFuel
data Issuing'transactionPurchase_detailsFleetReported_breakdownNon_fuel
instance Show Issuing'transactionPurchase_detailsFleetReported_breakdownNon_fuel
instance Eq Issuing'transactionPurchase_detailsFleetReported_breakdownNon_fuel
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsFleetReported_breakdownNon_fuel
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsFleetReported_breakdownNon_fuel
data Issuing'transactionPurchase_detailsFleetReported_breakdownTax
instance Show Issuing'transactionPurchase_detailsFleetReported_breakdownTax
instance Eq Issuing'transactionPurchase_detailsFleetReported_breakdownTax
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsFleetReported_breakdownTax
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsFleetReported_breakdownTax
data Issuing'transactionPurchase_detailsFlight
instance Show Issuing'transactionPurchase_detailsFlight
instance Eq Issuing'transactionPurchase_detailsFlight
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsFlight
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsFlight
data Issuing'transactionPurchase_detailsFuel
instance Show Issuing'transactionPurchase_detailsFuel
instance Eq Issuing'transactionPurchase_detailsFuel
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsFuel
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsFuel
data Issuing'transactionPurchase_detailsLodging
instance Show Issuing'transactionPurchase_detailsLodging
instance Eq Issuing'transactionPurchase_detailsLodging
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsLodging
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsLodging
data Issuing'transactionTokenVariants
instance Show Issuing'transactionTokenVariants
instance Eq Issuing'transactionTokenVariants
instance Data.Aeson.FromJSON Issuing'transactionTokenVariants
instance Data.Aeson.ToJSON Issuing'transactionTokenVariants
data Issuing'transactionTreasury
instance Show Issuing'transactionTreasury
instance Eq Issuing'transactionTreasury
instance Data.Aeson.FromJSON Issuing'transactionTreasury
instance Data.Aeson.ToJSON Issuing'transactionTreasury
