module Stripe.CustomerSession.Types.IssuingCardholderIndividual where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_cardholder_individual
instance Show Issuing_cardholder_individual
instance Eq Issuing_cardholder_individual
instance Data.Aeson.FromJSON Issuing_cardholder_individual
instance Data.Aeson.ToJSON Issuing_cardholder_individual
data Issuing_cardholder_individualCard_issuing
instance Show Issuing_cardholder_individualCard_issuing
instance Eq Issuing_cardholder_individualCard_issuing
instance Data.Aeson.FromJSON Issuing_cardholder_individualCard_issuing
instance Data.Aeson.ToJSON Issuing_cardholder_individualCard_issuing
data Issuing_cardholder_individualCard_issuingUser_terms_acceptance
instance Show Issuing_cardholder_individualCard_issuingUser_terms_acceptance
instance Eq Issuing_cardholder_individualCard_issuingUser_terms_acceptance
instance Data.Aeson.FromJSON Issuing_cardholder_individualCard_issuingUser_terms_acceptance
instance Data.Aeson.ToJSON Issuing_cardholder_individualCard_issuingUser_terms_acceptance
data Issuing_cardholder_individualDob
instance Show Issuing_cardholder_individualDob
instance Eq Issuing_cardholder_individualDob
instance Data.Aeson.FromJSON Issuing_cardholder_individualDob
instance Data.Aeson.ToJSON Issuing_cardholder_individualDob
data Issuing_cardholder_individualVerification
instance Show Issuing_cardholder_individualVerification
instance Eq Issuing_cardholder_individualVerification
instance Data.Aeson.FromJSON Issuing_cardholder_individualVerification
instance Data.Aeson.ToJSON Issuing_cardholder_individualVerification
data Issuing_cardholder_individualVerificationDocument
instance Show Issuing_cardholder_individualVerificationDocument
instance Eq Issuing_cardholder_individualVerificationDocument
instance Data.Aeson.FromJSON Issuing_cardholder_individualVerificationDocument
instance Data.Aeson.ToJSON Issuing_cardholder_individualVerificationDocument
data Issuing_cardholder_individualVerificationDocumentBackVariants
instance Show Issuing_cardholder_individualVerificationDocumentBackVariants
instance Eq Issuing_cardholder_individualVerificationDocumentBackVariants
instance Data.Aeson.FromJSON Issuing_cardholder_individualVerificationDocumentBackVariants
instance Data.Aeson.ToJSON Issuing_cardholder_individualVerificationDocumentBackVariants
data Issuing_cardholder_individualVerificationDocumentFrontVariants
instance Show Issuing_cardholder_individualVerificationDocumentFrontVariants
instance Eq Issuing_cardholder_individualVerificationDocumentFrontVariants
instance Data.Aeson.FromJSON Issuing_cardholder_individualVerificationDocumentFrontVariants
instance Data.Aeson.ToJSON Issuing_cardholder_individualVerificationDocumentFrontVariants
