module Stripe.CustomerSession.Types.IssuingCardSpendingLimit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_card_spending_limit
instance Show Issuing_card_spending_limit
instance Eq Issuing_card_spending_limit
instance Data.Aeson.FromJSON Issuing_card_spending_limit
instance Data.Aeson.ToJSON Issuing_card_spending_limit
data Issuing_card_spending_limitCategoriesNonNullable
instance Show Issuing_card_spending_limitCategoriesNonNullable
instance Eq Issuing_card_spending_limitCategoriesNonNullable
instance Data.Aeson.FromJSON Issuing_card_spending_limitCategoriesNonNullable
instance Data.Aeson.ToJSON Issuing_card_spending_limitCategoriesNonNullable
data Issuing_card_spending_limitInterval
instance Show Issuing_card_spending_limitInterval
instance Eq Issuing_card_spending_limitInterval
instance Data.Aeson.FromJSON Issuing_card_spending_limitInterval
instance Data.Aeson.ToJSON Issuing_card_spending_limitInterval
