module Stripe.CustomerSession.Types.Issuing_Cardholder where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing'cardholder
instance Show Issuing'cardholder
instance Eq Issuing'cardholder
instance Data.Aeson.FromJSON Issuing'cardholder
instance Data.Aeson.ToJSON Issuing'cardholder
data Issuing'cardholderCompanyNonNullable
instance Show Issuing'cardholderCompanyNonNullable
instance Eq Issuing'cardholderCompanyNonNullable
instance Data.Aeson.FromJSON Issuing'cardholderCompanyNonNullable
instance Data.Aeson.ToJSON Issuing'cardholderCompanyNonNullable
data Issuing'cardholderIndividualNonNullable
instance Show Issuing'cardholderIndividualNonNullable
instance Eq Issuing'cardholderIndividualNonNullable
instance Data.Aeson.FromJSON Issuing'cardholderIndividualNonNullable
instance Data.Aeson.ToJSON Issuing'cardholderIndividualNonNullable
data Issuing'cardholderIndividualNonNullableCard_issuingNonNullable
instance Show Issuing'cardholderIndividualNonNullableCard_issuingNonNullable
instance Eq Issuing'cardholderIndividualNonNullableCard_issuingNonNullable
instance Data.Aeson.FromJSON Issuing'cardholderIndividualNonNullableCard_issuingNonNullable
instance Data.Aeson.ToJSON Issuing'cardholderIndividualNonNullableCard_issuingNonNullable
data Issuing'cardholderIndividualNonNullableCard_issuingNonNullableUser_terms_acceptanceNonNullable
instance Show Issuing'cardholderIndividualNonNullableCard_issuingNonNullableUser_terms_acceptanceNonNullable
instance Eq Issuing'cardholderIndividualNonNullableCard_issuingNonNullableUser_terms_acceptanceNonNullable
instance Data.Aeson.FromJSON Issuing'cardholderIndividualNonNullableCard_issuingNonNullableUser_terms_acceptanceNonNullable
instance Data.Aeson.ToJSON Issuing'cardholderIndividualNonNullableCard_issuingNonNullableUser_terms_acceptanceNonNullable
data Issuing'cardholderIndividualNonNullableDobNonNullable
instance Show Issuing'cardholderIndividualNonNullableDobNonNullable
instance Eq Issuing'cardholderIndividualNonNullableDobNonNullable
instance Data.Aeson.FromJSON Issuing'cardholderIndividualNonNullableDobNonNullable
instance Data.Aeson.ToJSON Issuing'cardholderIndividualNonNullableDobNonNullable
data Issuing'cardholderIndividualNonNullableVerificationNonNullable
instance Show Issuing'cardholderIndividualNonNullableVerificationNonNullable
instance Eq Issuing'cardholderIndividualNonNullableVerificationNonNullable
instance Data.Aeson.FromJSON Issuing'cardholderIndividualNonNullableVerificationNonNullable
instance Data.Aeson.ToJSON Issuing'cardholderIndividualNonNullableVerificationNonNullable
data Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullable
instance Show Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullable
instance Eq Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullable
instance Data.Aeson.FromJSON Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullable
instance Data.Aeson.ToJSON Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullable
data Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullableBackNonNullableVariants
instance Show Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullableBackNonNullableVariants
instance Eq Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullableBackNonNullableVariants
instance Data.Aeson.FromJSON Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullableBackNonNullableVariants
instance Data.Aeson.ToJSON Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullableBackNonNullableVariants
data Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullableFrontNonNullableVariants
instance Show Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullableFrontNonNullableVariants
instance Eq Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullableFrontNonNullableVariants
instance Data.Aeson.FromJSON Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullableFrontNonNullableVariants
instance Data.Aeson.ToJSON Issuing'cardholderIndividualNonNullableVerificationNonNullableDocumentNonNullableFrontNonNullableVariants
data Issuing'cardholderPreferred_localesNonNullable
instance Show Issuing'cardholderPreferred_localesNonNullable
instance Eq Issuing'cardholderPreferred_localesNonNullable
instance Data.Aeson.FromJSON Issuing'cardholderPreferred_localesNonNullable
instance Data.Aeson.ToJSON Issuing'cardholderPreferred_localesNonNullable
data Issuing'cardholderSpending_controlsNonNullable
instance Show Issuing'cardholderSpending_controlsNonNullable
instance Eq Issuing'cardholderSpending_controlsNonNullable
instance Data.Aeson.FromJSON Issuing'cardholderSpending_controlsNonNullable
instance Data.Aeson.ToJSON Issuing'cardholderSpending_controlsNonNullable
data Issuing'cardholderSpending_controlsNonNullableAllowed_categoriesNonNullable
instance Show Issuing'cardholderSpending_controlsNonNullableAllowed_categoriesNonNullable
instance Eq Issuing'cardholderSpending_controlsNonNullableAllowed_categoriesNonNullable
instance Data.Aeson.FromJSON Issuing'cardholderSpending_controlsNonNullableAllowed_categoriesNonNullable
instance Data.Aeson.ToJSON Issuing'cardholderSpending_controlsNonNullableAllowed_categoriesNonNullable
data Issuing'cardholderSpending_controlsNonNullableBlocked_categoriesNonNullable
instance Show Issuing'cardholderSpending_controlsNonNullableBlocked_categoriesNonNullable
instance Eq Issuing'cardholderSpending_controlsNonNullableBlocked_categoriesNonNullable
instance Data.Aeson.FromJSON Issuing'cardholderSpending_controlsNonNullableBlocked_categoriesNonNullable
instance Data.Aeson.ToJSON Issuing'cardholderSpending_controlsNonNullableBlocked_categoriesNonNullable
data Issuing'cardholderStatus
instance Show Issuing'cardholderStatus
instance Eq Issuing'cardholderStatus
instance Data.Aeson.FromJSON Issuing'cardholderStatus
instance Data.Aeson.ToJSON Issuing'cardholderStatus
data Issuing'cardholderType
instance Show Issuing'cardholderType
instance Eq Issuing'cardholderType
instance Data.Aeson.FromJSON Issuing'cardholderType
instance Data.Aeson.ToJSON Issuing'cardholderType
