module Stripe.CustomerSession.Types.Issuing_Authorization where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing'authorization
instance Show Issuing'authorization
instance Eq Issuing'authorization
instance Data.Aeson.FromJSON Issuing'authorization
instance Data.Aeson.ToJSON Issuing'authorization
data Issuing'authorizationAmount_detailsNonNullable
instance Show Issuing'authorizationAmount_detailsNonNullable
instance Eq Issuing'authorizationAmount_detailsNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationAmount_detailsNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationAmount_detailsNonNullable
data Issuing'authorizationAuthorization_method
instance Show Issuing'authorizationAuthorization_method
instance Eq Issuing'authorizationAuthorization_method
instance Data.Aeson.FromJSON Issuing'authorizationAuthorization_method
instance Data.Aeson.ToJSON Issuing'authorizationAuthorization_method
data Issuing'authorizationCardholderNonNullableVariants
instance Show Issuing'authorizationCardholderNonNullableVariants
instance Eq Issuing'authorizationCardholderNonNullableVariants
instance Data.Aeson.FromJSON Issuing'authorizationCardholderNonNullableVariants
instance Data.Aeson.ToJSON Issuing'authorizationCardholderNonNullableVariants
data Issuing'authorizationFleetNonNullable
instance Show Issuing'authorizationFleetNonNullable
instance Eq Issuing'authorizationFleetNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationFleetNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationFleetNonNullable
data Issuing'authorizationFleetNonNullableCardholder_prompt_dataNonNullable
instance Show Issuing'authorizationFleetNonNullableCardholder_prompt_dataNonNullable
instance Eq Issuing'authorizationFleetNonNullableCardholder_prompt_dataNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationFleetNonNullableCardholder_prompt_dataNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationFleetNonNullableCardholder_prompt_dataNonNullable
data Issuing'authorizationFleetNonNullablePurchase_typeNonNullable
instance Show Issuing'authorizationFleetNonNullablePurchase_typeNonNullable
instance Eq Issuing'authorizationFleetNonNullablePurchase_typeNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationFleetNonNullablePurchase_typeNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationFleetNonNullablePurchase_typeNonNullable
data Issuing'authorizationFleetNonNullableReported_breakdownNonNullable
instance Show Issuing'authorizationFleetNonNullableReported_breakdownNonNullable
instance Eq Issuing'authorizationFleetNonNullableReported_breakdownNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationFleetNonNullableReported_breakdownNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationFleetNonNullableReported_breakdownNonNullable
data Issuing'authorizationFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Show Issuing'authorizationFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Eq Issuing'authorizationFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationFleetNonNullableReported_breakdownNonNullableFuelNonNullable
data Issuing'authorizationFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Show Issuing'authorizationFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Eq Issuing'authorizationFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
data Issuing'authorizationFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Show Issuing'authorizationFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Eq Issuing'authorizationFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationFleetNonNullableReported_breakdownNonNullableTaxNonNullable
data Issuing'authorizationFleetNonNullableService_typeNonNullable
instance Show Issuing'authorizationFleetNonNullableService_typeNonNullable
instance Eq Issuing'authorizationFleetNonNullableService_typeNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationFleetNonNullableService_typeNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationFleetNonNullableService_typeNonNullable
data Issuing'authorizationFuelNonNullable
instance Show Issuing'authorizationFuelNonNullable
instance Eq Issuing'authorizationFuelNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationFuelNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationFuelNonNullable
data Issuing'authorizationFuelNonNullableTypeNonNullable
instance Show Issuing'authorizationFuelNonNullableTypeNonNullable
instance Eq Issuing'authorizationFuelNonNullableTypeNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationFuelNonNullableTypeNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationFuelNonNullableTypeNonNullable
data Issuing'authorizationFuelNonNullableUnitNonNullable
instance Show Issuing'authorizationFuelNonNullableUnitNonNullable
instance Eq Issuing'authorizationFuelNonNullableUnitNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationFuelNonNullableUnitNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationFuelNonNullableUnitNonNullable
data Issuing'authorizationNetwork_dataNonNullable
instance Show Issuing'authorizationNetwork_dataNonNullable
instance Eq Issuing'authorizationNetwork_dataNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationNetwork_dataNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationNetwork_dataNonNullable
data Issuing'authorizationPending_requestNonNullable
instance Show Issuing'authorizationPending_requestNonNullable
instance Eq Issuing'authorizationPending_requestNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationPending_requestNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationPending_requestNonNullable
data Issuing'authorizationPending_requestNonNullableAmount_detailsNonNullable
instance Show Issuing'authorizationPending_requestNonNullableAmount_detailsNonNullable
instance Eq Issuing'authorizationPending_requestNonNullableAmount_detailsNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationPending_requestNonNullableAmount_detailsNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationPending_requestNonNullableAmount_detailsNonNullable
data Issuing'authorizationStatus
instance Show Issuing'authorizationStatus
instance Eq Issuing'authorizationStatus
instance Data.Aeson.FromJSON Issuing'authorizationStatus
instance Data.Aeson.ToJSON Issuing'authorizationStatus
data Issuing'authorizationTokenNonNullableVariants
instance Show Issuing'authorizationTokenNonNullableVariants
instance Eq Issuing'authorizationTokenNonNullableVariants
instance Data.Aeson.FromJSON Issuing'authorizationTokenNonNullableVariants
instance Data.Aeson.ToJSON Issuing'authorizationTokenNonNullableVariants
data Issuing'authorizationTreasuryNonNullable
instance Show Issuing'authorizationTreasuryNonNullable
instance Eq Issuing'authorizationTreasuryNonNullable
instance Data.Aeson.FromJSON Issuing'authorizationTreasuryNonNullable
instance Data.Aeson.ToJSON Issuing'authorizationTreasuryNonNullable
