module Stripe.CustomerSession.Types.IssuingDisputeCanceledEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_dispute_canceled_evidence
instance Show Issuing_dispute_canceled_evidence
instance Eq Issuing_dispute_canceled_evidence
instance Data.Aeson.FromJSON Issuing_dispute_canceled_evidence
instance Data.Aeson.ToJSON Issuing_dispute_canceled_evidence
data Issuing_dispute_canceled_evidenceAdditional_documentationVariants
instance Show Issuing_dispute_canceled_evidenceAdditional_documentationVariants
instance Eq Issuing_dispute_canceled_evidenceAdditional_documentationVariants
instance Data.Aeson.FromJSON Issuing_dispute_canceled_evidenceAdditional_documentationVariants
instance Data.Aeson.ToJSON Issuing_dispute_canceled_evidenceAdditional_documentationVariants
