module Stripe.CustomerSession.Types.IssuingNetworkTokenDevice where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_network_token_device
instance Show Issuing_network_token_device
instance Eq Issuing_network_token_device
instance Data.Aeson.FromJSON Issuing_network_token_device
instance Data.Aeson.ToJSON Issuing_network_token_device
