module Stripe.CustomerSession.Types.IssuingAuthorizationFleetData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_fleet_data
instance Show Issuing_authorization_fleet_data
instance Eq Issuing_authorization_fleet_data
instance Data.Aeson.FromJSON Issuing_authorization_fleet_data
instance Data.Aeson.ToJSON Issuing_authorization_fleet_data
data Issuing_authorization_fleet_dataCardholder_prompt_data
instance Show Issuing_authorization_fleet_dataCardholder_prompt_data
instance Eq Issuing_authorization_fleet_dataCardholder_prompt_data
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataCardholder_prompt_data
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataCardholder_prompt_data
data Issuing_authorization_fleet_dataReported_breakdown
instance Show Issuing_authorization_fleet_dataReported_breakdown
instance Eq Issuing_authorization_fleet_dataReported_breakdown
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataReported_breakdown
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataReported_breakdown
data Issuing_authorization_fleet_dataReported_breakdownFuel
instance Show Issuing_authorization_fleet_dataReported_breakdownFuel
instance Eq Issuing_authorization_fleet_dataReported_breakdownFuel
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataReported_breakdownFuel
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataReported_breakdownFuel
data Issuing_authorization_fleet_dataReported_breakdownNon_fuel
instance Show Issuing_authorization_fleet_dataReported_breakdownNon_fuel
instance Eq Issuing_authorization_fleet_dataReported_breakdownNon_fuel
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataReported_breakdownNon_fuel
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataReported_breakdownNon_fuel
data Issuing_authorization_fleet_dataReported_breakdownTax
instance Show Issuing_authorization_fleet_dataReported_breakdownTax
instance Eq Issuing_authorization_fleet_dataReported_breakdownTax
instance Data.Aeson.FromJSON Issuing_authorization_fleet_dataReported_breakdownTax
instance Data.Aeson.ToJSON Issuing_authorization_fleet_dataReported_breakdownTax
