module Stripe.CustomerSession.Types.IssuingAuthorizationVerificationData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_verification_data
instance Show Issuing_authorization_verification_data
instance Eq Issuing_authorization_verification_data
instance Data.Aeson.FromJSON Issuing_authorization_verification_data
instance Data.Aeson.ToJSON Issuing_authorization_verification_data
data Issuing_authorization_verification_dataAuthentication_exemption
instance Show Issuing_authorization_verification_dataAuthentication_exemption
instance Eq Issuing_authorization_verification_dataAuthentication_exemption
instance Data.Aeson.FromJSON Issuing_authorization_verification_dataAuthentication_exemption
instance Data.Aeson.ToJSON Issuing_authorization_verification_dataAuthentication_exemption
data Issuing_authorization_verification_dataThree_d_secure
instance Show Issuing_authorization_verification_dataThree_d_secure
instance Eq Issuing_authorization_verification_dataThree_d_secure
instance Data.Aeson.FromJSON Issuing_authorization_verification_dataThree_d_secure
instance Data.Aeson.ToJSON Issuing_authorization_verification_dataThree_d_secure
