module Stripe.CustomerSession.Types.IssuingCardholderVerification where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_cardholder_verification
instance Show Issuing_cardholder_verification
instance Eq Issuing_cardholder_verification
instance Data.Aeson.FromJSON Issuing_cardholder_verification
instance Data.Aeson.ToJSON Issuing_cardholder_verification
data Issuing_cardholder_verificationDocumentNonNullable
instance Show Issuing_cardholder_verificationDocumentNonNullable
instance Eq Issuing_cardholder_verificationDocumentNonNullable
instance Data.Aeson.FromJSON Issuing_cardholder_verificationDocumentNonNullable
instance Data.Aeson.ToJSON Issuing_cardholder_verificationDocumentNonNullable
data Issuing_cardholder_verificationDocumentNonNullableBackNonNullableVariants
instance Show Issuing_cardholder_verificationDocumentNonNullableBackNonNullableVariants
instance Eq Issuing_cardholder_verificationDocumentNonNullableBackNonNullableVariants
instance Data.Aeson.FromJSON Issuing_cardholder_verificationDocumentNonNullableBackNonNullableVariants
instance Data.Aeson.ToJSON Issuing_cardholder_verificationDocumentNonNullableBackNonNullableVariants
data Issuing_cardholder_verificationDocumentNonNullableFrontNonNullableVariants
instance Show Issuing_cardholder_verificationDocumentNonNullableFrontNonNullableVariants
instance Eq Issuing_cardholder_verificationDocumentNonNullableFrontNonNullableVariants
instance Data.Aeson.FromJSON Issuing_cardholder_verificationDocumentNonNullableFrontNonNullableVariants
instance Data.Aeson.ToJSON Issuing_cardholder_verificationDocumentNonNullableFrontNonNullableVariants
