module Stripe.CustomerSession.Types.IssuingPersonalizationDesignRejectionReasons where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_personalization_design_rejection_reasons
instance Show Issuing_personalization_design_rejection_reasons
instance Eq Issuing_personalization_design_rejection_reasons
instance Data.Aeson.FromJSON Issuing_personalization_design_rejection_reasons
instance Data.Aeson.ToJSON Issuing_personalization_design_rejection_reasons
