module Stripe.CustomerSession.Types.IssuingCardholderSpendingLimit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_cardholder_spending_limit
instance Show Issuing_cardholder_spending_limit
instance Eq Issuing_cardholder_spending_limit
instance Data.Aeson.FromJSON Issuing_cardholder_spending_limit
instance Data.Aeson.ToJSON Issuing_cardholder_spending_limit
