module Stripe.CustomerSession.Types.Issuing_Authorization where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing'authorization
instance Show Issuing'authorization
instance Eq Issuing'authorization
instance Data.Aeson.FromJSON Issuing'authorization
instance Data.Aeson.ToJSON Issuing'authorization
data Issuing'authorizationAmount_details
instance Show Issuing'authorizationAmount_details
instance Eq Issuing'authorizationAmount_details
instance Data.Aeson.FromJSON Issuing'authorizationAmount_details
instance Data.Aeson.ToJSON Issuing'authorizationAmount_details
data Issuing'authorizationCardholderVariants
instance Show Issuing'authorizationCardholderVariants
instance Eq Issuing'authorizationCardholderVariants
instance Data.Aeson.FromJSON Issuing'authorizationCardholderVariants
instance Data.Aeson.ToJSON Issuing'authorizationCardholderVariants
data Issuing'authorizationFleet
instance Show Issuing'authorizationFleet
instance Eq Issuing'authorizationFleet
instance Data.Aeson.FromJSON Issuing'authorizationFleet
instance Data.Aeson.ToJSON Issuing'authorizationFleet
data Issuing'authorizationFleetCardholder_prompt_data
instance Show Issuing'authorizationFleetCardholder_prompt_data
instance Eq Issuing'authorizationFleetCardholder_prompt_data
instance Data.Aeson.FromJSON Issuing'authorizationFleetCardholder_prompt_data
instance Data.Aeson.ToJSON Issuing'authorizationFleetCardholder_prompt_data
data Issuing'authorizationFleetReported_breakdown
instance Show Issuing'authorizationFleetReported_breakdown
instance Eq Issuing'authorizationFleetReported_breakdown
instance Data.Aeson.FromJSON Issuing'authorizationFleetReported_breakdown
instance Data.Aeson.ToJSON Issuing'authorizationFleetReported_breakdown
data Issuing'authorizationFleetReported_breakdownFuel
instance Show Issuing'authorizationFleetReported_breakdownFuel
instance Eq Issuing'authorizationFleetReported_breakdownFuel
instance Data.Aeson.FromJSON Issuing'authorizationFleetReported_breakdownFuel
instance Data.Aeson.ToJSON Issuing'authorizationFleetReported_breakdownFuel
data Issuing'authorizationFleetReported_breakdownNon_fuel
instance Show Issuing'authorizationFleetReported_breakdownNon_fuel
instance Eq Issuing'authorizationFleetReported_breakdownNon_fuel
instance Data.Aeson.FromJSON Issuing'authorizationFleetReported_breakdownNon_fuel
instance Data.Aeson.ToJSON Issuing'authorizationFleetReported_breakdownNon_fuel
data Issuing'authorizationFleetReported_breakdownTax
instance Show Issuing'authorizationFleetReported_breakdownTax
instance Eq Issuing'authorizationFleetReported_breakdownTax
instance Data.Aeson.FromJSON Issuing'authorizationFleetReported_breakdownTax
instance Data.Aeson.ToJSON Issuing'authorizationFleetReported_breakdownTax
data Issuing'authorizationFuel
instance Show Issuing'authorizationFuel
instance Eq Issuing'authorizationFuel
instance Data.Aeson.FromJSON Issuing'authorizationFuel
instance Data.Aeson.ToJSON Issuing'authorizationFuel
data Issuing'authorizationNetwork_data
instance Show Issuing'authorizationNetwork_data
instance Eq Issuing'authorizationNetwork_data
instance Data.Aeson.FromJSON Issuing'authorizationNetwork_data
instance Data.Aeson.ToJSON Issuing'authorizationNetwork_data
data Issuing'authorizationPending_request
instance Show Issuing'authorizationPending_request
instance Eq Issuing'authorizationPending_request
instance Data.Aeson.FromJSON Issuing'authorizationPending_request
instance Data.Aeson.ToJSON Issuing'authorizationPending_request
data Issuing'authorizationPending_requestAmount_details
instance Show Issuing'authorizationPending_requestAmount_details
instance Eq Issuing'authorizationPending_requestAmount_details
instance Data.Aeson.FromJSON Issuing'authorizationPending_requestAmount_details
instance Data.Aeson.ToJSON Issuing'authorizationPending_requestAmount_details
data Issuing'authorizationTokenVariants
instance Show Issuing'authorizationTokenVariants
instance Eq Issuing'authorizationTokenVariants
instance Data.Aeson.FromJSON Issuing'authorizationTokenVariants
instance Data.Aeson.ToJSON Issuing'authorizationTokenVariants
data Issuing'authorizationTreasury
instance Show Issuing'authorizationTreasury
instance Eq Issuing'authorizationTreasury
instance Data.Aeson.FromJSON Issuing'authorizationTreasury
instance Data.Aeson.ToJSON Issuing'authorizationTreasury
