-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema IssuingNetworkTokenNetworkData
module Stripe.CustomerSession.Types.IssuingNetworkTokenNetworkData where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingNetworkTokenDevice
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingNetworkTokenMastercard
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingNetworkTokenVisa
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingNetworkTokenWalletProvider

-- | Defines the object schema located at @components.schemas.issuing_network_token_network_data@ in the specification.
-- 
-- 
data Issuing_network_token_network_data = Issuing_network_token_network_data {
  -- | device: 
  issuing_network_token_network_dataDevice :: (GHC.Maybe.Maybe Issuing_network_token_device)
  -- | mastercard: 
  , issuing_network_token_network_dataMastercard :: (GHC.Maybe.Maybe Issuing_network_token_mastercard)
  -- | type: The network that the token is associated with. An additional hash is included with a name matching this value, containing tokenization data specific to the card network.
  , issuing_network_token_network_dataType :: Issuing_network_token_network_dataType
  -- | visa: 
  , issuing_network_token_network_dataVisa :: (GHC.Maybe.Maybe Issuing_network_token_visa)
  -- | wallet_provider: 
  , issuing_network_token_network_dataWallet_provider :: (GHC.Maybe.Maybe Issuing_network_token_wallet_provider)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing_network_token_network_data
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("device" Data.Aeson.Types.ToJSON..=)) (issuing_network_token_network_dataDevice obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("mastercard" Data.Aeson.Types.ToJSON..=)) (issuing_network_token_network_dataMastercard obj) : ["type" Data.Aeson.Types.ToJSON..= issuing_network_token_network_dataType obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("visa" Data.Aeson.Types.ToJSON..=)) (issuing_network_token_network_dataVisa obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("wallet_provider" Data.Aeson.Types.ToJSON..=)) (issuing_network_token_network_dataWallet_provider obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("device" Data.Aeson.Types.ToJSON..=)) (issuing_network_token_network_dataDevice obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("mastercard" Data.Aeson.Types.ToJSON..=)) (issuing_network_token_network_dataMastercard obj) : ["type" Data.Aeson.Types.ToJSON..= issuing_network_token_network_dataType obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("visa" Data.Aeson.Types.ToJSON..=)) (issuing_network_token_network_dataVisa obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("wallet_provider" Data.Aeson.Types.ToJSON..=)) (issuing_network_token_network_dataWallet_provider obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing_network_token_network_data
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing_network_token_network_data" (\obj -> ((((GHC.Base.pure Issuing_network_token_network_data GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "device")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "mastercard")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "visa")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "wallet_provider"))}
-- | Create a new 'Issuing_network_token_network_data' with all required fields.
mkIssuing_network_token_network_data :: Issuing_network_token_network_dataType -- ^ 'issuing_network_token_network_dataType'
  -> Issuing_network_token_network_data
mkIssuing_network_token_network_data issuing_network_token_network_dataType = Issuing_network_token_network_data{issuing_network_token_network_dataDevice = GHC.Maybe.Nothing,
                                                                                                                 issuing_network_token_network_dataMastercard = GHC.Maybe.Nothing,
                                                                                                                 issuing_network_token_network_dataType = issuing_network_token_network_dataType,
                                                                                                                 issuing_network_token_network_dataVisa = GHC.Maybe.Nothing,
                                                                                                                 issuing_network_token_network_dataWallet_provider = GHC.Maybe.Nothing}
-- | Defines the enum schema located at @components.schemas.issuing_network_token_network_data.properties.type@ in the specification.
-- 
-- The network that the token is associated with. An additional hash is included with a name matching this value, containing tokenization data specific to the card network.
data Issuing_network_token_network_dataType =
   Issuing_network_token_network_dataTypeOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | Issuing_network_token_network_dataTypeTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | Issuing_network_token_network_dataTypeEnumMastercard -- ^ Represents the JSON value @"mastercard"@
  | Issuing_network_token_network_dataTypeEnumVisa -- ^ Represents the JSON value @"visa"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing_network_token_network_dataType
    where {toJSON (Issuing_network_token_network_dataTypeOther val) = val;
           toJSON (Issuing_network_token_network_dataTypeTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (Issuing_network_token_network_dataTypeEnumMastercard) = "mastercard";
           toJSON (Issuing_network_token_network_dataTypeEnumVisa) = "visa"}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing_network_token_network_dataType
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "mastercard" -> Issuing_network_token_network_dataTypeEnumMastercard
                                             | val GHC.Classes.== "visa" -> Issuing_network_token_network_dataTypeEnumVisa
                                             | GHC.Base.otherwise -> Issuing_network_token_network_dataTypeOther val)}
