module Stripe.CustomerSession.Types.IssuingTransactionFleetData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_transaction_fleet_data
instance Show Issuing_transaction_fleet_data
instance Eq Issuing_transaction_fleet_data
instance Data.Aeson.FromJSON Issuing_transaction_fleet_data
instance Data.Aeson.ToJSON Issuing_transaction_fleet_data
data Issuing_transaction_fleet_dataCardholder_prompt_dataNonNullable
instance Show Issuing_transaction_fleet_dataCardholder_prompt_dataNonNullable
instance Eq Issuing_transaction_fleet_dataCardholder_prompt_dataNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_fleet_dataCardholder_prompt_dataNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_fleet_dataCardholder_prompt_dataNonNullable
data Issuing_transaction_fleet_dataReported_breakdownNonNullable
instance Show Issuing_transaction_fleet_dataReported_breakdownNonNullable
instance Eq Issuing_transaction_fleet_dataReported_breakdownNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_fleet_dataReported_breakdownNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_fleet_dataReported_breakdownNonNullable
data Issuing_transaction_fleet_dataReported_breakdownNonNullableFuelNonNullable
instance Show Issuing_transaction_fleet_dataReported_breakdownNonNullableFuelNonNullable
instance Eq Issuing_transaction_fleet_dataReported_breakdownNonNullableFuelNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_fleet_dataReported_breakdownNonNullableFuelNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_fleet_dataReported_breakdownNonNullableFuelNonNullable
data Issuing_transaction_fleet_dataReported_breakdownNonNullableNon_fuelNonNullable
instance Show Issuing_transaction_fleet_dataReported_breakdownNonNullableNon_fuelNonNullable
instance Eq Issuing_transaction_fleet_dataReported_breakdownNonNullableNon_fuelNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_fleet_dataReported_breakdownNonNullableNon_fuelNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_fleet_dataReported_breakdownNonNullableNon_fuelNonNullable
data Issuing_transaction_fleet_dataReported_breakdownNonNullableTaxNonNullable
instance Show Issuing_transaction_fleet_dataReported_breakdownNonNullableTaxNonNullable
instance Eq Issuing_transaction_fleet_dataReported_breakdownNonNullableTaxNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_fleet_dataReported_breakdownNonNullableTaxNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_fleet_dataReported_breakdownNonNullableTaxNonNullable
