module Stripe.CustomerSession.Types.IssuingCardAuthorizationControls where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_card_authorization_controls
instance Show Issuing_card_authorization_controls
instance Eq Issuing_card_authorization_controls
instance Data.Aeson.FromJSON Issuing_card_authorization_controls
instance Data.Aeson.ToJSON Issuing_card_authorization_controls
