module Stripe.CustomerSession.Types.IssuingDisputeNoValidAuthorizationEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_dispute_no_valid_authorization_evidence
instance Show Issuing_dispute_no_valid_authorization_evidence
instance Eq Issuing_dispute_no_valid_authorization_evidence
instance Data.Aeson.FromJSON Issuing_dispute_no_valid_authorization_evidence
instance Data.Aeson.ToJSON Issuing_dispute_no_valid_authorization_evidence
data Issuing_dispute_no_valid_authorization_evidenceAdditional_documentationVariants
instance Show Issuing_dispute_no_valid_authorization_evidenceAdditional_documentationVariants
instance Eq Issuing_dispute_no_valid_authorization_evidenceAdditional_documentationVariants
instance Data.Aeson.FromJSON Issuing_dispute_no_valid_authorization_evidenceAdditional_documentationVariants
instance Data.Aeson.ToJSON Issuing_dispute_no_valid_authorization_evidenceAdditional_documentationVariants
