module Stripe.CustomerSession.Types.IssuingCardholderCardIssuing where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_cardholder_card_issuing
instance Show Issuing_cardholder_card_issuing
instance Eq Issuing_cardholder_card_issuing
instance Data.Aeson.FromJSON Issuing_cardholder_card_issuing
instance Data.Aeson.ToJSON Issuing_cardholder_card_issuing
data Issuing_cardholder_card_issuingUser_terms_acceptanceNonNullable
instance Show Issuing_cardholder_card_issuingUser_terms_acceptanceNonNullable
instance Eq Issuing_cardholder_card_issuingUser_terms_acceptanceNonNullable
instance Data.Aeson.FromJSON Issuing_cardholder_card_issuingUser_terms_acceptanceNonNullable
instance Data.Aeson.ToJSON Issuing_cardholder_card_issuingUser_terms_acceptanceNonNullable
