module Stripe.CustomerSession.Types.IssuingCardholderIndividual where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_cardholder_individual
instance Show Issuing_cardholder_individual
instance Eq Issuing_cardholder_individual
instance Data.Aeson.FromJSON Issuing_cardholder_individual
instance Data.Aeson.ToJSON Issuing_cardholder_individual
data Issuing_cardholder_individualCard_issuingNonNullable
instance Show Issuing_cardholder_individualCard_issuingNonNullable
instance Eq Issuing_cardholder_individualCard_issuingNonNullable
instance Data.Aeson.FromJSON Issuing_cardholder_individualCard_issuingNonNullable
instance Data.Aeson.ToJSON Issuing_cardholder_individualCard_issuingNonNullable
data Issuing_cardholder_individualCard_issuingNonNullableUser_terms_acceptanceNonNullable
instance Show Issuing_cardholder_individualCard_issuingNonNullableUser_terms_acceptanceNonNullable
instance Eq Issuing_cardholder_individualCard_issuingNonNullableUser_terms_acceptanceNonNullable
instance Data.Aeson.FromJSON Issuing_cardholder_individualCard_issuingNonNullableUser_terms_acceptanceNonNullable
instance Data.Aeson.ToJSON Issuing_cardholder_individualCard_issuingNonNullableUser_terms_acceptanceNonNullable
data Issuing_cardholder_individualDobNonNullable
instance Show Issuing_cardholder_individualDobNonNullable
instance Eq Issuing_cardholder_individualDobNonNullable
instance Data.Aeson.FromJSON Issuing_cardholder_individualDobNonNullable
instance Data.Aeson.ToJSON Issuing_cardholder_individualDobNonNullable
data Issuing_cardholder_individualVerificationNonNullable
instance Show Issuing_cardholder_individualVerificationNonNullable
instance Eq Issuing_cardholder_individualVerificationNonNullable
instance Data.Aeson.FromJSON Issuing_cardholder_individualVerificationNonNullable
instance Data.Aeson.ToJSON Issuing_cardholder_individualVerificationNonNullable
data Issuing_cardholder_individualVerificationNonNullableDocumentNonNullable
instance Show Issuing_cardholder_individualVerificationNonNullableDocumentNonNullable
instance Eq Issuing_cardholder_individualVerificationNonNullableDocumentNonNullable
instance Data.Aeson.FromJSON Issuing_cardholder_individualVerificationNonNullableDocumentNonNullable
instance Data.Aeson.ToJSON Issuing_cardholder_individualVerificationNonNullableDocumentNonNullable
data Issuing_cardholder_individualVerificationNonNullableDocumentNonNullableBackNonNullableVariants
instance Show Issuing_cardholder_individualVerificationNonNullableDocumentNonNullableBackNonNullableVariants
instance Eq Issuing_cardholder_individualVerificationNonNullableDocumentNonNullableBackNonNullableVariants
instance Data.Aeson.FromJSON Issuing_cardholder_individualVerificationNonNullableDocumentNonNullableBackNonNullableVariants
instance Data.Aeson.ToJSON Issuing_cardholder_individualVerificationNonNullableDocumentNonNullableBackNonNullableVariants
data Issuing_cardholder_individualVerificationNonNullableDocumentNonNullableFrontNonNullableVariants
instance Show Issuing_cardholder_individualVerificationNonNullableDocumentNonNullableFrontNonNullableVariants
instance Eq Issuing_cardholder_individualVerificationNonNullableDocumentNonNullableFrontNonNullableVariants
instance Data.Aeson.FromJSON Issuing_cardholder_individualVerificationNonNullableDocumentNonNullableFrontNonNullableVariants
instance Data.Aeson.ToJSON Issuing_cardholder_individualVerificationNonNullableDocumentNonNullableFrontNonNullableVariants
