module Stripe.CustomerSession.Types.Issuing_PersonalizationDesign where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing'personalization_design
instance Show Issuing'personalization_design
instance Eq Issuing'personalization_design
instance Data.Aeson.FromJSON Issuing'personalization_design
instance Data.Aeson.ToJSON Issuing'personalization_design
data Issuing'personalization_designCard_logoNonNullableVariants
instance Show Issuing'personalization_designCard_logoNonNullableVariants
instance Eq Issuing'personalization_designCard_logoNonNullableVariants
instance Data.Aeson.FromJSON Issuing'personalization_designCard_logoNonNullableVariants
instance Data.Aeson.ToJSON Issuing'personalization_designCard_logoNonNullableVariants
data Issuing'personalization_designCarrier_textNonNullable
instance Show Issuing'personalization_designCarrier_textNonNullable
instance Eq Issuing'personalization_designCarrier_textNonNullable
instance Data.Aeson.FromJSON Issuing'personalization_designCarrier_textNonNullable
instance Data.Aeson.ToJSON Issuing'personalization_designCarrier_textNonNullable
data Issuing'personalization_designPhysical_bundleVariants
instance Show Issuing'personalization_designPhysical_bundleVariants
instance Eq Issuing'personalization_designPhysical_bundleVariants
instance Data.Aeson.FromJSON Issuing'personalization_designPhysical_bundleVariants
instance Data.Aeson.ToJSON Issuing'personalization_designPhysical_bundleVariants
data Issuing'personalization_designStatus
instance Show Issuing'personalization_designStatus
instance Eq Issuing'personalization_designStatus
instance Data.Aeson.FromJSON Issuing'personalization_designStatus
instance Data.Aeson.ToJSON Issuing'personalization_designStatus
