module Stripe.CustomerSession.Types.IssuingTransactionPurchaseDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_transaction_purchase_details
instance Show Issuing_transaction_purchase_details
instance Eq Issuing_transaction_purchase_details
instance Data.Aeson.FromJSON Issuing_transaction_purchase_details
instance Data.Aeson.ToJSON Issuing_transaction_purchase_details
data Issuing_transaction_purchase_detailsFleetNonNullable
instance Show Issuing_transaction_purchase_detailsFleetNonNullable
instance Eq Issuing_transaction_purchase_detailsFleetNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleetNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleetNonNullable
data Issuing_transaction_purchase_detailsFleetNonNullableCardholder_prompt_dataNonNullable
instance Show Issuing_transaction_purchase_detailsFleetNonNullableCardholder_prompt_dataNonNullable
instance Eq Issuing_transaction_purchase_detailsFleetNonNullableCardholder_prompt_dataNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleetNonNullableCardholder_prompt_dataNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleetNonNullableCardholder_prompt_dataNonNullable
data Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullable
instance Show Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullable
instance Eq Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullable
data Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Show Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Eq Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableFuelNonNullable
data Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Show Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Eq Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
data Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Show Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Eq Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleetNonNullableReported_breakdownNonNullableTaxNonNullable
data Issuing_transaction_purchase_detailsFlightNonNullable
instance Show Issuing_transaction_purchase_detailsFlightNonNullable
instance Eq Issuing_transaction_purchase_detailsFlightNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFlightNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFlightNonNullable
data Issuing_transaction_purchase_detailsFuelNonNullable
instance Show Issuing_transaction_purchase_detailsFuelNonNullable
instance Eq Issuing_transaction_purchase_detailsFuelNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFuelNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFuelNonNullable
data Issuing_transaction_purchase_detailsLodgingNonNullable
instance Show Issuing_transaction_purchase_detailsLodgingNonNullable
instance Eq Issuing_transaction_purchase_detailsLodgingNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsLodgingNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsLodgingNonNullable
