module Stripe.CustomerSession.Types.IssuingDisputeMerchandiseNotAsDescribedEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_dispute_merchandise_not_as_described_evidence
instance Show Issuing_dispute_merchandise_not_as_described_evidence
instance Eq Issuing_dispute_merchandise_not_as_described_evidence
instance Data.Aeson.FromJSON Issuing_dispute_merchandise_not_as_described_evidence
instance Data.Aeson.ToJSON Issuing_dispute_merchandise_not_as_described_evidence
data Issuing_dispute_merchandise_not_as_described_evidenceAdditional_documentationNonNullableVariants
instance Show Issuing_dispute_merchandise_not_as_described_evidenceAdditional_documentationNonNullableVariants
instance Eq Issuing_dispute_merchandise_not_as_described_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.FromJSON Issuing_dispute_merchandise_not_as_described_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.ToJSON Issuing_dispute_merchandise_not_as_described_evidenceAdditional_documentationNonNullableVariants
data Issuing_dispute_merchandise_not_as_described_evidenceReturn_statusNonNullable
instance Show Issuing_dispute_merchandise_not_as_described_evidenceReturn_statusNonNullable
instance Eq Issuing_dispute_merchandise_not_as_described_evidenceReturn_statusNonNullable
instance Data.Aeson.FromJSON Issuing_dispute_merchandise_not_as_described_evidenceReturn_statusNonNullable
instance Data.Aeson.ToJSON Issuing_dispute_merchandise_not_as_described_evidenceReturn_statusNonNullable
