module Stripe.CustomerSession.Types.IssuingCardholderRequirements where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_cardholder_requirements
instance Show Issuing_cardholder_requirements
instance Eq Issuing_cardholder_requirements
instance Data.Aeson.FromJSON Issuing_cardholder_requirements
instance Data.Aeson.ToJSON Issuing_cardholder_requirements
data Issuing_cardholder_requirementsDisabled_reasonNonNullable
instance Show Issuing_cardholder_requirementsDisabled_reasonNonNullable
instance Eq Issuing_cardholder_requirementsDisabled_reasonNonNullable
instance Data.Aeson.FromJSON Issuing_cardholder_requirementsDisabled_reasonNonNullable
instance Data.Aeson.ToJSON Issuing_cardholder_requirementsDisabled_reasonNonNullable
data Issuing_cardholder_requirementsPast_dueNonNullable
instance Show Issuing_cardholder_requirementsPast_dueNonNullable
instance Eq Issuing_cardholder_requirementsPast_dueNonNullable
instance Data.Aeson.FromJSON Issuing_cardholder_requirementsPast_dueNonNullable
instance Data.Aeson.ToJSON Issuing_cardholder_requirementsPast_dueNonNullable
