module Stripe.CustomerSession.Types.Issuing_Transaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing'transaction
instance Show Issuing'transaction
instance Eq Issuing'transaction
instance Data.Aeson.FromJSON Issuing'transaction
instance Data.Aeson.ToJSON Issuing'transaction
data Issuing'transactionAmount_detailsNonNullable
instance Show Issuing'transactionAmount_detailsNonNullable
instance Eq Issuing'transactionAmount_detailsNonNullable
instance Data.Aeson.FromJSON Issuing'transactionAmount_detailsNonNullable
instance Data.Aeson.ToJSON Issuing'transactionAmount_detailsNonNullable
data Issuing'transactionAuthorizationNonNullableVariants
instance Show Issuing'transactionAuthorizationNonNullableVariants
instance Eq Issuing'transactionAuthorizationNonNullableVariants
instance Data.Aeson.FromJSON Issuing'transactionAuthorizationNonNullableVariants
instance Data.Aeson.ToJSON Issuing'transactionAuthorizationNonNullableVariants
data Issuing'transactionBalance_transactionNonNullableVariants
instance Show Issuing'transactionBalance_transactionNonNullableVariants
instance Eq Issuing'transactionBalance_transactionNonNullableVariants
instance Data.Aeson.FromJSON Issuing'transactionBalance_transactionNonNullableVariants
instance Data.Aeson.ToJSON Issuing'transactionBalance_transactionNonNullableVariants
data Issuing'transactionCardVariants
instance Show Issuing'transactionCardVariants
instance Eq Issuing'transactionCardVariants
instance Data.Aeson.FromJSON Issuing'transactionCardVariants
instance Data.Aeson.ToJSON Issuing'transactionCardVariants
data Issuing'transactionCardholderNonNullableVariants
instance Show Issuing'transactionCardholderNonNullableVariants
instance Eq Issuing'transactionCardholderNonNullableVariants
instance Data.Aeson.FromJSON Issuing'transactionCardholderNonNullableVariants
instance Data.Aeson.ToJSON Issuing'transactionCardholderNonNullableVariants
data Issuing'transactionDisputeNonNullableVariants
instance Show Issuing'transactionDisputeNonNullableVariants
instance Eq Issuing'transactionDisputeNonNullableVariants
instance Data.Aeson.FromJSON Issuing'transactionDisputeNonNullableVariants
instance Data.Aeson.ToJSON Issuing'transactionDisputeNonNullableVariants
data Issuing'transactionNetwork_dataNonNullable
instance Show Issuing'transactionNetwork_dataNonNullable
instance Eq Issuing'transactionNetwork_dataNonNullable
instance Data.Aeson.FromJSON Issuing'transactionNetwork_dataNonNullable
instance Data.Aeson.ToJSON Issuing'transactionNetwork_dataNonNullable
data Issuing'transactionPurchase_detailsNonNullable
instance Show Issuing'transactionPurchase_detailsNonNullable
instance Eq Issuing'transactionPurchase_detailsNonNullable
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsNonNullable
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsNonNullable
data Issuing'transactionPurchase_detailsNonNullableFleetNonNullable
instance Show Issuing'transactionPurchase_detailsNonNullableFleetNonNullable
instance Eq Issuing'transactionPurchase_detailsNonNullableFleetNonNullable
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullable
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullable
data Issuing'transactionPurchase_detailsNonNullableFleetNonNullableCardholder_prompt_dataNonNullable
instance Show Issuing'transactionPurchase_detailsNonNullableFleetNonNullableCardholder_prompt_dataNonNullable
instance Eq Issuing'transactionPurchase_detailsNonNullableFleetNonNullableCardholder_prompt_dataNonNullable
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullableCardholder_prompt_dataNonNullable
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullableCardholder_prompt_dataNonNullable
data Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullable
instance Show Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullable
instance Eq Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullable
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullable
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullable
data Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Show Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Eq Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableFuelNonNullable
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableFuelNonNullable
data Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Show Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Eq Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableNon_fuelNonNullable
data Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Show Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Eq Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableTaxNonNullable
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsNonNullableFleetNonNullableReported_breakdownNonNullableTaxNonNullable
data Issuing'transactionPurchase_detailsNonNullableFlightNonNullable
instance Show Issuing'transactionPurchase_detailsNonNullableFlightNonNullable
instance Eq Issuing'transactionPurchase_detailsNonNullableFlightNonNullable
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsNonNullableFlightNonNullable
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsNonNullableFlightNonNullable
data Issuing'transactionPurchase_detailsNonNullableFuelNonNullable
instance Show Issuing'transactionPurchase_detailsNonNullableFuelNonNullable
instance Eq Issuing'transactionPurchase_detailsNonNullableFuelNonNullable
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsNonNullableFuelNonNullable
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsNonNullableFuelNonNullable
data Issuing'transactionPurchase_detailsNonNullableLodgingNonNullable
instance Show Issuing'transactionPurchase_detailsNonNullableLodgingNonNullable
instance Eq Issuing'transactionPurchase_detailsNonNullableLodgingNonNullable
instance Data.Aeson.FromJSON Issuing'transactionPurchase_detailsNonNullableLodgingNonNullable
instance Data.Aeson.ToJSON Issuing'transactionPurchase_detailsNonNullableLodgingNonNullable
data Issuing'transactionTokenNonNullableVariants
instance Show Issuing'transactionTokenNonNullableVariants
instance Eq Issuing'transactionTokenNonNullableVariants
instance Data.Aeson.FromJSON Issuing'transactionTokenNonNullableVariants
instance Data.Aeson.ToJSON Issuing'transactionTokenNonNullableVariants
data Issuing'transactionTreasuryNonNullable
instance Show Issuing'transactionTreasuryNonNullable
instance Eq Issuing'transactionTreasuryNonNullable
instance Data.Aeson.FromJSON Issuing'transactionTreasuryNonNullable
instance Data.Aeson.ToJSON Issuing'transactionTreasuryNonNullable
data Issuing'transactionType
instance Show Issuing'transactionType
instance Eq Issuing'transactionType
instance Data.Aeson.FromJSON Issuing'transactionType
instance Data.Aeson.ToJSON Issuing'transactionType
data Issuing'transactionWalletNonNullable
instance Show Issuing'transactionWalletNonNullable
instance Eq Issuing'transactionWalletNonNullable
instance Data.Aeson.FromJSON Issuing'transactionWalletNonNullable
instance Data.Aeson.ToJSON Issuing'transactionWalletNonNullable
