module Stripe.CustomerSession.Types.IssuingTransactionFleetReportedBreakdown where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_transaction_fleet_reported_breakdown
instance Show Issuing_transaction_fleet_reported_breakdown
instance Eq Issuing_transaction_fleet_reported_breakdown
instance Data.Aeson.FromJSON Issuing_transaction_fleet_reported_breakdown
instance Data.Aeson.ToJSON Issuing_transaction_fleet_reported_breakdown
data Issuing_transaction_fleet_reported_breakdownFuelNonNullable
instance Show Issuing_transaction_fleet_reported_breakdownFuelNonNullable
instance Eq Issuing_transaction_fleet_reported_breakdownFuelNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_fleet_reported_breakdownFuelNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_fleet_reported_breakdownFuelNonNullable
data Issuing_transaction_fleet_reported_breakdownNon_fuelNonNullable
instance Show Issuing_transaction_fleet_reported_breakdownNon_fuelNonNullable
instance Eq Issuing_transaction_fleet_reported_breakdownNon_fuelNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_fleet_reported_breakdownNon_fuelNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_fleet_reported_breakdownNon_fuelNonNullable
data Issuing_transaction_fleet_reported_breakdownTaxNonNullable
instance Show Issuing_transaction_fleet_reported_breakdownTaxNonNullable
instance Eq Issuing_transaction_fleet_reported_breakdownTaxNonNullable
instance Data.Aeson.FromJSON Issuing_transaction_fleet_reported_breakdownTaxNonNullable
instance Data.Aeson.ToJSON Issuing_transaction_fleet_reported_breakdownTaxNonNullable
