module Stripe.CustomerSession.Types.Issuing_Cardholder where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing'cardholder
instance Show Issuing'cardholder
instance Eq Issuing'cardholder
instance Data.Aeson.FromJSON Issuing'cardholder
instance Data.Aeson.ToJSON Issuing'cardholder
data Issuing'cardholderCompany
instance Show Issuing'cardholderCompany
instance Eq Issuing'cardholderCompany
instance Data.Aeson.FromJSON Issuing'cardholderCompany
instance Data.Aeson.ToJSON Issuing'cardholderCompany
data Issuing'cardholderIndividual
instance Show Issuing'cardholderIndividual
instance Eq Issuing'cardholderIndividual
instance Data.Aeson.FromJSON Issuing'cardholderIndividual
instance Data.Aeson.ToJSON Issuing'cardholderIndividual
data Issuing'cardholderIndividualCard_issuing
instance Show Issuing'cardholderIndividualCard_issuing
instance Eq Issuing'cardholderIndividualCard_issuing
instance Data.Aeson.FromJSON Issuing'cardholderIndividualCard_issuing
instance Data.Aeson.ToJSON Issuing'cardholderIndividualCard_issuing
data Issuing'cardholderIndividualCard_issuingUser_terms_acceptance
instance Show Issuing'cardholderIndividualCard_issuingUser_terms_acceptance
instance Eq Issuing'cardholderIndividualCard_issuingUser_terms_acceptance
instance Data.Aeson.FromJSON Issuing'cardholderIndividualCard_issuingUser_terms_acceptance
instance Data.Aeson.ToJSON Issuing'cardholderIndividualCard_issuingUser_terms_acceptance
data Issuing'cardholderIndividualDob
instance Show Issuing'cardholderIndividualDob
instance Eq Issuing'cardholderIndividualDob
instance Data.Aeson.FromJSON Issuing'cardholderIndividualDob
instance Data.Aeson.ToJSON Issuing'cardholderIndividualDob
data Issuing'cardholderIndividualVerification
instance Show Issuing'cardholderIndividualVerification
instance Eq Issuing'cardholderIndividualVerification
instance Data.Aeson.FromJSON Issuing'cardholderIndividualVerification
instance Data.Aeson.ToJSON Issuing'cardholderIndividualVerification
data Issuing'cardholderIndividualVerificationDocument
instance Show Issuing'cardholderIndividualVerificationDocument
instance Eq Issuing'cardholderIndividualVerificationDocument
instance Data.Aeson.FromJSON Issuing'cardholderIndividualVerificationDocument
instance Data.Aeson.ToJSON Issuing'cardholderIndividualVerificationDocument
data Issuing'cardholderIndividualVerificationDocumentBackVariants
instance Show Issuing'cardholderIndividualVerificationDocumentBackVariants
instance Eq Issuing'cardholderIndividualVerificationDocumentBackVariants
instance Data.Aeson.FromJSON Issuing'cardholderIndividualVerificationDocumentBackVariants
instance Data.Aeson.ToJSON Issuing'cardholderIndividualVerificationDocumentBackVariants
data Issuing'cardholderIndividualVerificationDocumentFrontVariants
instance Show Issuing'cardholderIndividualVerificationDocumentFrontVariants
instance Eq Issuing'cardholderIndividualVerificationDocumentFrontVariants
instance Data.Aeson.FromJSON Issuing'cardholderIndividualVerificationDocumentFrontVariants
instance Data.Aeson.ToJSON Issuing'cardholderIndividualVerificationDocumentFrontVariants
data Issuing'cardholderSpending_controls
instance Show Issuing'cardholderSpending_controls
instance Eq Issuing'cardholderSpending_controls
instance Data.Aeson.FromJSON Issuing'cardholderSpending_controls
instance Data.Aeson.ToJSON Issuing'cardholderSpending_controls
