module Stripe.CustomerSession.Types.IssuingDisputeCanceledEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_dispute_canceled_evidence
instance Show Issuing_dispute_canceled_evidence
instance Eq Issuing_dispute_canceled_evidence
instance Data.Aeson.FromJSON Issuing_dispute_canceled_evidence
instance Data.Aeson.ToJSON Issuing_dispute_canceled_evidence
data Issuing_dispute_canceled_evidenceAdditional_documentationNonNullableVariants
instance Show Issuing_dispute_canceled_evidenceAdditional_documentationNonNullableVariants
instance Eq Issuing_dispute_canceled_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.FromJSON Issuing_dispute_canceled_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.ToJSON Issuing_dispute_canceled_evidenceAdditional_documentationNonNullableVariants
data Issuing_dispute_canceled_evidenceProduct_typeNonNullable
instance Show Issuing_dispute_canceled_evidenceProduct_typeNonNullable
instance Eq Issuing_dispute_canceled_evidenceProduct_typeNonNullable
instance Data.Aeson.FromJSON Issuing_dispute_canceled_evidenceProduct_typeNonNullable
instance Data.Aeson.ToJSON Issuing_dispute_canceled_evidenceProduct_typeNonNullable
data Issuing_dispute_canceled_evidenceReturn_statusNonNullable
instance Show Issuing_dispute_canceled_evidenceReturn_statusNonNullable
instance Eq Issuing_dispute_canceled_evidenceReturn_statusNonNullable
instance Data.Aeson.FromJSON Issuing_dispute_canceled_evidenceReturn_statusNonNullable
instance Data.Aeson.ToJSON Issuing_dispute_canceled_evidenceReturn_statusNonNullable
