module Stripe.CustomerSession.Types.Issuing_Card where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing'card
instance Show Issuing'card
instance Eq Issuing'card
instance Data.Aeson.FromJSON Issuing'card
instance Data.Aeson.ToJSON Issuing'card
data Issuing'cardCancellation_reasonNonNullable
instance Show Issuing'cardCancellation_reasonNonNullable
instance Eq Issuing'cardCancellation_reasonNonNullable
instance Data.Aeson.FromJSON Issuing'cardCancellation_reasonNonNullable
instance Data.Aeson.ToJSON Issuing'cardCancellation_reasonNonNullable
data Issuing'cardLatest_fraud_warningNonNullable
instance Show Issuing'cardLatest_fraud_warningNonNullable
instance Eq Issuing'cardLatest_fraud_warningNonNullable
instance Data.Aeson.FromJSON Issuing'cardLatest_fraud_warningNonNullable
instance Data.Aeson.ToJSON Issuing'cardLatest_fraud_warningNonNullable
data Issuing'cardLatest_fraud_warningNonNullableTypeNonNullable
instance Show Issuing'cardLatest_fraud_warningNonNullableTypeNonNullable
instance Eq Issuing'cardLatest_fraud_warningNonNullableTypeNonNullable
instance Data.Aeson.FromJSON Issuing'cardLatest_fraud_warningNonNullableTypeNonNullable
instance Data.Aeson.ToJSON Issuing'cardLatest_fraud_warningNonNullableTypeNonNullable
data Issuing'cardPersonalization_designNonNullableVariants
instance Show Issuing'cardPersonalization_designNonNullableVariants
instance Eq Issuing'cardPersonalization_designNonNullableVariants
instance Data.Aeson.FromJSON Issuing'cardPersonalization_designNonNullableVariants
instance Data.Aeson.ToJSON Issuing'cardPersonalization_designNonNullableVariants
data Issuing'cardReplaced_byNonNullableVariants
instance Show Issuing'cardReplaced_byNonNullableVariants
instance Eq Issuing'cardReplaced_byNonNullableVariants
instance Data.Aeson.FromJSON Issuing'cardReplaced_byNonNullableVariants
instance Data.Aeson.ToJSON Issuing'cardReplaced_byNonNullableVariants
data Issuing'cardReplacement_forNonNullableVariants
instance Show Issuing'cardReplacement_forNonNullableVariants
instance Eq Issuing'cardReplacement_forNonNullableVariants
instance Data.Aeson.FromJSON Issuing'cardReplacement_forNonNullableVariants
instance Data.Aeson.ToJSON Issuing'cardReplacement_forNonNullableVariants
data Issuing'cardReplacement_reasonNonNullable
instance Show Issuing'cardReplacement_reasonNonNullable
instance Eq Issuing'cardReplacement_reasonNonNullable
instance Data.Aeson.FromJSON Issuing'cardReplacement_reasonNonNullable
instance Data.Aeson.ToJSON Issuing'cardReplacement_reasonNonNullable
data Issuing'cardShippingNonNullable
instance Show Issuing'cardShippingNonNullable
instance Eq Issuing'cardShippingNonNullable
instance Data.Aeson.FromJSON Issuing'cardShippingNonNullable
instance Data.Aeson.ToJSON Issuing'cardShippingNonNullable
data Issuing'cardShippingNonNullableAddress_validationNonNullable
instance Show Issuing'cardShippingNonNullableAddress_validationNonNullable
instance Eq Issuing'cardShippingNonNullableAddress_validationNonNullable
instance Data.Aeson.FromJSON Issuing'cardShippingNonNullableAddress_validationNonNullable
instance Data.Aeson.ToJSON Issuing'cardShippingNonNullableAddress_validationNonNullable
data Issuing'cardShippingNonNullableAddress_validationNonNullableMode
instance Show Issuing'cardShippingNonNullableAddress_validationNonNullableMode
instance Eq Issuing'cardShippingNonNullableAddress_validationNonNullableMode
instance Data.Aeson.FromJSON Issuing'cardShippingNonNullableAddress_validationNonNullableMode
instance Data.Aeson.ToJSON Issuing'cardShippingNonNullableAddress_validationNonNullableMode
data Issuing'cardShippingNonNullableAddress_validationNonNullableNormalized_addressNonNullable
instance Show Issuing'cardShippingNonNullableAddress_validationNonNullableNormalized_addressNonNullable
instance Eq Issuing'cardShippingNonNullableAddress_validationNonNullableNormalized_addressNonNullable
instance Data.Aeson.FromJSON Issuing'cardShippingNonNullableAddress_validationNonNullableNormalized_addressNonNullable
instance Data.Aeson.ToJSON Issuing'cardShippingNonNullableAddress_validationNonNullableNormalized_addressNonNullable
data Issuing'cardShippingNonNullableAddress_validationNonNullableResultNonNullable
instance Show Issuing'cardShippingNonNullableAddress_validationNonNullableResultNonNullable
instance Eq Issuing'cardShippingNonNullableAddress_validationNonNullableResultNonNullable
instance Data.Aeson.FromJSON Issuing'cardShippingNonNullableAddress_validationNonNullableResultNonNullable
instance Data.Aeson.ToJSON Issuing'cardShippingNonNullableAddress_validationNonNullableResultNonNullable
data Issuing'cardShippingNonNullableCarrierNonNullable
instance Show Issuing'cardShippingNonNullableCarrierNonNullable
instance Eq Issuing'cardShippingNonNullableCarrierNonNullable
instance Data.Aeson.FromJSON Issuing'cardShippingNonNullableCarrierNonNullable
instance Data.Aeson.ToJSON Issuing'cardShippingNonNullableCarrierNonNullable
data Issuing'cardShippingNonNullableCustomsNonNullable
instance Show Issuing'cardShippingNonNullableCustomsNonNullable
instance Eq Issuing'cardShippingNonNullableCustomsNonNullable
instance Data.Aeson.FromJSON Issuing'cardShippingNonNullableCustomsNonNullable
instance Data.Aeson.ToJSON Issuing'cardShippingNonNullableCustomsNonNullable
data Issuing'cardShippingNonNullableService
instance Show Issuing'cardShippingNonNullableService
instance Eq Issuing'cardShippingNonNullableService
instance Data.Aeson.FromJSON Issuing'cardShippingNonNullableService
instance Data.Aeson.ToJSON Issuing'cardShippingNonNullableService
data Issuing'cardShippingNonNullableStatusNonNullable
instance Show Issuing'cardShippingNonNullableStatusNonNullable
instance Eq Issuing'cardShippingNonNullableStatusNonNullable
instance Data.Aeson.FromJSON Issuing'cardShippingNonNullableStatusNonNullable
instance Data.Aeson.ToJSON Issuing'cardShippingNonNullableStatusNonNullable
data Issuing'cardShippingNonNullableType
instance Show Issuing'cardShippingNonNullableType
instance Eq Issuing'cardShippingNonNullableType
instance Data.Aeson.FromJSON Issuing'cardShippingNonNullableType
instance Data.Aeson.ToJSON Issuing'cardShippingNonNullableType
data Issuing'cardStatus
instance Show Issuing'cardStatus
instance Eq Issuing'cardStatus
instance Data.Aeson.FromJSON Issuing'cardStatus
instance Data.Aeson.ToJSON Issuing'cardStatus
data Issuing'cardType
instance Show Issuing'cardType
instance Eq Issuing'cardType
instance Data.Aeson.FromJSON Issuing'cardType
instance Data.Aeson.ToJSON Issuing'cardType
data Issuing'cardWalletsNonNullable
instance Show Issuing'cardWalletsNonNullable
instance Eq Issuing'cardWalletsNonNullable
instance Data.Aeson.FromJSON Issuing'cardWalletsNonNullable
instance Data.Aeson.ToJSON Issuing'cardWalletsNonNullable
