module Stripe.CustomerSession.Types.IssuingPhysicalBundleFeatures where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_physical_bundle_features
instance Show Issuing_physical_bundle_features
instance Eq Issuing_physical_bundle_features
instance Data.Aeson.FromJSON Issuing_physical_bundle_features
instance Data.Aeson.ToJSON Issuing_physical_bundle_features
data Issuing_physical_bundle_featuresCard_logo
instance Show Issuing_physical_bundle_featuresCard_logo
instance Eq Issuing_physical_bundle_featuresCard_logo
instance Data.Aeson.FromJSON Issuing_physical_bundle_featuresCard_logo
instance Data.Aeson.ToJSON Issuing_physical_bundle_featuresCard_logo
data Issuing_physical_bundle_featuresCarrier_text
instance Show Issuing_physical_bundle_featuresCarrier_text
instance Eq Issuing_physical_bundle_featuresCarrier_text
instance Data.Aeson.FromJSON Issuing_physical_bundle_featuresCarrier_text
instance Data.Aeson.ToJSON Issuing_physical_bundle_featuresCarrier_text
data Issuing_physical_bundle_featuresSecond_line
instance Show Issuing_physical_bundle_featuresSecond_line
instance Eq Issuing_physical_bundle_featuresSecond_line
instance Data.Aeson.FromJSON Issuing_physical_bundle_featuresSecond_line
instance Data.Aeson.ToJSON Issuing_physical_bundle_featuresSecond_line
