module Stripe.CustomerSession.Types.IssuingAuthorizationPendingRequest where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_pending_request
instance Show Issuing_authorization_pending_request
instance Eq Issuing_authorization_pending_request
instance Data.Aeson.FromJSON Issuing_authorization_pending_request
instance Data.Aeson.ToJSON Issuing_authorization_pending_request
data Issuing_authorization_pending_requestAmount_detailsNonNullable
instance Show Issuing_authorization_pending_requestAmount_detailsNonNullable
instance Eq Issuing_authorization_pending_requestAmount_detailsNonNullable
instance Data.Aeson.FromJSON Issuing_authorization_pending_requestAmount_detailsNonNullable
instance Data.Aeson.ToJSON Issuing_authorization_pending_requestAmount_detailsNonNullable
