module Stripe.CustomerSession.Types.IssuingDisputeFraudulentEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_dispute_fraudulent_evidence
instance Show Issuing_dispute_fraudulent_evidence
instance Eq Issuing_dispute_fraudulent_evidence
instance Data.Aeson.FromJSON Issuing_dispute_fraudulent_evidence
instance Data.Aeson.ToJSON Issuing_dispute_fraudulent_evidence
data Issuing_dispute_fraudulent_evidenceAdditional_documentationNonNullableVariants
instance Show Issuing_dispute_fraudulent_evidenceAdditional_documentationNonNullableVariants
instance Eq Issuing_dispute_fraudulent_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.FromJSON Issuing_dispute_fraudulent_evidenceAdditional_documentationNonNullableVariants
instance Data.Aeson.ToJSON Issuing_dispute_fraudulent_evidenceAdditional_documentationNonNullableVariants
