module Stripe.CustomerSession.Types.LegalEntityPersonVerification where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Legal_entity_person_verification
instance Show Legal_entity_person_verification
instance Eq Legal_entity_person_verification
instance Data.Aeson.FromJSON Legal_entity_person_verification
instance Data.Aeson.ToJSON Legal_entity_person_verification
data Legal_entity_person_verificationAdditional_document
instance Show Legal_entity_person_verificationAdditional_document
instance Eq Legal_entity_person_verificationAdditional_document
instance Data.Aeson.FromJSON Legal_entity_person_verificationAdditional_document
instance Data.Aeson.ToJSON Legal_entity_person_verificationAdditional_document
data Legal_entity_person_verificationAdditional_documentBackVariants
instance Show Legal_entity_person_verificationAdditional_documentBackVariants
instance Eq Legal_entity_person_verificationAdditional_documentBackVariants
instance Data.Aeson.FromJSON Legal_entity_person_verificationAdditional_documentBackVariants
instance Data.Aeson.ToJSON Legal_entity_person_verificationAdditional_documentBackVariants
data Legal_entity_person_verificationAdditional_documentFrontVariants
instance Show Legal_entity_person_verificationAdditional_documentFrontVariants
instance Eq Legal_entity_person_verificationAdditional_documentFrontVariants
instance Data.Aeson.FromJSON Legal_entity_person_verificationAdditional_documentFrontVariants
instance Data.Aeson.ToJSON Legal_entity_person_verificationAdditional_documentFrontVariants
