module Stripe.CustomerSession.Types.LegalEntityPersonVerificationDocument where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Legal_entity_person_verification_document
instance Show Legal_entity_person_verification_document
instance Eq Legal_entity_person_verification_document
instance Data.Aeson.FromJSON Legal_entity_person_verification_document
instance Data.Aeson.ToJSON Legal_entity_person_verification_document
data Legal_entity_person_verification_documentBackNonNullableVariants
instance Show Legal_entity_person_verification_documentBackNonNullableVariants
instance Eq Legal_entity_person_verification_documentBackNonNullableVariants
instance Data.Aeson.FromJSON Legal_entity_person_verification_documentBackNonNullableVariants
instance Data.Aeson.ToJSON Legal_entity_person_verification_documentBackNonNullableVariants
data Legal_entity_person_verification_documentFrontNonNullableVariants
instance Show Legal_entity_person_verification_documentFrontNonNullableVariants
instance Eq Legal_entity_person_verification_documentFrontNonNullableVariants
instance Data.Aeson.FromJSON Legal_entity_person_verification_documentFrontNonNullableVariants
instance Data.Aeson.ToJSON Legal_entity_person_verification_documentFrontNonNullableVariants
