module Stripe.CustomerSession.Types.LegalEntityCompany where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Legal_entity_company
instance Show Legal_entity_company
instance Eq Legal_entity_company
instance Data.Aeson.FromJSON Legal_entity_company
instance Data.Aeson.ToJSON Legal_entity_company
data Legal_entity_companyAddress_kanaNonNullable
instance Show Legal_entity_companyAddress_kanaNonNullable
instance Eq Legal_entity_companyAddress_kanaNonNullable
instance Data.Aeson.FromJSON Legal_entity_companyAddress_kanaNonNullable
instance Data.Aeson.ToJSON Legal_entity_companyAddress_kanaNonNullable
data Legal_entity_companyAddress_kanjiNonNullable
instance Show Legal_entity_companyAddress_kanjiNonNullable
instance Eq Legal_entity_companyAddress_kanjiNonNullable
instance Data.Aeson.FromJSON Legal_entity_companyAddress_kanjiNonNullable
instance Data.Aeson.ToJSON Legal_entity_companyAddress_kanjiNonNullable
data Legal_entity_companyDirectorship_declarationNonNullable
instance Show Legal_entity_companyDirectorship_declarationNonNullable
instance Eq Legal_entity_companyDirectorship_declarationNonNullable
instance Data.Aeson.FromJSON Legal_entity_companyDirectorship_declarationNonNullable
instance Data.Aeson.ToJSON Legal_entity_companyDirectorship_declarationNonNullable
data Legal_entity_companyOwnership_declarationNonNullable
instance Show Legal_entity_companyOwnership_declarationNonNullable
instance Eq Legal_entity_companyOwnership_declarationNonNullable
instance Data.Aeson.FromJSON Legal_entity_companyOwnership_declarationNonNullable
instance Data.Aeson.ToJSON Legal_entity_companyOwnership_declarationNonNullable
data Legal_entity_companyOwnership_exemption_reason
instance Show Legal_entity_companyOwnership_exemption_reason
instance Eq Legal_entity_companyOwnership_exemption_reason
instance Data.Aeson.FromJSON Legal_entity_companyOwnership_exemption_reason
instance Data.Aeson.ToJSON Legal_entity_companyOwnership_exemption_reason
data Legal_entity_companyRepresentative_declarationNonNullable
instance Show Legal_entity_companyRepresentative_declarationNonNullable
instance Eq Legal_entity_companyRepresentative_declarationNonNullable
instance Data.Aeson.FromJSON Legal_entity_companyRepresentative_declarationNonNullable
instance Data.Aeson.ToJSON Legal_entity_companyRepresentative_declarationNonNullable
data Legal_entity_companyStructure
instance Show Legal_entity_companyStructure
instance Eq Legal_entity_companyStructure
instance Data.Aeson.FromJSON Legal_entity_companyStructure
instance Data.Aeson.ToJSON Legal_entity_companyStructure
data Legal_entity_companyVerificationNonNullable
instance Show Legal_entity_companyVerificationNonNullable
instance Eq Legal_entity_companyVerificationNonNullable
instance Data.Aeson.FromJSON Legal_entity_companyVerificationNonNullable
instance Data.Aeson.ToJSON Legal_entity_companyVerificationNonNullable
