module Stripe.CustomerSession.Types.LegalEntityPersonVerification where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Legal_entity_person_verification
instance Show Legal_entity_person_verification
instance Eq Legal_entity_person_verification
instance Data.Aeson.FromJSON Legal_entity_person_verification
instance Data.Aeson.ToJSON Legal_entity_person_verification
data Legal_entity_person_verificationAdditional_documentNonNullable
instance Show Legal_entity_person_verificationAdditional_documentNonNullable
instance Eq Legal_entity_person_verificationAdditional_documentNonNullable
instance Data.Aeson.FromJSON Legal_entity_person_verificationAdditional_documentNonNullable
instance Data.Aeson.ToJSON Legal_entity_person_verificationAdditional_documentNonNullable
data Legal_entity_person_verificationAdditional_documentNonNullableBackNonNullableVariants
instance Show Legal_entity_person_verificationAdditional_documentNonNullableBackNonNullableVariants
instance Eq Legal_entity_person_verificationAdditional_documentNonNullableBackNonNullableVariants
instance Data.Aeson.FromJSON Legal_entity_person_verificationAdditional_documentNonNullableBackNonNullableVariants
instance Data.Aeson.ToJSON Legal_entity_person_verificationAdditional_documentNonNullableBackNonNullableVariants
data Legal_entity_person_verificationAdditional_documentNonNullableFrontNonNullableVariants
instance Show Legal_entity_person_verificationAdditional_documentNonNullableFrontNonNullableVariants
instance Eq Legal_entity_person_verificationAdditional_documentNonNullableFrontNonNullableVariants
instance Data.Aeson.FromJSON Legal_entity_person_verificationAdditional_documentNonNullableFrontNonNullableVariants
instance Data.Aeson.ToJSON Legal_entity_person_verificationAdditional_documentNonNullableFrontNonNullableVariants
