module Stripe.CustomerSession.Types.LineItem where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Line_item
instance Show Line_item
instance Eq Line_item
instance Data.Aeson.FromJSON Line_item
instance Data.Aeson.ToJSON Line_item
data Line_itemDiscountsVariants
instance Show Line_itemDiscountsVariants
instance Eq Line_itemDiscountsVariants
instance Data.Aeson.FromJSON Line_itemDiscountsVariants
instance Data.Aeson.ToJSON Line_itemDiscountsVariants
data Line_itemParentNonNullable
instance Show Line_itemParentNonNullable
instance Eq Line_itemParentNonNullable
instance Data.Aeson.FromJSON Line_itemParentNonNullable
instance Data.Aeson.ToJSON Line_itemParentNonNullable
data Line_itemParentNonNullableInvoice_item_detailsNonNullable
instance Show Line_itemParentNonNullableInvoice_item_detailsNonNullable
instance Eq Line_itemParentNonNullableInvoice_item_detailsNonNullable
instance Data.Aeson.FromJSON Line_itemParentNonNullableInvoice_item_detailsNonNullable
instance Data.Aeson.ToJSON Line_itemParentNonNullableInvoice_item_detailsNonNullable
data Line_itemParentNonNullableInvoice_item_detailsNonNullableProration_detailsNonNullable
instance Show Line_itemParentNonNullableInvoice_item_detailsNonNullableProration_detailsNonNullable
instance Eq Line_itemParentNonNullableInvoice_item_detailsNonNullableProration_detailsNonNullable
instance Data.Aeson.FromJSON Line_itemParentNonNullableInvoice_item_detailsNonNullableProration_detailsNonNullable
instance Data.Aeson.ToJSON Line_itemParentNonNullableInvoice_item_detailsNonNullableProration_detailsNonNullable
data Line_itemParentNonNullableInvoice_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Show Line_itemParentNonNullableInvoice_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Eq Line_itemParentNonNullableInvoice_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Data.Aeson.FromJSON Line_itemParentNonNullableInvoice_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Data.Aeson.ToJSON Line_itemParentNonNullableInvoice_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
data Line_itemParentNonNullableSubscription_item_detailsNonNullable
instance Show Line_itemParentNonNullableSubscription_item_detailsNonNullable
instance Eq Line_itemParentNonNullableSubscription_item_detailsNonNullable
instance Data.Aeson.FromJSON Line_itemParentNonNullableSubscription_item_detailsNonNullable
instance Data.Aeson.ToJSON Line_itemParentNonNullableSubscription_item_detailsNonNullable
data Line_itemParentNonNullableSubscription_item_detailsNonNullableProration_detailsNonNullable
instance Show Line_itemParentNonNullableSubscription_item_detailsNonNullableProration_detailsNonNullable
instance Eq Line_itemParentNonNullableSubscription_item_detailsNonNullableProration_detailsNonNullable
instance Data.Aeson.FromJSON Line_itemParentNonNullableSubscription_item_detailsNonNullableProration_detailsNonNullable
instance Data.Aeson.ToJSON Line_itemParentNonNullableSubscription_item_detailsNonNullableProration_detailsNonNullable
data Line_itemParentNonNullableSubscription_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Show Line_itemParentNonNullableSubscription_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Eq Line_itemParentNonNullableSubscription_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Data.Aeson.FromJSON Line_itemParentNonNullableSubscription_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
instance Data.Aeson.ToJSON Line_itemParentNonNullableSubscription_item_detailsNonNullableProration_detailsNonNullableCredited_itemsNonNullable
data Line_itemParentNonNullableType
instance Show Line_itemParentNonNullableType
instance Eq Line_itemParentNonNullableType
instance Data.Aeson.FromJSON Line_itemParentNonNullableType
instance Data.Aeson.ToJSON Line_itemParentNonNullableType
data Line_itemPricingNonNullable
instance Show Line_itemPricingNonNullable
instance Eq Line_itemPricingNonNullable
instance Data.Aeson.FromJSON Line_itemPricingNonNullable
instance Data.Aeson.ToJSON Line_itemPricingNonNullable
data Line_itemPricingNonNullableType
instance Show Line_itemPricingNonNullableType
instance Eq Line_itemPricingNonNullableType
instance Data.Aeson.FromJSON Line_itemPricingNonNullableType
instance Data.Aeson.ToJSON Line_itemPricingNonNullableType
data Line_itemSubscriptionNonNullableVariants
instance Show Line_itemSubscriptionNonNullableVariants
instance Eq Line_itemSubscriptionNonNullableVariants
instance Data.Aeson.FromJSON Line_itemSubscriptionNonNullableVariants
instance Data.Aeson.ToJSON Line_itemSubscriptionNonNullableVariants
