module Stripe.CustomerSession.Types.MandateUsBankAccount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Mandate_us_bank_account
instance Show Mandate_us_bank_account
instance Eq Mandate_us_bank_account
instance Data.Aeson.FromJSON Mandate_us_bank_account
instance Data.Aeson.ToJSON Mandate_us_bank_account
