module Stripe.CustomerSession.Types.PaymentMethodOptionsCustomerBalanceBankTransfer where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_customer_balance_bank_transfer
instance Show Payment_method_options_customer_balance_bank_transfer
instance Eq Payment_method_options_customer_balance_bank_transfer
instance Data.Aeson.FromJSON Payment_method_options_customer_balance_bank_transfer
instance Data.Aeson.ToJSON Payment_method_options_customer_balance_bank_transfer
data Payment_method_options_customer_balance_bank_transferRequested_address_types
instance Show Payment_method_options_customer_balance_bank_transferRequested_address_types
instance Eq Payment_method_options_customer_balance_bank_transferRequested_address_types
instance Data.Aeson.FromJSON Payment_method_options_customer_balance_bank_transferRequested_address_types
instance Data.Aeson.ToJSON Payment_method_options_customer_balance_bank_transferRequested_address_types
data Payment_method_options_customer_balance_bank_transferTypeNonNullable
instance Show Payment_method_options_customer_balance_bank_transferTypeNonNullable
instance Eq Payment_method_options_customer_balance_bank_transferTypeNonNullable
instance Data.Aeson.FromJSON Payment_method_options_customer_balance_bank_transferTypeNonNullable
instance Data.Aeson.ToJSON Payment_method_options_customer_balance_bank_transferTypeNonNullable
