module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceChecks where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payments_primitives_payment_records_resource_payment_method_card_details_resource_checks
instance Show Payments_primitives_payment_records_resource_payment_method_card_details_resource_checks
instance Eq Payments_primitives_payment_records_resource_payment_method_card_details_resource_checks
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_checks
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_checks
