module Stripe.CustomerSession.Types.PaymentFlowsAutomaticPaymentMethodsSetupIntent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_automatic_payment_methods_setup_intent
instance Show Payment_flows_automatic_payment_methods_setup_intent
instance Eq Payment_flows_automatic_payment_methods_setup_intent
instance Data.Aeson.FromJSON Payment_flows_automatic_payment_methods_setup_intent
instance Data.Aeson.ToJSON Payment_flows_automatic_payment_methods_setup_intent
data Payment_flows_automatic_payment_methods_setup_intentAllow_redirects
instance Show Payment_flows_automatic_payment_methods_setup_intentAllow_redirects
instance Eq Payment_flows_automatic_payment_methods_setup_intentAllow_redirects
instance Data.Aeson.FromJSON Payment_flows_automatic_payment_methods_setup_intentAllow_redirects
instance Data.Aeson.ToJSON Payment_flows_automatic_payment_methods_setup_intentAllow_redirects
