module Stripe.CustomerSession.Types.PaymentMethodUsBankAccount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_us_bank_account
instance Show Payment_method_us_bank_account
instance Eq Payment_method_us_bank_account
instance Data.Aeson.FromJSON Payment_method_us_bank_account
instance Data.Aeson.ToJSON Payment_method_us_bank_account
data Payment_method_us_bank_accountAccount_holder_typeNonNullable
instance Show Payment_method_us_bank_accountAccount_holder_typeNonNullable
instance Eq Payment_method_us_bank_accountAccount_holder_typeNonNullable
instance Data.Aeson.FromJSON Payment_method_us_bank_accountAccount_holder_typeNonNullable
instance Data.Aeson.ToJSON Payment_method_us_bank_accountAccount_holder_typeNonNullable
data Payment_method_us_bank_accountAccount_typeNonNullable
instance Show Payment_method_us_bank_accountAccount_typeNonNullable
instance Eq Payment_method_us_bank_accountAccount_typeNonNullable
instance Data.Aeson.FromJSON Payment_method_us_bank_accountAccount_typeNonNullable
instance Data.Aeson.ToJSON Payment_method_us_bank_accountAccount_typeNonNullable
data Payment_method_us_bank_accountNetworksNonNullable
instance Show Payment_method_us_bank_accountNetworksNonNullable
instance Eq Payment_method_us_bank_accountNetworksNonNullable
instance Data.Aeson.FromJSON Payment_method_us_bank_accountNetworksNonNullable
instance Data.Aeson.ToJSON Payment_method_us_bank_accountNetworksNonNullable
data Payment_method_us_bank_accountNetworksNonNullableSupported
instance Show Payment_method_us_bank_accountNetworksNonNullableSupported
instance Eq Payment_method_us_bank_accountNetworksNonNullableSupported
instance Data.Aeson.FromJSON Payment_method_us_bank_accountNetworksNonNullableSupported
instance Data.Aeson.ToJSON Payment_method_us_bank_accountNetworksNonNullableSupported
data Payment_method_us_bank_accountStatus_detailsNonNullable
instance Show Payment_method_us_bank_accountStatus_detailsNonNullable
instance Eq Payment_method_us_bank_accountStatus_detailsNonNullable
instance Data.Aeson.FromJSON Payment_method_us_bank_accountStatus_detailsNonNullable
instance Data.Aeson.ToJSON Payment_method_us_bank_accountStatus_detailsNonNullable
