module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordKonbini where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_konbini
instance Show Payment_method_details_payment_record_konbini
instance Eq Payment_method_details_payment_record_konbini
instance Data.Aeson.FromJSON Payment_method_details_payment_record_konbini
instance Data.Aeson.ToJSON Payment_method_details_payment_record_konbini
data Payment_method_details_payment_record_konbiniStoreNonNullable
instance Show Payment_method_details_payment_record_konbiniStoreNonNullable
instance Eq Payment_method_details_payment_record_konbiniStoreNonNullable
instance Data.Aeson.FromJSON Payment_method_details_payment_record_konbiniStoreNonNullable
instance Data.Aeson.ToJSON Payment_method_details_payment_record_konbiniStoreNonNullable
data Payment_method_details_payment_record_konbiniStoreNonNullableChainNonNullable
instance Show Payment_method_details_payment_record_konbiniStoreNonNullableChainNonNullable
instance Eq Payment_method_details_payment_record_konbiniStoreNonNullableChainNonNullable
instance Data.Aeson.FromJSON Payment_method_details_payment_record_konbiniStoreNonNullableChainNonNullable
instance Data.Aeson.ToJSON Payment_method_details_payment_record_konbiniStoreNonNullableChainNonNullable
