module Stripe.CustomerSession.Types.PaymentMethodDetailsInteracPresent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_interac_present
instance Show Payment_method_details_interac_present
instance Eq Payment_method_details_interac_present
instance Data.Aeson.FromJSON Payment_method_details_interac_present
instance Data.Aeson.ToJSON Payment_method_details_interac_present
data Payment_method_details_interac_presentRead_methodNonNullable
instance Show Payment_method_details_interac_presentRead_methodNonNullable
instance Eq Payment_method_details_interac_presentRead_methodNonNullable
instance Data.Aeson.FromJSON Payment_method_details_interac_presentRead_methodNonNullable
instance Data.Aeson.ToJSON Payment_method_details_interac_presentRead_methodNonNullable
data Payment_method_details_interac_presentReceiptNonNullable
instance Show Payment_method_details_interac_presentReceiptNonNullable
instance Eq Payment_method_details_interac_presentReceiptNonNullable
instance Data.Aeson.FromJSON Payment_method_details_interac_presentReceiptNonNullable
instance Data.Aeson.ToJSON Payment_method_details_interac_presentReceiptNonNullable
data Payment_method_details_interac_presentReceiptNonNullableAccount_type
instance Show Payment_method_details_interac_presentReceiptNonNullableAccount_type
instance Eq Payment_method_details_interac_presentReceiptNonNullableAccount_type
instance Data.Aeson.FromJSON Payment_method_details_interac_presentReceiptNonNullableAccount_type
instance Data.Aeson.ToJSON Payment_method_details_interac_presentReceiptNonNullableAccount_type
