module Stripe.CustomerSession.Types.PaymentMethodDetailsPaypal where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_paypal
instance Show Payment_method_details_paypal
instance Eq Payment_method_details_paypal
instance Data.Aeson.FromJSON Payment_method_details_paypal
instance Data.Aeson.ToJSON Payment_method_details_paypal
data Payment_method_details_paypalSeller_protectionNonNullable
instance Show Payment_method_details_paypalSeller_protectionNonNullable
instance Eq Payment_method_details_paypalSeller_protectionNonNullable
instance Data.Aeson.FromJSON Payment_method_details_paypalSeller_protectionNonNullable
instance Data.Aeson.ToJSON Payment_method_details_paypalSeller_protectionNonNullable
data Payment_method_details_paypalSeller_protectionNonNullableDispute_categoriesNonNullable
instance Show Payment_method_details_paypalSeller_protectionNonNullableDispute_categoriesNonNullable
instance Eq Payment_method_details_paypalSeller_protectionNonNullableDispute_categoriesNonNullable
instance Data.Aeson.FromJSON Payment_method_details_paypalSeller_protectionNonNullableDispute_categoriesNonNullable
instance Data.Aeson.ToJSON Payment_method_details_paypalSeller_protectionNonNullableDispute_categoriesNonNullable
data Payment_method_details_paypalSeller_protectionNonNullableStatus
instance Show Payment_method_details_paypalSeller_protectionNonNullableStatus
instance Eq Payment_method_details_paypalSeller_protectionNonNullableStatus
instance Data.Aeson.FromJSON Payment_method_details_paypalSeller_protectionNonNullableStatus
instance Data.Aeson.ToJSON Payment_method_details_paypalSeller_protectionNonNullableStatus
