module Stripe.CustomerSession.Types.PaymentMethodDetailsUsBankAccount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_us_bank_account
instance Show Payment_method_details_us_bank_account
instance Eq Payment_method_details_us_bank_account
instance Data.Aeson.FromJSON Payment_method_details_us_bank_account
instance Data.Aeson.ToJSON Payment_method_details_us_bank_account
data Payment_method_details_us_bank_accountAccount_holder_typeNonNullable
instance Show Payment_method_details_us_bank_accountAccount_holder_typeNonNullable
instance Eq Payment_method_details_us_bank_accountAccount_holder_typeNonNullable
instance Data.Aeson.FromJSON Payment_method_details_us_bank_accountAccount_holder_typeNonNullable
instance Data.Aeson.ToJSON Payment_method_details_us_bank_accountAccount_holder_typeNonNullable
data Payment_method_details_us_bank_accountAccount_typeNonNullable
instance Show Payment_method_details_us_bank_accountAccount_typeNonNullable
instance Eq Payment_method_details_us_bank_accountAccount_typeNonNullable
instance Data.Aeson.FromJSON Payment_method_details_us_bank_accountAccount_typeNonNullable
instance Data.Aeson.ToJSON Payment_method_details_us_bank_accountAccount_typeNonNullable
data Payment_method_details_us_bank_accountMandateVariants
instance Show Payment_method_details_us_bank_accountMandateVariants
instance Eq Payment_method_details_us_bank_accountMandateVariants
instance Data.Aeson.FromJSON Payment_method_details_us_bank_accountMandateVariants
instance Data.Aeson.ToJSON Payment_method_details_us_bank_accountMandateVariants
