module Stripe.CustomerSession.Types.PaymentIntentNextActionCardAwaitNotification where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_card_await_notification
instance Show Payment_intent_next_action_card_await_notification
instance Eq Payment_intent_next_action_card_await_notification
instance Data.Aeson.FromJSON Payment_intent_next_action_card_await_notification
instance Data.Aeson.ToJSON Payment_intent_next_action_card_await_notification
