module Stripe.CustomerSession.Types.PaymentMethodOptionsCardMandateOptions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_card_mandate_options
instance Show Payment_method_options_card_mandate_options
instance Eq Payment_method_options_card_mandate_options
instance Data.Aeson.FromJSON Payment_method_options_card_mandate_options
instance Data.Aeson.ToJSON Payment_method_options_card_mandate_options
