module Stripe.CustomerSession.Types.PaymentRecord where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_record
instance Show Payment_record
instance Eq Payment_record
instance Data.Aeson.FromJSON Payment_record
instance Data.Aeson.ToJSON Payment_record
data Payment_recordCustomer_details
instance Show Payment_recordCustomer_details
instance Eq Payment_recordCustomer_details
instance Data.Aeson.FromJSON Payment_recordCustomer_details
instance Data.Aeson.ToJSON Payment_recordCustomer_details
data Payment_recordPayment_method_details
instance Show Payment_recordPayment_method_details
instance Eq Payment_recordPayment_method_details
instance Data.Aeson.FromJSON Payment_recordPayment_method_details
instance Data.Aeson.ToJSON Payment_recordPayment_method_details
data Payment_recordPayment_method_detailsBilling_details
instance Show Payment_recordPayment_method_detailsBilling_details
instance Eq Payment_recordPayment_method_detailsBilling_details
instance Data.Aeson.FromJSON Payment_recordPayment_method_detailsBilling_details
instance Data.Aeson.ToJSON Payment_recordPayment_method_detailsBilling_details
data Payment_recordShipping_details
instance Show Payment_recordShipping_details
instance Eq Payment_recordShipping_details
instance Data.Aeson.FromJSON Payment_recordShipping_details
instance Data.Aeson.ToJSON Payment_recordShipping_details
