module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsBlik where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_blik
instance Show Payment_intent_payment_method_options_blik
instance Eq Payment_intent_payment_method_options_blik
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_blik
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_blik
