module Stripe.CustomerSession.Types.PaymentMethodOptionsCustomerBalance where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_customer_balance
instance Show Payment_method_options_customer_balance
instance Eq Payment_method_options_customer_balance
instance Data.Aeson.FromJSON Payment_method_options_customer_balance
instance Data.Aeson.ToJSON Payment_method_options_customer_balance
