module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordBancontact where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_bancontact
instance Show Payment_method_details_payment_record_bancontact
instance Eq Payment_method_details_payment_record_bancontact
instance Data.Aeson.FromJSON Payment_method_details_payment_record_bancontact
instance Data.Aeson.ToJSON Payment_method_details_payment_record_bancontact
data Payment_method_details_payment_record_bancontactGenerated_sepa_debitNonNullableVariants
instance Show Payment_method_details_payment_record_bancontactGenerated_sepa_debitNonNullableVariants
instance Eq Payment_method_details_payment_record_bancontactGenerated_sepa_debitNonNullableVariants
instance Data.Aeson.FromJSON Payment_method_details_payment_record_bancontactGenerated_sepa_debitNonNullableVariants
instance Data.Aeson.ToJSON Payment_method_details_payment_record_bancontactGenerated_sepa_debitNonNullableVariants
data Payment_method_details_payment_record_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Show Payment_method_details_payment_record_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Eq Payment_method_details_payment_record_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Data.Aeson.FromJSON Payment_method_details_payment_record_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Data.Aeson.ToJSON Payment_method_details_payment_record_bancontactGenerated_sepa_debit_mandateNonNullableVariants
data Payment_method_details_payment_record_bancontactPreferred_languageNonNullable
instance Show Payment_method_details_payment_record_bancontactPreferred_languageNonNullable
instance Eq Payment_method_details_payment_record_bancontactPreferred_languageNonNullable
instance Data.Aeson.FromJSON Payment_method_details_payment_record_bancontactPreferred_languageNonNullable
instance Data.Aeson.ToJSON Payment_method_details_payment_record_bancontactPreferred_languageNonNullable
