module Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceEnterpriseFeaturesExtendedAuthorizationExtendedAuthorization where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_extended_authorization_extended_authorization
instance Show Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_extended_authorization_extended_authorization
instance Eq Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_extended_authorization_extended_authorization
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_extended_authorization_extended_authorization
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_extended_authorization_extended_authorization
data Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_extended_authorization_extended_authorizationStatus
instance Show Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_extended_authorization_extended_authorizationStatus
instance Eq Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_extended_authorization_extended_authorizationStatus
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_extended_authorization_extended_authorizationStatus
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_extended_authorization_extended_authorizationStatus
