module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordKonbini where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_konbini
instance Show Payment_method_details_payment_record_konbini
instance Eq Payment_method_details_payment_record_konbini
instance Data.Aeson.FromJSON Payment_method_details_payment_record_konbini
instance Data.Aeson.ToJSON Payment_method_details_payment_record_konbini
data Payment_method_details_payment_record_konbiniStore
instance Show Payment_method_details_payment_record_konbiniStore
instance Eq Payment_method_details_payment_record_konbiniStore
instance Data.Aeson.FromJSON Payment_method_details_payment_record_konbiniStore
instance Data.Aeson.ToJSON Payment_method_details_payment_record_konbiniStore
