module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsEps where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_eps
instance Show Payment_intent_payment_method_options_eps
instance Eq Payment_intent_payment_method_options_eps
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_eps
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_eps
data Payment_intent_payment_method_options_epsSetup_future_usage
instance Show Payment_intent_payment_method_options_epsSetup_future_usage
instance Eq Payment_intent_payment_method_options_epsSetup_future_usage
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_epsSetup_future_usage
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_epsSetup_future_usage
