module Stripe.CustomerSession.Types.PaymentMethodDetailsGiropay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_giropay
instance Show Payment_method_details_giropay
instance Eq Payment_method_details_giropay
instance Data.Aeson.FromJSON Payment_method_details_giropay
instance Data.Aeson.ToJSON Payment_method_details_giropay
