module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceWalletResourceApplePay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payments_primitives_payment_records_resource_payment_method_card_details_resource_wallet_resource_apple_pay
instance Show Payments_primitives_payment_records_resource_payment_method_card_details_resource_wallet_resource_apple_pay
instance Eq Payments_primitives_payment_records_resource_payment_method_card_details_resource_wallet_resource_apple_pay
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_wallet_resource_apple_pay
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_wallet_resource_apple_pay
