-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PaymentIntentAmountDetailsLineItem
module Stripe.CustomerSession.Types.PaymentIntentAmountDetailsLineItem where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias
import {-# SOURCE #-} Stripe.CustomerSession.Types.PaymentFlowsAmountDetailsResourceLineItemsListResourceLineItemResourcePaymentMethodOptions
import {-# SOURCE #-} Stripe.CustomerSession.Types.PaymentFlowsAmountDetailsResourceLineItemsListResourceLineItemResourceTax
import {-# SOURCE #-} Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsCardPaymentIntentAmountDetailsLineItemPaymentMethodOptions
import {-# SOURCE #-} Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsCardPresentAmountDetailsLineItemPaymentMethodOptions
import {-# SOURCE #-} Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsKlarnaPaymentIntentAmountDetailsLineItemPaymentMethodOptions
import {-# SOURCE #-} Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsPaypalAmountDetailsLineItemPaymentMethodOptions

-- | Defines the object schema located at @components.schemas.payment_intent_amount_details_line_item@ in the specification.
-- 
-- 
data Payment_intent_amount_details_line_item = Payment_intent_amount_details_line_item {
  -- | discount_amount: The discount applied on this line item represented in the [smallest currency unit](https:\/\/docs.stripe.com\/currencies\#zero-decimal). An integer greater than 0.
  -- 
  -- This field is mutually exclusive with the \`amount_details[discount_amount]\` field.
  payment_intent_amount_details_line_itemDiscount_amount :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable GHC.Types.Int))
  -- | id: Unique identifier for the object.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , payment_intent_amount_details_line_itemId :: Data.Text.Internal.Text
  -- | payment_method_options: Payment method-specific information for line items.
  , payment_intent_amount_details_line_itemPayment_method_options :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable))
  -- | product_code: The product code of the line item, such as an SKU. Required for L3 rates. At most 12 characters long.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , payment_intent_amount_details_line_itemProduct_code :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Data.Text.Internal.Text))
  -- | product_name: The product name of the line item. Required for L3 rates. At most 1024 characters long.
  -- 
  -- For Cards, this field is truncated to 26 alphanumeric characters before being sent to the card networks. For PayPal, this field is truncated to 127 characters.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , payment_intent_amount_details_line_itemProduct_name :: Data.Text.Internal.Text
  -- | quantity: The quantity of items. Required for L3 rates. An integer greater than 0.
  , payment_intent_amount_details_line_itemQuantity :: GHC.Types.Int
  -- | tax: Contains information about the tax on the item.
  , payment_intent_amount_details_line_itemTax :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Payment_intent_amount_details_line_itemTaxNonNullable))
  -- | unit_cost: The unit cost of the line item represented in the [smallest currency unit](https:\/\/docs.stripe.com\/currencies\#zero-decimal). Required for L3 rates. An integer greater than or equal to 0.
  , payment_intent_amount_details_line_itemUnit_cost :: GHC.Types.Int
  -- | unit_of_measure: A unit of measure for the line item, such as gallons, feet, meters, etc. Required for L3 rates. At most 12 alphanumeric characters long.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , payment_intent_amount_details_line_itemUnit_of_measure :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Data.Text.Internal.Text))
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Payment_intent_amount_details_line_item
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("discount_amount" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemDiscount_amount obj) : ["id" Data.Aeson.Types.ToJSON..= payment_intent_amount_details_line_itemId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_options" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemPayment_method_options obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("product_code" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemProduct_code obj) : ["product_name" Data.Aeson.Types.ToJSON..= payment_intent_amount_details_line_itemProduct_name obj] : ["quantity" Data.Aeson.Types.ToJSON..= payment_intent_amount_details_line_itemQuantity obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("tax" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemTax obj) : ["unit_cost" Data.Aeson.Types.ToJSON..= payment_intent_amount_details_line_itemUnit_cost obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("unit_of_measure" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemUnit_of_measure obj) : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "payment_intent_amount_details_line_item"] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("discount_amount" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemDiscount_amount obj) : ["id" Data.Aeson.Types.ToJSON..= payment_intent_amount_details_line_itemId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("payment_method_options" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemPayment_method_options obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("product_code" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemProduct_code obj) : ["product_name" Data.Aeson.Types.ToJSON..= payment_intent_amount_details_line_itemProduct_name obj] : ["quantity" Data.Aeson.Types.ToJSON..= payment_intent_amount_details_line_itemQuantity obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("tax" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemTax obj) : ["unit_cost" Data.Aeson.Types.ToJSON..= payment_intent_amount_details_line_itemUnit_cost obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("unit_of_measure" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemUnit_of_measure obj) : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "payment_intent_amount_details_line_item"] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Payment_intent_amount_details_line_item
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Payment_intent_amount_details_line_item" (\obj -> ((((((((GHC.Base.pure Payment_intent_amount_details_line_item GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "discount_amount")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "payment_method_options")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "product_code")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "product_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "quantity")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "tax")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "unit_cost")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "unit_of_measure"))}
-- | Create a new 'Payment_intent_amount_details_line_item' with all required fields.
mkPayment_intent_amount_details_line_item :: Data.Text.Internal.Text -- ^ 'payment_intent_amount_details_line_itemId'
  -> Data.Text.Internal.Text -- ^ 'payment_intent_amount_details_line_itemProduct_name'
  -> GHC.Types.Int -- ^ 'payment_intent_amount_details_line_itemQuantity'
  -> GHC.Types.Int -- ^ 'payment_intent_amount_details_line_itemUnit_cost'
  -> Payment_intent_amount_details_line_item
mkPayment_intent_amount_details_line_item payment_intent_amount_details_line_itemId payment_intent_amount_details_line_itemProduct_name payment_intent_amount_details_line_itemQuantity payment_intent_amount_details_line_itemUnit_cost = Payment_intent_amount_details_line_item{payment_intent_amount_details_line_itemDiscount_amount = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                   payment_intent_amount_details_line_itemId = payment_intent_amount_details_line_itemId,
                                                                                                                                                                                                                                                                                   payment_intent_amount_details_line_itemPayment_method_options = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                   payment_intent_amount_details_line_itemProduct_code = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                   payment_intent_amount_details_line_itemProduct_name = payment_intent_amount_details_line_itemProduct_name,
                                                                                                                                                                                                                                                                                   payment_intent_amount_details_line_itemQuantity = payment_intent_amount_details_line_itemQuantity,
                                                                                                                                                                                                                                                                                   payment_intent_amount_details_line_itemTax = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                   payment_intent_amount_details_line_itemUnit_cost = payment_intent_amount_details_line_itemUnit_cost,
                                                                                                                                                                                                                                                                                   payment_intent_amount_details_line_itemUnit_of_measure = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.payment_intent_amount_details_line_item.properties.payment_method_options.anyOf@ in the specification.
-- 
-- Payment method-specific information for line items.
data Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable = Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable {
  -- | card: 
  payment_intent_amount_details_line_itemPayment_method_optionsNonNullableCard :: (GHC.Maybe.Maybe Payment_flows_private_payment_methods_card_payment_intent_amount_details_line_item_payment_method_options)
  -- | card_present: 
  , payment_intent_amount_details_line_itemPayment_method_optionsNonNullableCard_present :: (GHC.Maybe.Maybe Payment_flows_private_payment_methods_card_present_amount_details_line_item_payment_method_options)
  -- | klarna: 
  , payment_intent_amount_details_line_itemPayment_method_optionsNonNullableKlarna :: (GHC.Maybe.Maybe Payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options)
  -- | paypal: 
  , payment_intent_amount_details_line_itemPayment_method_optionsNonNullablePaypal :: (GHC.Maybe.Maybe Payment_flows_private_payment_methods_paypal_amount_details_line_item_payment_method_options)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("card" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemPayment_method_optionsNonNullableCard obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("card_present" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemPayment_method_optionsNonNullableCard_present obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("klarna" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemPayment_method_optionsNonNullableKlarna obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("paypal" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemPayment_method_optionsNonNullablePaypal obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("card" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemPayment_method_optionsNonNullableCard obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("card_present" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemPayment_method_optionsNonNullableCard_present obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("klarna" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemPayment_method_optionsNonNullableKlarna obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("paypal" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemPayment_method_optionsNonNullablePaypal obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable" (\obj -> (((GHC.Base.pure Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "card")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "card_present")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "klarna")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "paypal"))}
-- | Create a new 'Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable' with all required fields.
mkPayment_intent_amount_details_line_itemPayment_method_optionsNonNullable :: Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable
mkPayment_intent_amount_details_line_itemPayment_method_optionsNonNullable = Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable{payment_intent_amount_details_line_itemPayment_method_optionsNonNullableCard = GHC.Maybe.Nothing,
                                                                                                                                                      payment_intent_amount_details_line_itemPayment_method_optionsNonNullableCard_present = GHC.Maybe.Nothing,
                                                                                                                                                      payment_intent_amount_details_line_itemPayment_method_optionsNonNullableKlarna = GHC.Maybe.Nothing,
                                                                                                                                                      payment_intent_amount_details_line_itemPayment_method_optionsNonNullablePaypal = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.payment_intent_amount_details_line_item.properties.tax.anyOf@ in the specification.
-- 
-- Contains information about the tax on the item.
data Payment_intent_amount_details_line_itemTaxNonNullable = Payment_intent_amount_details_line_itemTaxNonNullable {
  -- | total_tax_amount: The total amount of tax on the transaction represented in the [smallest currency unit](https:\/\/docs.stripe.com\/currencies\#zero-decimal). Required for L2 rates. An integer greater than or equal to 0.
  -- 
  -- This field is mutually exclusive with the \`amount_details[line_items][\#][tax][total_tax_amount]\` field.
  payment_intent_amount_details_line_itemTaxNonNullableTotal_tax_amount :: (GHC.Maybe.Maybe GHC.Types.Int)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Payment_intent_amount_details_line_itemTaxNonNullable
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("total_tax_amount" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemTaxNonNullableTotal_tax_amount obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("total_tax_amount" Data.Aeson.Types.ToJSON..=)) (payment_intent_amount_details_line_itemTaxNonNullableTotal_tax_amount obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Payment_intent_amount_details_line_itemTaxNonNullable
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Payment_intent_amount_details_line_itemTaxNonNullable" (\obj -> GHC.Base.pure Payment_intent_amount_details_line_itemTaxNonNullable GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "total_tax_amount"))}
-- | Create a new 'Payment_intent_amount_details_line_itemTaxNonNullable' with all required fields.
mkPayment_intent_amount_details_line_itemTaxNonNullable :: Payment_intent_amount_details_line_itemTaxNonNullable
mkPayment_intent_amount_details_line_itemTaxNonNullable = Payment_intent_amount_details_line_itemTaxNonNullable{payment_intent_amount_details_line_itemTaxNonNullableTotal_tax_amount = GHC.Maybe.Nothing}
