module Stripe.CustomerSession.Types.PaymentIntentNextActionVerifyWithMicrodeposits where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_verify_with_microdeposits
instance Show Payment_intent_next_action_verify_with_microdeposits
instance Eq Payment_intent_next_action_verify_with_microdeposits
instance Data.Aeson.FromJSON Payment_intent_next_action_verify_with_microdeposits
instance Data.Aeson.ToJSON Payment_intent_next_action_verify_with_microdeposits
data Payment_intent_next_action_verify_with_microdepositsMicrodeposit_typeNonNullable
instance Show Payment_intent_next_action_verify_with_microdepositsMicrodeposit_typeNonNullable
instance Eq Payment_intent_next_action_verify_with_microdepositsMicrodeposit_typeNonNullable
instance Data.Aeson.FromJSON Payment_intent_next_action_verify_with_microdepositsMicrodeposit_typeNonNullable
instance Data.Aeson.ToJSON Payment_intent_next_action_verify_with_microdepositsMicrodeposit_typeNonNullable
