module Stripe.CustomerSession.Types.PaymentMethodOptionsPaynow where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_paynow
instance Show Payment_method_options_paynow
instance Eq Payment_method_options_paynow
instance Data.Aeson.FromJSON Payment_method_options_paynow
instance Data.Aeson.ToJSON Payment_method_options_paynow
data Payment_method_options_paynowSetup_future_usage
instance Show Payment_method_options_paynowSetup_future_usage
instance Eq Payment_method_options_paynowSetup_future_usage
instance Data.Aeson.FromJSON Payment_method_options_paynowSetup_future_usage
instance Data.Aeson.ToJSON Payment_method_options_paynowSetup_future_usage
