module Stripe.CustomerSession.Types.PaymentMethodCardChecks where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_card_checks
instance Show Payment_method_card_checks
instance Eq Payment_method_card_checks
instance Data.Aeson.FromJSON Payment_method_card_checks
instance Data.Aeson.ToJSON Payment_method_card_checks
