module Stripe.CustomerSession.Types.PaymentMethodDetailsBoleto where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_boleto
instance Show Payment_method_details_boleto
instance Eq Payment_method_details_boleto
instance Data.Aeson.FromJSON Payment_method_details_boleto
instance Data.Aeson.ToJSON Payment_method_details_boleto
