module Stripe.CustomerSession.Types.PaymentMethodCardPresent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_card_present
instance Show Payment_method_card_present
instance Eq Payment_method_card_present
instance Data.Aeson.FromJSON Payment_method_card_present
instance Data.Aeson.ToJSON Payment_method_card_present
data Payment_method_card_presentNetworksNonNullable
instance Show Payment_method_card_presentNetworksNonNullable
instance Eq Payment_method_card_presentNetworksNonNullable
instance Data.Aeson.FromJSON Payment_method_card_presentNetworksNonNullable
instance Data.Aeson.ToJSON Payment_method_card_presentNetworksNonNullable
data Payment_method_card_presentOfflineNonNullable
instance Show Payment_method_card_presentOfflineNonNullable
instance Eq Payment_method_card_presentOfflineNonNullable
instance Data.Aeson.FromJSON Payment_method_card_presentOfflineNonNullable
instance Data.Aeson.ToJSON Payment_method_card_presentOfflineNonNullable
data Payment_method_card_presentOfflineNonNullableTypeNonNullable
instance Show Payment_method_card_presentOfflineNonNullableTypeNonNullable
instance Eq Payment_method_card_presentOfflineNonNullableTypeNonNullable
instance Data.Aeson.FromJSON Payment_method_card_presentOfflineNonNullableTypeNonNullable
instance Data.Aeson.ToJSON Payment_method_card_presentOfflineNonNullableTypeNonNullable
data Payment_method_card_presentRead_methodNonNullable
instance Show Payment_method_card_presentRead_methodNonNullable
instance Eq Payment_method_card_presentRead_methodNonNullable
instance Data.Aeson.FromJSON Payment_method_card_presentRead_methodNonNullable
instance Data.Aeson.ToJSON Payment_method_card_presentRead_methodNonNullable
