module Stripe.CustomerSession.Types.PaymentMethodOptionsCardPresentRouting where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_card_present_routing
instance Show Payment_method_options_card_present_routing
instance Eq Payment_method_options_card_present_routing
instance Data.Aeson.FromJSON Payment_method_options_card_present_routing
instance Data.Aeson.ToJSON Payment_method_options_card_present_routing
