module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordSwish where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_swish
instance Show Payment_method_details_payment_record_swish
instance Eq Payment_method_details_payment_record_swish
instance Data.Aeson.FromJSON Payment_method_details_payment_record_swish
instance Data.Aeson.ToJSON Payment_method_details_payment_record_swish
