module Stripe.CustomerSession.Types.PaymentMethodOptionsAffirm where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_affirm
instance Show Payment_method_options_affirm
instance Eq Payment_method_options_affirm
instance Data.Aeson.FromJSON Payment_method_options_affirm
instance Data.Aeson.ToJSON Payment_method_options_affirm
data Payment_method_options_affirmCapture_method
instance Show Payment_method_options_affirmCapture_method
instance Eq Payment_method_options_affirmCapture_method
instance Data.Aeson.FromJSON Payment_method_options_affirmCapture_method
instance Data.Aeson.ToJSON Payment_method_options_affirmCapture_method
data Payment_method_options_affirmSetup_future_usage
instance Show Payment_method_options_affirmSetup_future_usage
instance Eq Payment_method_options_affirmSetup_future_usage
instance Data.Aeson.FromJSON Payment_method_options_affirmSetup_future_usage
instance Data.Aeson.ToJSON Payment_method_options_affirmSetup_future_usage
