module Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceEnterpriseFeaturesOvercaptureOvercapture where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_overcapture_overcapture
instance Show Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_overcapture_overcapture
instance Eq Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_overcapture_overcapture
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_overcapture_overcapture
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_overcapture_overcapture
data Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_overcapture_overcaptureStatus
instance Show Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_overcapture_overcaptureStatus
instance Eq Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_overcapture_overcaptureStatus
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_overcapture_overcaptureStatus
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_card_details_api_resource_enterprise_features_overcapture_overcaptureStatus
