module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsLink where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_link
instance Show Payment_intent_payment_method_options_link
instance Eq Payment_intent_payment_method_options_link
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_link
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_link
