module Stripe.CustomerSession.Types.PaymentMethodOptionsMultibanco where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_multibanco
instance Show Payment_method_options_multibanco
instance Eq Payment_method_options_multibanco
instance Data.Aeson.FromJSON Payment_method_options_multibanco
instance Data.Aeson.ToJSON Payment_method_options_multibanco
data Payment_method_options_multibancoSetup_future_usage
instance Show Payment_method_options_multibancoSetup_future_usage
instance Eq Payment_method_options_multibancoSetup_future_usage
instance Data.Aeson.FromJSON Payment_method_options_multibancoSetup_future_usage
instance Data.Aeson.ToJSON Payment_method_options_multibancoSetup_future_usage
