module Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsSamsungPayPaymentMethodOptions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_private_payment_methods_samsung_pay_payment_method_options
instance Show Payment_flows_private_payment_methods_samsung_pay_payment_method_options
instance Eq Payment_flows_private_payment_methods_samsung_pay_payment_method_options
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_samsung_pay_payment_method_options
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_samsung_pay_payment_method_options
data Payment_flows_private_payment_methods_samsung_pay_payment_method_optionsCapture_method
instance Show Payment_flows_private_payment_methods_samsung_pay_payment_method_optionsCapture_method
instance Eq Payment_flows_private_payment_methods_samsung_pay_payment_method_optionsCapture_method
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_samsung_pay_payment_method_optionsCapture_method
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_samsung_pay_payment_method_optionsCapture_method
