-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PaymentMethodNaverPay
module Stripe.CustomerSession.Types.PaymentMethodNaverPay where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias

-- | Defines the object schema located at @components.schemas.payment_method_naver_pay@ in the specification.
-- 
-- 
data Payment_method_naver_pay = Payment_method_naver_pay {
  -- | buyer_id: Uniquely identifies this particular Naver Pay account. You can use this attribute to check whether two Naver Pay accounts are the same.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  payment_method_naver_payBuyer_id :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Data.Text.Internal.Text))
  -- | funding: Whether to fund this transaction with Naver Pay points or a card.
  , payment_method_naver_payFunding :: Payment_method_naver_payFunding
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Payment_method_naver_pay
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("buyer_id" Data.Aeson.Types.ToJSON..=)) (payment_method_naver_payBuyer_id obj) : ["funding" Data.Aeson.Types.ToJSON..= payment_method_naver_payFunding obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("buyer_id" Data.Aeson.Types.ToJSON..=)) (payment_method_naver_payBuyer_id obj) : ["funding" Data.Aeson.Types.ToJSON..= payment_method_naver_payFunding obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Payment_method_naver_pay
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Payment_method_naver_pay" (\obj -> (GHC.Base.pure Payment_method_naver_pay GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "buyer_id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "funding"))}
-- | Create a new 'Payment_method_naver_pay' with all required fields.
mkPayment_method_naver_pay :: Payment_method_naver_payFunding -- ^ 'payment_method_naver_payFunding'
  -> Payment_method_naver_pay
mkPayment_method_naver_pay payment_method_naver_payFunding = Payment_method_naver_pay{payment_method_naver_payBuyer_id = GHC.Maybe.Nothing,
                                                                                      payment_method_naver_payFunding = payment_method_naver_payFunding}
-- | Defines the enum schema located at @components.schemas.payment_method_naver_pay.properties.funding@ in the specification.
-- 
-- Whether to fund this transaction with Naver Pay points or a card.
data Payment_method_naver_payFunding =
   Payment_method_naver_payFundingOther Data.Aeson.Types.Internal.Value -- ^ This case is used if the value encountered during decoding does not match any of the provided cases in the specification.
  | Payment_method_naver_payFundingTyped Data.Text.Internal.Text -- ^ This constructor can be used to send values to the server which are not present in the specification yet.
  | Payment_method_naver_payFundingEnumCard -- ^ Represents the JSON value @"card"@
  | Payment_method_naver_payFundingEnumPoints -- ^ Represents the JSON value @"points"@
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Payment_method_naver_payFunding
    where {toJSON (Payment_method_naver_payFundingOther val) = val;
           toJSON (Payment_method_naver_payFundingTyped val) = Data.Aeson.Types.ToJSON.toJSON val;
           toJSON (Payment_method_naver_payFundingEnumCard) = "card";
           toJSON (Payment_method_naver_payFundingEnumPoints) = "points"}
instance Data.Aeson.Types.FromJSON.FromJSON Payment_method_naver_payFunding
    where {parseJSON val = GHC.Base.pure (if | val GHC.Classes.== "card" -> Payment_method_naver_payFundingEnumCard
                                             | val GHC.Classes.== "points" -> Payment_method_naver_payFundingEnumPoints
                                             | GHC.Base.otherwise -> Payment_method_naver_payFundingOther val)}
