module Stripe.CustomerSession.Types.PaymentIntentNextActionKonbiniStores where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_konbini_stores
instance Show Payment_intent_next_action_konbini_stores
instance Eq Payment_intent_next_action_konbini_stores
instance Data.Aeson.FromJSON Payment_intent_next_action_konbini_stores
instance Data.Aeson.ToJSON Payment_intent_next_action_konbini_stores
data Payment_intent_next_action_konbini_storesFamilymartNonNullable
instance Show Payment_intent_next_action_konbini_storesFamilymartNonNullable
instance Eq Payment_intent_next_action_konbini_storesFamilymartNonNullable
instance Data.Aeson.FromJSON Payment_intent_next_action_konbini_storesFamilymartNonNullable
instance Data.Aeson.ToJSON Payment_intent_next_action_konbini_storesFamilymartNonNullable
data Payment_intent_next_action_konbini_storesLawsonNonNullable
instance Show Payment_intent_next_action_konbini_storesLawsonNonNullable
instance Eq Payment_intent_next_action_konbini_storesLawsonNonNullable
instance Data.Aeson.FromJSON Payment_intent_next_action_konbini_storesLawsonNonNullable
instance Data.Aeson.ToJSON Payment_intent_next_action_konbini_storesLawsonNonNullable
data Payment_intent_next_action_konbini_storesMinistopNonNullable
instance Show Payment_intent_next_action_konbini_storesMinistopNonNullable
instance Eq Payment_intent_next_action_konbini_storesMinistopNonNullable
instance Data.Aeson.FromJSON Payment_intent_next_action_konbini_storesMinistopNonNullable
instance Data.Aeson.ToJSON Payment_intent_next_action_konbini_storesMinistopNonNullable
data Payment_intent_next_action_konbini_storesSeicomartNonNullable
instance Show Payment_intent_next_action_konbini_storesSeicomartNonNullable
instance Eq Payment_intent_next_action_konbini_storesSeicomartNonNullable
instance Data.Aeson.FromJSON Payment_intent_next_action_konbini_storesSeicomartNonNullable
instance Data.Aeson.ToJSON Payment_intent_next_action_konbini_storesSeicomartNonNullable
