module Stripe.CustomerSession.Types.PaymentMethodDetailsInteracPresent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_interac_present
instance Show Payment_method_details_interac_present
instance Eq Payment_method_details_interac_present
instance Data.Aeson.FromJSON Payment_method_details_interac_present
instance Data.Aeson.ToJSON Payment_method_details_interac_present
data Payment_method_details_interac_presentReceipt
instance Show Payment_method_details_interac_presentReceipt
instance Eq Payment_method_details_interac_presentReceipt
instance Data.Aeson.FromJSON Payment_method_details_interac_presentReceipt
instance Data.Aeson.ToJSON Payment_method_details_interac_presentReceipt
