module Stripe.CustomerSession.Types.PaymentMethodOptionsCustomerBalance where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_customer_balance
instance Show Payment_method_options_customer_balance
instance Eq Payment_method_options_customer_balance
instance Data.Aeson.FromJSON Payment_method_options_customer_balance
instance Data.Aeson.ToJSON Payment_method_options_customer_balance
data Payment_method_options_customer_balanceFunding_typeNonNullable
instance Show Payment_method_options_customer_balanceFunding_typeNonNullable
instance Eq Payment_method_options_customer_balanceFunding_typeNonNullable
instance Data.Aeson.FromJSON Payment_method_options_customer_balanceFunding_typeNonNullable
instance Data.Aeson.ToJSON Payment_method_options_customer_balanceFunding_typeNonNullable
data Payment_method_options_customer_balanceSetup_future_usage
instance Show Payment_method_options_customer_balanceSetup_future_usage
instance Eq Payment_method_options_customer_balanceSetup_future_usage
instance Data.Aeson.FromJSON Payment_method_options_customer_balanceSetup_future_usage
instance Data.Aeson.ToJSON Payment_method_options_customer_balanceSetup_future_usage
