module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourcePaymentMethodMobilepayDetailsResourceCard where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payments_primitives_payment_records_resource_payment_method_mobilepay_details_resource_card
instance Show Payments_primitives_payment_records_resource_payment_method_mobilepay_details_resource_card
instance Eq Payments_primitives_payment_records_resource_payment_method_mobilepay_details_resource_card
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_payment_method_mobilepay_details_resource_card
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_payment_method_mobilepay_details_resource_card
