module Stripe.CustomerSession.Types.PaymentMethodDetailsCardInstallments where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_card_installments
instance Show Payment_method_details_card_installments
instance Eq Payment_method_details_card_installments
instance Data.Aeson.FromJSON Payment_method_details_card_installments
instance Data.Aeson.ToJSON Payment_method_details_card_installments
data Payment_method_details_card_installmentsPlanNonNullable
instance Show Payment_method_details_card_installmentsPlanNonNullable
instance Eq Payment_method_details_card_installmentsPlanNonNullable
instance Data.Aeson.FromJSON Payment_method_details_card_installmentsPlanNonNullable
instance Data.Aeson.ToJSON Payment_method_details_card_installmentsPlanNonNullable
data Payment_method_details_card_installmentsPlanNonNullableIntervalNonNullable
instance Show Payment_method_details_card_installmentsPlanNonNullableIntervalNonNullable
instance Eq Payment_method_details_card_installmentsPlanNonNullableIntervalNonNullable
instance Data.Aeson.FromJSON Payment_method_details_card_installmentsPlanNonNullableIntervalNonNullable
instance Data.Aeson.ToJSON Payment_method_details_card_installmentsPlanNonNullableIntervalNonNullable
data Payment_method_details_card_installmentsPlanNonNullableType
instance Show Payment_method_details_card_installmentsPlanNonNullableType
instance Eq Payment_method_details_card_installmentsPlanNonNullableType
instance Data.Aeson.FromJSON Payment_method_details_card_installmentsPlanNonNullableType
instance Data.Aeson.ToJSON Payment_method_details_card_installmentsPlanNonNullableType
