module Stripe.CustomerSession.Types.PaymentMethodOptionsRevolutPay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_revolut_pay
instance Show Payment_method_options_revolut_pay
instance Eq Payment_method_options_revolut_pay
instance Data.Aeson.FromJSON Payment_method_options_revolut_pay
instance Data.Aeson.ToJSON Payment_method_options_revolut_pay
data Payment_method_options_revolut_payCapture_method
instance Show Payment_method_options_revolut_payCapture_method
instance Eq Payment_method_options_revolut_payCapture_method
instance Data.Aeson.FromJSON Payment_method_options_revolut_payCapture_method
instance Data.Aeson.ToJSON Payment_method_options_revolut_payCapture_method
data Payment_method_options_revolut_paySetup_future_usage
instance Show Payment_method_options_revolut_paySetup_future_usage
instance Eq Payment_method_options_revolut_paySetup_future_usage
instance Data.Aeson.FromJSON Payment_method_options_revolut_paySetup_future_usage
instance Data.Aeson.ToJSON Payment_method_options_revolut_paySetup_future_usage
