module Stripe.CustomerSession.Types.PaymentMethodDetailsEps where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_eps
instance Show Payment_method_details_eps
instance Eq Payment_method_details_eps
instance Data.Aeson.FromJSON Payment_method_details_eps
instance Data.Aeson.ToJSON Payment_method_details_eps
data Payment_method_details_epsBankNonNullable
instance Show Payment_method_details_epsBankNonNullable
instance Eq Payment_method_details_epsBankNonNullable
instance Data.Aeson.FromJSON Payment_method_details_epsBankNonNullable
instance Data.Aeson.ToJSON Payment_method_details_epsBankNonNullable
