module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsSwish where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_swish
instance Show Payment_intent_payment_method_options_swish
instance Eq Payment_intent_payment_method_options_swish
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_swish
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_swish
data Payment_intent_payment_method_options_swishSetup_future_usage
instance Show Payment_intent_payment_method_options_swishSetup_future_usage
instance Eq Payment_intent_payment_method_options_swishSetup_future_usage
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_swishSetup_future_usage
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_swishSetup_future_usage
