module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordGiropay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_giropay
instance Show Payment_method_details_payment_record_giropay
instance Eq Payment_method_details_payment_record_giropay
instance Data.Aeson.FromJSON Payment_method_details_payment_record_giropay
instance Data.Aeson.ToJSON Payment_method_details_payment_record_giropay
