module Stripe.CustomerSession.Types.PaymentMethodOptionsAfterpayClearpay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_afterpay_clearpay
instance Show Payment_method_options_afterpay_clearpay
instance Eq Payment_method_options_afterpay_clearpay
instance Data.Aeson.FromJSON Payment_method_options_afterpay_clearpay
instance Data.Aeson.ToJSON Payment_method_options_afterpay_clearpay
