module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourcePaymentMethodDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payments_primitives_payment_records_resource_payment_method_details
instance Show Payments_primitives_payment_records_resource_payment_method_details
instance Eq Payments_primitives_payment_records_resource_payment_method_details
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_payment_method_details
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_payment_method_details
data Payments_primitives_payment_records_resource_payment_method_detailsBilling_details
instance Show Payments_primitives_payment_records_resource_payment_method_detailsBilling_details
instance Eq Payments_primitives_payment_records_resource_payment_method_detailsBilling_details
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_payment_method_detailsBilling_details
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_payment_method_detailsBilling_details
