module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsAcssDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_acss_debit
instance Show Payment_intent_payment_method_options_acss_debit
instance Eq Payment_intent_payment_method_options_acss_debit
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_acss_debit
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_acss_debit
data Payment_intent_payment_method_options_acss_debitSetup_future_usage
instance Show Payment_intent_payment_method_options_acss_debitSetup_future_usage
instance Eq Payment_intent_payment_method_options_acss_debitSetup_future_usage
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_acss_debitSetup_future_usage
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_acss_debitSetup_future_usage
data Payment_intent_payment_method_options_acss_debitVerification_method
instance Show Payment_intent_payment_method_options_acss_debitVerification_method
instance Eq Payment_intent_payment_method_options_acss_debitVerification_method
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_acss_debitVerification_method
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_acss_debitVerification_method
