module Stripe.CustomerSession.Types.PaymentMethodDetailsCardPresent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_card_present
instance Show Payment_method_details_card_present
instance Eq Payment_method_details_card_present
instance Data.Aeson.FromJSON Payment_method_details_card_present
instance Data.Aeson.ToJSON Payment_method_details_card_present
data Payment_method_details_card_presentOfflineNonNullable
instance Show Payment_method_details_card_presentOfflineNonNullable
instance Eq Payment_method_details_card_presentOfflineNonNullable
instance Data.Aeson.FromJSON Payment_method_details_card_presentOfflineNonNullable
instance Data.Aeson.ToJSON Payment_method_details_card_presentOfflineNonNullable
data Payment_method_details_card_presentOfflineNonNullableTypeNonNullable
instance Show Payment_method_details_card_presentOfflineNonNullableTypeNonNullable
instance Eq Payment_method_details_card_presentOfflineNonNullableTypeNonNullable
instance Data.Aeson.FromJSON Payment_method_details_card_presentOfflineNonNullableTypeNonNullable
instance Data.Aeson.ToJSON Payment_method_details_card_presentOfflineNonNullableTypeNonNullable
data Payment_method_details_card_presentRead_methodNonNullable
instance Show Payment_method_details_card_presentRead_methodNonNullable
instance Eq Payment_method_details_card_presentRead_methodNonNullable
instance Data.Aeson.FromJSON Payment_method_details_card_presentRead_methodNonNullable
instance Data.Aeson.ToJSON Payment_method_details_card_presentRead_methodNonNullable
data Payment_method_details_card_presentReceiptNonNullable
instance Show Payment_method_details_card_presentReceiptNonNullable
instance Eq Payment_method_details_card_presentReceiptNonNullable
instance Data.Aeson.FromJSON Payment_method_details_card_presentReceiptNonNullable
instance Data.Aeson.ToJSON Payment_method_details_card_presentReceiptNonNullable
data Payment_method_details_card_presentReceiptNonNullableAccount_type
instance Show Payment_method_details_card_presentReceiptNonNullableAccount_type
instance Eq Payment_method_details_card_presentReceiptNonNullableAccount_type
instance Data.Aeson.FromJSON Payment_method_details_card_presentReceiptNonNullableAccount_type
instance Data.Aeson.ToJSON Payment_method_details_card_presentReceiptNonNullableAccount_type
