module Stripe.CustomerSession.Types.PaymentMethodDetailsCrypto where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_crypto
instance Show Payment_method_details_crypto
instance Eq Payment_method_details_crypto
instance Data.Aeson.FromJSON Payment_method_details_crypto
instance Data.Aeson.ToJSON Payment_method_details_crypto
