module Stripe.CustomerSession.Types.PaymentMethodOptionsPaypal where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_paypal
instance Show Payment_method_options_paypal
instance Eq Payment_method_options_paypal
instance Data.Aeson.FromJSON Payment_method_options_paypal
instance Data.Aeson.ToJSON Payment_method_options_paypal
