module Stripe.CustomerSession.Types.PaymentIntentAmountDetailsLineItem where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_amount_details_line_item
instance Show Payment_intent_amount_details_line_item
instance Eq Payment_intent_amount_details_line_item
instance Data.Aeson.FromJSON Payment_intent_amount_details_line_item
instance Data.Aeson.ToJSON Payment_intent_amount_details_line_item
data Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable
instance Show Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable
instance Eq Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable
instance Data.Aeson.FromJSON Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable
instance Data.Aeson.ToJSON Payment_intent_amount_details_line_itemPayment_method_optionsNonNullable
data Payment_intent_amount_details_line_itemTaxNonNullable
instance Show Payment_intent_amount_details_line_itemTaxNonNullable
instance Eq Payment_intent_amount_details_line_itemTaxNonNullable
instance Data.Aeson.FromJSON Payment_intent_amount_details_line_itemTaxNonNullable
instance Data.Aeson.ToJSON Payment_intent_amount_details_line_itemTaxNonNullable
