module Stripe.CustomerSession.Types.PaymentMethodOptionsUsBankAccountMandateOptions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_us_bank_account_mandate_options
instance Show Payment_method_options_us_bank_account_mandate_options
instance Eq Payment_method_options_us_bank_account_mandate_options
instance Data.Aeson.FromJSON Payment_method_options_us_bank_account_mandate_options
instance Data.Aeson.ToJSON Payment_method_options_us_bank_account_mandate_options
data Payment_method_options_us_bank_account_mandate_optionsCollection_method
instance Show Payment_method_options_us_bank_account_mandate_optionsCollection_method
instance Eq Payment_method_options_us_bank_account_mandate_optionsCollection_method
instance Data.Aeson.FromJSON Payment_method_options_us_bank_account_mandate_optionsCollection_method
instance Data.Aeson.ToJSON Payment_method_options_us_bank_account_mandate_optionsCollection_method
