module Stripe.CustomerSession.Types.PaymentMethodOptionsCustomerBalanceBankTransfer where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_customer_balance_bank_transfer
instance Show Payment_method_options_customer_balance_bank_transfer
instance Eq Payment_method_options_customer_balance_bank_transfer
instance Data.Aeson.FromJSON Payment_method_options_customer_balance_bank_transfer
instance Data.Aeson.ToJSON Payment_method_options_customer_balance_bank_transfer
