module Stripe.CustomerSession.Types.PaymentMethodOptionsPix where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_pix
instance Show Payment_method_options_pix
instance Eq Payment_method_options_pix
instance Data.Aeson.FromJSON Payment_method_options_pix
instance Data.Aeson.ToJSON Payment_method_options_pix
data Payment_method_options_pixAmount_includes_iof
instance Show Payment_method_options_pixAmount_includes_iof
instance Eq Payment_method_options_pixAmount_includes_iof
instance Data.Aeson.FromJSON Payment_method_options_pixAmount_includes_iof
instance Data.Aeson.ToJSON Payment_method_options_pixAmount_includes_iof
data Payment_method_options_pixSetup_future_usage
instance Show Payment_method_options_pixSetup_future_usage
instance Eq Payment_method_options_pixSetup_future_usage
instance Data.Aeson.FromJSON Payment_method_options_pixSetup_future_usage
instance Data.Aeson.ToJSON Payment_method_options_pixSetup_future_usage
