module Stripe.CustomerSession.Types.PaymentMethodDetailsInteracPresentReceipt where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_interac_present_receipt
instance Show Payment_method_details_interac_present_receipt
instance Eq Payment_method_details_interac_present_receipt
instance Data.Aeson.FromJSON Payment_method_details_interac_present_receipt
instance Data.Aeson.ToJSON Payment_method_details_interac_present_receipt
data Payment_method_details_interac_present_receiptAccount_type
instance Show Payment_method_details_interac_present_receiptAccount_type
instance Eq Payment_method_details_interac_present_receiptAccount_type
instance Data.Aeson.FromJSON Payment_method_details_interac_present_receiptAccount_type
instance Data.Aeson.ToJSON Payment_method_details_interac_present_receiptAccount_type
