module Stripe.CustomerSession.Types.PaymentMethodOptionsKlarna where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_klarna
instance Show Payment_method_options_klarna
instance Eq Payment_method_options_klarna
instance Data.Aeson.FromJSON Payment_method_options_klarna
instance Data.Aeson.ToJSON Payment_method_options_klarna
data Payment_method_options_klarnaCapture_method
instance Show Payment_method_options_klarnaCapture_method
instance Eq Payment_method_options_klarnaCapture_method
instance Data.Aeson.FromJSON Payment_method_options_klarnaCapture_method
instance Data.Aeson.ToJSON Payment_method_options_klarnaCapture_method
data Payment_method_options_klarnaSetup_future_usage
instance Show Payment_method_options_klarnaSetup_future_usage
instance Eq Payment_method_options_klarnaSetup_future_usage
instance Data.Aeson.FromJSON Payment_method_options_klarnaSetup_future_usage
instance Data.Aeson.ToJSON Payment_method_options_klarnaSetup_future_usage
