module Stripe.CustomerSession.Types.PaymentMethodCardGeneratedCard where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_card_generated_card
instance Show Payment_method_card_generated_card
instance Eq Payment_method_card_generated_card
instance Data.Aeson.FromJSON Payment_method_card_generated_card
instance Data.Aeson.ToJSON Payment_method_card_generated_card
data Payment_method_card_generated_cardPayment_method_details
instance Show Payment_method_card_generated_cardPayment_method_details
instance Eq Payment_method_card_generated_cardPayment_method_details
instance Data.Aeson.FromJSON Payment_method_card_generated_cardPayment_method_details
instance Data.Aeson.ToJSON Payment_method_card_generated_cardPayment_method_details
data Payment_method_card_generated_cardSetup_attemptVariants
instance Show Payment_method_card_generated_cardSetup_attemptVariants
instance Eq Payment_method_card_generated_cardSetup_attemptVariants
instance Data.Aeson.FromJSON Payment_method_card_generated_cardSetup_attemptVariants
instance Data.Aeson.ToJSON Payment_method_card_generated_cardSetup_attemptVariants
