module Stripe.CustomerSession.Types.PaymentIntentNextActionDisplayBankTransferInstructions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_display_bank_transfer_instructions
instance Show Payment_intent_next_action_display_bank_transfer_instructions
instance Eq Payment_intent_next_action_display_bank_transfer_instructions
instance Data.Aeson.FromJSON Payment_intent_next_action_display_bank_transfer_instructions
instance Data.Aeson.ToJSON Payment_intent_next_action_display_bank_transfer_instructions
data Payment_intent_next_action_display_bank_transfer_instructionsType
instance Show Payment_intent_next_action_display_bank_transfer_instructionsType
instance Eq Payment_intent_next_action_display_bank_transfer_instructionsType
instance Data.Aeson.FromJSON Payment_intent_next_action_display_bank_transfer_instructionsType
instance Data.Aeson.ToJSON Payment_intent_next_action_display_bank_transfer_instructionsType
