module Stripe.CustomerSession.Types.PaymentMethodOptionsPromptpay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_promptpay
instance Show Payment_method_options_promptpay
instance Eq Payment_method_options_promptpay
instance Data.Aeson.FromJSON Payment_method_options_promptpay
instance Data.Aeson.ToJSON Payment_method_options_promptpay
