module Stripe.CustomerSession.Types.PaymentMethodOptionsCardMandateOptions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_card_mandate_options
instance Show Payment_method_options_card_mandate_options
instance Eq Payment_method_options_card_mandate_options
instance Data.Aeson.FromJSON Payment_method_options_card_mandate_options
instance Data.Aeson.ToJSON Payment_method_options_card_mandate_options
data Payment_method_options_card_mandate_optionsAmount_type
instance Show Payment_method_options_card_mandate_optionsAmount_type
instance Eq Payment_method_options_card_mandate_optionsAmount_type
instance Data.Aeson.FromJSON Payment_method_options_card_mandate_optionsAmount_type
instance Data.Aeson.ToJSON Payment_method_options_card_mandate_optionsAmount_type
data Payment_method_options_card_mandate_optionsInterval
instance Show Payment_method_options_card_mandate_optionsInterval
instance Eq Payment_method_options_card_mandate_optionsInterval
instance Data.Aeson.FromJSON Payment_method_options_card_mandate_optionsInterval
instance Data.Aeson.ToJSON Payment_method_options_card_mandate_optionsInterval
data Payment_method_options_card_mandate_optionsSupported_typesNonNullable
instance Show Payment_method_options_card_mandate_optionsSupported_typesNonNullable
instance Eq Payment_method_options_card_mandate_optionsSupported_typesNonNullable
instance Data.Aeson.FromJSON Payment_method_options_card_mandate_optionsSupported_typesNonNullable
instance Data.Aeson.ToJSON Payment_method_options_card_mandate_optionsSupported_typesNonNullable
