module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_mandate_options_acss_debit
instance Show Payment_intent_payment_method_options_mandate_options_acss_debit
instance Eq Payment_intent_payment_method_options_mandate_options_acss_debit
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_mandate_options_acss_debit
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_mandate_options_acss_debit
data Payment_intent_payment_method_options_mandate_options_acss_debitPayment_scheduleNonNullable
instance Show Payment_intent_payment_method_options_mandate_options_acss_debitPayment_scheduleNonNullable
instance Eq Payment_intent_payment_method_options_mandate_options_acss_debitPayment_scheduleNonNullable
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_mandate_options_acss_debitPayment_scheduleNonNullable
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_mandate_options_acss_debitPayment_scheduleNonNullable
data Payment_intent_payment_method_options_mandate_options_acss_debitTransaction_typeNonNullable
instance Show Payment_intent_payment_method_options_mandate_options_acss_debitTransaction_typeNonNullable
instance Eq Payment_intent_payment_method_options_mandate_options_acss_debitTransaction_typeNonNullable
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_mandate_options_acss_debitTransaction_typeNonNullable
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_mandate_options_acss_debitTransaction_typeNonNullable
