module Stripe.CustomerSession.Types.PaymentMethodAuBecsDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_au_becs_debit
instance Show Payment_method_au_becs_debit
instance Eq Payment_method_au_becs_debit
instance Data.Aeson.FromJSON Payment_method_au_becs_debit
instance Data.Aeson.ToJSON Payment_method_au_becs_debit
