module Stripe.CustomerSession.Types.PaymentMethodDetailsCrypto where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_crypto
instance Show Payment_method_details_crypto
instance Eq Payment_method_details_crypto
instance Data.Aeson.FromJSON Payment_method_details_crypto
instance Data.Aeson.ToJSON Payment_method_details_crypto
data Payment_method_details_cryptoNetwork
instance Show Payment_method_details_cryptoNetwork
instance Eq Payment_method_details_cryptoNetwork
instance Data.Aeson.FromJSON Payment_method_details_cryptoNetwork
instance Data.Aeson.ToJSON Payment_method_details_cryptoNetwork
data Payment_method_details_cryptoToken_currency
instance Show Payment_method_details_cryptoToken_currency
instance Eq Payment_method_details_cryptoToken_currency
instance Data.Aeson.FromJSON Payment_method_details_cryptoToken_currency
instance Data.Aeson.ToJSON Payment_method_details_cryptoToken_currency
