module Stripe.CustomerSession.Types.PaymentMethodDetailsAchDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_ach_debit
instance Show Payment_method_details_ach_debit
instance Eq Payment_method_details_ach_debit
instance Data.Aeson.FromJSON Payment_method_details_ach_debit
instance Data.Aeson.ToJSON Payment_method_details_ach_debit
data Payment_method_details_ach_debitAccount_holder_typeNonNullable
instance Show Payment_method_details_ach_debitAccount_holder_typeNonNullable
instance Eq Payment_method_details_ach_debitAccount_holder_typeNonNullable
instance Data.Aeson.FromJSON Payment_method_details_ach_debitAccount_holder_typeNonNullable
instance Data.Aeson.ToJSON Payment_method_details_ach_debitAccount_holder_typeNonNullable
