module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallmentPlan where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payments_primitives_payment_records_resource_payment_method_card_details_resource_installment_plan
instance Show Payments_primitives_payment_records_resource_payment_method_card_details_resource_installment_plan
instance Eq Payments_primitives_payment_records_resource_payment_method_card_details_resource_installment_plan
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_installment_plan
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_installment_plan
