module Stripe.CustomerSession.Types.PaymentMethodOptionsSofort where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_sofort
instance Show Payment_method_options_sofort
instance Eq Payment_method_options_sofort
instance Data.Aeson.FromJSON Payment_method_options_sofort
instance Data.Aeson.ToJSON Payment_method_options_sofort
data Payment_method_options_sofortPreferred_languageNonNullable
instance Show Payment_method_options_sofortPreferred_languageNonNullable
instance Eq Payment_method_options_sofortPreferred_languageNonNullable
instance Data.Aeson.FromJSON Payment_method_options_sofortPreferred_languageNonNullable
instance Data.Aeson.ToJSON Payment_method_options_sofortPreferred_languageNonNullable
data Payment_method_options_sofortSetup_future_usage
instance Show Payment_method_options_sofortSetup_future_usage
instance Eq Payment_method_options_sofortSetup_future_usage
instance Data.Aeson.FromJSON Payment_method_options_sofortSetup_future_usage
instance Data.Aeson.ToJSON Payment_method_options_sofortSetup_future_usage
