module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsBacsDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_bacs_debit
instance Show Payment_intent_payment_method_options_bacs_debit
instance Eq Payment_intent_payment_method_options_bacs_debit
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_bacs_debit
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_bacs_debit
data Payment_intent_payment_method_options_bacs_debitSetup_future_usage
instance Show Payment_intent_payment_method_options_bacs_debitSetup_future_usage
instance Eq Payment_intent_payment_method_options_bacs_debitSetup_future_usage
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_bacs_debitSetup_future_usage
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_bacs_debitSetup_future_usage
