module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourceProcessorDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payments_primitives_payment_records_resource_processor_details
instance Show Payments_primitives_payment_records_resource_processor_details
instance Eq Payments_primitives_payment_records_resource_processor_details
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_processor_details
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_processor_details
