module Stripe.CustomerSession.Types.PaymentMethodCardWalletMasterpass where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_card_wallet_masterpass
instance Show Payment_method_card_wallet_masterpass
instance Eq Payment_method_card_wallet_masterpass
instance Data.Aeson.FromJSON Payment_method_card_wallet_masterpass
instance Data.Aeson.ToJSON Payment_method_card_wallet_masterpass
data Payment_method_card_wallet_masterpassBilling_addressNonNullable
instance Show Payment_method_card_wallet_masterpassBilling_addressNonNullable
instance Eq Payment_method_card_wallet_masterpassBilling_addressNonNullable
instance Data.Aeson.FromJSON Payment_method_card_wallet_masterpassBilling_addressNonNullable
instance Data.Aeson.ToJSON Payment_method_card_wallet_masterpassBilling_addressNonNullable
data Payment_method_card_wallet_masterpassShipping_addressNonNullable
instance Show Payment_method_card_wallet_masterpassShipping_addressNonNullable
instance Eq Payment_method_card_wallet_masterpassShipping_addressNonNullable
instance Data.Aeson.FromJSON Payment_method_card_wallet_masterpassShipping_addressNonNullable
instance Data.Aeson.ToJSON Payment_method_card_wallet_masterpassShipping_addressNonNullable
