module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsUsBankAccount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_us_bank_account
instance Show Payment_intent_payment_method_options_us_bank_account
instance Eq Payment_intent_payment_method_options_us_bank_account
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_us_bank_account
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_us_bank_account
