module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsUsBankAccount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_us_bank_account
instance Show Payment_intent_payment_method_options_us_bank_account
instance Eq Payment_intent_payment_method_options_us_bank_account
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_us_bank_account
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_us_bank_account
data Payment_intent_payment_method_options_us_bank_accountSetup_future_usage
instance Show Payment_intent_payment_method_options_us_bank_accountSetup_future_usage
instance Eq Payment_intent_payment_method_options_us_bank_accountSetup_future_usage
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_us_bank_accountSetup_future_usage
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_us_bank_accountSetup_future_usage
data Payment_intent_payment_method_options_us_bank_accountTransaction_purpose
instance Show Payment_intent_payment_method_options_us_bank_accountTransaction_purpose
instance Eq Payment_intent_payment_method_options_us_bank_accountTransaction_purpose
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_us_bank_accountTransaction_purpose
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_us_bank_accountTransaction_purpose
data Payment_intent_payment_method_options_us_bank_accountVerification_method
instance Show Payment_intent_payment_method_options_us_bank_accountVerification_method
instance Eq Payment_intent_payment_method_options_us_bank_accountVerification_method
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_us_bank_accountVerification_method
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_us_bank_accountVerification_method
