module Stripe.CustomerSession.Types.PaymentMethodOptionsBancontact where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_bancontact
instance Show Payment_method_options_bancontact
instance Eq Payment_method_options_bancontact
instance Data.Aeson.FromJSON Payment_method_options_bancontact
instance Data.Aeson.ToJSON Payment_method_options_bancontact
data Payment_method_options_bancontactPreferred_language
instance Show Payment_method_options_bancontactPreferred_language
instance Eq Payment_method_options_bancontactPreferred_language
instance Data.Aeson.FromJSON Payment_method_options_bancontactPreferred_language
instance Data.Aeson.ToJSON Payment_method_options_bancontactPreferred_language
data Payment_method_options_bancontactSetup_future_usage
instance Show Payment_method_options_bancontactSetup_future_usage
instance Eq Payment_method_options_bancontactSetup_future_usage
instance Data.Aeson.FromJSON Payment_method_options_bancontactSetup_future_usage
instance Data.Aeson.ToJSON Payment_method_options_bancontactSetup_future_usage
