module Stripe.CustomerSession.Types.PaymentMethodDetailsKlarna where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_klarna
instance Show Payment_method_details_klarna
instance Eq Payment_method_details_klarna
instance Data.Aeson.FromJSON Payment_method_details_klarna
instance Data.Aeson.ToJSON Payment_method_details_klarna
data Payment_method_details_klarnaPayer_detailsNonNullable
instance Show Payment_method_details_klarnaPayer_detailsNonNullable
instance Eq Payment_method_details_klarnaPayer_detailsNonNullable
instance Data.Aeson.FromJSON Payment_method_details_klarnaPayer_detailsNonNullable
instance Data.Aeson.ToJSON Payment_method_details_klarnaPayer_detailsNonNullable
data Payment_method_details_klarnaPayer_detailsNonNullableAddressNonNullable
instance Show Payment_method_details_klarnaPayer_detailsNonNullableAddressNonNullable
instance Eq Payment_method_details_klarnaPayer_detailsNonNullableAddressNonNullable
instance Data.Aeson.FromJSON Payment_method_details_klarnaPayer_detailsNonNullableAddressNonNullable
instance Data.Aeson.ToJSON Payment_method_details_klarnaPayer_detailsNonNullableAddressNonNullable
