module Stripe.CustomerSession.Types.PaymentMethodDetailsKonbiniStore where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_konbini_store
instance Show Payment_method_details_konbini_store
instance Eq Payment_method_details_konbini_store
instance Data.Aeson.FromJSON Payment_method_details_konbini_store
instance Data.Aeson.ToJSON Payment_method_details_konbini_store
