module Stripe.CustomerSession.Types.PaymentIntentNextActionPromptpayDisplayQrCode where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_promptpay_display_qr_code
instance Show Payment_intent_next_action_promptpay_display_qr_code
instance Eq Payment_intent_next_action_promptpay_display_qr_code
instance Data.Aeson.FromJSON Payment_intent_next_action_promptpay_display_qr_code
instance Data.Aeson.ToJSON Payment_intent_next_action_promptpay_display_qr_code
