module Stripe.CustomerSession.Types.PaymentMethodOptionsCustomerBalanceEuBankAccount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_customer_balance_eu_bank_account
instance Show Payment_method_options_customer_balance_eu_bank_account
instance Eq Payment_method_options_customer_balance_eu_bank_account
instance Data.Aeson.FromJSON Payment_method_options_customer_balance_eu_bank_account
instance Data.Aeson.ToJSON Payment_method_options_customer_balance_eu_bank_account
