-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PaymentMethodDetailsP24
module Stripe.CustomerSession.Types.PaymentMethodDetailsP24 where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias

-- | Defines the object schema located at @components.schemas.payment_method_details_p24@ in the specification.
-- 
-- 
data Payment_method_details_p24 = Payment_method_details_p24 {
  -- | bank: The customer\'s bank. Can be one of \`ing\`, \`citi_handlowy\`, \`tmobile_usbugi_bankowe\`, \`plus_bank\`, \`etransfer_pocztowy24\`, \`banki_spbdzielcze\`, \`bank_nowy_bfg_sa\`, \`getin_bank\`, \`velobank\`, \`blik\`, \`noble_pay\`, \`ideabank\`, \`envelobank\`, \`santander_przelew24\`, \`nest_przelew\`, \`mbank_mtransfer\`, \`inteligo\`, \`pbac_z_ipko\`, \`bnp_paribas\`, \`credit_agricole\`, \`toyota_bank\`, \`bank_pekao_sa\`, \`volkswagen_bank\`, \`bank_millennium\`, \`alior_bank\`, or \`boz\`.
  payment_method_details_p24Bank :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | reference: Unique reference for this Przelewy24 payment.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , payment_method_details_p24Reference :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | verified_name: Owner\'s verified full name. Values are verified or provided by Przelewy24 directly
  -- (if supported) at the time of authorization or settlement. They cannot be set or mutated.
  -- Przelewy24 rarely provides this information so the attribute is usually empty.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , payment_method_details_p24Verified_name :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Payment_method_details_p24
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("bank" Data.Aeson.Types.ToJSON..=)) (payment_method_details_p24Bank obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("reference" Data.Aeson.Types.ToJSON..=)) (payment_method_details_p24Reference obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("verified_name" Data.Aeson.Types.ToJSON..=)) (payment_method_details_p24Verified_name obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("bank" Data.Aeson.Types.ToJSON..=)) (payment_method_details_p24Bank obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("reference" Data.Aeson.Types.ToJSON..=)) (payment_method_details_p24Reference obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("verified_name" Data.Aeson.Types.ToJSON..=)) (payment_method_details_p24Verified_name obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Payment_method_details_p24
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Payment_method_details_p24" (\obj -> ((GHC.Base.pure Payment_method_details_p24 GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "bank")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "reference")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "verified_name"))}
-- | Create a new 'Payment_method_details_p24' with all required fields.
mkPayment_method_details_p24 :: Payment_method_details_p24
mkPayment_method_details_p24 = Payment_method_details_p24{payment_method_details_p24Bank = GHC.Maybe.Nothing,
                                                          payment_method_details_p24Reference = GHC.Maybe.Nothing,
                                                          payment_method_details_p24Verified_name = GHC.Maybe.Nothing}
