module Stripe.CustomerSession.Types.PaymentMethodDetailsBancontact where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_bancontact
instance Show Payment_method_details_bancontact
instance Eq Payment_method_details_bancontact
instance Data.Aeson.FromJSON Payment_method_details_bancontact
instance Data.Aeson.ToJSON Payment_method_details_bancontact
data Payment_method_details_bancontactGenerated_sepa_debitNonNullableVariants
instance Show Payment_method_details_bancontactGenerated_sepa_debitNonNullableVariants
instance Eq Payment_method_details_bancontactGenerated_sepa_debitNonNullableVariants
instance Data.Aeson.FromJSON Payment_method_details_bancontactGenerated_sepa_debitNonNullableVariants
instance Data.Aeson.ToJSON Payment_method_details_bancontactGenerated_sepa_debitNonNullableVariants
data Payment_method_details_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Show Payment_method_details_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Eq Payment_method_details_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Data.Aeson.FromJSON Payment_method_details_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Data.Aeson.ToJSON Payment_method_details_bancontactGenerated_sepa_debit_mandateNonNullableVariants
data Payment_method_details_bancontactPreferred_languageNonNullable
instance Show Payment_method_details_bancontactPreferred_languageNonNullable
instance Eq Payment_method_details_bancontactPreferred_languageNonNullable
instance Data.Aeson.FromJSON Payment_method_details_bancontactPreferred_languageNonNullable
instance Data.Aeson.ToJSON Payment_method_details_bancontactPreferred_languageNonNullable
