module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourceAmount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payments_primitives_payment_records_resource_amount
instance Show Payments_primitives_payment_records_resource_amount
instance Eq Payments_primitives_payment_records_resource_amount
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_amount
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_amount
