module Stripe.CustomerSession.Types.PaymentMethodDetailsKrCard where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_kr_card
instance Show Payment_method_details_kr_card
instance Eq Payment_method_details_kr_card
instance Data.Aeson.FromJSON Payment_method_details_kr_card
instance Data.Aeson.ToJSON Payment_method_details_kr_card
