-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PaymentFlowsPrivatePaymentMethodsKlarnaPaymentIntentAmountDetailsLineItemPaymentMethodOptions
module Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsKlarnaPaymentIntentAmountDetailsLineItemPaymentMethodOptions where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias

-- | Defines the object schema located at @components.schemas.payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options@ in the specification.
-- 
-- 
data Payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options = Payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options {
  -- | image_url
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 2048
  payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsImage_url :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | product_url
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 2048
  , payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsProduct_url :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | reference
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 255
  , payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsReference :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | subscription_reference
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 2048
  , payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsSubscription_reference :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("image_url" Data.Aeson.Types.ToJSON..=)) (payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsImage_url obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("product_url" Data.Aeson.Types.ToJSON..=)) (payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsProduct_url obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("reference" Data.Aeson.Types.ToJSON..=)) (payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsReference obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription_reference" Data.Aeson.Types.ToJSON..=)) (payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsSubscription_reference obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("image_url" Data.Aeson.Types.ToJSON..=)) (payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsImage_url obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("product_url" Data.Aeson.Types.ToJSON..=)) (payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsProduct_url obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("reference" Data.Aeson.Types.ToJSON..=)) (payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsReference obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("subscription_reference" Data.Aeson.Types.ToJSON..=)) (payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsSubscription_reference obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options" (\obj -> (((GHC.Base.pure Payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "image_url")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "product_url")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "reference")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "subscription_reference"))}
-- | Create a new 'Payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options' with all required fields.
mkPayment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options :: Payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options
mkPayment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options = Payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_options{payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsImage_url = GHC.Maybe.Nothing,
                                                                                                                                                                                                                            payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsProduct_url = GHC.Maybe.Nothing,
                                                                                                                                                                                                                            payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsReference = GHC.Maybe.Nothing,
                                                                                                                                                                                                                            payment_flows_private_payment_methods_klarna_payment_intent_amount_details_line_item_payment_method_optionsSubscription_reference = GHC.Maybe.Nothing}
