module Stripe.CustomerSession.Types.PaymentMethodCardGeneratedCard where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_card_generated_card
instance Show Payment_method_card_generated_card
instance Eq Payment_method_card_generated_card
instance Data.Aeson.FromJSON Payment_method_card_generated_card
instance Data.Aeson.ToJSON Payment_method_card_generated_card
data Payment_method_card_generated_cardPayment_method_detailsNonNullable
instance Show Payment_method_card_generated_cardPayment_method_detailsNonNullable
instance Eq Payment_method_card_generated_cardPayment_method_detailsNonNullable
instance Data.Aeson.FromJSON Payment_method_card_generated_cardPayment_method_detailsNonNullable
instance Data.Aeson.ToJSON Payment_method_card_generated_cardPayment_method_detailsNonNullable
data Payment_method_card_generated_cardSetup_attemptNonNullableVariants
instance Show Payment_method_card_generated_cardSetup_attemptNonNullableVariants
instance Eq Payment_method_card_generated_cardSetup_attemptNonNullableVariants
instance Data.Aeson.FromJSON Payment_method_card_generated_cardSetup_attemptNonNullableVariants
instance Data.Aeson.ToJSON Payment_method_card_generated_cardSetup_attemptNonNullableVariants
