module Stripe.CustomerSession.Types.PaymentMethodFpx where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_fpx
instance Show Payment_method_fpx
instance Eq Payment_method_fpx
instance Data.Aeson.FromJSON Payment_method_fpx
instance Data.Aeson.ToJSON Payment_method_fpx
data Payment_method_fpxBank
instance Show Payment_method_fpxBank
instance Eq Payment_method_fpxBank
instance Data.Aeson.FromJSON Payment_method_fpxBank
instance Data.Aeson.ToJSON Payment_method_fpxBank
