module Stripe.CustomerSession.Types.PaymentMethodDetailsAchCreditTransfer where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_ach_credit_transfer
instance Show Payment_method_details_ach_credit_transfer
instance Eq Payment_method_details_ach_credit_transfer
instance Data.Aeson.FromJSON Payment_method_details_ach_credit_transfer
instance Data.Aeson.ToJSON Payment_method_details_ach_credit_transfer
