module Stripe.CustomerSession.Types.PaymentIntentNextActionAlipayHandleRedirect where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_alipay_handle_redirect
instance Show Payment_intent_next_action_alipay_handle_redirect
instance Eq Payment_intent_next_action_alipay_handle_redirect
instance Data.Aeson.FromJSON Payment_intent_next_action_alipay_handle_redirect
instance Data.Aeson.ToJSON Payment_intent_next_action_alipay_handle_redirect
