module Stripe.CustomerSession.Types.PaymentIntentNextActionUpiqrCode where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_upiqr_code
instance Show Payment_intent_next_action_upiqr_code
instance Eq Payment_intent_next_action_upiqr_code
instance Data.Aeson.FromJSON Payment_intent_next_action_upiqr_code
instance Data.Aeson.ToJSON Payment_intent_next_action_upiqr_code
