module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsPayto where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_payto
instance Show Payment_intent_payment_method_options_payto
instance Eq Payment_intent_payment_method_options_payto
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_payto
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_payto
data Payment_intent_payment_method_options_paytoSetup_future_usage
instance Show Payment_intent_payment_method_options_paytoSetup_future_usage
instance Eq Payment_intent_payment_method_options_paytoSetup_future_usage
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_paytoSetup_future_usage
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_paytoSetup_future_usage
