module Stripe.CustomerSession.Types.PaymentMethodDetailsKonbini where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_konbini
instance Show Payment_method_details_konbini
instance Eq Payment_method_details_konbini
instance Data.Aeson.FromJSON Payment_method_details_konbini
instance Data.Aeson.ToJSON Payment_method_details_konbini
data Payment_method_details_konbiniStoreNonNullable
instance Show Payment_method_details_konbiniStoreNonNullable
instance Eq Payment_method_details_konbiniStoreNonNullable
instance Data.Aeson.FromJSON Payment_method_details_konbiniStoreNonNullable
instance Data.Aeson.ToJSON Payment_method_details_konbiniStoreNonNullable
data Payment_method_details_konbiniStoreNonNullableChainNonNullable
instance Show Payment_method_details_konbiniStoreNonNullableChainNonNullable
instance Eq Payment_method_details_konbiniStoreNonNullableChainNonNullable
instance Data.Aeson.FromJSON Payment_method_details_konbiniStoreNonNullableChainNonNullable
instance Data.Aeson.ToJSON Payment_method_details_konbiniStoreNonNullableChainNonNullable
