module Stripe.CustomerSession.Types.PaymentMethodDetailsMultibanco where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_multibanco
instance Show Payment_method_details_multibanco
instance Eq Payment_method_details_multibanco
instance Data.Aeson.FromJSON Payment_method_details_multibanco
instance Data.Aeson.ToJSON Payment_method_details_multibanco
