module Stripe.CustomerSession.Types.PaymentRecord where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_record
instance Show Payment_record
instance Eq Payment_record
instance Data.Aeson.FromJSON Payment_record
instance Data.Aeson.ToJSON Payment_record
data Payment_recordCustomer_detailsNonNullable
instance Show Payment_recordCustomer_detailsNonNullable
instance Eq Payment_recordCustomer_detailsNonNullable
instance Data.Aeson.FromJSON Payment_recordCustomer_detailsNonNullable
instance Data.Aeson.ToJSON Payment_recordCustomer_detailsNonNullable
data Payment_recordCustomer_presenceNonNullable
instance Show Payment_recordCustomer_presenceNonNullable
instance Eq Payment_recordCustomer_presenceNonNullable
instance Data.Aeson.FromJSON Payment_recordCustomer_presenceNonNullable
instance Data.Aeson.ToJSON Payment_recordCustomer_presenceNonNullable
data Payment_recordPayment_method_detailsNonNullable
instance Show Payment_recordPayment_method_detailsNonNullable
instance Eq Payment_recordPayment_method_detailsNonNullable
instance Data.Aeson.FromJSON Payment_recordPayment_method_detailsNonNullable
instance Data.Aeson.ToJSON Payment_recordPayment_method_detailsNonNullable
data Payment_recordPayment_method_detailsNonNullableBilling_detailsNonNullable
instance Show Payment_recordPayment_method_detailsNonNullableBilling_detailsNonNullable
instance Eq Payment_recordPayment_method_detailsNonNullableBilling_detailsNonNullable
instance Data.Aeson.FromJSON Payment_recordPayment_method_detailsNonNullableBilling_detailsNonNullable
instance Data.Aeson.ToJSON Payment_recordPayment_method_detailsNonNullableBilling_detailsNonNullable
data Payment_recordReported_by
instance Show Payment_recordReported_by
instance Eq Payment_recordReported_by
instance Data.Aeson.FromJSON Payment_recordReported_by
instance Data.Aeson.ToJSON Payment_recordReported_by
data Payment_recordShipping_detailsNonNullable
instance Show Payment_recordShipping_detailsNonNullable
instance Eq Payment_recordShipping_detailsNonNullable
instance Data.Aeson.FromJSON Payment_recordShipping_detailsNonNullable
instance Data.Aeson.ToJSON Payment_recordShipping_detailsNonNullable
