module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceThreeDSecure where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payments_primitives_payment_records_resource_payment_method_card_details_resource_three_d_secure
instance Show Payments_primitives_payment_records_resource_payment_method_card_details_resource_three_d_secure
instance Eq Payments_primitives_payment_records_resource_payment_method_card_details_resource_three_d_secure
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_three_d_secure
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_three_d_secure
