module Stripe.CustomerSession.Types.PaymentMethodConfigBizPaymentMethodConfigurationDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_config_biz_payment_method_configuration_details
instance Show Payment_method_config_biz_payment_method_configuration_details
instance Eq Payment_method_config_biz_payment_method_configuration_details
instance Data.Aeson.FromJSON Payment_method_config_biz_payment_method_configuration_details
instance Data.Aeson.ToJSON Payment_method_config_biz_payment_method_configuration_details
