module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourcePaymentMethodKonbiniDetailsResourceStore where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payments_primitives_payment_records_resource_payment_method_konbini_details_resource_store
instance Show Payments_primitives_payment_records_resource_payment_method_konbini_details_resource_store
instance Eq Payments_primitives_payment_records_resource_payment_method_konbini_details_resource_store
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_payment_method_konbini_details_resource_store
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_payment_method_konbini_details_resource_store
