module Stripe.CustomerSession.Types.PaymentMethodDetailsBlik where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_blik
instance Show Payment_method_details_blik
instance Eq Payment_method_details_blik
instance Data.Aeson.FromJSON Payment_method_details_blik
instance Data.Aeson.ToJSON Payment_method_details_blik
