module Stripe.CustomerSession.Types.PaymentMethodCardWalletVisaCheckout where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_card_wallet_visa_checkout
instance Show Payment_method_card_wallet_visa_checkout
instance Eq Payment_method_card_wallet_visa_checkout
instance Data.Aeson.FromJSON Payment_method_card_wallet_visa_checkout
instance Data.Aeson.ToJSON Payment_method_card_wallet_visa_checkout
data Payment_method_card_wallet_visa_checkoutBilling_addressNonNullable
instance Show Payment_method_card_wallet_visa_checkoutBilling_addressNonNullable
instance Eq Payment_method_card_wallet_visa_checkoutBilling_addressNonNullable
instance Data.Aeson.FromJSON Payment_method_card_wallet_visa_checkoutBilling_addressNonNullable
instance Data.Aeson.ToJSON Payment_method_card_wallet_visa_checkoutBilling_addressNonNullable
data Payment_method_card_wallet_visa_checkoutShipping_addressNonNullable
instance Show Payment_method_card_wallet_visa_checkoutShipping_addressNonNullable
instance Eq Payment_method_card_wallet_visa_checkoutShipping_addressNonNullable
instance Data.Aeson.FromJSON Payment_method_card_wallet_visa_checkoutShipping_addressNonNullable
instance Data.Aeson.ToJSON Payment_method_card_wallet_visa_checkoutShipping_addressNonNullable
