module Stripe.CustomerSession.Types.PaymentIntentTypeSpecificPaymentMethodOptionsClient where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_type_specific_payment_method_options_client
instance Show Payment_intent_type_specific_payment_method_options_client
instance Eq Payment_intent_type_specific_payment_method_options_client
instance Data.Aeson.FromJSON Payment_intent_type_specific_payment_method_options_client
instance Data.Aeson.ToJSON Payment_intent_type_specific_payment_method_options_client
data Payment_intent_type_specific_payment_method_options_clientCapture_method
instance Show Payment_intent_type_specific_payment_method_options_clientCapture_method
instance Eq Payment_intent_type_specific_payment_method_options_clientCapture_method
instance Data.Aeson.FromJSON Payment_intent_type_specific_payment_method_options_clientCapture_method
instance Data.Aeson.ToJSON Payment_intent_type_specific_payment_method_options_clientCapture_method
data Payment_intent_type_specific_payment_method_options_clientSetup_future_usage
instance Show Payment_intent_type_specific_payment_method_options_clientSetup_future_usage
instance Eq Payment_intent_type_specific_payment_method_options_clientSetup_future_usage
instance Data.Aeson.FromJSON Payment_intent_type_specific_payment_method_options_clientSetup_future_usage
instance Data.Aeson.ToJSON Payment_intent_type_specific_payment_method_options_clientSetup_future_usage
data Payment_intent_type_specific_payment_method_options_clientVerification_method
instance Show Payment_intent_type_specific_payment_method_options_clientVerification_method
instance Eq Payment_intent_type_specific_payment_method_options_clientVerification_method
instance Data.Aeson.FromJSON Payment_intent_type_specific_payment_method_options_clientVerification_method
instance Data.Aeson.ToJSON Payment_intent_type_specific_payment_method_options_clientVerification_method
