module Stripe.CustomerSession.Types.PaymentMethodDetailsSatispay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_satispay
instance Show Payment_method_details_satispay
instance Eq Payment_method_details_satispay
instance Data.Aeson.FromJSON Payment_method_details_satispay
instance Data.Aeson.ToJSON Payment_method_details_satispay
