module Stripe.CustomerSession.Types.PaymentFlowsAmountDetailsResourceLineItemsListResourceLineItemResourcePaymentMethodOptions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_amount_details_resource_line_items_list_resource_line_item_resource_payment_method_options
instance Show Payment_flows_amount_details_resource_line_items_list_resource_line_item_resource_payment_method_options
instance Eq Payment_flows_amount_details_resource_line_items_list_resource_line_item_resource_payment_method_options
instance Data.Aeson.FromJSON Payment_flows_amount_details_resource_line_items_list_resource_line_item_resource_payment_method_options
instance Data.Aeson.ToJSON Payment_flows_amount_details_resource_line_items_list_resource_line_item_resource_payment_method_options
