module Stripe.CustomerSession.Types.PaymentMethodOptionsWechatPay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_wechat_pay
instance Show Payment_method_options_wechat_pay
instance Eq Payment_method_options_wechat_pay
instance Data.Aeson.FromJSON Payment_method_options_wechat_pay
instance Data.Aeson.ToJSON Payment_method_options_wechat_pay
data Payment_method_options_wechat_payClientNonNullable
instance Show Payment_method_options_wechat_payClientNonNullable
instance Eq Payment_method_options_wechat_payClientNonNullable
instance Data.Aeson.FromJSON Payment_method_options_wechat_payClientNonNullable
instance Data.Aeson.ToJSON Payment_method_options_wechat_payClientNonNullable
data Payment_method_options_wechat_paySetup_future_usage
instance Show Payment_method_options_wechat_paySetup_future_usage
instance Eq Payment_method_options_wechat_paySetup_future_usage
instance Data.Aeson.FromJSON Payment_method_options_wechat_paySetup_future_usage
instance Data.Aeson.ToJSON Payment_method_options_wechat_paySetup_future_usage
