module Stripe.CustomerSession.Types.PaymentMethodCardWallet where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_card_wallet
instance Show Payment_method_card_wallet
instance Eq Payment_method_card_wallet
instance Data.Aeson.FromJSON Payment_method_card_wallet
instance Data.Aeson.ToJSON Payment_method_card_wallet
