module Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsCardPresentAmountDetailsLineItemPaymentMethodOptions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_private_payment_methods_card_present_amount_details_line_item_payment_method_options
instance Show Payment_flows_private_payment_methods_card_present_amount_details_line_item_payment_method_options
instance Eq Payment_flows_private_payment_methods_card_present_amount_details_line_item_payment_method_options
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_card_present_amount_details_line_item_payment_method_options
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_card_present_amount_details_line_item_payment_method_options
