module Stripe.CustomerSession.Types.Payout where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payout
instance Show Payout
instance Eq Payout
instance Data.Aeson.FromJSON Payout
instance Data.Aeson.ToJSON Payout
data PayoutApplication_feeNonNullableVariants
instance Show PayoutApplication_feeNonNullableVariants
instance Eq PayoutApplication_feeNonNullableVariants
instance Data.Aeson.FromJSON PayoutApplication_feeNonNullableVariants
instance Data.Aeson.ToJSON PayoutApplication_feeNonNullableVariants
data PayoutBalance_transactionNonNullableVariants
instance Show PayoutBalance_transactionNonNullableVariants
instance Eq PayoutBalance_transactionNonNullableVariants
instance Data.Aeson.FromJSON PayoutBalance_transactionNonNullableVariants
instance Data.Aeson.ToJSON PayoutBalance_transactionNonNullableVariants
data PayoutDestinationNonNullableVariants
instance Show PayoutDestinationNonNullableVariants
instance Eq PayoutDestinationNonNullableVariants
instance Data.Aeson.FromJSON PayoutDestinationNonNullableVariants
instance Data.Aeson.ToJSON PayoutDestinationNonNullableVariants
data PayoutFailure_balance_transactionNonNullableVariants
instance Show PayoutFailure_balance_transactionNonNullableVariants
instance Eq PayoutFailure_balance_transactionNonNullableVariants
instance Data.Aeson.FromJSON PayoutFailure_balance_transactionNonNullableVariants
instance Data.Aeson.ToJSON PayoutFailure_balance_transactionNonNullableVariants
data PayoutOriginal_payoutNonNullableVariants
instance Show PayoutOriginal_payoutNonNullableVariants
instance Eq PayoutOriginal_payoutNonNullableVariants
instance Data.Aeson.FromJSON PayoutOriginal_payoutNonNullableVariants
instance Data.Aeson.ToJSON PayoutOriginal_payoutNonNullableVariants
data PayoutReconciliation_status
instance Show PayoutReconciliation_status
instance Eq PayoutReconciliation_status
instance Data.Aeson.FromJSON PayoutReconciliation_status
instance Data.Aeson.ToJSON PayoutReconciliation_status
data PayoutReversed_byNonNullableVariants
instance Show PayoutReversed_byNonNullableVariants
instance Eq PayoutReversed_byNonNullableVariants
instance Data.Aeson.FromJSON PayoutReversed_byNonNullableVariants
instance Data.Aeson.ToJSON PayoutReversed_byNonNullableVariants
data PayoutTrace_idNonNullable
instance Show PayoutTrace_idNonNullable
instance Eq PayoutTrace_idNonNullable
instance Data.Aeson.FromJSON PayoutTrace_idNonNullable
instance Data.Aeson.ToJSON PayoutTrace_idNonNullable
data PayoutType
instance Show PayoutType
instance Eq PayoutType
instance Data.Aeson.FromJSON PayoutType
instance Data.Aeson.ToJSON PayoutType
