module Stripe.CustomerSession.Types.Payout where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payout
instance Show Payout
instance Eq Payout
instance Data.Aeson.FromJSON Payout
instance Data.Aeson.ToJSON Payout
data PayoutApplication_feeVariants
instance Show PayoutApplication_feeVariants
instance Eq PayoutApplication_feeVariants
instance Data.Aeson.FromJSON PayoutApplication_feeVariants
instance Data.Aeson.ToJSON PayoutApplication_feeVariants
data PayoutBalance_transactionVariants
instance Show PayoutBalance_transactionVariants
instance Eq PayoutBalance_transactionVariants
instance Data.Aeson.FromJSON PayoutBalance_transactionVariants
instance Data.Aeson.ToJSON PayoutBalance_transactionVariants
data PayoutDestinationVariants
instance Show PayoutDestinationVariants
instance Eq PayoutDestinationVariants
instance Data.Aeson.FromJSON PayoutDestinationVariants
instance Data.Aeson.ToJSON PayoutDestinationVariants
data PayoutFailure_balance_transactionVariants
instance Show PayoutFailure_balance_transactionVariants
instance Eq PayoutFailure_balance_transactionVariants
instance Data.Aeson.FromJSON PayoutFailure_balance_transactionVariants
instance Data.Aeson.ToJSON PayoutFailure_balance_transactionVariants
data PayoutOriginal_payoutVariants
instance Show PayoutOriginal_payoutVariants
instance Eq PayoutOriginal_payoutVariants
instance Data.Aeson.FromJSON PayoutOriginal_payoutVariants
instance Data.Aeson.ToJSON PayoutOriginal_payoutVariants
data PayoutReversed_byVariants
instance Show PayoutReversed_byVariants
instance Eq PayoutReversed_byVariants
instance Data.Aeson.FromJSON PayoutReversed_byVariants
instance Data.Aeson.ToJSON PayoutReversed_byVariants
data PayoutTrace_id
instance Show PayoutTrace_id
instance Eq PayoutTrace_id
instance Data.Aeson.FromJSON PayoutTrace_id
instance Data.Aeson.ToJSON PayoutTrace_id
