module Stripe.CustomerSession.Types.PersonRaceDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Person_race_details
instance Show Person_race_details
instance Eq Person_race_details
instance Data.Aeson.FromJSON Person_race_details
instance Data.Aeson.ToJSON Person_race_details
data Person_race_detailsRaceNonNullable
instance Show Person_race_detailsRaceNonNullable
instance Eq Person_race_detailsRaceNonNullable
instance Data.Aeson.FromJSON Person_race_detailsRaceNonNullable
instance Data.Aeson.ToJSON Person_race_detailsRaceNonNullable
