module Stripe.CustomerSession.Types.PersonEthnicityDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Person_ethnicity_details
instance Show Person_ethnicity_details
instance Eq Person_ethnicity_details
instance Data.Aeson.FromJSON Person_ethnicity_details
instance Data.Aeson.ToJSON Person_ethnicity_details
