module Stripe.CustomerSession.Types.PersonUsCfpbData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Person_us_cfpb_data
instance Show Person_us_cfpb_data
instance Eq Person_us_cfpb_data
instance Data.Aeson.FromJSON Person_us_cfpb_data
instance Data.Aeson.ToJSON Person_us_cfpb_data
data Person_us_cfpb_dataEthnicity_detailsNonNullable
instance Show Person_us_cfpb_dataEthnicity_detailsNonNullable
instance Eq Person_us_cfpb_dataEthnicity_detailsNonNullable
instance Data.Aeson.FromJSON Person_us_cfpb_dataEthnicity_detailsNonNullable
instance Data.Aeson.ToJSON Person_us_cfpb_dataEthnicity_detailsNonNullable
data Person_us_cfpb_dataEthnicity_detailsNonNullableEthnicityNonNullable
instance Show Person_us_cfpb_dataEthnicity_detailsNonNullableEthnicityNonNullable
instance Eq Person_us_cfpb_dataEthnicity_detailsNonNullableEthnicityNonNullable
instance Data.Aeson.FromJSON Person_us_cfpb_dataEthnicity_detailsNonNullableEthnicityNonNullable
instance Data.Aeson.ToJSON Person_us_cfpb_dataEthnicity_detailsNonNullableEthnicityNonNullable
data Person_us_cfpb_dataRace_detailsNonNullable
instance Show Person_us_cfpb_dataRace_detailsNonNullable
instance Eq Person_us_cfpb_dataRace_detailsNonNullable
instance Data.Aeson.FromJSON Person_us_cfpb_dataRace_detailsNonNullable
instance Data.Aeson.ToJSON Person_us_cfpb_dataRace_detailsNonNullable
data Person_us_cfpb_dataRace_detailsNonNullableRaceNonNullable
instance Show Person_us_cfpb_dataRace_detailsNonNullableRaceNonNullable
instance Eq Person_us_cfpb_dataRace_detailsNonNullableRaceNonNullable
instance Data.Aeson.FromJSON Person_us_cfpb_dataRace_detailsNonNullableRaceNonNullable
instance Data.Aeson.ToJSON Person_us_cfpb_dataRace_detailsNonNullableRaceNonNullable
