module Stripe.CustomerSession.Types.PlatformEarningFeeSource where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Platform_earning_fee_source
instance Show Platform_earning_fee_source
instance Eq Platform_earning_fee_source
instance Data.Aeson.FromJSON Platform_earning_fee_source
instance Data.Aeson.ToJSON Platform_earning_fee_source
