module Stripe.CustomerSession.Types.PromotionCodesResourcePromotion where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Promotion_codes_resource_promotion
instance Show Promotion_codes_resource_promotion
instance Eq Promotion_codes_resource_promotion
instance Data.Aeson.FromJSON Promotion_codes_resource_promotion
instance Data.Aeson.ToJSON Promotion_codes_resource_promotion
data Promotion_codes_resource_promotionCouponVariants
instance Show Promotion_codes_resource_promotionCouponVariants
instance Eq Promotion_codes_resource_promotionCouponVariants
instance Data.Aeson.FromJSON Promotion_codes_resource_promotionCouponVariants
instance Data.Aeson.ToJSON Promotion_codes_resource_promotionCouponVariants
