module Stripe.CustomerSession.Types.Refund where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Refund
instance Show Refund
instance Eq Refund
instance Data.Aeson.FromJSON Refund
instance Data.Aeson.ToJSON Refund
data RefundBalance_transactionVariants
instance Show RefundBalance_transactionVariants
instance Eq RefundBalance_transactionVariants
instance Data.Aeson.FromJSON RefundBalance_transactionVariants
instance Data.Aeson.ToJSON RefundBalance_transactionVariants
data RefundChargeVariants
instance Show RefundChargeVariants
instance Eq RefundChargeVariants
instance Data.Aeson.FromJSON RefundChargeVariants
instance Data.Aeson.ToJSON RefundChargeVariants
data RefundFailure_balance_transactionVariants
instance Show RefundFailure_balance_transactionVariants
instance Eq RefundFailure_balance_transactionVariants
instance Data.Aeson.FromJSON RefundFailure_balance_transactionVariants
instance Data.Aeson.ToJSON RefundFailure_balance_transactionVariants
data RefundPayment_intentVariants
instance Show RefundPayment_intentVariants
instance Eq RefundPayment_intentVariants
instance Data.Aeson.FromJSON RefundPayment_intentVariants
instance Data.Aeson.ToJSON RefundPayment_intentVariants
data RefundSource_transfer_reversalVariants
instance Show RefundSource_transfer_reversalVariants
instance Eq RefundSource_transfer_reversalVariants
instance Data.Aeson.FromJSON RefundSource_transfer_reversalVariants
instance Data.Aeson.ToJSON RefundSource_transfer_reversalVariants
data RefundTransfer_reversalVariants
instance Show RefundTransfer_reversalVariants
instance Eq RefundTransfer_reversalVariants
instance Data.Aeson.FromJSON RefundTransfer_reversalVariants
instance Data.Aeson.ToJSON RefundTransfer_reversalVariants
