module Stripe.CustomerSession.Types.Refund where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Refund
instance Show Refund
instance Eq Refund
instance Data.Aeson.FromJSON Refund
instance Data.Aeson.ToJSON Refund
data RefundBalance_transactionNonNullableVariants
instance Show RefundBalance_transactionNonNullableVariants
instance Eq RefundBalance_transactionNonNullableVariants
instance Data.Aeson.FromJSON RefundBalance_transactionNonNullableVariants
instance Data.Aeson.ToJSON RefundBalance_transactionNonNullableVariants
data RefundChargeNonNullableVariants
instance Show RefundChargeNonNullableVariants
instance Eq RefundChargeNonNullableVariants
instance Data.Aeson.FromJSON RefundChargeNonNullableVariants
instance Data.Aeson.ToJSON RefundChargeNonNullableVariants
data RefundFailure_balance_transactionVariants
instance Show RefundFailure_balance_transactionVariants
instance Eq RefundFailure_balance_transactionVariants
instance Data.Aeson.FromJSON RefundFailure_balance_transactionVariants
instance Data.Aeson.ToJSON RefundFailure_balance_transactionVariants
data RefundPayment_intentNonNullableVariants
instance Show RefundPayment_intentNonNullableVariants
instance Eq RefundPayment_intentNonNullableVariants
instance Data.Aeson.FromJSON RefundPayment_intentNonNullableVariants
instance Data.Aeson.ToJSON RefundPayment_intentNonNullableVariants
data RefundPending_reason
instance Show RefundPending_reason
instance Eq RefundPending_reason
instance Data.Aeson.FromJSON RefundPending_reason
instance Data.Aeson.ToJSON RefundPending_reason
data RefundReasonNonNullable
instance Show RefundReasonNonNullable
instance Eq RefundReasonNonNullable
instance Data.Aeson.FromJSON RefundReasonNonNullable
instance Data.Aeson.ToJSON RefundReasonNonNullable
data RefundSource_transfer_reversalNonNullableVariants
instance Show RefundSource_transfer_reversalNonNullableVariants
instance Eq RefundSource_transfer_reversalNonNullableVariants
instance Data.Aeson.FromJSON RefundSource_transfer_reversalNonNullableVariants
instance Data.Aeson.ToJSON RefundSource_transfer_reversalNonNullableVariants
data RefundTransfer_reversalNonNullableVariants
instance Show RefundTransfer_reversalNonNullableVariants
instance Eq RefundTransfer_reversalNonNullableVariants
instance Data.Aeson.FromJSON RefundTransfer_reversalNonNullableVariants
instance Data.Aeson.ToJSON RefundTransfer_reversalNonNullableVariants
