module Stripe.CustomerSession.Types.RefundDestinationDetailsGbBankTransfer where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Refund_destination_details_gb_bank_transfer
instance Show Refund_destination_details_gb_bank_transfer
instance Eq Refund_destination_details_gb_bank_transfer
instance Data.Aeson.FromJSON Refund_destination_details_gb_bank_transfer
instance Data.Aeson.ToJSON Refund_destination_details_gb_bank_transfer
