module Stripe.CustomerSession.Types.SchedulesPhaseAutomaticTax where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Schedules_phase_automatic_tax
instance Show Schedules_phase_automatic_tax
instance Eq Schedules_phase_automatic_tax
instance Data.Aeson.FromJSON Schedules_phase_automatic_tax
instance Data.Aeson.ToJSON Schedules_phase_automatic_tax
data Schedules_phase_automatic_taxDisabled_reasonNonNullable
instance Show Schedules_phase_automatic_taxDisabled_reasonNonNullable
instance Eq Schedules_phase_automatic_taxDisabled_reasonNonNullable
instance Data.Aeson.FromJSON Schedules_phase_automatic_taxDisabled_reasonNonNullable
instance Data.Aeson.ToJSON Schedules_phase_automatic_taxDisabled_reasonNonNullable
data Schedules_phase_automatic_taxLiabilityNonNullable
instance Show Schedules_phase_automatic_taxLiabilityNonNullable
instance Eq Schedules_phase_automatic_taxLiabilityNonNullable
instance Data.Aeson.FromJSON Schedules_phase_automatic_taxLiabilityNonNullable
instance Data.Aeson.ToJSON Schedules_phase_automatic_taxLiabilityNonNullable
data Schedules_phase_automatic_taxLiabilityNonNullableAccountVariants
instance Show Schedules_phase_automatic_taxLiabilityNonNullableAccountVariants
instance Eq Schedules_phase_automatic_taxLiabilityNonNullableAccountVariants
instance Data.Aeson.FromJSON Schedules_phase_automatic_taxLiabilityNonNullableAccountVariants
instance Data.Aeson.ToJSON Schedules_phase_automatic_taxLiabilityNonNullableAccountVariants
data Schedules_phase_automatic_taxLiabilityNonNullableType
instance Show Schedules_phase_automatic_taxLiabilityNonNullableType
instance Eq Schedules_phase_automatic_taxLiabilityNonNullableType
instance Data.Aeson.FromJSON Schedules_phase_automatic_taxLiabilityNonNullableType
instance Data.Aeson.ToJSON Schedules_phase_automatic_taxLiabilityNonNullableType
