module Stripe.CustomerSession.Types.SepaDebitGeneratedFrom where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Sepa_debit_generated_from
instance Show Sepa_debit_generated_from
instance Eq Sepa_debit_generated_from
instance Data.Aeson.FromJSON Sepa_debit_generated_from
instance Data.Aeson.ToJSON Sepa_debit_generated_from
data Sepa_debit_generated_fromChargeNonNullableVariants
instance Show Sepa_debit_generated_fromChargeNonNullableVariants
instance Eq Sepa_debit_generated_fromChargeNonNullableVariants
instance Data.Aeson.FromJSON Sepa_debit_generated_fromChargeNonNullableVariants
instance Data.Aeson.ToJSON Sepa_debit_generated_fromChargeNonNullableVariants
data Sepa_debit_generated_fromSetup_attemptNonNullableVariants
instance Show Sepa_debit_generated_fromSetup_attemptNonNullableVariants
instance Eq Sepa_debit_generated_fromSetup_attemptNonNullableVariants
instance Data.Aeson.FromJSON Sepa_debit_generated_fromSetup_attemptNonNullableVariants
instance Data.Aeson.ToJSON Sepa_debit_generated_fromSetup_attemptNonNullableVariants
