module Stripe.CustomerSession.Types.SetupIntentPaymentMethodOptionsMandateOptionsPayto where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_payment_method_options_mandate_options_payto
instance Show Setup_intent_payment_method_options_mandate_options_payto
instance Eq Setup_intent_payment_method_options_mandate_options_payto
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_mandate_options_payto
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_mandate_options_payto
data Setup_intent_payment_method_options_mandate_options_paytoAmount_typeNonNullable
instance Show Setup_intent_payment_method_options_mandate_options_paytoAmount_typeNonNullable
instance Eq Setup_intent_payment_method_options_mandate_options_paytoAmount_typeNonNullable
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_mandate_options_paytoAmount_typeNonNullable
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_mandate_options_paytoAmount_typeNonNullable
data Setup_intent_payment_method_options_mandate_options_paytoPayment_scheduleNonNullable
instance Show Setup_intent_payment_method_options_mandate_options_paytoPayment_scheduleNonNullable
instance Eq Setup_intent_payment_method_options_mandate_options_paytoPayment_scheduleNonNullable
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_mandate_options_paytoPayment_scheduleNonNullable
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_mandate_options_paytoPayment_scheduleNonNullable
data Setup_intent_payment_method_options_mandate_options_paytoPurposeNonNullable
instance Show Setup_intent_payment_method_options_mandate_options_paytoPurposeNonNullable
instance Eq Setup_intent_payment_method_options_mandate_options_paytoPurposeNonNullable
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_mandate_options_paytoPurposeNonNullable
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_mandate_options_paytoPurposeNonNullable
