module Stripe.CustomerSession.Types.SetupAttemptPaymentMethodDetailsCardPresent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_attempt_payment_method_details_card_present
instance Show Setup_attempt_payment_method_details_card_present
instance Eq Setup_attempt_payment_method_details_card_present
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_card_present
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_card_present
data Setup_attempt_payment_method_details_card_presentGenerated_cardVariants
instance Show Setup_attempt_payment_method_details_card_presentGenerated_cardVariants
instance Eq Setup_attempt_payment_method_details_card_presentGenerated_cardVariants
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_card_presentGenerated_cardVariants
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_card_presentGenerated_cardVariants
data Setup_attempt_payment_method_details_card_presentOffline
instance Show Setup_attempt_payment_method_details_card_presentOffline
instance Eq Setup_attempt_payment_method_details_card_presentOffline
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_card_presentOffline
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_card_presentOffline
