module Stripe.CustomerSession.Types.SetupAttempt where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_attempt
instance Show Setup_attempt
instance Eq Setup_attempt
instance Data.Aeson.FromJSON Setup_attempt
instance Data.Aeson.ToJSON Setup_attempt
data Setup_attemptApplicationVariants
instance Show Setup_attemptApplicationVariants
instance Eq Setup_attemptApplicationVariants
instance Data.Aeson.FromJSON Setup_attemptApplicationVariants
instance Data.Aeson.ToJSON Setup_attemptApplicationVariants
data Setup_attemptCustomerVariants
instance Show Setup_attemptCustomerVariants
instance Eq Setup_attemptCustomerVariants
instance Data.Aeson.FromJSON Setup_attemptCustomerVariants
instance Data.Aeson.ToJSON Setup_attemptCustomerVariants
data Setup_attemptOn_behalf_ofVariants
instance Show Setup_attemptOn_behalf_ofVariants
instance Eq Setup_attemptOn_behalf_ofVariants
instance Data.Aeson.FromJSON Setup_attemptOn_behalf_ofVariants
instance Data.Aeson.ToJSON Setup_attemptOn_behalf_ofVariants
data Setup_attemptPayment_methodVariants
instance Show Setup_attemptPayment_methodVariants
instance Eq Setup_attemptPayment_methodVariants
instance Data.Aeson.FromJSON Setup_attemptPayment_methodVariants
instance Data.Aeson.ToJSON Setup_attemptPayment_methodVariants
data Setup_attemptSetup_error
instance Show Setup_attemptSetup_error
instance Eq Setup_attemptSetup_error
instance Data.Aeson.FromJSON Setup_attemptSetup_error
instance Data.Aeson.ToJSON Setup_attemptSetup_error
data Setup_attemptSetup_errorSource
instance Show Setup_attemptSetup_errorSource
instance Eq Setup_attemptSetup_errorSource
instance Data.Aeson.FromJSON Setup_attemptSetup_errorSource
instance Data.Aeson.ToJSON Setup_attemptSetup_errorSource
data Setup_attemptSetup_errorSourceAccountVariants
instance Show Setup_attemptSetup_errorSourceAccountVariants
instance Eq Setup_attemptSetup_errorSourceAccountVariants
instance Data.Aeson.FromJSON Setup_attemptSetup_errorSourceAccountVariants
instance Data.Aeson.ToJSON Setup_attemptSetup_errorSourceAccountVariants
data Setup_attemptSetup_errorSourceCustomerVariants
instance Show Setup_attemptSetup_errorSourceCustomerVariants
instance Eq Setup_attemptSetup_errorSourceCustomerVariants
instance Data.Aeson.FromJSON Setup_attemptSetup_errorSourceCustomerVariants
instance Data.Aeson.ToJSON Setup_attemptSetup_errorSourceCustomerVariants
data Setup_attemptSetup_errorSourceFuture_requirements
instance Show Setup_attemptSetup_errorSourceFuture_requirements
instance Eq Setup_attemptSetup_errorSourceFuture_requirements
instance Data.Aeson.FromJSON Setup_attemptSetup_errorSourceFuture_requirements
instance Data.Aeson.ToJSON Setup_attemptSetup_errorSourceFuture_requirements
data Setup_attemptSetup_errorSourceOwner
instance Show Setup_attemptSetup_errorSourceOwner
instance Eq Setup_attemptSetup_errorSourceOwner
instance Data.Aeson.FromJSON Setup_attemptSetup_errorSourceOwner
instance Data.Aeson.ToJSON Setup_attemptSetup_errorSourceOwner
data Setup_attemptSetup_errorSourceOwnerAddress
instance Show Setup_attemptSetup_errorSourceOwnerAddress
instance Eq Setup_attemptSetup_errorSourceOwnerAddress
instance Data.Aeson.FromJSON Setup_attemptSetup_errorSourceOwnerAddress
instance Data.Aeson.ToJSON Setup_attemptSetup_errorSourceOwnerAddress
data Setup_attemptSetup_errorSourceOwnerVerified_address
instance Show Setup_attemptSetup_errorSourceOwnerVerified_address
instance Eq Setup_attemptSetup_errorSourceOwnerVerified_address
instance Data.Aeson.FromJSON Setup_attemptSetup_errorSourceOwnerVerified_address
instance Data.Aeson.ToJSON Setup_attemptSetup_errorSourceOwnerVerified_address
data Setup_attemptSetup_errorSourceRequirements
instance Show Setup_attemptSetup_errorSourceRequirements
instance Eq Setup_attemptSetup_errorSourceRequirements
instance Data.Aeson.FromJSON Setup_attemptSetup_errorSourceRequirements
instance Data.Aeson.ToJSON Setup_attemptSetup_errorSourceRequirements
data Setup_attemptSetup_intentVariants
instance Show Setup_attemptSetup_intentVariants
instance Eq Setup_attemptSetup_intentVariants
instance Data.Aeson.FromJSON Setup_attemptSetup_intentVariants
instance Data.Aeson.ToJSON Setup_attemptSetup_intentVariants
