module Stripe.CustomerSession.Types.SetupIntentPaymentMethodOptionsCardMandateOptions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_payment_method_options_card_mandate_options
instance Show Setup_intent_payment_method_options_card_mandate_options
instance Eq Setup_intent_payment_method_options_card_mandate_options
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_card_mandate_options
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_card_mandate_options
