module Stripe.CustomerSession.Types.SetupIntentNextActionVerifyWithMicrodeposits where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_next_action_verify_with_microdeposits
instance Show Setup_intent_next_action_verify_with_microdeposits
instance Eq Setup_intent_next_action_verify_with_microdeposits
instance Data.Aeson.FromJSON Setup_intent_next_action_verify_with_microdeposits
instance Data.Aeson.ToJSON Setup_intent_next_action_verify_with_microdeposits
data Setup_intent_next_action_verify_with_microdepositsMicrodeposit_typeNonNullable
instance Show Setup_intent_next_action_verify_with_microdepositsMicrodeposit_typeNonNullable
instance Eq Setup_intent_next_action_verify_with_microdepositsMicrodeposit_typeNonNullable
instance Data.Aeson.FromJSON Setup_intent_next_action_verify_with_microdepositsMicrodeposit_typeNonNullable
instance Data.Aeson.ToJSON Setup_intent_next_action_verify_with_microdepositsMicrodeposit_typeNonNullable
