module Stripe.CustomerSession.Types.SetupAttemptPaymentMethodDetailsIdeal where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_attempt_payment_method_details_ideal
instance Show Setup_attempt_payment_method_details_ideal
instance Eq Setup_attempt_payment_method_details_ideal
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_ideal
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_ideal
data Setup_attempt_payment_method_details_idealBankNonNullable
instance Show Setup_attempt_payment_method_details_idealBankNonNullable
instance Eq Setup_attempt_payment_method_details_idealBankNonNullable
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_idealBankNonNullable
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_idealBankNonNullable
data Setup_attempt_payment_method_details_idealBicNonNullable
instance Show Setup_attempt_payment_method_details_idealBicNonNullable
instance Eq Setup_attempt_payment_method_details_idealBicNonNullable
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_idealBicNonNullable
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_idealBicNonNullable
data Setup_attempt_payment_method_details_idealGenerated_sepa_debitNonNullableVariants
instance Show Setup_attempt_payment_method_details_idealGenerated_sepa_debitNonNullableVariants
instance Eq Setup_attempt_payment_method_details_idealGenerated_sepa_debitNonNullableVariants
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_idealGenerated_sepa_debitNonNullableVariants
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_idealGenerated_sepa_debitNonNullableVariants
data Setup_attempt_payment_method_details_idealGenerated_sepa_debit_mandateNonNullableVariants
instance Show Setup_attempt_payment_method_details_idealGenerated_sepa_debit_mandateNonNullableVariants
instance Eq Setup_attempt_payment_method_details_idealGenerated_sepa_debit_mandateNonNullableVariants
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_idealGenerated_sepa_debit_mandateNonNullableVariants
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_idealGenerated_sepa_debit_mandateNonNullableVariants
