module Stripe.CustomerSession.Types.SetupIntentPaymentMethodOptionsAcssDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_payment_method_options_acss_debit
instance Show Setup_intent_payment_method_options_acss_debit
instance Eq Setup_intent_payment_method_options_acss_debit
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_acss_debit
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_acss_debit
data Setup_intent_payment_method_options_acss_debitCurrencyNonNullable
instance Show Setup_intent_payment_method_options_acss_debitCurrencyNonNullable
instance Eq Setup_intent_payment_method_options_acss_debitCurrencyNonNullable
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_acss_debitCurrencyNonNullable
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_acss_debitCurrencyNonNullable
data Setup_intent_payment_method_options_acss_debitVerification_method
instance Show Setup_intent_payment_method_options_acss_debitVerification_method
instance Eq Setup_intent_payment_method_options_acss_debitVerification_method
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_acss_debitVerification_method
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_acss_debitVerification_method
