module Stripe.CustomerSession.Types.SetupIntentPaymentMethodOptionsMandateOptionsBacsDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_payment_method_options_mandate_options_bacs_debit
instance Show Setup_intent_payment_method_options_mandate_options_bacs_debit
instance Eq Setup_intent_payment_method_options_mandate_options_bacs_debit
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_mandate_options_bacs_debit
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_mandate_options_bacs_debit
