module Stripe.CustomerSession.Types.SetupAttemptPaymentMethodDetailsSofort where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_attempt_payment_method_details_sofort
instance Show Setup_attempt_payment_method_details_sofort
instance Eq Setup_attempt_payment_method_details_sofort
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_sofort
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_sofort
data Setup_attempt_payment_method_details_sofortGenerated_sepa_debitNonNullableVariants
instance Show Setup_attempt_payment_method_details_sofortGenerated_sepa_debitNonNullableVariants
instance Eq Setup_attempt_payment_method_details_sofortGenerated_sepa_debitNonNullableVariants
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_sofortGenerated_sepa_debitNonNullableVariants
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_sofortGenerated_sepa_debitNonNullableVariants
data Setup_attempt_payment_method_details_sofortGenerated_sepa_debit_mandateNonNullableVariants
instance Show Setup_attempt_payment_method_details_sofortGenerated_sepa_debit_mandateNonNullableVariants
instance Eq Setup_attempt_payment_method_details_sofortGenerated_sepa_debit_mandateNonNullableVariants
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_sofortGenerated_sepa_debit_mandateNonNullableVariants
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_sofortGenerated_sepa_debit_mandateNonNullableVariants
data Setup_attempt_payment_method_details_sofortPreferred_languageNonNullable
instance Show Setup_attempt_payment_method_details_sofortPreferred_languageNonNullable
instance Eq Setup_attempt_payment_method_details_sofortPreferred_languageNonNullable
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_sofortPreferred_languageNonNullable
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_sofortPreferred_languageNonNullable
