module Stripe.CustomerSession.Types.SetupAttemptPaymentMethodDetailsCardPresent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_attempt_payment_method_details_card_present
instance Show Setup_attempt_payment_method_details_card_present
instance Eq Setup_attempt_payment_method_details_card_present
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_card_present
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_card_present
data Setup_attempt_payment_method_details_card_presentGenerated_cardNonNullableVariants
instance Show Setup_attempt_payment_method_details_card_presentGenerated_cardNonNullableVariants
instance Eq Setup_attempt_payment_method_details_card_presentGenerated_cardNonNullableVariants
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_card_presentGenerated_cardNonNullableVariants
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_card_presentGenerated_cardNonNullableVariants
data Setup_attempt_payment_method_details_card_presentOfflineNonNullable
instance Show Setup_attempt_payment_method_details_card_presentOfflineNonNullable
instance Eq Setup_attempt_payment_method_details_card_presentOfflineNonNullable
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_card_presentOfflineNonNullable
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_card_presentOfflineNonNullable
data Setup_attempt_payment_method_details_card_presentOfflineNonNullableTypeNonNullable
instance Show Setup_attempt_payment_method_details_card_presentOfflineNonNullableTypeNonNullable
instance Eq Setup_attempt_payment_method_details_card_presentOfflineNonNullableTypeNonNullable
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_card_presentOfflineNonNullableTypeNonNullable
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_card_presentOfflineNonNullableTypeNonNullable
