module Stripe.CustomerSession.Types.SetupIntentPaymentMethodOptionsMandateOptionsAcssDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_payment_method_options_mandate_options_acss_debit
instance Show Setup_intent_payment_method_options_mandate_options_acss_debit
instance Eq Setup_intent_payment_method_options_mandate_options_acss_debit
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_mandate_options_acss_debit
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_mandate_options_acss_debit
data Setup_intent_payment_method_options_mandate_options_acss_debitDefault_for
instance Show Setup_intent_payment_method_options_mandate_options_acss_debitDefault_for
instance Eq Setup_intent_payment_method_options_mandate_options_acss_debitDefault_for
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_mandate_options_acss_debitDefault_for
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_mandate_options_acss_debitDefault_for
data Setup_intent_payment_method_options_mandate_options_acss_debitPayment_scheduleNonNullable
instance Show Setup_intent_payment_method_options_mandate_options_acss_debitPayment_scheduleNonNullable
instance Eq Setup_intent_payment_method_options_mandate_options_acss_debitPayment_scheduleNonNullable
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_mandate_options_acss_debitPayment_scheduleNonNullable
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_mandate_options_acss_debitPayment_scheduleNonNullable
data Setup_intent_payment_method_options_mandate_options_acss_debitTransaction_typeNonNullable
instance Show Setup_intent_payment_method_options_mandate_options_acss_debitTransaction_typeNonNullable
instance Eq Setup_intent_payment_method_options_mandate_options_acss_debitTransaction_typeNonNullable
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_mandate_options_acss_debitTransaction_typeNonNullable
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_mandate_options_acss_debitTransaction_typeNonNullable
