module Stripe.CustomerSession.Types.SetupIntentTypeSpecificPaymentMethodOptionsClient where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_type_specific_payment_method_options_client
instance Show Setup_intent_type_specific_payment_method_options_client
instance Eq Setup_intent_type_specific_payment_method_options_client
instance Data.Aeson.FromJSON Setup_intent_type_specific_payment_method_options_client
instance Data.Aeson.ToJSON Setup_intent_type_specific_payment_method_options_client
data Setup_intent_type_specific_payment_method_options_clientVerification_method
instance Show Setup_intent_type_specific_payment_method_options_clientVerification_method
instance Eq Setup_intent_type_specific_payment_method_options_clientVerification_method
instance Data.Aeson.FromJSON Setup_intent_type_specific_payment_method_options_clientVerification_method
instance Data.Aeson.ToJSON Setup_intent_type_specific_payment_method_options_clientVerification_method
