module Stripe.CustomerSession.Types.SetupAttemptPaymentMethodDetailsCardWallet where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_attempt_payment_method_details_card_wallet
instance Show Setup_attempt_payment_method_details_card_wallet
instance Eq Setup_attempt_payment_method_details_card_wallet
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_card_wallet
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_card_wallet
data Setup_attempt_payment_method_details_card_walletType
instance Show Setup_attempt_payment_method_details_card_walletType
instance Eq Setup_attempt_payment_method_details_card_walletType
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_card_walletType
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_card_walletType
