module Stripe.CustomerSession.Types.SetupAttempt where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_attempt
instance Show Setup_attempt
instance Eq Setup_attempt
instance Data.Aeson.FromJSON Setup_attempt
instance Data.Aeson.ToJSON Setup_attempt
data Setup_attemptApplicationNonNullableVariants
instance Show Setup_attemptApplicationNonNullableVariants
instance Eq Setup_attemptApplicationNonNullableVariants
instance Data.Aeson.FromJSON Setup_attemptApplicationNonNullableVariants
instance Data.Aeson.ToJSON Setup_attemptApplicationNonNullableVariants
data Setup_attemptCustomerNonNullableVariants
instance Show Setup_attemptCustomerNonNullableVariants
instance Eq Setup_attemptCustomerNonNullableVariants
instance Data.Aeson.FromJSON Setup_attemptCustomerNonNullableVariants
instance Data.Aeson.ToJSON Setup_attemptCustomerNonNullableVariants
data Setup_attemptFlow_directionsNonNullable
instance Show Setup_attemptFlow_directionsNonNullable
instance Eq Setup_attemptFlow_directionsNonNullable
instance Data.Aeson.FromJSON Setup_attemptFlow_directionsNonNullable
instance Data.Aeson.ToJSON Setup_attemptFlow_directionsNonNullable
data Setup_attemptOn_behalf_ofNonNullableVariants
instance Show Setup_attemptOn_behalf_ofNonNullableVariants
instance Eq Setup_attemptOn_behalf_ofNonNullableVariants
instance Data.Aeson.FromJSON Setup_attemptOn_behalf_ofNonNullableVariants
instance Data.Aeson.ToJSON Setup_attemptOn_behalf_ofNonNullableVariants
data Setup_attemptPayment_methodVariants
instance Show Setup_attemptPayment_methodVariants
instance Eq Setup_attemptPayment_methodVariants
instance Data.Aeson.FromJSON Setup_attemptPayment_methodVariants
instance Data.Aeson.ToJSON Setup_attemptPayment_methodVariants
data Setup_attemptSetup_errorNonNullable
instance Show Setup_attemptSetup_errorNonNullable
instance Eq Setup_attemptSetup_errorNonNullable
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullable
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullable
data Setup_attemptSetup_errorNonNullableSource
instance Show Setup_attemptSetup_errorNonNullableSource
instance Eq Setup_attemptSetup_errorNonNullableSource
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSource
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSource
data Setup_attemptSetup_errorNonNullableSourceAccountNonNullableVariants
instance Show Setup_attemptSetup_errorNonNullableSourceAccountNonNullableVariants
instance Eq Setup_attemptSetup_errorNonNullableSourceAccountNonNullableVariants
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceAccountNonNullableVariants
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceAccountNonNullableVariants
data Setup_attemptSetup_errorNonNullableSourceAllow_redisplayNonNullable
instance Show Setup_attemptSetup_errorNonNullableSourceAllow_redisplayNonNullable
instance Eq Setup_attemptSetup_errorNonNullableSourceAllow_redisplayNonNullable
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceAllow_redisplayNonNullable
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceAllow_redisplayNonNullable
data Setup_attemptSetup_errorNonNullableSourceAvailable_payout_methodsNonNullable
instance Show Setup_attemptSetup_errorNonNullableSourceAvailable_payout_methodsNonNullable
instance Eq Setup_attemptSetup_errorNonNullableSourceAvailable_payout_methodsNonNullable
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceAvailable_payout_methodsNonNullable
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceAvailable_payout_methodsNonNullable
data Setup_attemptSetup_errorNonNullableSourceCustomerNonNullableVariants
instance Show Setup_attemptSetup_errorNonNullableSourceCustomerNonNullableVariants
instance Eq Setup_attemptSetup_errorNonNullableSourceCustomerNonNullableVariants
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceCustomerNonNullableVariants
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceCustomerNonNullableVariants
data Setup_attemptSetup_errorNonNullableSourceFuture_requirementsNonNullable
instance Show Setup_attemptSetup_errorNonNullableSourceFuture_requirementsNonNullable
instance Eq Setup_attemptSetup_errorNonNullableSourceFuture_requirementsNonNullable
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceFuture_requirementsNonNullable
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceFuture_requirementsNonNullable
data Setup_attemptSetup_errorNonNullableSourceObject
instance Show Setup_attemptSetup_errorNonNullableSourceObject
instance Eq Setup_attemptSetup_errorNonNullableSourceObject
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceObject
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceObject
data Setup_attemptSetup_errorNonNullableSourceOwnerNonNullable
instance Show Setup_attemptSetup_errorNonNullableSourceOwnerNonNullable
instance Eq Setup_attemptSetup_errorNonNullableSourceOwnerNonNullable
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceOwnerNonNullable
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceOwnerNonNullable
data Setup_attemptSetup_errorNonNullableSourceOwnerNonNullableAddressNonNullable
instance Show Setup_attemptSetup_errorNonNullableSourceOwnerNonNullableAddressNonNullable
instance Eq Setup_attemptSetup_errorNonNullableSourceOwnerNonNullableAddressNonNullable
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceOwnerNonNullableAddressNonNullable
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceOwnerNonNullableAddressNonNullable
data Setup_attemptSetup_errorNonNullableSourceOwnerNonNullableVerified_addressNonNullable
instance Show Setup_attemptSetup_errorNonNullableSourceOwnerNonNullableVerified_addressNonNullable
instance Eq Setup_attemptSetup_errorNonNullableSourceOwnerNonNullableVerified_addressNonNullable
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceOwnerNonNullableVerified_addressNonNullable
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceOwnerNonNullableVerified_addressNonNullable
data Setup_attemptSetup_errorNonNullableSourceRegulated_statusNonNullable
instance Show Setup_attemptSetup_errorNonNullableSourceRegulated_statusNonNullable
instance Eq Setup_attemptSetup_errorNonNullableSourceRegulated_statusNonNullable
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceRegulated_statusNonNullable
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceRegulated_statusNonNullable
data Setup_attemptSetup_errorNonNullableSourceRequirementsNonNullable
instance Show Setup_attemptSetup_errorNonNullableSourceRequirementsNonNullable
instance Eq Setup_attemptSetup_errorNonNullableSourceRequirementsNonNullable
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceRequirementsNonNullable
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceRequirementsNonNullable
data Setup_attemptSetup_errorNonNullableSourceType
instance Show Setup_attemptSetup_errorNonNullableSourceType
instance Eq Setup_attemptSetup_errorNonNullableSourceType
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableSourceType
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableSourceType
data Setup_attemptSetup_errorNonNullableType
instance Show Setup_attemptSetup_errorNonNullableType
instance Eq Setup_attemptSetup_errorNonNullableType
instance Data.Aeson.FromJSON Setup_attemptSetup_errorNonNullableType
instance Data.Aeson.ToJSON Setup_attemptSetup_errorNonNullableType
data Setup_attemptSetup_intentVariants
instance Show Setup_attemptSetup_intentVariants
instance Eq Setup_attemptSetup_intentVariants
instance Data.Aeson.FromJSON Setup_attemptSetup_intentVariants
instance Data.Aeson.ToJSON Setup_attemptSetup_intentVariants
