module Stripe.CustomerSession.Types.SetupAttemptPaymentMethodDetailsBancontact where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_attempt_payment_method_details_bancontact
instance Show Setup_attempt_payment_method_details_bancontact
instance Eq Setup_attempt_payment_method_details_bancontact
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_bancontact
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_bancontact
data Setup_attempt_payment_method_details_bancontactGenerated_sepa_debitNonNullableVariants
instance Show Setup_attempt_payment_method_details_bancontactGenerated_sepa_debitNonNullableVariants
instance Eq Setup_attempt_payment_method_details_bancontactGenerated_sepa_debitNonNullableVariants
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_bancontactGenerated_sepa_debitNonNullableVariants
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_bancontactGenerated_sepa_debitNonNullableVariants
data Setup_attempt_payment_method_details_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Show Setup_attempt_payment_method_details_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Eq Setup_attempt_payment_method_details_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_bancontactGenerated_sepa_debit_mandateNonNullableVariants
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_bancontactGenerated_sepa_debit_mandateNonNullableVariants
data Setup_attempt_payment_method_details_bancontactPreferred_languageNonNullable
instance Show Setup_attempt_payment_method_details_bancontactPreferred_languageNonNullable
instance Eq Setup_attempt_payment_method_details_bancontactPreferred_languageNonNullable
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_bancontactPreferred_languageNonNullable
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_bancontactPreferred_languageNonNullable
