module Stripe.CustomerSession.Types.SetupIntentPaymentMethodOptionsCardMandateOptions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_payment_method_options_card_mandate_options
instance Show Setup_intent_payment_method_options_card_mandate_options
instance Eq Setup_intent_payment_method_options_card_mandate_options
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_card_mandate_options
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_card_mandate_options
data Setup_intent_payment_method_options_card_mandate_optionsAmount_type
instance Show Setup_intent_payment_method_options_card_mandate_optionsAmount_type
instance Eq Setup_intent_payment_method_options_card_mandate_optionsAmount_type
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_card_mandate_optionsAmount_type
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_card_mandate_optionsAmount_type
data Setup_intent_payment_method_options_card_mandate_optionsInterval
instance Show Setup_intent_payment_method_options_card_mandate_optionsInterval
instance Eq Setup_intent_payment_method_options_card_mandate_optionsInterval
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_card_mandate_optionsInterval
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_card_mandate_optionsInterval
data Setup_intent_payment_method_options_card_mandate_optionsSupported_typesNonNullable
instance Show Setup_intent_payment_method_options_card_mandate_optionsSupported_typesNonNullable
instance Eq Setup_intent_payment_method_options_card_mandate_optionsSupported_typesNonNullable
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_card_mandate_optionsSupported_typesNonNullable
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_card_mandate_optionsSupported_typesNonNullable
