module Stripe.CustomerSession.Types.ShippingRate where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Shipping_rate
instance Show Shipping_rate
instance Eq Shipping_rate
instance Data.Aeson.FromJSON Shipping_rate
instance Data.Aeson.ToJSON Shipping_rate
data Shipping_rateDelivery_estimateNonNullable
instance Show Shipping_rateDelivery_estimateNonNullable
instance Eq Shipping_rateDelivery_estimateNonNullable
instance Data.Aeson.FromJSON Shipping_rateDelivery_estimateNonNullable
instance Data.Aeson.ToJSON Shipping_rateDelivery_estimateNonNullable
data Shipping_rateDelivery_estimateNonNullableMaximumNonNullable
instance Show Shipping_rateDelivery_estimateNonNullableMaximumNonNullable
instance Eq Shipping_rateDelivery_estimateNonNullableMaximumNonNullable
instance Data.Aeson.FromJSON Shipping_rateDelivery_estimateNonNullableMaximumNonNullable
instance Data.Aeson.ToJSON Shipping_rateDelivery_estimateNonNullableMaximumNonNullable
data Shipping_rateDelivery_estimateNonNullableMaximumNonNullableUnit
instance Show Shipping_rateDelivery_estimateNonNullableMaximumNonNullableUnit
instance Eq Shipping_rateDelivery_estimateNonNullableMaximumNonNullableUnit
instance Data.Aeson.FromJSON Shipping_rateDelivery_estimateNonNullableMaximumNonNullableUnit
instance Data.Aeson.ToJSON Shipping_rateDelivery_estimateNonNullableMaximumNonNullableUnit
data Shipping_rateDelivery_estimateNonNullableMinimumNonNullable
instance Show Shipping_rateDelivery_estimateNonNullableMinimumNonNullable
instance Eq Shipping_rateDelivery_estimateNonNullableMinimumNonNullable
instance Data.Aeson.FromJSON Shipping_rateDelivery_estimateNonNullableMinimumNonNullable
instance Data.Aeson.ToJSON Shipping_rateDelivery_estimateNonNullableMinimumNonNullable
data Shipping_rateDelivery_estimateNonNullableMinimumNonNullableUnit
instance Show Shipping_rateDelivery_estimateNonNullableMinimumNonNullableUnit
instance Eq Shipping_rateDelivery_estimateNonNullableMinimumNonNullableUnit
instance Data.Aeson.FromJSON Shipping_rateDelivery_estimateNonNullableMinimumNonNullableUnit
instance Data.Aeson.ToJSON Shipping_rateDelivery_estimateNonNullableMinimumNonNullableUnit
data Shipping_rateTax_behaviorNonNullable
instance Show Shipping_rateTax_behaviorNonNullable
instance Eq Shipping_rateTax_behaviorNonNullable
instance Data.Aeson.FromJSON Shipping_rateTax_behaviorNonNullable
instance Data.Aeson.ToJSON Shipping_rateTax_behaviorNonNullable
data Shipping_rateTax_codeNonNullableVariants
instance Show Shipping_rateTax_codeNonNullableVariants
instance Eq Shipping_rateTax_codeNonNullableVariants
instance Data.Aeson.FromJSON Shipping_rateTax_codeNonNullableVariants
instance Data.Aeson.ToJSON Shipping_rateTax_codeNonNullableVariants
