module Stripe.CustomerSession.Types.ShippingRate where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Shipping_rate
instance Show Shipping_rate
instance Eq Shipping_rate
instance Data.Aeson.FromJSON Shipping_rate
instance Data.Aeson.ToJSON Shipping_rate
data Shipping_rateDelivery_estimate
instance Show Shipping_rateDelivery_estimate
instance Eq Shipping_rateDelivery_estimate
instance Data.Aeson.FromJSON Shipping_rateDelivery_estimate
instance Data.Aeson.ToJSON Shipping_rateDelivery_estimate
data Shipping_rateDelivery_estimateMaximum
instance Show Shipping_rateDelivery_estimateMaximum
instance Eq Shipping_rateDelivery_estimateMaximum
instance Data.Aeson.FromJSON Shipping_rateDelivery_estimateMaximum
instance Data.Aeson.ToJSON Shipping_rateDelivery_estimateMaximum
data Shipping_rateDelivery_estimateMinimum
instance Show Shipping_rateDelivery_estimateMinimum
instance Eq Shipping_rateDelivery_estimateMinimum
instance Data.Aeson.FromJSON Shipping_rateDelivery_estimateMinimum
instance Data.Aeson.ToJSON Shipping_rateDelivery_estimateMinimum
data Shipping_rateTax_codeVariants
instance Show Shipping_rateTax_codeVariants
instance Eq Shipping_rateTax_codeVariants
instance Data.Aeson.FromJSON Shipping_rateTax_codeVariants
instance Data.Aeson.ToJSON Shipping_rateTax_codeVariants
