module Stripe.CustomerSession.Types.ShippingRateDeliveryEstimate where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Shipping_rate_delivery_estimate
instance Show Shipping_rate_delivery_estimate
instance Eq Shipping_rate_delivery_estimate
instance Data.Aeson.FromJSON Shipping_rate_delivery_estimate
instance Data.Aeson.ToJSON Shipping_rate_delivery_estimate
data Shipping_rate_delivery_estimateMaximumNonNullable
instance Show Shipping_rate_delivery_estimateMaximumNonNullable
instance Eq Shipping_rate_delivery_estimateMaximumNonNullable
instance Data.Aeson.FromJSON Shipping_rate_delivery_estimateMaximumNonNullable
instance Data.Aeson.ToJSON Shipping_rate_delivery_estimateMaximumNonNullable
data Shipping_rate_delivery_estimateMaximumNonNullableUnit
instance Show Shipping_rate_delivery_estimateMaximumNonNullableUnit
instance Eq Shipping_rate_delivery_estimateMaximumNonNullableUnit
instance Data.Aeson.FromJSON Shipping_rate_delivery_estimateMaximumNonNullableUnit
instance Data.Aeson.ToJSON Shipping_rate_delivery_estimateMaximumNonNullableUnit
data Shipping_rate_delivery_estimateMinimumNonNullable
instance Show Shipping_rate_delivery_estimateMinimumNonNullable
instance Eq Shipping_rate_delivery_estimateMinimumNonNullable
instance Data.Aeson.FromJSON Shipping_rate_delivery_estimateMinimumNonNullable
instance Data.Aeson.ToJSON Shipping_rate_delivery_estimateMinimumNonNullable
data Shipping_rate_delivery_estimateMinimumNonNullableUnit
instance Show Shipping_rate_delivery_estimateMinimumNonNullableUnit
instance Eq Shipping_rate_delivery_estimateMinimumNonNullableUnit
instance Data.Aeson.FromJSON Shipping_rate_delivery_estimateMinimumNonNullableUnit
instance Data.Aeson.ToJSON Shipping_rate_delivery_estimateMinimumNonNullableUnit
