module Stripe.CustomerSession.Types.StackableDiscountWithDiscountSettings where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Stackable_discount_with_discount_settings
instance Show Stackable_discount_with_discount_settings
instance Eq Stackable_discount_with_discount_settings
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settings
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settings
data Stackable_discount_with_discount_settingsCouponVariants
instance Show Stackable_discount_with_discount_settingsCouponVariants
instance Eq Stackable_discount_with_discount_settingsCouponVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settingsCouponVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settingsCouponVariants
data Stackable_discount_with_discount_settingsDiscountVariants
instance Show Stackable_discount_with_discount_settingsDiscountVariants
instance Eq Stackable_discount_with_discount_settingsDiscountVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settingsDiscountVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settingsDiscountVariants
data Stackable_discount_with_discount_settingsPromotion_codeVariants
instance Show Stackable_discount_with_discount_settingsPromotion_codeVariants
instance Eq Stackable_discount_with_discount_settingsPromotion_codeVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settingsPromotion_codeVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settingsPromotion_codeVariants
