module Stripe.CustomerSession.Types.StackableDiscountWithDiscountSettings where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Stackable_discount_with_discount_settings
instance Show Stackable_discount_with_discount_settings
instance Eq Stackable_discount_with_discount_settings
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settings
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settings
data Stackable_discount_with_discount_settingsCouponNonNullableVariants
instance Show Stackable_discount_with_discount_settingsCouponNonNullableVariants
instance Eq Stackable_discount_with_discount_settingsCouponNonNullableVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settingsCouponNonNullableVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settingsCouponNonNullableVariants
data Stackable_discount_with_discount_settingsDiscountNonNullableVariants
instance Show Stackable_discount_with_discount_settingsDiscountNonNullableVariants
instance Eq Stackable_discount_with_discount_settingsDiscountNonNullableVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settingsDiscountNonNullableVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settingsDiscountNonNullableVariants
data Stackable_discount_with_discount_settingsPromotion_codeNonNullableVariants
instance Show Stackable_discount_with_discount_settingsPromotion_codeNonNullableVariants
instance Eq Stackable_discount_with_discount_settingsPromotion_codeNonNullableVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settingsPromotion_codeNonNullableVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settingsPromotion_codeNonNullableVariants
