module Stripe.CustomerSession.Types.StackableDiscountWithDiscountSettingsAndDiscountEnd where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Stackable_discount_with_discount_settings_and_discount_end
instance Show Stackable_discount_with_discount_settings_and_discount_end
instance Eq Stackable_discount_with_discount_settings_and_discount_end
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settings_and_discount_end
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settings_and_discount_end
data Stackable_discount_with_discount_settings_and_discount_endCouponNonNullableVariants
instance Show Stackable_discount_with_discount_settings_and_discount_endCouponNonNullableVariants
instance Eq Stackable_discount_with_discount_settings_and_discount_endCouponNonNullableVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settings_and_discount_endCouponNonNullableVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settings_and_discount_endCouponNonNullableVariants
data Stackable_discount_with_discount_settings_and_discount_endDiscountNonNullableVariants
instance Show Stackable_discount_with_discount_settings_and_discount_endDiscountNonNullableVariants
instance Eq Stackable_discount_with_discount_settings_and_discount_endDiscountNonNullableVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settings_and_discount_endDiscountNonNullableVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settings_and_discount_endDiscountNonNullableVariants
data Stackable_discount_with_discount_settings_and_discount_endPromotion_codeNonNullableVariants
instance Show Stackable_discount_with_discount_settings_and_discount_endPromotion_codeNonNullableVariants
instance Eq Stackable_discount_with_discount_settings_and_discount_endPromotion_codeNonNullableVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settings_and_discount_endPromotion_codeNonNullableVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settings_and_discount_endPromotion_codeNonNullableVariants
