module Stripe.CustomerSession.Types.SubscriptionsResourcePauseCollection where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscriptions_resource_pause_collection
instance Show Subscriptions_resource_pause_collection
instance Eq Subscriptions_resource_pause_collection
instance Data.Aeson.FromJSON Subscriptions_resource_pause_collection
instance Data.Aeson.ToJSON Subscriptions_resource_pause_collection
data Subscriptions_resource_pause_collectionBehavior
instance Show Subscriptions_resource_pause_collectionBehavior
instance Eq Subscriptions_resource_pause_collectionBehavior
instance Data.Aeson.FromJSON Subscriptions_resource_pause_collectionBehavior
instance Data.Aeson.ToJSON Subscriptions_resource_pause_collectionBehavior
