module Stripe.CustomerSession.Types.SubscriptionsResourceBillingCycleAnchorConfig where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscriptions_resource_billing_cycle_anchor_config
instance Show Subscriptions_resource_billing_cycle_anchor_config
instance Eq Subscriptions_resource_billing_cycle_anchor_config
instance Data.Aeson.FromJSON Subscriptions_resource_billing_cycle_anchor_config
instance Data.Aeson.ToJSON Subscriptions_resource_billing_cycle_anchor_config
