module Stripe.CustomerSession.Types.SubscriptionsResourceBillingMode where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscriptions_resource_billing_mode
instance Show Subscriptions_resource_billing_mode
instance Eq Subscriptions_resource_billing_mode
instance Data.Aeson.FromJSON Subscriptions_resource_billing_mode
instance Data.Aeson.ToJSON Subscriptions_resource_billing_mode
data Subscriptions_resource_billing_modeFlexible
instance Show Subscriptions_resource_billing_modeFlexible
instance Eq Subscriptions_resource_billing_modeFlexible
instance Data.Aeson.FromJSON Subscriptions_resource_billing_modeFlexible
instance Data.Aeson.ToJSON Subscriptions_resource_billing_modeFlexible
