module Stripe.CustomerSession.Types.SubscriptionSchedulePhaseConfiguration where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_schedule_phase_configuration
instance Show Subscription_schedule_phase_configuration
instance Eq Subscription_schedule_phase_configuration
instance Data.Aeson.FromJSON Subscription_schedule_phase_configuration
instance Data.Aeson.ToJSON Subscription_schedule_phase_configuration
data Subscription_schedule_phase_configurationBilling_cycle_anchorNonNullable
instance Show Subscription_schedule_phase_configurationBilling_cycle_anchorNonNullable
instance Eq Subscription_schedule_phase_configurationBilling_cycle_anchorNonNullable
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationBilling_cycle_anchorNonNullable
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationBilling_cycle_anchorNonNullable
data Subscription_schedule_phase_configurationBilling_thresholdsNonNullable
instance Show Subscription_schedule_phase_configurationBilling_thresholdsNonNullable
instance Eq Subscription_schedule_phase_configurationBilling_thresholdsNonNullable
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationBilling_thresholdsNonNullable
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationBilling_thresholdsNonNullable
data Subscription_schedule_phase_configurationCollection_methodNonNullable
instance Show Subscription_schedule_phase_configurationCollection_methodNonNullable
instance Eq Subscription_schedule_phase_configurationCollection_methodNonNullable
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationCollection_methodNonNullable
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationCollection_methodNonNullable
data Subscription_schedule_phase_configurationDefault_payment_methodNonNullableVariants
instance Show Subscription_schedule_phase_configurationDefault_payment_methodNonNullableVariants
instance Eq Subscription_schedule_phase_configurationDefault_payment_methodNonNullableVariants
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationDefault_payment_methodNonNullableVariants
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationDefault_payment_methodNonNullableVariants
data Subscription_schedule_phase_configurationInvoice_settingsNonNullable
instance Show Subscription_schedule_phase_configurationInvoice_settingsNonNullable
instance Eq Subscription_schedule_phase_configurationInvoice_settingsNonNullable
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationInvoice_settingsNonNullable
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationInvoice_settingsNonNullable
data Subscription_schedule_phase_configurationInvoice_settingsNonNullableAccount_tax_idsNonNullableVariants
instance Show Subscription_schedule_phase_configurationInvoice_settingsNonNullableAccount_tax_idsNonNullableVariants
instance Eq Subscription_schedule_phase_configurationInvoice_settingsNonNullableAccount_tax_idsNonNullableVariants
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationInvoice_settingsNonNullableAccount_tax_idsNonNullableVariants
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationInvoice_settingsNonNullableAccount_tax_idsNonNullableVariants
data Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullable
instance Show Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullable
instance Eq Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullable
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullable
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullable
data Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullableAccountVariants
instance Show Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullableAccountVariants
instance Eq Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullableAccountVariants
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullableAccountVariants
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullableAccountVariants
data Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullableType
instance Show Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullableType
instance Eq Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullableType
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullableType
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationInvoice_settingsNonNullableIssuerNonNullableType
data Subscription_schedule_phase_configurationOn_behalf_ofNonNullableVariants
instance Show Subscription_schedule_phase_configurationOn_behalf_ofNonNullableVariants
instance Eq Subscription_schedule_phase_configurationOn_behalf_ofNonNullableVariants
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationOn_behalf_ofNonNullableVariants
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationOn_behalf_ofNonNullableVariants
data Subscription_schedule_phase_configurationProration_behavior
instance Show Subscription_schedule_phase_configurationProration_behavior
instance Eq Subscription_schedule_phase_configurationProration_behavior
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationProration_behavior
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationProration_behavior
data Subscription_schedule_phase_configurationTransfer_dataNonNullable
instance Show Subscription_schedule_phase_configurationTransfer_dataNonNullable
instance Eq Subscription_schedule_phase_configurationTransfer_dataNonNullable
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationTransfer_dataNonNullable
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationTransfer_dataNonNullable
data Subscription_schedule_phase_configurationTransfer_dataNonNullableDestinationVariants
instance Show Subscription_schedule_phase_configurationTransfer_dataNonNullableDestinationVariants
instance Eq Subscription_schedule_phase_configurationTransfer_dataNonNullableDestinationVariants
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationTransfer_dataNonNullableDestinationVariants
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationTransfer_dataNonNullableDestinationVariants
