module Stripe.CustomerSession.Types.SubscriptionsResourceSubscriptionInvoiceSettings where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscriptions_resource_subscription_invoice_settings
instance Show Subscriptions_resource_subscription_invoice_settings
instance Eq Subscriptions_resource_subscription_invoice_settings
instance Data.Aeson.FromJSON Subscriptions_resource_subscription_invoice_settings
instance Data.Aeson.ToJSON Subscriptions_resource_subscription_invoice_settings
data Subscriptions_resource_subscription_invoice_settingsAccount_tax_idsNonNullableVariants
instance Show Subscriptions_resource_subscription_invoice_settingsAccount_tax_idsNonNullableVariants
instance Eq Subscriptions_resource_subscription_invoice_settingsAccount_tax_idsNonNullableVariants
instance Data.Aeson.FromJSON Subscriptions_resource_subscription_invoice_settingsAccount_tax_idsNonNullableVariants
instance Data.Aeson.ToJSON Subscriptions_resource_subscription_invoice_settingsAccount_tax_idsNonNullableVariants
