module Stripe.CustomerSession.Types.SubscriptionsResourceBillingMode where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscriptions_resource_billing_mode
instance Show Subscriptions_resource_billing_mode
instance Eq Subscriptions_resource_billing_mode
instance Data.Aeson.FromJSON Subscriptions_resource_billing_mode
instance Data.Aeson.ToJSON Subscriptions_resource_billing_mode
data Subscriptions_resource_billing_modeFlexibleNonNullable
instance Show Subscriptions_resource_billing_modeFlexibleNonNullable
instance Eq Subscriptions_resource_billing_modeFlexibleNonNullable
instance Data.Aeson.FromJSON Subscriptions_resource_billing_modeFlexibleNonNullable
instance Data.Aeson.ToJSON Subscriptions_resource_billing_modeFlexibleNonNullable
data Subscriptions_resource_billing_modeFlexibleNonNullableProration_discounts
instance Show Subscriptions_resource_billing_modeFlexibleNonNullableProration_discounts
instance Eq Subscriptions_resource_billing_modeFlexibleNonNullableProration_discounts
instance Data.Aeson.FromJSON Subscriptions_resource_billing_modeFlexibleNonNullableProration_discounts
instance Data.Aeson.ToJSON Subscriptions_resource_billing_modeFlexibleNonNullableProration_discounts
data Subscriptions_resource_billing_modeType
instance Show Subscriptions_resource_billing_modeType
instance Eq Subscriptions_resource_billing_modeType
instance Data.Aeson.FromJSON Subscriptions_resource_billing_modeType
instance Data.Aeson.ToJSON Subscriptions_resource_billing_modeType
