module Stripe.CustomerSession.Types.SubscriptionSchedulesResourceDefaultSettingsAutomaticTax where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_schedules_resource_default_settings_automatic_tax
instance Show Subscription_schedules_resource_default_settings_automatic_tax
instance Eq Subscription_schedules_resource_default_settings_automatic_tax
instance Data.Aeson.FromJSON Subscription_schedules_resource_default_settings_automatic_tax
instance Data.Aeson.ToJSON Subscription_schedules_resource_default_settings_automatic_tax
data Subscription_schedules_resource_default_settings_automatic_taxDisabled_reasonNonNullable
instance Show Subscription_schedules_resource_default_settings_automatic_taxDisabled_reasonNonNullable
instance Eq Subscription_schedules_resource_default_settings_automatic_taxDisabled_reasonNonNullable
instance Data.Aeson.FromJSON Subscription_schedules_resource_default_settings_automatic_taxDisabled_reasonNonNullable
instance Data.Aeson.ToJSON Subscription_schedules_resource_default_settings_automatic_taxDisabled_reasonNonNullable
data Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullable
instance Show Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullable
instance Eq Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullable
instance Data.Aeson.FromJSON Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullable
instance Data.Aeson.ToJSON Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullable
data Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullableAccountVariants
instance Show Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullableAccountVariants
instance Eq Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullableAccountVariants
instance Data.Aeson.FromJSON Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullableAccountVariants
instance Data.Aeson.ToJSON Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullableAccountVariants
data Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullableType
instance Show Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullableType
instance Eq Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullableType
instance Data.Aeson.FromJSON Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullableType
instance Data.Aeson.ToJSON Subscription_schedules_resource_default_settings_automatic_taxLiabilityNonNullableType
