module Stripe.CustomerSession.Types.SubscriptionPendingInvoiceItemInterval where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_pending_invoice_item_interval
instance Show Subscription_pending_invoice_item_interval
instance Eq Subscription_pending_invoice_item_interval
instance Data.Aeson.FromJSON Subscription_pending_invoice_item_interval
instance Data.Aeson.ToJSON Subscription_pending_invoice_item_interval
data Subscription_pending_invoice_item_intervalInterval
instance Show Subscription_pending_invoice_item_intervalInterval
instance Eq Subscription_pending_invoice_item_intervalInterval
instance Data.Aeson.FromJSON Subscription_pending_invoice_item_intervalInterval
instance Data.Aeson.ToJSON Subscription_pending_invoice_item_intervalInterval
