module Stripe.CustomerSession.Types.SubscriptionsResourceBillingModeFlexible where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscriptions_resource_billing_mode_flexible
instance Show Subscriptions_resource_billing_mode_flexible
instance Eq Subscriptions_resource_billing_mode_flexible
instance Data.Aeson.FromJSON Subscriptions_resource_billing_mode_flexible
instance Data.Aeson.ToJSON Subscriptions_resource_billing_mode_flexible
data Subscriptions_resource_billing_mode_flexibleProration_discounts
instance Show Subscriptions_resource_billing_mode_flexibleProration_discounts
instance Eq Subscriptions_resource_billing_mode_flexibleProration_discounts
instance Data.Aeson.FromJSON Subscriptions_resource_billing_mode_flexibleProration_discounts
instance Data.Aeson.ToJSON Subscriptions_resource_billing_mode_flexibleProration_discounts
