module Stripe.CustomerSession.Types.SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodStart where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_schedules_resource_invoice_item_period_resource_period_start
instance Show Subscription_schedules_resource_invoice_item_period_resource_period_start
instance Eq Subscription_schedules_resource_invoice_item_period_resource_period_start
instance Data.Aeson.FromJSON Subscription_schedules_resource_invoice_item_period_resource_period_start
instance Data.Aeson.ToJSON Subscription_schedules_resource_invoice_item_period_resource_period_start
data Subscription_schedules_resource_invoice_item_period_resource_period_startType
instance Show Subscription_schedules_resource_invoice_item_period_resource_period_startType
instance Eq Subscription_schedules_resource_invoice_item_period_resource_period_startType
instance Data.Aeson.FromJSON Subscription_schedules_resource_invoice_item_period_resource_period_startType
instance Data.Aeson.ToJSON Subscription_schedules_resource_invoice_item_period_resource_period_startType
