module Stripe.CustomerSession.Types.SubscriptionSchedule where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_schedule
instance Show Subscription_schedule
instance Eq Subscription_schedule
instance Data.Aeson.FromJSON Subscription_schedule
instance Data.Aeson.ToJSON Subscription_schedule
data Subscription_scheduleApplicationNonNullableVariants
instance Show Subscription_scheduleApplicationNonNullableVariants
instance Eq Subscription_scheduleApplicationNonNullableVariants
instance Data.Aeson.FromJSON Subscription_scheduleApplicationNonNullableVariants
instance Data.Aeson.ToJSON Subscription_scheduleApplicationNonNullableVariants
data Subscription_scheduleCurrent_phaseNonNullable
instance Show Subscription_scheduleCurrent_phaseNonNullable
instance Eq Subscription_scheduleCurrent_phaseNonNullable
instance Data.Aeson.FromJSON Subscription_scheduleCurrent_phaseNonNullable
instance Data.Aeson.ToJSON Subscription_scheduleCurrent_phaseNonNullable
data Subscription_scheduleCustomerVariants
instance Show Subscription_scheduleCustomerVariants
instance Eq Subscription_scheduleCustomerVariants
instance Data.Aeson.FromJSON Subscription_scheduleCustomerVariants
instance Data.Aeson.ToJSON Subscription_scheduleCustomerVariants
data Subscription_scheduleEnd_behavior
instance Show Subscription_scheduleEnd_behavior
instance Eq Subscription_scheduleEnd_behavior
instance Data.Aeson.FromJSON Subscription_scheduleEnd_behavior
instance Data.Aeson.ToJSON Subscription_scheduleEnd_behavior
data Subscription_scheduleStatus
instance Show Subscription_scheduleStatus
instance Eq Subscription_scheduleStatus
instance Data.Aeson.FromJSON Subscription_scheduleStatus
instance Data.Aeson.ToJSON Subscription_scheduleStatus
data Subscription_scheduleSubscriptionNonNullableVariants
instance Show Subscription_scheduleSubscriptionNonNullableVariants
instance Eq Subscription_scheduleSubscriptionNonNullableVariants
instance Data.Aeson.FromJSON Subscription_scheduleSubscriptionNonNullableVariants
instance Data.Aeson.ToJSON Subscription_scheduleSubscriptionNonNullableVariants
data Subscription_scheduleTest_clockNonNullableVariants
instance Show Subscription_scheduleTest_clockNonNullableVariants
instance Eq Subscription_scheduleTest_clockNonNullableVariants
instance Data.Aeson.FromJSON Subscription_scheduleTest_clockNonNullableVariants
instance Data.Aeson.ToJSON Subscription_scheduleTest_clockNonNullableVariants
