module Stripe.CustomerSession.Types.SubscriptionSchedule where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_schedule
instance Show Subscription_schedule
instance Eq Subscription_schedule
instance Data.Aeson.FromJSON Subscription_schedule
instance Data.Aeson.ToJSON Subscription_schedule
data Subscription_scheduleApplicationVariants
instance Show Subscription_scheduleApplicationVariants
instance Eq Subscription_scheduleApplicationVariants
instance Data.Aeson.FromJSON Subscription_scheduleApplicationVariants
instance Data.Aeson.ToJSON Subscription_scheduleApplicationVariants
data Subscription_scheduleCurrent_phase
instance Show Subscription_scheduleCurrent_phase
instance Eq Subscription_scheduleCurrent_phase
instance Data.Aeson.FromJSON Subscription_scheduleCurrent_phase
instance Data.Aeson.ToJSON Subscription_scheduleCurrent_phase
data Subscription_scheduleCustomerVariants
instance Show Subscription_scheduleCustomerVariants
instance Eq Subscription_scheduleCustomerVariants
instance Data.Aeson.FromJSON Subscription_scheduleCustomerVariants
instance Data.Aeson.ToJSON Subscription_scheduleCustomerVariants
data Subscription_scheduleSubscriptionVariants
instance Show Subscription_scheduleSubscriptionVariants
instance Eq Subscription_scheduleSubscriptionVariants
instance Data.Aeson.FromJSON Subscription_scheduleSubscriptionVariants
instance Data.Aeson.ToJSON Subscription_scheduleSubscriptionVariants
data Subscription_scheduleTest_clockVariants
instance Show Subscription_scheduleTest_clockVariants
instance Eq Subscription_scheduleTest_clockVariants
instance Data.Aeson.FromJSON Subscription_scheduleTest_clockVariants
instance Data.Aeson.ToJSON Subscription_scheduleTest_clockVariants
