module Stripe.CustomerSession.Types.SubscriptionAutomaticTax where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_automatic_tax
instance Show Subscription_automatic_tax
instance Eq Subscription_automatic_tax
instance Data.Aeson.FromJSON Subscription_automatic_tax
instance Data.Aeson.ToJSON Subscription_automatic_tax
data Subscription_automatic_taxDisabled_reasonNonNullable
instance Show Subscription_automatic_taxDisabled_reasonNonNullable
instance Eq Subscription_automatic_taxDisabled_reasonNonNullable
instance Data.Aeson.FromJSON Subscription_automatic_taxDisabled_reasonNonNullable
instance Data.Aeson.ToJSON Subscription_automatic_taxDisabled_reasonNonNullable
data Subscription_automatic_taxLiabilityNonNullable
instance Show Subscription_automatic_taxLiabilityNonNullable
instance Eq Subscription_automatic_taxLiabilityNonNullable
instance Data.Aeson.FromJSON Subscription_automatic_taxLiabilityNonNullable
instance Data.Aeson.ToJSON Subscription_automatic_taxLiabilityNonNullable
data Subscription_automatic_taxLiabilityNonNullableAccountVariants
instance Show Subscription_automatic_taxLiabilityNonNullableAccountVariants
instance Eq Subscription_automatic_taxLiabilityNonNullableAccountVariants
instance Data.Aeson.FromJSON Subscription_automatic_taxLiabilityNonNullableAccountVariants
instance Data.Aeson.ToJSON Subscription_automatic_taxLiabilityNonNullableAccountVariants
data Subscription_automatic_taxLiabilityNonNullableType
instance Show Subscription_automatic_taxLiabilityNonNullableType
instance Eq Subscription_automatic_taxLiabilityNonNullableType
instance Data.Aeson.FromJSON Subscription_automatic_taxLiabilityNonNullableType
instance Data.Aeson.ToJSON Subscription_automatic_taxLiabilityNonNullableType
