module Stripe.CustomerSession.Types.ThreeDSecureDetailsCharge where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Three_d_secure_details_charge
instance Show Three_d_secure_details_charge
instance Eq Three_d_secure_details_charge
instance Data.Aeson.FromJSON Three_d_secure_details_charge
instance Data.Aeson.ToJSON Three_d_secure_details_charge
