module Stripe.CustomerSession.Types.ThreeDSecureDetailsCharge where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Three_d_secure_details_charge
instance Show Three_d_secure_details_charge
instance Eq Three_d_secure_details_charge
instance Data.Aeson.FromJSON Three_d_secure_details_charge
instance Data.Aeson.ToJSON Three_d_secure_details_charge
data Three_d_secure_details_chargeAuthentication_flowNonNullable
instance Show Three_d_secure_details_chargeAuthentication_flowNonNullable
instance Eq Three_d_secure_details_chargeAuthentication_flowNonNullable
instance Data.Aeson.FromJSON Three_d_secure_details_chargeAuthentication_flowNonNullable
instance Data.Aeson.ToJSON Three_d_secure_details_chargeAuthentication_flowNonNullable
data Three_d_secure_details_chargeElectronic_commerce_indicatorNonNullable
instance Show Three_d_secure_details_chargeElectronic_commerce_indicatorNonNullable
instance Eq Three_d_secure_details_chargeElectronic_commerce_indicatorNonNullable
instance Data.Aeson.FromJSON Three_d_secure_details_chargeElectronic_commerce_indicatorNonNullable
instance Data.Aeson.ToJSON Three_d_secure_details_chargeElectronic_commerce_indicatorNonNullable
data Three_d_secure_details_chargeExemption_indicatorNonNullable
instance Show Three_d_secure_details_chargeExemption_indicatorNonNullable
instance Eq Three_d_secure_details_chargeExemption_indicatorNonNullable
instance Data.Aeson.FromJSON Three_d_secure_details_chargeExemption_indicatorNonNullable
instance Data.Aeson.ToJSON Three_d_secure_details_chargeExemption_indicatorNonNullable
data Three_d_secure_details_chargeResultNonNullable
instance Show Three_d_secure_details_chargeResultNonNullable
instance Eq Three_d_secure_details_chargeResultNonNullable
instance Data.Aeson.FromJSON Three_d_secure_details_chargeResultNonNullable
instance Data.Aeson.ToJSON Three_d_secure_details_chargeResultNonNullable
data Three_d_secure_details_chargeResult_reasonNonNullable
instance Show Three_d_secure_details_chargeResult_reasonNonNullable
instance Eq Three_d_secure_details_chargeResult_reasonNonNullable
instance Data.Aeson.FromJSON Three_d_secure_details_chargeResult_reasonNonNullable
instance Data.Aeson.ToJSON Three_d_secure_details_chargeResult_reasonNonNullable
data Three_d_secure_details_chargeVersionNonNullable
instance Show Three_d_secure_details_chargeVersionNonNullable
instance Eq Three_d_secure_details_chargeVersionNonNullable
instance Data.Aeson.FromJSON Three_d_secure_details_chargeVersionNonNullable
instance Data.Aeson.ToJSON Three_d_secure_details_chargeVersionNonNullable
