module Stripe.CustomerSession.Types.ThreeDSecureDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Three_d_secure_details
instance Show Three_d_secure_details
instance Eq Three_d_secure_details
instance Data.Aeson.FromJSON Three_d_secure_details
instance Data.Aeson.ToJSON Three_d_secure_details
data Three_d_secure_detailsAuthentication_flowNonNullable
instance Show Three_d_secure_detailsAuthentication_flowNonNullable
instance Eq Three_d_secure_detailsAuthentication_flowNonNullable
instance Data.Aeson.FromJSON Three_d_secure_detailsAuthentication_flowNonNullable
instance Data.Aeson.ToJSON Three_d_secure_detailsAuthentication_flowNonNullable
data Three_d_secure_detailsElectronic_commerce_indicatorNonNullable
instance Show Three_d_secure_detailsElectronic_commerce_indicatorNonNullable
instance Eq Three_d_secure_detailsElectronic_commerce_indicatorNonNullable
instance Data.Aeson.FromJSON Three_d_secure_detailsElectronic_commerce_indicatorNonNullable
instance Data.Aeson.ToJSON Three_d_secure_detailsElectronic_commerce_indicatorNonNullable
data Three_d_secure_detailsResultNonNullable
instance Show Three_d_secure_detailsResultNonNullable
instance Eq Three_d_secure_detailsResultNonNullable
instance Data.Aeson.FromJSON Three_d_secure_detailsResultNonNullable
instance Data.Aeson.ToJSON Three_d_secure_detailsResultNonNullable
data Three_d_secure_detailsResult_reasonNonNullable
instance Show Three_d_secure_detailsResult_reasonNonNullable
instance Eq Three_d_secure_detailsResult_reasonNonNullable
instance Data.Aeson.FromJSON Three_d_secure_detailsResult_reasonNonNullable
instance Data.Aeson.ToJSON Three_d_secure_detailsResult_reasonNonNullable
data Three_d_secure_detailsVersionNonNullable
instance Show Three_d_secure_detailsVersionNonNullable
instance Eq Three_d_secure_detailsVersionNonNullable
instance Data.Aeson.FromJSON Three_d_secure_detailsVersionNonNullable
instance Data.Aeson.ToJSON Three_d_secure_detailsVersionNonNullable
