module Stripe.CustomerSession.Types.TransferReversal where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Transfer_reversal
instance Show Transfer_reversal
instance Eq Transfer_reversal
instance Data.Aeson.FromJSON Transfer_reversal
instance Data.Aeson.ToJSON Transfer_reversal
data Transfer_reversalBalance_transactionNonNullableVariants
instance Show Transfer_reversalBalance_transactionNonNullableVariants
instance Eq Transfer_reversalBalance_transactionNonNullableVariants
instance Data.Aeson.FromJSON Transfer_reversalBalance_transactionNonNullableVariants
instance Data.Aeson.ToJSON Transfer_reversalBalance_transactionNonNullableVariants
data Transfer_reversalDestination_payment_refundNonNullableVariants
instance Show Transfer_reversalDestination_payment_refundNonNullableVariants
instance Eq Transfer_reversalDestination_payment_refundNonNullableVariants
instance Data.Aeson.FromJSON Transfer_reversalDestination_payment_refundNonNullableVariants
instance Data.Aeson.ToJSON Transfer_reversalDestination_payment_refundNonNullableVariants
data Transfer_reversalSource_refundNonNullableVariants
instance Show Transfer_reversalSource_refundNonNullableVariants
instance Eq Transfer_reversalSource_refundNonNullableVariants
instance Data.Aeson.FromJSON Transfer_reversalSource_refundNonNullableVariants
instance Data.Aeson.ToJSON Transfer_reversalSource_refundNonNullableVariants
data Transfer_reversalTransferVariants
instance Show Transfer_reversalTransferVariants
instance Eq Transfer_reversalTransferVariants
instance Data.Aeson.FromJSON Transfer_reversalTransferVariants
instance Data.Aeson.ToJSON Transfer_reversalTransferVariants
