-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema TransferReversal
module Stripe.CustomerSession.Types.TransferReversal where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias
import {-# SOURCE #-} Stripe.CustomerSession.Types.BalanceTransaction
import {-# SOURCE #-} Stripe.CustomerSession.Types.Refund
import {-# SOURCE #-} Stripe.CustomerSession.Types.Transfer

-- | Defines the object schema located at @components.schemas.transfer_reversal@ in the specification.
-- 
-- [Stripe Connect](https:\/\/docs.stripe.com\/connect) platforms can reverse transfers made to a
-- connected account, either entirely or partially, and can also specify whether
-- to refund any related application fees. Transfer reversals add to the
-- platform\'s balance and subtract from the destination account\'s balance.
-- 
-- Reversing a transfer that was made for a [destination
-- charge](\/docs\/connect\/destination-charges) is allowed only up to the amount of
-- the charge. It is possible to reverse a
-- [transfer_group](https:\/\/docs.stripe.com\/connect\/separate-charges-and-transfers\#transfer-options)
-- transfer only if the destination account has enough balance to cover the
-- reversal.
-- 
-- Related guide: [Reverse transfers](https:\/\/docs.stripe.com\/connect\/separate-charges-and-transfers\#reverse-transfers)
data Transfer_reversal = Transfer_reversal {
  -- | amount: Amount, in cents (or local equivalent).
  transfer_reversalAmount :: GHC.Types.Int
  -- | balance_transaction: Balance transaction that describes the impact on your account balance.
  , transfer_reversalBalance_transaction :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Transfer_reversalBalance_transactionNonNullableVariants))
  -- | created: Time at which the object was created. Measured in seconds since the Unix epoch.
  , transfer_reversalCreated :: GHC.Types.Int
  -- | currency: Three-letter [ISO currency code](https:\/\/www.iso.org\/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https:\/\/stripe.com\/docs\/currencies).
  , transfer_reversalCurrency :: Data.Text.Internal.Text
  -- | destination_payment_refund: Linked payment refund for the transfer reversal.
  , transfer_reversalDestination_payment_refund :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Transfer_reversalDestination_payment_refundNonNullableVariants))
  -- | id: Unique identifier for the object.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , transfer_reversalId :: Data.Text.Internal.Text
  -- | metadata: Set of [key-value pairs](https:\/\/docs.stripe.com\/api\/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
  , transfer_reversalMetadata :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Data.Aeson.Types.Internal.Object))
  -- | source_refund: ID of the refund responsible for the transfer reversal.
  , transfer_reversalSource_refund :: (GHC.Maybe.Maybe (Stripe.CustomerSession.Common.Nullable Transfer_reversalSource_refundNonNullableVariants))
  -- | transfer: ID of the transfer that was reversed.
  , transfer_reversalTransfer :: Transfer_reversalTransferVariants
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Transfer_reversal
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["amount" Data.Aeson.Types.ToJSON..= transfer_reversalAmount obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("balance_transaction" Data.Aeson.Types.ToJSON..=)) (transfer_reversalBalance_transaction obj) : ["created" Data.Aeson.Types.ToJSON..= transfer_reversalCreated obj] : ["currency" Data.Aeson.Types.ToJSON..= transfer_reversalCurrency obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("destination_payment_refund" Data.Aeson.Types.ToJSON..=)) (transfer_reversalDestination_payment_refund obj) : ["id" Data.Aeson.Types.ToJSON..= transfer_reversalId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (transfer_reversalMetadata obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("source_refund" Data.Aeson.Types.ToJSON..=)) (transfer_reversalSource_refund obj) : ["transfer" Data.Aeson.Types.ToJSON..= transfer_reversalTransfer obj] : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "transfer_reversal"] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["amount" Data.Aeson.Types.ToJSON..= transfer_reversalAmount obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("balance_transaction" Data.Aeson.Types.ToJSON..=)) (transfer_reversalBalance_transaction obj) : ["created" Data.Aeson.Types.ToJSON..= transfer_reversalCreated obj] : ["currency" Data.Aeson.Types.ToJSON..= transfer_reversalCurrency obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("destination_payment_refund" Data.Aeson.Types.ToJSON..=)) (transfer_reversalDestination_payment_refund obj) : ["id" Data.Aeson.Types.ToJSON..= transfer_reversalId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("metadata" Data.Aeson.Types.ToJSON..=)) (transfer_reversalMetadata obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("source_refund" Data.Aeson.Types.ToJSON..=)) (transfer_reversalSource_refund obj) : ["transfer" Data.Aeson.Types.ToJSON..= transfer_reversalTransfer obj] : ["object" Data.Aeson.Types.ToJSON..= Data.Aeson.Types.Internal.String "transfer_reversal"] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Transfer_reversal
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Transfer_reversal" (\obj -> ((((((((GHC.Base.pure Transfer_reversal GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "amount")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "balance_transaction")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "created")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "currency")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "destination_payment_refund")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "metadata")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "source_refund")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "transfer"))}
-- | Create a new 'Transfer_reversal' with all required fields.
mkTransfer_reversal :: GHC.Types.Int -- ^ 'transfer_reversalAmount'
  -> GHC.Types.Int -- ^ 'transfer_reversalCreated'
  -> Data.Text.Internal.Text -- ^ 'transfer_reversalCurrency'
  -> Data.Text.Internal.Text -- ^ 'transfer_reversalId'
  -> Transfer_reversalTransferVariants -- ^ 'transfer_reversalTransfer'
  -> Transfer_reversal
mkTransfer_reversal transfer_reversalAmount transfer_reversalCreated transfer_reversalCurrency transfer_reversalId transfer_reversalTransfer = Transfer_reversal{transfer_reversalAmount = transfer_reversalAmount,
                                                                                                                                                                 transfer_reversalBalance_transaction = GHC.Maybe.Nothing,
                                                                                                                                                                 transfer_reversalCreated = transfer_reversalCreated,
                                                                                                                                                                 transfer_reversalCurrency = transfer_reversalCurrency,
                                                                                                                                                                 transfer_reversalDestination_payment_refund = GHC.Maybe.Nothing,
                                                                                                                                                                 transfer_reversalId = transfer_reversalId,
                                                                                                                                                                 transfer_reversalMetadata = GHC.Maybe.Nothing,
                                                                                                                                                                 transfer_reversalSource_refund = GHC.Maybe.Nothing,
                                                                                                                                                                 transfer_reversalTransfer = transfer_reversalTransfer}
-- | Defines the oneOf schema located at @components.schemas.transfer_reversal.properties.balance_transaction.anyOf@ in the specification.
-- 
-- Balance transaction that describes the impact on your account balance.
data Transfer_reversalBalance_transactionNonNullableVariants =
   Transfer_reversalBalance_transactionNonNullableText Data.Text.Internal.Text
  | Transfer_reversalBalance_transactionNonNullableBalance_transaction Balance_transaction
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Transfer_reversalBalance_transactionNonNullableVariants
    where {toJSON (Transfer_reversalBalance_transactionNonNullableText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Transfer_reversalBalance_transactionNonNullableBalance_transaction a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON Transfer_reversalBalance_transactionNonNullableVariants
    where {parseJSON val = case (Transfer_reversalBalance_transactionNonNullableText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((Transfer_reversalBalance_transactionNonNullableBalance_transaction Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the oneOf schema located at @components.schemas.transfer_reversal.properties.destination_payment_refund.anyOf@ in the specification.
-- 
-- Linked payment refund for the transfer reversal.
data Transfer_reversalDestination_payment_refundNonNullableVariants =
   Transfer_reversalDestination_payment_refundNonNullableText Data.Text.Internal.Text
  | Transfer_reversalDestination_payment_refundNonNullableRefund Refund
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Transfer_reversalDestination_payment_refundNonNullableVariants
    where {toJSON (Transfer_reversalDestination_payment_refundNonNullableText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Transfer_reversalDestination_payment_refundNonNullableRefund a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON Transfer_reversalDestination_payment_refundNonNullableVariants
    where {parseJSON val = case (Transfer_reversalDestination_payment_refundNonNullableText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((Transfer_reversalDestination_payment_refundNonNullableRefund Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the oneOf schema located at @components.schemas.transfer_reversal.properties.source_refund.anyOf@ in the specification.
-- 
-- ID of the refund responsible for the transfer reversal.
data Transfer_reversalSource_refundNonNullableVariants =
   Transfer_reversalSource_refundNonNullableText Data.Text.Internal.Text
  | Transfer_reversalSource_refundNonNullableRefund Refund
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Transfer_reversalSource_refundNonNullableVariants
    where {toJSON (Transfer_reversalSource_refundNonNullableText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Transfer_reversalSource_refundNonNullableRefund a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON Transfer_reversalSource_refundNonNullableVariants
    where {parseJSON val = case (Transfer_reversalSource_refundNonNullableText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((Transfer_reversalSource_refundNonNullableRefund Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the oneOf schema located at @components.schemas.transfer_reversal.properties.transfer.anyOf@ in the specification.
-- 
-- ID of the transfer that was reversed.
data Transfer_reversalTransferVariants =
   Transfer_reversalTransferText Data.Text.Internal.Text
  | Transfer_reversalTransferTransfer Transfer
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Transfer_reversalTransferVariants
    where {toJSON (Transfer_reversalTransferText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Transfer_reversalTransferTransfer a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON Transfer_reversalTransferVariants
    where {parseJSON val = case (Transfer_reversalTransferText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((Transfer_reversalTransferTransfer Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
