module Stripe.CustomerSession.Types.AccountCapabilities where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_capabilities
instance Show Account_capabilities
instance Eq Account_capabilities
instance Data.Aeson.FromJSON Account_capabilities
instance Data.Aeson.ToJSON Account_capabilities
