module Stripe.CustomerSession.Types.AccountUnificationAccountController where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_unification_account_controller
instance Show Account_unification_account_controller
instance Eq Account_unification_account_controller
instance Data.Aeson.FromJSON Account_unification_account_controller
instance Data.Aeson.ToJSON Account_unification_account_controller
