module Stripe.CustomerSession.Types.AccountBrandingSettings where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Account_branding_settings
instance Show Account_branding_settings
instance Eq Account_branding_settings
instance Data.Aeson.FromJSON Account_branding_settings
instance Data.Aeson.ToJSON Account_branding_settings
data Account_branding_settingsIconVariants
instance Show Account_branding_settingsIconVariants
instance Eq Account_branding_settingsIconVariants
instance Data.Aeson.FromJSON Account_branding_settingsIconVariants
instance Data.Aeson.ToJSON Account_branding_settingsIconVariants
data Account_branding_settingsLogoVariants
instance Show Account_branding_settingsLogoVariants
instance Eq Account_branding_settingsLogoVariants
instance Data.Aeson.FromJSON Account_branding_settingsLogoVariants
instance Data.Aeson.ToJSON Account_branding_settingsLogoVariants
