-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema AlmaInstallments
module Stripe.CustomerSession.Types.AlmaInstallments where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias

-- | Defines the object schema located at @components.schemas.alma_installments@ in the specification.
-- 
-- 
data Alma_installments = Alma_installments {
  -- | count: The number of installments.
  alma_installmentsCount :: GHC.Types.Int
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Alma_installments
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["count" Data.Aeson.Types.ToJSON..= alma_installmentsCount obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["count" Data.Aeson.Types.ToJSON..= alma_installmentsCount obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Alma_installments
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Alma_installments" (\obj -> GHC.Base.pure Alma_installments GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "count"))}
-- | Create a new 'Alma_installments' with all required fields.
mkAlma_installments :: GHC.Types.Int -- ^ 'alma_installmentsCount'
  -> Alma_installments
mkAlma_installments alma_installmentsCount = Alma_installments{alma_installmentsCount = alma_installmentsCount}
