module Stripe.CustomerSession.Types.ApplicationFee where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Application_fee
instance Show Application_fee
instance Eq Application_fee
instance Data.Aeson.FromJSON Application_fee
instance Data.Aeson.ToJSON Application_fee
data Application_feeAccountVariants
instance Show Application_feeAccountVariants
instance Eq Application_feeAccountVariants
instance Data.Aeson.FromJSON Application_feeAccountVariants
instance Data.Aeson.ToJSON Application_feeAccountVariants
data Application_feeApplicationVariants
instance Show Application_feeApplicationVariants
instance Eq Application_feeApplicationVariants
instance Data.Aeson.FromJSON Application_feeApplicationVariants
instance Data.Aeson.ToJSON Application_feeApplicationVariants
data Application_feeBalance_transactionVariants
instance Show Application_feeBalance_transactionVariants
instance Eq Application_feeBalance_transactionVariants
instance Data.Aeson.FromJSON Application_feeBalance_transactionVariants
instance Data.Aeson.ToJSON Application_feeBalance_transactionVariants
data Application_feeChargeVariants
instance Show Application_feeChargeVariants
instance Eq Application_feeChargeVariants
instance Data.Aeson.FromJSON Application_feeChargeVariants
instance Data.Aeson.ToJSON Application_feeChargeVariants
data Application_feeFee_source
instance Show Application_feeFee_source
instance Eq Application_feeFee_source
instance Data.Aeson.FromJSON Application_feeFee_source
instance Data.Aeson.ToJSON Application_feeFee_source
data Application_feeOriginating_transactionVariants
instance Show Application_feeOriginating_transactionVariants
instance Eq Application_feeOriginating_transactionVariants
instance Data.Aeson.FromJSON Application_feeOriginating_transactionVariants
instance Data.Aeson.ToJSON Application_feeOriginating_transactionVariants
data Application_feeRefunds
instance Show Application_feeRefunds
instance Eq Application_feeRefunds
instance Data.Aeson.FromJSON Application_feeRefunds
instance Data.Aeson.ToJSON Application_feeRefunds
