module Stripe.CustomerSession.Types.BalanceTransaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Balance_transaction
instance Show Balance_transaction
instance Eq Balance_transaction
instance Data.Aeson.FromJSON Balance_transaction
instance Data.Aeson.ToJSON Balance_transaction
data Balance_transactionSourceVariants
instance Show Balance_transactionSourceVariants
instance Eq Balance_transactionSourceVariants
instance Data.Aeson.FromJSON Balance_transactionSourceVariants
instance Data.Aeson.ToJSON Balance_transactionSourceVariants
