module Stripe.CustomerSession.Types.BankAccount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Bank_account
instance Show Bank_account
instance Eq Bank_account
instance Data.Aeson.FromJSON Bank_account
instance Data.Aeson.ToJSON Bank_account
data Bank_accountAccountVariants
instance Show Bank_accountAccountVariants
instance Eq Bank_accountAccountVariants
instance Data.Aeson.FromJSON Bank_accountAccountVariants
instance Data.Aeson.ToJSON Bank_accountAccountVariants
data Bank_accountCustomerVariants
instance Show Bank_accountCustomerVariants
instance Eq Bank_accountCustomerVariants
instance Data.Aeson.FromJSON Bank_accountCustomerVariants
instance Data.Aeson.ToJSON Bank_accountCustomerVariants
data Bank_accountFuture_requirements
instance Show Bank_accountFuture_requirements
instance Eq Bank_accountFuture_requirements
instance Data.Aeson.FromJSON Bank_accountFuture_requirements
instance Data.Aeson.ToJSON Bank_accountFuture_requirements
data Bank_accountRequirements
instance Show Bank_accountRequirements
instance Eq Bank_accountRequirements
instance Data.Aeson.FromJSON Bank_accountRequirements
instance Data.Aeson.ToJSON Bank_accountRequirements
