module Stripe.CustomerSession.Types.BillingBillResourceInvoicingParentsInvoiceSubscriptionParent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_parents_invoice_subscription_parent
instance Show Billing_bill_resource_invoicing_parents_invoice_subscription_parent
instance Eq Billing_bill_resource_invoicing_parents_invoice_subscription_parent
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_parents_invoice_subscription_parent
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_parents_invoice_subscription_parent
data Billing_bill_resource_invoicing_parents_invoice_subscription_parentSubscriptionVariants
instance Show Billing_bill_resource_invoicing_parents_invoice_subscription_parentSubscriptionVariants
instance Eq Billing_bill_resource_invoicing_parents_invoice_subscription_parentSubscriptionVariants
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_parents_invoice_subscription_parentSubscriptionVariants
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_parents_invoice_subscription_parentSubscriptionVariants
