module Stripe.CustomerSession.Types.BillingCreditGrantsResourceBalanceDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_credit_grants_resource_balance_debit
instance Show Billing_credit_grants_resource_balance_debit
instance Eq Billing_credit_grants_resource_balance_debit
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_debit
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_debit
data Billing_credit_grants_resource_balance_debitCredits_applied
instance Show Billing_credit_grants_resource_balance_debitCredits_applied
instance Eq Billing_credit_grants_resource_balance_debitCredits_applied
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_debitCredits_applied
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_debitCredits_applied
data Billing_credit_grants_resource_balance_debitCredits_appliedInvoiceVariants
instance Show Billing_credit_grants_resource_balance_debitCredits_appliedInvoiceVariants
instance Eq Billing_credit_grants_resource_balance_debitCredits_appliedInvoiceVariants
instance Data.Aeson.FromJSON Billing_credit_grants_resource_balance_debitCredits_appliedInvoiceVariants
instance Data.Aeson.ToJSON Billing_credit_grants_resource_balance_debitCredits_appliedInvoiceVariants
