module Stripe.CustomerSession.Types.BillingBillResourceInvoicingLinesParentsInvoiceLineItemParent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parent
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_details
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_details
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_details
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_details
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_details
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsProration_details
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsProration_details
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsProration_details
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsProration_details
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsProration_details
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsProration_detailsCredited_items
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsProration_detailsCredited_items
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsProration_detailsCredited_items
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsProration_detailsCredited_items
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentInvoice_item_detailsProration_detailsCredited_items
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_details
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_details
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_details
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_details
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_details
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsProration_details
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsProration_details
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsProration_details
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsProration_details
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsProration_details
data Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsProration_detailsCredited_items
instance Show Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsProration_detailsCredited_items
instance Eq Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsProration_detailsCredited_items
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsProration_detailsCredited_items
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_parents_invoice_line_item_parentSubscription_item_detailsProration_detailsCredited_items
