module Stripe.CustomerSession.Types.BillingBillResourceInvoicingTaxesTax where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_taxes_tax
instance Show Billing_bill_resource_invoicing_taxes_tax
instance Eq Billing_bill_resource_invoicing_taxes_tax
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_taxes_tax
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_taxes_tax
data Billing_bill_resource_invoicing_taxes_taxTax_rate_details
instance Show Billing_bill_resource_invoicing_taxes_taxTax_rate_details
instance Eq Billing_bill_resource_invoicing_taxes_taxTax_rate_details
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_taxes_taxTax_rate_details
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_taxes_taxTax_rate_details
