module Stripe.CustomerSession.Types.BillingBillResourceInvoicingParentsInvoiceQuoteParent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_parents_invoice_quote_parent
instance Show Billing_bill_resource_invoicing_parents_invoice_quote_parent
instance Eq Billing_bill_resource_invoicing_parents_invoice_quote_parent
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_parents_invoice_quote_parent
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_parents_invoice_quote_parent
