module Stripe.CustomerSession.Types.BillingBillResourceInvoicingLinesCommonCreditedItems where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_lines_common_credited_items
instance Show Billing_bill_resource_invoicing_lines_common_credited_items
instance Eq Billing_bill_resource_invoicing_lines_common_credited_items
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_lines_common_credited_items
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_lines_common_credited_items
