module Stripe.CustomerSession.Types.Billing_CreditBalanceTransaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing'credit_balance_transaction
instance Show Billing'credit_balance_transaction
instance Eq Billing'credit_balance_transaction
instance Data.Aeson.FromJSON Billing'credit_balance_transaction
instance Data.Aeson.ToJSON Billing'credit_balance_transaction
data Billing'credit_balance_transactionCredit
instance Show Billing'credit_balance_transactionCredit
instance Eq Billing'credit_balance_transactionCredit
instance Data.Aeson.FromJSON Billing'credit_balance_transactionCredit
instance Data.Aeson.ToJSON Billing'credit_balance_transactionCredit
data Billing'credit_balance_transactionCreditCredits_application_invoice_voided
instance Show Billing'credit_balance_transactionCreditCredits_application_invoice_voided
instance Eq Billing'credit_balance_transactionCreditCredits_application_invoice_voided
instance Data.Aeson.FromJSON Billing'credit_balance_transactionCreditCredits_application_invoice_voided
instance Data.Aeson.ToJSON Billing'credit_balance_transactionCreditCredits_application_invoice_voided
data Billing'credit_balance_transactionCreditCredits_application_invoice_voidedInvoiceVariants
instance Show Billing'credit_balance_transactionCreditCredits_application_invoice_voidedInvoiceVariants
instance Eq Billing'credit_balance_transactionCreditCredits_application_invoice_voidedInvoiceVariants
instance Data.Aeson.FromJSON Billing'credit_balance_transactionCreditCredits_application_invoice_voidedInvoiceVariants
instance Data.Aeson.ToJSON Billing'credit_balance_transactionCreditCredits_application_invoice_voidedInvoiceVariants
data Billing'credit_balance_transactionCredit_grantVariants
instance Show Billing'credit_balance_transactionCredit_grantVariants
instance Eq Billing'credit_balance_transactionCredit_grantVariants
instance Data.Aeson.FromJSON Billing'credit_balance_transactionCredit_grantVariants
instance Data.Aeson.ToJSON Billing'credit_balance_transactionCredit_grantVariants
data Billing'credit_balance_transactionDebit
instance Show Billing'credit_balance_transactionDebit
instance Eq Billing'credit_balance_transactionDebit
instance Data.Aeson.FromJSON Billing'credit_balance_transactionDebit
instance Data.Aeson.ToJSON Billing'credit_balance_transactionDebit
data Billing'credit_balance_transactionDebitCredits_applied
instance Show Billing'credit_balance_transactionDebitCredits_applied
instance Eq Billing'credit_balance_transactionDebitCredits_applied
instance Data.Aeson.FromJSON Billing'credit_balance_transactionDebitCredits_applied
instance Data.Aeson.ToJSON Billing'credit_balance_transactionDebitCredits_applied
data Billing'credit_balance_transactionDebitCredits_appliedInvoiceVariants
instance Show Billing'credit_balance_transactionDebitCredits_appliedInvoiceVariants
instance Eq Billing'credit_balance_transactionDebitCredits_appliedInvoiceVariants
instance Data.Aeson.FromJSON Billing'credit_balance_transactionDebitCredits_appliedInvoiceVariants
instance Data.Aeson.ToJSON Billing'credit_balance_transactionDebitCredits_appliedInvoiceVariants
data Billing'credit_balance_transactionTest_clockVariants
instance Show Billing'credit_balance_transactionTest_clockVariants
instance Eq Billing'credit_balance_transactionTest_clockVariants
instance Data.Aeson.FromJSON Billing'credit_balance_transactionTest_clockVariants
instance Data.Aeson.ToJSON Billing'credit_balance_transactionTest_clockVariants
