module Stripe.CustomerSession.Types.BillingCreditGrantsResourceAmount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_credit_grants_resource_amount
instance Show Billing_credit_grants_resource_amount
instance Eq Billing_credit_grants_resource_amount
instance Data.Aeson.FromJSON Billing_credit_grants_resource_amount
instance Data.Aeson.ToJSON Billing_credit_grants_resource_amount
data Billing_credit_grants_resource_amountMonetary
instance Show Billing_credit_grants_resource_amountMonetary
instance Eq Billing_credit_grants_resource_amountMonetary
instance Data.Aeson.FromJSON Billing_credit_grants_resource_amountMonetary
instance Data.Aeson.ToJSON Billing_credit_grants_resource_amountMonetary
