module Stripe.CustomerSession.Types.BillingBillResourceInvoicingPricingPricingPriceDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Billing_bill_resource_invoicing_pricing_pricing_price_details
instance Show Billing_bill_resource_invoicing_pricing_pricing_price_details
instance Eq Billing_bill_resource_invoicing_pricing_pricing_price_details
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_pricing_pricing_price_details
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_pricing_pricing_price_details
data Billing_bill_resource_invoicing_pricing_pricing_price_detailsPriceVariants
instance Show Billing_bill_resource_invoicing_pricing_pricing_price_detailsPriceVariants
instance Eq Billing_bill_resource_invoicing_pricing_pricing_price_detailsPriceVariants
instance Data.Aeson.FromJSON Billing_bill_resource_invoicing_pricing_pricing_price_detailsPriceVariants
instance Data.Aeson.ToJSON Billing_bill_resource_invoicing_pricing_pricing_price_detailsPriceVariants
