module Stripe.CustomerSession.Types.Charge where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Charge
instance Show Charge
instance Eq Charge
instance Data.Aeson.FromJSON Charge
instance Data.Aeson.ToJSON Charge
data ChargeApplicationVariants
instance Show ChargeApplicationVariants
instance Eq ChargeApplicationVariants
instance Data.Aeson.FromJSON ChargeApplicationVariants
instance Data.Aeson.ToJSON ChargeApplicationVariants
data ChargeApplication_feeVariants
instance Show ChargeApplication_feeVariants
instance Eq ChargeApplication_feeVariants
instance Data.Aeson.FromJSON ChargeApplication_feeVariants
instance Data.Aeson.ToJSON ChargeApplication_feeVariants
data ChargeBalance_transactionVariants
instance Show ChargeBalance_transactionVariants
instance Eq ChargeBalance_transactionVariants
instance Data.Aeson.FromJSON ChargeBalance_transactionVariants
instance Data.Aeson.ToJSON ChargeBalance_transactionVariants
data ChargeCustomerVariants
instance Show ChargeCustomerVariants
instance Eq ChargeCustomerVariants
instance Data.Aeson.FromJSON ChargeCustomerVariants
instance Data.Aeson.ToJSON ChargeCustomerVariants
data ChargeFailure_balance_transactionVariants
instance Show ChargeFailure_balance_transactionVariants
instance Eq ChargeFailure_balance_transactionVariants
instance Data.Aeson.FromJSON ChargeFailure_balance_transactionVariants
instance Data.Aeson.ToJSON ChargeFailure_balance_transactionVariants
data ChargeFraud_details
instance Show ChargeFraud_details
instance Eq ChargeFraud_details
instance Data.Aeson.FromJSON ChargeFraud_details
instance Data.Aeson.ToJSON ChargeFraud_details
data ChargeOn_behalf_ofVariants
instance Show ChargeOn_behalf_ofVariants
instance Eq ChargeOn_behalf_ofVariants
instance Data.Aeson.FromJSON ChargeOn_behalf_ofVariants
instance Data.Aeson.ToJSON ChargeOn_behalf_ofVariants
data ChargeOutcome
instance Show ChargeOutcome
instance Eq ChargeOutcome
instance Data.Aeson.FromJSON ChargeOutcome
instance Data.Aeson.ToJSON ChargeOutcome
data ChargeOutcomeRuleVariants
instance Show ChargeOutcomeRuleVariants
instance Eq ChargeOutcomeRuleVariants
instance Data.Aeson.FromJSON ChargeOutcomeRuleVariants
instance Data.Aeson.ToJSON ChargeOutcomeRuleVariants
data ChargePayment_intentVariants
instance Show ChargePayment_intentVariants
instance Eq ChargePayment_intentVariants
instance Data.Aeson.FromJSON ChargePayment_intentVariants
instance Data.Aeson.ToJSON ChargePayment_intentVariants
data ChargePayment_method_details
instance Show ChargePayment_method_details
instance Eq ChargePayment_method_details
instance Data.Aeson.FromJSON ChargePayment_method_details
instance Data.Aeson.ToJSON ChargePayment_method_details
data ChargeRefunds
instance Show ChargeRefunds
instance Eq ChargeRefunds
instance Data.Aeson.FromJSON ChargeRefunds
instance Data.Aeson.ToJSON ChargeRefunds
data ChargeReviewVariants
instance Show ChargeReviewVariants
instance Eq ChargeReviewVariants
instance Data.Aeson.FromJSON ChargeReviewVariants
instance Data.Aeson.ToJSON ChargeReviewVariants
data ChargeShipping
instance Show ChargeShipping
instance Eq ChargeShipping
instance Data.Aeson.FromJSON ChargeShipping
instance Data.Aeson.ToJSON ChargeShipping
data ChargeSource_transferVariants
instance Show ChargeSource_transferVariants
instance Eq ChargeSource_transferVariants
instance Data.Aeson.FromJSON ChargeSource_transferVariants
instance Data.Aeson.ToJSON ChargeSource_transferVariants
data ChargeTransferVariants
instance Show ChargeTransferVariants
instance Eq ChargeTransferVariants
instance Data.Aeson.FromJSON ChargeTransferVariants
instance Data.Aeson.ToJSON ChargeTransferVariants
data ChargeTransfer_data
instance Show ChargeTransfer_data
instance Eq ChargeTransfer_data
instance Data.Aeson.FromJSON ChargeTransfer_data
instance Data.Aeson.ToJSON ChargeTransfer_data
data ChargeTransfer_dataDestinationVariants
instance Show ChargeTransfer_dataDestinationVariants
instance Eq ChargeTransfer_dataDestinationVariants
instance Data.Aeson.FromJSON ChargeTransfer_dataDestinationVariants
instance Data.Aeson.ToJSON ChargeTransfer_dataDestinationVariants
