module Stripe.CustomerSession.Types.CustomerSessionResourceComponentsResourceBuyButton where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_session_resource_components_resource_buy_button
instance Show Customer_session_resource_components_resource_buy_button
instance Eq Customer_session_resource_components_resource_buy_button
instance Data.Aeson.FromJSON Customer_session_resource_components_resource_buy_button
instance Data.Aeson.ToJSON Customer_session_resource_components_resource_buy_button
