module Stripe.CustomerSession.Types.CustomerSessionResourceComponentsResourcePricingTable where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_session_resource_components_resource_pricing_table
instance Show Customer_session_resource_components_resource_pricing_table
instance Eq Customer_session_resource_components_resource_pricing_table
instance Data.Aeson.FromJSON Customer_session_resource_components_resource_pricing_table
instance Data.Aeson.ToJSON Customer_session_resource_components_resource_pricing_table
