module Stripe.CustomerSession.Types.CustomerCashBalanceTransaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_cash_balance_transaction
instance Show Customer_cash_balance_transaction
instance Eq Customer_cash_balance_transaction
instance Data.Aeson.FromJSON Customer_cash_balance_transaction
instance Data.Aeson.ToJSON Customer_cash_balance_transaction
data Customer_cash_balance_transactionCustomerVariants
instance Show Customer_cash_balance_transactionCustomerVariants
instance Eq Customer_cash_balance_transactionCustomerVariants
instance Data.Aeson.FromJSON Customer_cash_balance_transactionCustomerVariants
instance Data.Aeson.ToJSON Customer_cash_balance_transactionCustomerVariants
