module Stripe.CustomerSession.Types.CustomerBalanceResourceCashBalanceTransactionResourceAdjustedForOverdraft where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraft
instance Show Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraft
instance Eq Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraft
instance Data.Aeson.FromJSON Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraft
instance Data.Aeson.ToJSON Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraft
data Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraftBalance_transactionVariants
instance Show Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraftBalance_transactionVariants
instance Eq Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraftBalance_transactionVariants
instance Data.Aeson.FromJSON Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraftBalance_transactionVariants
instance Data.Aeson.ToJSON Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraftBalance_transactionVariants
data Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraftLinked_transactionVariants
instance Show Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraftLinked_transactionVariants
instance Eq Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraftLinked_transactionVariants
instance Data.Aeson.FromJSON Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraftLinked_transactionVariants
instance Data.Aeson.ToJSON Customer_balance_resource_cash_balance_transaction_resource_adjusted_for_overdraftLinked_transactionVariants
