module Stripe.CustomerSession.Types.CustomerSessionResourceComponentsResourceMobilePaymentElementResourceFeatures where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Customer_session_resource_components_resource_mobile_payment_element_resource_features
instance Show Customer_session_resource_components_resource_mobile_payment_element_resource_features
instance Eq Customer_session_resource_components_resource_mobile_payment_element_resource_features
instance Data.Aeson.FromJSON Customer_session_resource_components_resource_mobile_payment_element_resource_features
instance Data.Aeson.ToJSON Customer_session_resource_components_resource_mobile_payment_element_resource_features
