module Stripe.CustomerSession.Types.DeletedDiscount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Deleted_discount
instance Show Deleted_discount
instance Eq Deleted_discount
instance Data.Aeson.FromJSON Deleted_discount
instance Data.Aeson.ToJSON Deleted_discount
data Deleted_discountCustomerVariants
instance Show Deleted_discountCustomerVariants
instance Eq Deleted_discountCustomerVariants
instance Data.Aeson.FromJSON Deleted_discountCustomerVariants
instance Data.Aeson.ToJSON Deleted_discountCustomerVariants
data Deleted_discountPromotion_codeVariants
instance Show Deleted_discountPromotion_codeVariants
instance Eq Deleted_discountPromotion_codeVariants
instance Data.Aeson.FromJSON Deleted_discountPromotion_codeVariants
instance Data.Aeson.ToJSON Deleted_discountPromotion_codeVariants
