module Stripe.CustomerSession.Types.DiscountsResourceDiscountAmount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Discounts_resource_discount_amount
instance Show Discounts_resource_discount_amount
instance Eq Discounts_resource_discount_amount
instance Data.Aeson.FromJSON Discounts_resource_discount_amount
instance Data.Aeson.ToJSON Discounts_resource_discount_amount
data Discounts_resource_discount_amountDiscountVariants
instance Show Discounts_resource_discount_amountDiscountVariants
instance Eq Discounts_resource_discount_amountDiscountVariants
instance Data.Aeson.FromJSON Discounts_resource_discount_amountDiscountVariants
instance Data.Aeson.ToJSON Discounts_resource_discount_amountDiscountVariants
