module Stripe.CustomerSession.Types.Discount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Discount
instance Show Discount
instance Eq Discount
instance Data.Aeson.FromJSON Discount
instance Data.Aeson.ToJSON Discount
data DiscountCustomerVariants
instance Show DiscountCustomerVariants
instance Eq DiscountCustomerVariants
instance Data.Aeson.FromJSON DiscountCustomerVariants
instance Data.Aeson.ToJSON DiscountCustomerVariants
data DiscountPromotion_codeVariants
instance Show DiscountPromotion_codeVariants
instance Eq DiscountPromotion_codeVariants
instance Data.Aeson.FromJSON DiscountPromotion_codeVariants
instance Data.Aeson.ToJSON DiscountPromotion_codeVariants
