module Stripe.CustomerSession.Types.DisputePaymentMethodDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Dispute_payment_method_details
instance Show Dispute_payment_method_details
instance Eq Dispute_payment_method_details
instance Data.Aeson.FromJSON Dispute_payment_method_details
instance Data.Aeson.ToJSON Dispute_payment_method_details
