module Stripe.CustomerSession.Types.DisputeVisaCompellingEvidence3DisputedTransaction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Dispute_visa_compelling_evidence3_disputed_transaction
instance Show Dispute_visa_compelling_evidence3_disputed_transaction
instance Eq Dispute_visa_compelling_evidence3_disputed_transaction
instance Data.Aeson.FromJSON Dispute_visa_compelling_evidence3_disputed_transaction
instance Data.Aeson.ToJSON Dispute_visa_compelling_evidence3_disputed_transaction
data Dispute_visa_compelling_evidence3_disputed_transactionShipping_address
instance Show Dispute_visa_compelling_evidence3_disputed_transactionShipping_address
instance Eq Dispute_visa_compelling_evidence3_disputed_transactionShipping_address
instance Data.Aeson.FromJSON Dispute_visa_compelling_evidence3_disputed_transactionShipping_address
instance Data.Aeson.ToJSON Dispute_visa_compelling_evidence3_disputed_transactionShipping_address
