module Stripe.CustomerSession.Types.DisputeEnhancedEvidenceVisaCompellingEvidence3 where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Dispute_enhanced_evidence_visa_compelling_evidence3
instance Show Dispute_enhanced_evidence_visa_compelling_evidence3
instance Eq Dispute_enhanced_evidence_visa_compelling_evidence3
instance Data.Aeson.FromJSON Dispute_enhanced_evidence_visa_compelling_evidence3
instance Data.Aeson.ToJSON Dispute_enhanced_evidence_visa_compelling_evidence3
data Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transaction
instance Show Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transaction
instance Eq Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transaction
instance Data.Aeson.FromJSON Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transaction
instance Data.Aeson.ToJSON Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transaction
data Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionShipping_address
instance Show Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionShipping_address
instance Eq Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionShipping_address
instance Data.Aeson.FromJSON Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionShipping_address
instance Data.Aeson.ToJSON Dispute_enhanced_evidence_visa_compelling_evidence3Disputed_transactionShipping_address
