module Stripe.CustomerSession.Types.FundingInstructionsBankTransferZenginRecord where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Funding_instructions_bank_transfer_zengin_record
instance Show Funding_instructions_bank_transfer_zengin_record
instance Eq Funding_instructions_bank_transfer_zengin_record
instance Data.Aeson.FromJSON Funding_instructions_bank_transfer_zengin_record
instance Data.Aeson.ToJSON Funding_instructions_bank_transfer_zengin_record
