-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema InvoiceLineItemPeriod
module Stripe.CustomerSession.Types.InvoiceLineItemPeriod where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias

-- | Defines the object schema located at @components.schemas.invoice_line_item_period@ in the specification.
-- 
-- 
data Invoice_line_item_period = Invoice_line_item_period {
  -- | end: The end of the period, which must be greater than or equal to the start. This value is inclusive.
  invoice_line_item_periodEnd :: GHC.Types.Int
  -- | start: The start of the period. This value is inclusive.
  , invoice_line_item_periodStart :: GHC.Types.Int
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Invoice_line_item_period
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["end" Data.Aeson.Types.ToJSON..= invoice_line_item_periodEnd obj] : ["start" Data.Aeson.Types.ToJSON..= invoice_line_item_periodStart obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["end" Data.Aeson.Types.ToJSON..= invoice_line_item_periodEnd obj] : ["start" Data.Aeson.Types.ToJSON..= invoice_line_item_periodStart obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Invoice_line_item_period
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Invoice_line_item_period" (\obj -> (GHC.Base.pure Invoice_line_item_period GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "end")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "start"))}
-- | Create a new 'Invoice_line_item_period' with all required fields.
mkInvoice_line_item_period :: GHC.Types.Int -- ^ 'invoice_line_item_periodEnd'
  -> GHC.Types.Int -- ^ 'invoice_line_item_periodStart'
  -> Invoice_line_item_period
mkInvoice_line_item_period invoice_line_item_periodEnd invoice_line_item_periodStart = Invoice_line_item_period{invoice_line_item_periodEnd = invoice_line_item_periodEnd,
                                                                                                                invoice_line_item_periodStart = invoice_line_item_periodStart}
