module Stripe.CustomerSession.Types.InvoicesResourceShippingCost where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoices_resource_shipping_cost
instance Show Invoices_resource_shipping_cost
instance Eq Invoices_resource_shipping_cost
instance Data.Aeson.FromJSON Invoices_resource_shipping_cost
instance Data.Aeson.ToJSON Invoices_resource_shipping_cost
data Invoices_resource_shipping_costShipping_rateVariants
instance Show Invoices_resource_shipping_costShipping_rateVariants
instance Eq Invoices_resource_shipping_costShipping_rateVariants
instance Data.Aeson.FromJSON Invoices_resource_shipping_costShipping_rateVariants
instance Data.Aeson.ToJSON Invoices_resource_shipping_costShipping_rateVariants
