module Stripe.CustomerSession.Types.InvoiceRenderingPdf where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_rendering_pdf
instance Show Invoice_rendering_pdf
instance Eq Invoice_rendering_pdf
instance Data.Aeson.FromJSON Invoice_rendering_pdf
instance Data.Aeson.ToJSON Invoice_rendering_pdf
