module Stripe.CustomerSession.Types.InvoicesResourceInvoiceRendering where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoices_resource_invoice_rendering
instance Show Invoices_resource_invoice_rendering
instance Eq Invoices_resource_invoice_rendering
instance Data.Aeson.FromJSON Invoices_resource_invoice_rendering
instance Data.Aeson.ToJSON Invoices_resource_invoice_rendering
data Invoices_resource_invoice_renderingPdf
instance Show Invoices_resource_invoice_renderingPdf
instance Eq Invoices_resource_invoice_renderingPdf
instance Data.Aeson.FromJSON Invoices_resource_invoice_renderingPdf
instance Data.Aeson.ToJSON Invoices_resource_invoice_renderingPdf
