module Stripe.CustomerSession.Types.InvoiceSettingCustomerSetting where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_setting_customer_setting
instance Show Invoice_setting_customer_setting
instance Eq Invoice_setting_customer_setting
instance Data.Aeson.FromJSON Invoice_setting_customer_setting
instance Data.Aeson.ToJSON Invoice_setting_customer_setting
data Invoice_setting_customer_settingDefault_payment_methodVariants
instance Show Invoice_setting_customer_settingDefault_payment_methodVariants
instance Eq Invoice_setting_customer_settingDefault_payment_methodVariants
instance Data.Aeson.FromJSON Invoice_setting_customer_settingDefault_payment_methodVariants
instance Data.Aeson.ToJSON Invoice_setting_customer_settingDefault_payment_methodVariants
data Invoice_setting_customer_settingRendering_options
instance Show Invoice_setting_customer_settingRendering_options
instance Eq Invoice_setting_customer_settingRendering_options
instance Data.Aeson.FromJSON Invoice_setting_customer_settingRendering_options
instance Data.Aeson.ToJSON Invoice_setting_customer_settingRendering_options
