module Stripe.CustomerSession.Types.InvoicePaymentMethodOptionsAcssDebitMandateOptions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoice_payment_method_options_acss_debit_mandate_options
instance Show Invoice_payment_method_options_acss_debit_mandate_options
instance Eq Invoice_payment_method_options_acss_debit_mandate_options
instance Data.Aeson.FromJSON Invoice_payment_method_options_acss_debit_mandate_options
instance Data.Aeson.ToJSON Invoice_payment_method_options_acss_debit_mandate_options
