module Stripe.CustomerSession.Types.InvoicesPaymentsInvoicePaymentStatusTransitions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Invoices_payments_invoice_payment_status_transitions
instance Show Invoices_payments_invoice_payment_status_transitions
instance Eq Invoices_payments_invoice_payment_status_transitions
instance Data.Aeson.FromJSON Invoices_payments_invoice_payment_status_transitions
instance Data.Aeson.ToJSON Invoices_payments_invoice_payment_status_transitions
