module Stripe.CustomerSession.Types.IssuingAuthorizationFuelData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_fuel_data
instance Show Issuing_authorization_fuel_data
instance Eq Issuing_authorization_fuel_data
instance Data.Aeson.FromJSON Issuing_authorization_fuel_data
instance Data.Aeson.ToJSON Issuing_authorization_fuel_data
