module Stripe.CustomerSession.Types.IssuingTransactionPurchaseDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_transaction_purchase_details
instance Show Issuing_transaction_purchase_details
instance Eq Issuing_transaction_purchase_details
instance Data.Aeson.FromJSON Issuing_transaction_purchase_details
instance Data.Aeson.ToJSON Issuing_transaction_purchase_details
data Issuing_transaction_purchase_detailsFleet
instance Show Issuing_transaction_purchase_detailsFleet
instance Eq Issuing_transaction_purchase_detailsFleet
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleet
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleet
data Issuing_transaction_purchase_detailsFleetCardholder_prompt_data
instance Show Issuing_transaction_purchase_detailsFleetCardholder_prompt_data
instance Eq Issuing_transaction_purchase_detailsFleetCardholder_prompt_data
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleetCardholder_prompt_data
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleetCardholder_prompt_data
data Issuing_transaction_purchase_detailsFleetReported_breakdown
instance Show Issuing_transaction_purchase_detailsFleetReported_breakdown
instance Eq Issuing_transaction_purchase_detailsFleetReported_breakdown
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleetReported_breakdown
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleetReported_breakdown
data Issuing_transaction_purchase_detailsFleetReported_breakdownFuel
instance Show Issuing_transaction_purchase_detailsFleetReported_breakdownFuel
instance Eq Issuing_transaction_purchase_detailsFleetReported_breakdownFuel
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleetReported_breakdownFuel
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleetReported_breakdownFuel
data Issuing_transaction_purchase_detailsFleetReported_breakdownNon_fuel
instance Show Issuing_transaction_purchase_detailsFleetReported_breakdownNon_fuel
instance Eq Issuing_transaction_purchase_detailsFleetReported_breakdownNon_fuel
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleetReported_breakdownNon_fuel
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleetReported_breakdownNon_fuel
data Issuing_transaction_purchase_detailsFleetReported_breakdownTax
instance Show Issuing_transaction_purchase_detailsFleetReported_breakdownTax
instance Eq Issuing_transaction_purchase_detailsFleetReported_breakdownTax
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFleetReported_breakdownTax
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFleetReported_breakdownTax
data Issuing_transaction_purchase_detailsFlight
instance Show Issuing_transaction_purchase_detailsFlight
instance Eq Issuing_transaction_purchase_detailsFlight
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFlight
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFlight
data Issuing_transaction_purchase_detailsFuel
instance Show Issuing_transaction_purchase_detailsFuel
instance Eq Issuing_transaction_purchase_detailsFuel
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsFuel
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsFuel
data Issuing_transaction_purchase_detailsLodging
instance Show Issuing_transaction_purchase_detailsLodging
instance Eq Issuing_transaction_purchase_detailsLodging
instance Data.Aeson.FromJSON Issuing_transaction_purchase_detailsLodging
instance Data.Aeson.ToJSON Issuing_transaction_purchase_detailsLodging
