module Stripe.CustomerSession.Types.IssuingTransactionNetworkData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_transaction_network_data
instance Show Issuing_transaction_network_data
instance Eq Issuing_transaction_network_data
instance Data.Aeson.FromJSON Issuing_transaction_network_data
instance Data.Aeson.ToJSON Issuing_transaction_network_data
