module Stripe.CustomerSession.Types.IssuingCardholderIdDocument where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_cardholder_id_document
instance Show Issuing_cardholder_id_document
instance Eq Issuing_cardholder_id_document
instance Data.Aeson.FromJSON Issuing_cardholder_id_document
instance Data.Aeson.ToJSON Issuing_cardholder_id_document
data Issuing_cardholder_id_documentBackVariants
instance Show Issuing_cardholder_id_documentBackVariants
instance Eq Issuing_cardholder_id_documentBackVariants
instance Data.Aeson.FromJSON Issuing_cardholder_id_documentBackVariants
instance Data.Aeson.ToJSON Issuing_cardholder_id_documentBackVariants
data Issuing_cardholder_id_documentFrontVariants
instance Show Issuing_cardholder_id_documentFrontVariants
instance Eq Issuing_cardholder_id_documentFrontVariants
instance Data.Aeson.FromJSON Issuing_cardholder_id_documentFrontVariants
instance Data.Aeson.ToJSON Issuing_cardholder_id_documentFrontVariants
