module Stripe.CustomerSession.Types.IssuingTransactionFleetTaxData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_transaction_fleet_tax_data
instance Show Issuing_transaction_fleet_tax_data
instance Eq Issuing_transaction_fleet_tax_data
instance Data.Aeson.FromJSON Issuing_transaction_fleet_tax_data
instance Data.Aeson.ToJSON Issuing_transaction_fleet_tax_data
