module Stripe.CustomerSession.Types.IssuingAuthorizationFraudChallenge where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_fraud_challenge
instance Show Issuing_authorization_fraud_challenge
instance Eq Issuing_authorization_fraud_challenge
instance Data.Aeson.FromJSON Issuing_authorization_fraud_challenge
instance Data.Aeson.ToJSON Issuing_authorization_fraud_challenge
