module Stripe.CustomerSession.Types.IssuingCardFraudWarning where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_card_fraud_warning
instance Show Issuing_card_fraud_warning
instance Eq Issuing_card_fraud_warning
instance Data.Aeson.FromJSON Issuing_card_fraud_warning
instance Data.Aeson.ToJSON Issuing_card_fraud_warning
