module Stripe.CustomerSession.Types.IssuingTransactionFleetNonFuelPriceData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_transaction_fleet_non_fuel_price_data
instance Show Issuing_transaction_fleet_non_fuel_price_data
instance Eq Issuing_transaction_fleet_non_fuel_price_data
instance Data.Aeson.FromJSON Issuing_transaction_fleet_non_fuel_price_data
instance Data.Aeson.ToJSON Issuing_transaction_fleet_non_fuel_price_data
