module Stripe.CustomerSession.Types.IssuingCardholderVerification where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_cardholder_verification
instance Show Issuing_cardholder_verification
instance Eq Issuing_cardholder_verification
instance Data.Aeson.FromJSON Issuing_cardholder_verification
instance Data.Aeson.ToJSON Issuing_cardholder_verification
data Issuing_cardholder_verificationDocument
instance Show Issuing_cardholder_verificationDocument
instance Eq Issuing_cardholder_verificationDocument
instance Data.Aeson.FromJSON Issuing_cardholder_verificationDocument
instance Data.Aeson.ToJSON Issuing_cardholder_verificationDocument
data Issuing_cardholder_verificationDocumentBackVariants
instance Show Issuing_cardholder_verificationDocumentBackVariants
instance Eq Issuing_cardholder_verificationDocumentBackVariants
instance Data.Aeson.FromJSON Issuing_cardholder_verificationDocumentBackVariants
instance Data.Aeson.ToJSON Issuing_cardholder_verificationDocumentBackVariants
data Issuing_cardholder_verificationDocumentFrontVariants
instance Show Issuing_cardholder_verificationDocumentFrontVariants
instance Eq Issuing_cardholder_verificationDocumentFrontVariants
instance Data.Aeson.FromJSON Issuing_cardholder_verificationDocumentFrontVariants
instance Data.Aeson.ToJSON Issuing_cardholder_verificationDocumentFrontVariants
