module Stripe.CustomerSession.Types.Issuing_Card where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing'card
instance Show Issuing'card
instance Eq Issuing'card
instance Data.Aeson.FromJSON Issuing'card
instance Data.Aeson.ToJSON Issuing'card
data Issuing'cardLatest_fraud_warning
instance Show Issuing'cardLatest_fraud_warning
instance Eq Issuing'cardLatest_fraud_warning
instance Data.Aeson.FromJSON Issuing'cardLatest_fraud_warning
instance Data.Aeson.ToJSON Issuing'cardLatest_fraud_warning
data Issuing'cardLifecycle_controls
instance Show Issuing'cardLifecycle_controls
instance Eq Issuing'cardLifecycle_controls
instance Data.Aeson.FromJSON Issuing'cardLifecycle_controls
instance Data.Aeson.ToJSON Issuing'cardLifecycle_controls
data Issuing'cardPersonalization_designVariants
instance Show Issuing'cardPersonalization_designVariants
instance Eq Issuing'cardPersonalization_designVariants
instance Data.Aeson.FromJSON Issuing'cardPersonalization_designVariants
instance Data.Aeson.ToJSON Issuing'cardPersonalization_designVariants
data Issuing'cardReplaced_byVariants
instance Show Issuing'cardReplaced_byVariants
instance Eq Issuing'cardReplaced_byVariants
instance Data.Aeson.FromJSON Issuing'cardReplaced_byVariants
instance Data.Aeson.ToJSON Issuing'cardReplaced_byVariants
data Issuing'cardReplacement_forVariants
instance Show Issuing'cardReplacement_forVariants
instance Eq Issuing'cardReplacement_forVariants
instance Data.Aeson.FromJSON Issuing'cardReplacement_forVariants
instance Data.Aeson.ToJSON Issuing'cardReplacement_forVariants
data Issuing'cardShipping
instance Show Issuing'cardShipping
instance Eq Issuing'cardShipping
instance Data.Aeson.FromJSON Issuing'cardShipping
instance Data.Aeson.ToJSON Issuing'cardShipping
data Issuing'cardShippingAddress_validation
instance Show Issuing'cardShippingAddress_validation
instance Eq Issuing'cardShippingAddress_validation
instance Data.Aeson.FromJSON Issuing'cardShippingAddress_validation
instance Data.Aeson.ToJSON Issuing'cardShippingAddress_validation
data Issuing'cardShippingAddress_validationNormalized_address
instance Show Issuing'cardShippingAddress_validationNormalized_address
instance Eq Issuing'cardShippingAddress_validationNormalized_address
instance Data.Aeson.FromJSON Issuing'cardShippingAddress_validationNormalized_address
instance Data.Aeson.ToJSON Issuing'cardShippingAddress_validationNormalized_address
data Issuing'cardShippingCustoms
instance Show Issuing'cardShippingCustoms
instance Eq Issuing'cardShippingCustoms
instance Data.Aeson.FromJSON Issuing'cardShippingCustoms
instance Data.Aeson.ToJSON Issuing'cardShippingCustoms
data Issuing'cardWallets
instance Show Issuing'cardWallets
instance Eq Issuing'cardWallets
instance Data.Aeson.FromJSON Issuing'cardWallets
instance Data.Aeson.ToJSON Issuing'cardWallets
