module Stripe.CustomerSession.Types.IssuingDisputeOtherEvidence where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_dispute_other_evidence
instance Show Issuing_dispute_other_evidence
instance Eq Issuing_dispute_other_evidence
instance Data.Aeson.FromJSON Issuing_dispute_other_evidence
instance Data.Aeson.ToJSON Issuing_dispute_other_evidence
data Issuing_dispute_other_evidenceAdditional_documentationVariants
instance Show Issuing_dispute_other_evidenceAdditional_documentationVariants
instance Eq Issuing_dispute_other_evidenceAdditional_documentationVariants
instance Data.Aeson.FromJSON Issuing_dispute_other_evidenceAdditional_documentationVariants
instance Data.Aeson.ToJSON Issuing_dispute_other_evidenceAdditional_documentationVariants
