module Stripe.CustomerSession.Types.IssuingCardShipping where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_card_shipping
instance Show Issuing_card_shipping
instance Eq Issuing_card_shipping
instance Data.Aeson.FromJSON Issuing_card_shipping
instance Data.Aeson.ToJSON Issuing_card_shipping
data Issuing_card_shippingAddress_validation
instance Show Issuing_card_shippingAddress_validation
instance Eq Issuing_card_shippingAddress_validation
instance Data.Aeson.FromJSON Issuing_card_shippingAddress_validation
instance Data.Aeson.ToJSON Issuing_card_shippingAddress_validation
data Issuing_card_shippingAddress_validationNormalized_address
instance Show Issuing_card_shippingAddress_validationNormalized_address
instance Eq Issuing_card_shippingAddress_validationNormalized_address
instance Data.Aeson.FromJSON Issuing_card_shippingAddress_validationNormalized_address
instance Data.Aeson.ToJSON Issuing_card_shippingAddress_validationNormalized_address
data Issuing_card_shippingCustoms
instance Show Issuing_card_shippingCustoms
instance Eq Issuing_card_shippingCustoms
instance Data.Aeson.FromJSON Issuing_card_shippingCustoms
instance Data.Aeson.ToJSON Issuing_card_shippingCustoms
