module Stripe.CustomerSession.Types.IssuingPhysicalBundleFeatures where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_physical_bundle_features
instance Show Issuing_physical_bundle_features
instance Eq Issuing_physical_bundle_features
instance Data.Aeson.FromJSON Issuing_physical_bundle_features
instance Data.Aeson.ToJSON Issuing_physical_bundle_features
