module Stripe.CustomerSession.Types.IssuingCardholderRequirements where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_cardholder_requirements
instance Show Issuing_cardholder_requirements
instance Eq Issuing_cardholder_requirements
instance Data.Aeson.FromJSON Issuing_cardholder_requirements
instance Data.Aeson.ToJSON Issuing_cardholder_requirements
