-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema Issuing_Cardholder
module Stripe.CustomerSession.Types.Issuing_Cardholder where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias
import {-# SOURCE #-} Stripe.CustomerSession.Types.File
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingCardholderAddress
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingCardholderAuthorizationControls
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingCardholderCardIssuing
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingCardholderCompany
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingCardholderIdDocument
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingCardholderIndividual
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingCardholderIndividualDob
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingCardholderRequirements
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingCardholderSpendingLimit
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingCardholderUserTermsAcceptance
import {-# SOURCE #-} Stripe.CustomerSession.Types.IssuingCardholderVerification

-- | Defines the object schema located at @components.schemas.issuing.cardholder@ in the specification.
-- 
-- An Issuing \`Cardholder\` object represents an individual or business entity who is [issued](https:\/\/docs.stripe.com\/issuing) cards.
-- 
-- Related guide: [How to create a cardholder](https:\/\/docs.stripe.com\/issuing\/cards\/virtual\/issue-cards\#create-cardholder)
data Issuing'cardholder = Issuing'cardholder {
  -- | billing: 
  issuing'cardholderBilling :: Issuing_cardholder_address
  -- | company: Additional information about a \`company\` cardholder.
  , issuing'cardholderCompany :: (GHC.Maybe.Maybe Issuing'cardholderCompany)
  -- | created: Time at which the object was created. Measured in seconds since the Unix epoch.
  , issuing'cardholderCreated :: GHC.Types.Int
  -- | email: The cardholder\'s email address.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , issuing'cardholderEmail :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | id: Unique identifier for the object.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , issuing'cardholderId :: Data.Text.Internal.Text
  -- | individual: Additional information about an \`individual\` cardholder.
  , issuing'cardholderIndividual :: (GHC.Maybe.Maybe Issuing'cardholderIndividual)
  -- | livemode: If the object exists in live mode, the value is \`true\`. If the object exists in test mode, the value is \`false\`.
  , issuing'cardholderLivemode :: GHC.Types.Bool
  -- | metadata: Set of [key-value pairs](https:\/\/docs.stripe.com\/api\/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
  , issuing'cardholderMetadata :: Data.Aeson.Types.Internal.Object
  -- | name: The cardholder\'s name. This will be printed on cards issued to them.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , issuing'cardholderName :: Data.Text.Internal.Text
  -- | object: String representing the object\'s type. Objects of the same type share the same value.
  , issuing'cardholderObject :: Data.Text.Internal.Text
  -- | phone_number: The cardholder\'s phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https:\/\/docs.stripe.com\/issuing\/3d-secure\#when-is-3d-secure-applied) for more details.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , issuing'cardholderPhone_number :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | preferred_locales: The cardholder’s preferred locales (languages), ordered by preference. Locales can be \`da\`, \`de\`, \`en\`, \`es\`, \`fr\`, \`it\`, \`pl\`, or \`sv\`.
  --  This changes the language of the [3D Secure flow](https:\/\/docs.stripe.com\/issuing\/3d-secure) and one-time password messages sent to the cardholder.
  , issuing'cardholderPreferred_locales :: (GHC.Maybe.Maybe [Data.Text.Internal.Text])
  -- | requirements: 
  , issuing'cardholderRequirements :: Issuing_cardholder_requirements
  -- | spending_controls: Rules that control spending across this cardholder\'s cards. Refer to our [documentation](https:\/\/docs.stripe.com\/issuing\/controls\/spending-controls) for more details.
  , issuing'cardholderSpending_controls :: (GHC.Maybe.Maybe Issuing'cardholderSpending_controls)
  -- | status: Specifies whether to permit authorizations on this cardholder\'s cards.
  , issuing'cardholderStatus :: Data.Text.Internal.Text
  -- | type: One of \`individual\` or \`company\`. See [Choose a cardholder type](https:\/\/docs.stripe.com\/issuing\/other\/choose-cardholder) for more details.
  , issuing'cardholderType :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing'cardholder
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (["billing" Data.Aeson.Types.ToJSON..= issuing'cardholderBilling obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("company" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderCompany obj) : ["created" Data.Aeson.Types.ToJSON..= issuing'cardholderCreated obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("email" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderEmail obj) : ["id" Data.Aeson.Types.ToJSON..= issuing'cardholderId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("individual" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividual obj) : ["livemode" Data.Aeson.Types.ToJSON..= issuing'cardholderLivemode obj] : ["metadata" Data.Aeson.Types.ToJSON..= issuing'cardholderMetadata obj] : ["name" Data.Aeson.Types.ToJSON..= issuing'cardholderName obj] : ["object" Data.Aeson.Types.ToJSON..= issuing'cardholderObject obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("phone_number" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderPhone_number obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("preferred_locales" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderPreferred_locales obj) : ["requirements" Data.Aeson.Types.ToJSON..= issuing'cardholderRequirements obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("spending_controls" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controls obj) : ["status" Data.Aeson.Types.ToJSON..= issuing'cardholderStatus obj] : ["type" Data.Aeson.Types.ToJSON..= issuing'cardholderType obj] : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (["billing" Data.Aeson.Types.ToJSON..= issuing'cardholderBilling obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("company" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderCompany obj) : ["created" Data.Aeson.Types.ToJSON..= issuing'cardholderCreated obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("email" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderEmail obj) : ["id" Data.Aeson.Types.ToJSON..= issuing'cardholderId obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("individual" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividual obj) : ["livemode" Data.Aeson.Types.ToJSON..= issuing'cardholderLivemode obj] : ["metadata" Data.Aeson.Types.ToJSON..= issuing'cardholderMetadata obj] : ["name" Data.Aeson.Types.ToJSON..= issuing'cardholderName obj] : ["object" Data.Aeson.Types.ToJSON..= issuing'cardholderObject obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("phone_number" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderPhone_number obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("preferred_locales" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderPreferred_locales obj) : ["requirements" Data.Aeson.Types.ToJSON..= issuing'cardholderRequirements obj] : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("spending_controls" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controls obj) : ["status" Data.Aeson.Types.ToJSON..= issuing'cardholderStatus obj] : ["type" Data.Aeson.Types.ToJSON..= issuing'cardholderType obj] : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing'cardholder
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing'cardholder" (\obj -> (((((((((((((((GHC.Base.pure Issuing'cardholder GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "billing")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "company")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "created")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "email")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "id")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "individual")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "livemode")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "metadata")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "object")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "phone_number")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "preferred_locales")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "requirements")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "spending_controls")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "status")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "type"))}
-- | Create a new 'Issuing'cardholder' with all required fields.
mkIssuing'cardholder :: Issuing_cardholder_address -- ^ 'issuing'cardholderBilling'
  -> GHC.Types.Int -- ^ 'issuing'cardholderCreated'
  -> Data.Text.Internal.Text -- ^ 'issuing'cardholderId'
  -> GHC.Types.Bool -- ^ 'issuing'cardholderLivemode'
  -> Data.Aeson.Types.Internal.Object -- ^ 'issuing'cardholderMetadata'
  -> Data.Text.Internal.Text -- ^ 'issuing'cardholderName'
  -> Data.Text.Internal.Text -- ^ 'issuing'cardholderObject'
  -> Issuing_cardholder_requirements -- ^ 'issuing'cardholderRequirements'
  -> Data.Text.Internal.Text -- ^ 'issuing'cardholderStatus'
  -> Data.Text.Internal.Text -- ^ 'issuing'cardholderType'
  -> Issuing'cardholder
mkIssuing'cardholder issuing'cardholderBilling issuing'cardholderCreated issuing'cardholderId issuing'cardholderLivemode issuing'cardholderMetadata issuing'cardholderName issuing'cardholderObject issuing'cardholderRequirements issuing'cardholderStatus issuing'cardholderType = Issuing'cardholder{issuing'cardholderBilling = issuing'cardholderBilling,
                                                                                                                                                                                                                                                                                                        issuing'cardholderCompany = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                                        issuing'cardholderCreated = issuing'cardholderCreated,
                                                                                                                                                                                                                                                                                                        issuing'cardholderEmail = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                                        issuing'cardholderId = issuing'cardholderId,
                                                                                                                                                                                                                                                                                                        issuing'cardholderIndividual = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                                        issuing'cardholderLivemode = issuing'cardholderLivemode,
                                                                                                                                                                                                                                                                                                        issuing'cardholderMetadata = issuing'cardholderMetadata,
                                                                                                                                                                                                                                                                                                        issuing'cardholderName = issuing'cardholderName,
                                                                                                                                                                                                                                                                                                        issuing'cardholderObject = issuing'cardholderObject,
                                                                                                                                                                                                                                                                                                        issuing'cardholderPhone_number = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                                        issuing'cardholderPreferred_locales = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                                        issuing'cardholderRequirements = issuing'cardholderRequirements,
                                                                                                                                                                                                                                                                                                        issuing'cardholderSpending_controls = GHC.Maybe.Nothing,
                                                                                                                                                                                                                                                                                                        issuing'cardholderStatus = issuing'cardholderStatus,
                                                                                                                                                                                                                                                                                                        issuing'cardholderType = issuing'cardholderType}
-- | Defines the object schema located at @components.schemas.issuing.cardholder.properties.company.anyOf@ in the specification.
-- 
-- Additional information about a \\\`company\\\` cardholder.
data Issuing'cardholderCompany = Issuing'cardholderCompany {
  -- | tax_id_provided: Whether the company\'s business ID number was provided.
  issuing'cardholderCompanyTax_id_provided :: (GHC.Maybe.Maybe GHC.Types.Bool)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing'cardholderCompany
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("tax_id_provided" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderCompanyTax_id_provided obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("tax_id_provided" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderCompanyTax_id_provided obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing'cardholderCompany
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing'cardholderCompany" (\obj -> GHC.Base.pure Issuing'cardholderCompany GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "tax_id_provided"))}
-- | Create a new 'Issuing'cardholderCompany' with all required fields.
mkIssuing'cardholderCompany :: Issuing'cardholderCompany
mkIssuing'cardholderCompany = Issuing'cardholderCompany{issuing'cardholderCompanyTax_id_provided = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.issuing.cardholder.properties.individual.anyOf@ in the specification.
-- 
-- Additional information about an \\\`individual\\\` cardholder.
data Issuing'cardholderIndividual = Issuing'cardholderIndividual {
  -- | card_issuing: Information related to the card_issuing program for this cardholder.
  issuing'cardholderIndividualCard_issuing :: (GHC.Maybe.Maybe Issuing'cardholderIndividualCard_issuing)
  -- | dob: The date of birth of this cardholder.
  , issuing'cardholderIndividualDob :: (GHC.Maybe.Maybe Issuing'cardholderIndividualDob)
  -- | first_name: The first name of this cardholder. Required before activating Cards. This field cannot contain any numbers, special characters (except periods, commas, hyphens, spaces and apostrophes) or non-latin letters.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , issuing'cardholderIndividualFirst_name :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | last_name: The last name of this cardholder. Required before activating Cards. This field cannot contain any numbers, special characters (except periods, commas, hyphens, spaces and apostrophes) or non-latin letters.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , issuing'cardholderIndividualLast_name :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | verification: Government-issued ID document for this cardholder.
  , issuing'cardholderIndividualVerification :: (GHC.Maybe.Maybe Issuing'cardholderIndividualVerification)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing'cardholderIndividual
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("card_issuing" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualCard_issuing obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("dob" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualDob obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("first_name" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualFirst_name obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("last_name" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualLast_name obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("verification" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualVerification obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("card_issuing" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualCard_issuing obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("dob" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualDob obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("first_name" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualFirst_name obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("last_name" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualLast_name obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("verification" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualVerification obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing'cardholderIndividual
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing'cardholderIndividual" (\obj -> ((((GHC.Base.pure Issuing'cardholderIndividual GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "card_issuing")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "dob")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "first_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "last_name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "verification"))}
-- | Create a new 'Issuing'cardholderIndividual' with all required fields.
mkIssuing'cardholderIndividual :: Issuing'cardholderIndividual
mkIssuing'cardholderIndividual = Issuing'cardholderIndividual{issuing'cardholderIndividualCard_issuing = GHC.Maybe.Nothing,
                                                              issuing'cardholderIndividualDob = GHC.Maybe.Nothing,
                                                              issuing'cardholderIndividualFirst_name = GHC.Maybe.Nothing,
                                                              issuing'cardholderIndividualLast_name = GHC.Maybe.Nothing,
                                                              issuing'cardholderIndividualVerification = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.issuing.cardholder.properties.individual.anyOf.properties.card_issuing.anyOf@ in the specification.
-- 
-- Information related to the card_issuing program for this cardholder.
data Issuing'cardholderIndividualCard_issuing = Issuing'cardholderIndividualCard_issuing {
  -- | user_terms_acceptance: Information about cardholder acceptance of Celtic [Authorized User Terms](https:\/\/stripe.com\/docs\/issuing\/cards\#accept-authorized-user-terms). Required for cards backed by a Celtic program.
  issuing'cardholderIndividualCard_issuingUser_terms_acceptance :: (GHC.Maybe.Maybe Issuing'cardholderIndividualCard_issuingUser_terms_acceptance)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing'cardholderIndividualCard_issuing
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("user_terms_acceptance" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualCard_issuingUser_terms_acceptance obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("user_terms_acceptance" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualCard_issuingUser_terms_acceptance obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing'cardholderIndividualCard_issuing
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing'cardholderIndividualCard_issuing" (\obj -> GHC.Base.pure Issuing'cardholderIndividualCard_issuing GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "user_terms_acceptance"))}
-- | Create a new 'Issuing'cardholderIndividualCard_issuing' with all required fields.
mkIssuing'cardholderIndividualCard_issuing :: Issuing'cardholderIndividualCard_issuing
mkIssuing'cardholderIndividualCard_issuing = Issuing'cardholderIndividualCard_issuing{issuing'cardholderIndividualCard_issuingUser_terms_acceptance = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.issuing.cardholder.properties.individual.anyOf.properties.card_issuing.anyOf.properties.user_terms_acceptance.anyOf@ in the specification.
-- 
-- Information about cardholder acceptance of Celtic [Authorized User Terms](https:\\\/\\\/stripe.com\\\/docs\\\/issuing\\\/cards\\\#accept-authorized-user-terms). Required for cards backed by a Celtic program.
data Issuing'cardholderIndividualCard_issuingUser_terms_acceptance = Issuing'cardholderIndividualCard_issuingUser_terms_acceptance {
  -- | date: The Unix timestamp marking when the cardholder accepted the Authorized User Terms.
  issuing'cardholderIndividualCard_issuingUser_terms_acceptanceDate :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | ip: The IP address from which the cardholder accepted the Authorized User Terms.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , issuing'cardholderIndividualCard_issuingUser_terms_acceptanceIp :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | user_agent: The user agent of the browser from which the cardholder accepted the Authorized User Terms.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , issuing'cardholderIndividualCard_issuingUser_terms_acceptanceUser_agent :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing'cardholderIndividualCard_issuingUser_terms_acceptance
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("date" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualCard_issuingUser_terms_acceptanceDate obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("ip" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualCard_issuingUser_terms_acceptanceIp obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("user_agent" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualCard_issuingUser_terms_acceptanceUser_agent obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("date" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualCard_issuingUser_terms_acceptanceDate obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("ip" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualCard_issuingUser_terms_acceptanceIp obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("user_agent" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualCard_issuingUser_terms_acceptanceUser_agent obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing'cardholderIndividualCard_issuingUser_terms_acceptance
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing'cardholderIndividualCard_issuingUser_terms_acceptance" (\obj -> ((GHC.Base.pure Issuing'cardholderIndividualCard_issuingUser_terms_acceptance GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "date")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "ip")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "user_agent"))}
-- | Create a new 'Issuing'cardholderIndividualCard_issuingUser_terms_acceptance' with all required fields.
mkIssuing'cardholderIndividualCard_issuingUser_terms_acceptance :: Issuing'cardholderIndividualCard_issuingUser_terms_acceptance
mkIssuing'cardholderIndividualCard_issuingUser_terms_acceptance = Issuing'cardholderIndividualCard_issuingUser_terms_acceptance{issuing'cardholderIndividualCard_issuingUser_terms_acceptanceDate = GHC.Maybe.Nothing,
                                                                                                                                issuing'cardholderIndividualCard_issuingUser_terms_acceptanceIp = GHC.Maybe.Nothing,
                                                                                                                                issuing'cardholderIndividualCard_issuingUser_terms_acceptanceUser_agent = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.issuing.cardholder.properties.individual.anyOf.properties.dob.anyOf@ in the specification.
-- 
-- The date of birth of this cardholder.
data Issuing'cardholderIndividualDob = Issuing'cardholderIndividualDob {
  -- | day: The day of birth, between 1 and 31.
  issuing'cardholderIndividualDobDay :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | month: The month of birth, between 1 and 12.
  , issuing'cardholderIndividualDobMonth :: (GHC.Maybe.Maybe GHC.Types.Int)
  -- | year: The four-digit year of birth.
  , issuing'cardholderIndividualDobYear :: (GHC.Maybe.Maybe GHC.Types.Int)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing'cardholderIndividualDob
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("day" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualDobDay obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("month" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualDobMonth obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("year" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualDobYear obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("day" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualDobDay obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("month" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualDobMonth obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("year" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualDobYear obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing'cardholderIndividualDob
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing'cardholderIndividualDob" (\obj -> ((GHC.Base.pure Issuing'cardholderIndividualDob GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "day")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "month")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "year"))}
-- | Create a new 'Issuing'cardholderIndividualDob' with all required fields.
mkIssuing'cardholderIndividualDob :: Issuing'cardholderIndividualDob
mkIssuing'cardholderIndividualDob = Issuing'cardholderIndividualDob{issuing'cardholderIndividualDobDay = GHC.Maybe.Nothing,
                                                                    issuing'cardholderIndividualDobMonth = GHC.Maybe.Nothing,
                                                                    issuing'cardholderIndividualDobYear = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.issuing.cardholder.properties.individual.anyOf.properties.verification.anyOf@ in the specification.
-- 
-- Government-issued ID document for this cardholder.
data Issuing'cardholderIndividualVerification = Issuing'cardholderIndividualVerification {
  -- | document: An identifying document, either a passport or local ID card.
  issuing'cardholderIndividualVerificationDocument :: (GHC.Maybe.Maybe Issuing'cardholderIndividualVerificationDocument)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing'cardholderIndividualVerification
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("document" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualVerificationDocument obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("document" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualVerificationDocument obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing'cardholderIndividualVerification
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing'cardholderIndividualVerification" (\obj -> GHC.Base.pure Issuing'cardholderIndividualVerification GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "document"))}
-- | Create a new 'Issuing'cardholderIndividualVerification' with all required fields.
mkIssuing'cardholderIndividualVerification :: Issuing'cardholderIndividualVerification
mkIssuing'cardholderIndividualVerification = Issuing'cardholderIndividualVerification{issuing'cardholderIndividualVerificationDocument = GHC.Maybe.Nothing}
-- | Defines the object schema located at @components.schemas.issuing.cardholder.properties.individual.anyOf.properties.verification.anyOf.properties.document.anyOf@ in the specification.
-- 
-- An identifying document, either a passport or local ID card.
data Issuing'cardholderIndividualVerificationDocument = Issuing'cardholderIndividualVerificationDocument {
  -- | back: The back of a document returned by a [file upload](https:\/\/api.stripe.com\#create_file) with a \`purpose\` value of \`identity_document\`.
  issuing'cardholderIndividualVerificationDocumentBack :: (GHC.Maybe.Maybe Issuing'cardholderIndividualVerificationDocumentBackVariants)
  -- | front: The front of a document returned by a [file upload](https:\/\/api.stripe.com\#create_file) with a \`purpose\` value of \`identity_document\`.
  , issuing'cardholderIndividualVerificationDocumentFront :: (GHC.Maybe.Maybe Issuing'cardholderIndividualVerificationDocumentFrontVariants)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing'cardholderIndividualVerificationDocument
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("back" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualVerificationDocumentBack obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("front" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualVerificationDocumentFront obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("back" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualVerificationDocumentBack obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("front" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderIndividualVerificationDocumentFront obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing'cardholderIndividualVerificationDocument
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing'cardholderIndividualVerificationDocument" (\obj -> (GHC.Base.pure Issuing'cardholderIndividualVerificationDocument GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "back")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "front"))}
-- | Create a new 'Issuing'cardholderIndividualVerificationDocument' with all required fields.
mkIssuing'cardholderIndividualVerificationDocument :: Issuing'cardholderIndividualVerificationDocument
mkIssuing'cardholderIndividualVerificationDocument = Issuing'cardholderIndividualVerificationDocument{issuing'cardholderIndividualVerificationDocumentBack = GHC.Maybe.Nothing,
                                                                                                      issuing'cardholderIndividualVerificationDocumentFront = GHC.Maybe.Nothing}
-- | Defines the oneOf schema located at @components.schemas.issuing.cardholder.properties.individual.anyOf.properties.verification.anyOf.properties.document.anyOf.properties.back.anyOf@ in the specification.
-- 
-- The back of a document returned by a [file upload](https:\/\/api.stripe.com\#create_file) with a \`purpose\` value of \`identity_document\`.
data Issuing'cardholderIndividualVerificationDocumentBackVariants =
   Issuing'cardholderIndividualVerificationDocumentBackText Data.Text.Internal.Text
  | Issuing'cardholderIndividualVerificationDocumentBackFile File
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing'cardholderIndividualVerificationDocumentBackVariants
    where {toJSON (Issuing'cardholderIndividualVerificationDocumentBackText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Issuing'cardholderIndividualVerificationDocumentBackFile a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing'cardholderIndividualVerificationDocumentBackVariants
    where {parseJSON val = case (Issuing'cardholderIndividualVerificationDocumentBackText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((Issuing'cardholderIndividualVerificationDocumentBackFile Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the oneOf schema located at @components.schemas.issuing.cardholder.properties.individual.anyOf.properties.verification.anyOf.properties.document.anyOf.properties.front.anyOf@ in the specification.
-- 
-- The front of a document returned by a [file upload](https:\/\/api.stripe.com\#create_file) with a \`purpose\` value of \`identity_document\`.
data Issuing'cardholderIndividualVerificationDocumentFrontVariants =
   Issuing'cardholderIndividualVerificationDocumentFrontText Data.Text.Internal.Text
  | Issuing'cardholderIndividualVerificationDocumentFrontFile File
  deriving (GHC.Show.Show, GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing'cardholderIndividualVerificationDocumentFrontVariants
    where {toJSON (Issuing'cardholderIndividualVerificationDocumentFrontText a) = Data.Aeson.Types.ToJSON.toJSON a;
           toJSON (Issuing'cardholderIndividualVerificationDocumentFrontFile a) = Data.Aeson.Types.ToJSON.toJSON a}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing'cardholderIndividualVerificationDocumentFrontVariants
    where {parseJSON val = case (Issuing'cardholderIndividualVerificationDocumentFrontText Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> ((Issuing'cardholderIndividualVerificationDocumentFrontFile Data.Functor.<$> Data.Aeson.Types.FromJSON.fromJSON val) GHC.Base.<|> Data.Aeson.Types.Internal.Error "No variant matched") of
                           {Data.Aeson.Types.Internal.Success a -> GHC.Base.pure a;
                            Data.Aeson.Types.Internal.Error a -> Control.Monad.Fail.fail a}}
-- | Defines the object schema located at @components.schemas.issuing.cardholder.properties.spending_controls.anyOf@ in the specification.
-- 
-- Rules that control spending across this cardholder\\\'s cards. Refer to our [documentation](https:\\\/\\\/docs.stripe.com\\\/issuing\\\/controls\\\/spending-controls) for more details.
data Issuing'cardholderSpending_controls = Issuing'cardholderSpending_controls {
  -- | allowed_categories: Array of strings containing [categories](https:\/\/docs.stripe.com\/api\#issuing_authorization_object-merchant_data-category) of authorizations to allow. All other categories will be blocked. Cannot be set with \`blocked_categories\`.
  issuing'cardholderSpending_controlsAllowed_categories :: (GHC.Maybe.Maybe [Data.Text.Internal.Text])
  -- | allowed_merchant_countries: Array of strings containing representing countries from which authorizations will be allowed. Authorizations from merchants in all other countries will be declined. Country codes should be ISO 3166 alpha-2 country codes (e.g. \`US\`). Cannot be set with \`blocked_merchant_countries\`. Provide an empty value to unset this control.
  , issuing'cardholderSpending_controlsAllowed_merchant_countries :: (GHC.Maybe.Maybe [Data.Text.Internal.Text])
  -- | blocked_categories: Array of strings containing [categories](https:\/\/docs.stripe.com\/api\#issuing_authorization_object-merchant_data-category) of authorizations to decline. All other categories will be allowed. Cannot be set with \`allowed_categories\`.
  , issuing'cardholderSpending_controlsBlocked_categories :: (GHC.Maybe.Maybe [Data.Text.Internal.Text])
  -- | blocked_merchant_countries: Array of strings containing representing countries from which authorizations will be declined. Country codes should be ISO 3166 alpha-2 country codes (e.g. \`US\`). Cannot be set with \`allowed_merchant_countries\`. Provide an empty value to unset this control.
  , issuing'cardholderSpending_controlsBlocked_merchant_countries :: (GHC.Maybe.Maybe [Data.Text.Internal.Text])
  -- | spending_limits: Limit spending with amount-based rules that apply across this cardholder\'s cards.
  , issuing'cardholderSpending_controlsSpending_limits :: (GHC.Maybe.Maybe [Issuing_cardholder_spending_limit])
  -- | spending_limits_currency: Currency of the amounts within \`spending_limits\`.
  , issuing'cardholderSpending_controlsSpending_limits_currency :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Issuing'cardholderSpending_controls
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("allowed_categories" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsAllowed_categories obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("allowed_merchant_countries" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsAllowed_merchant_countries obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("blocked_categories" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsBlocked_categories obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("blocked_merchant_countries" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsBlocked_merchant_countries obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("spending_limits" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsSpending_limits obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("spending_limits_currency" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsSpending_limits_currency obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("allowed_categories" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsAllowed_categories obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("allowed_merchant_countries" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsAllowed_merchant_countries obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("blocked_categories" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsBlocked_categories obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("blocked_merchant_countries" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsBlocked_merchant_countries obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("spending_limits" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsSpending_limits obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("spending_limits_currency" Data.Aeson.Types.ToJSON..=)) (issuing'cardholderSpending_controlsSpending_limits_currency obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Issuing'cardholderSpending_controls
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Issuing'cardholderSpending_controls" (\obj -> (((((GHC.Base.pure Issuing'cardholderSpending_controls GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "allowed_categories")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "allowed_merchant_countries")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "blocked_categories")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "blocked_merchant_countries")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "spending_limits")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "spending_limits_currency"))}
-- | Create a new 'Issuing'cardholderSpending_controls' with all required fields.
mkIssuing'cardholderSpending_controls :: Issuing'cardholderSpending_controls
mkIssuing'cardholderSpending_controls = Issuing'cardholderSpending_controls{issuing'cardholderSpending_controlsAllowed_categories = GHC.Maybe.Nothing,
                                                                            issuing'cardholderSpending_controlsAllowed_merchant_countries = GHC.Maybe.Nothing,
                                                                            issuing'cardholderSpending_controlsBlocked_categories = GHC.Maybe.Nothing,
                                                                            issuing'cardholderSpending_controlsBlocked_merchant_countries = GHC.Maybe.Nothing,
                                                                            issuing'cardholderSpending_controlsSpending_limits = GHC.Maybe.Nothing,
                                                                            issuing'cardholderSpending_controlsSpending_limits_currency = GHC.Maybe.Nothing}
