module Stripe.CustomerSession.Types.Issuing_PersonalizationDesign where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing'personalization_design
instance Show Issuing'personalization_design
instance Eq Issuing'personalization_design
instance Data.Aeson.FromJSON Issuing'personalization_design
instance Data.Aeson.ToJSON Issuing'personalization_design
data Issuing'personalization_designCard_logoVariants
instance Show Issuing'personalization_designCard_logoVariants
instance Eq Issuing'personalization_designCard_logoVariants
instance Data.Aeson.FromJSON Issuing'personalization_designCard_logoVariants
instance Data.Aeson.ToJSON Issuing'personalization_designCard_logoVariants
data Issuing'personalization_designCarrier_text
instance Show Issuing'personalization_designCarrier_text
instance Eq Issuing'personalization_designCarrier_text
instance Data.Aeson.FromJSON Issuing'personalization_designCarrier_text
instance Data.Aeson.ToJSON Issuing'personalization_designCarrier_text
data Issuing'personalization_designPhysical_bundleVariants
instance Show Issuing'personalization_designPhysical_bundleVariants
instance Eq Issuing'personalization_designPhysical_bundleVariants
instance Data.Aeson.FromJSON Issuing'personalization_designPhysical_bundleVariants
instance Data.Aeson.ToJSON Issuing'personalization_designPhysical_bundleVariants
