module Stripe.CustomerSession.Types.IssuingAuthorizationRequest where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_request
instance Show Issuing_authorization_request
instance Eq Issuing_authorization_request
instance Data.Aeson.FromJSON Issuing_authorization_request
instance Data.Aeson.ToJSON Issuing_authorization_request
data Issuing_authorization_requestAmount_details
instance Show Issuing_authorization_requestAmount_details
instance Eq Issuing_authorization_requestAmount_details
instance Data.Aeson.FromJSON Issuing_authorization_requestAmount_details
instance Data.Aeson.ToJSON Issuing_authorization_requestAmount_details
