module Stripe.CustomerSession.Types.IssuingNetworkTokenWalletProvider where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_network_token_wallet_provider
instance Show Issuing_network_token_wallet_provider
instance Eq Issuing_network_token_wallet_provider
instance Data.Aeson.FromJSON Issuing_network_token_wallet_provider
instance Data.Aeson.ToJSON Issuing_network_token_wallet_provider
