module Stripe.CustomerSession.Types.IssuingAuthorizationFleetCardholderPromptData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_authorization_fleet_cardholder_prompt_data
instance Show Issuing_authorization_fleet_cardholder_prompt_data
instance Eq Issuing_authorization_fleet_cardholder_prompt_data
instance Data.Aeson.FromJSON Issuing_authorization_fleet_cardholder_prompt_data
instance Data.Aeson.ToJSON Issuing_authorization_fleet_cardholder_prompt_data
