module Stripe.CustomerSession.Types.IssuingCardShippingAddressValidation where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Issuing_card_shipping_address_validation
instance Show Issuing_card_shipping_address_validation
instance Eq Issuing_card_shipping_address_validation
instance Data.Aeson.FromJSON Issuing_card_shipping_address_validation
instance Data.Aeson.ToJSON Issuing_card_shipping_address_validation
data Issuing_card_shipping_address_validationNormalized_address
instance Show Issuing_card_shipping_address_validationNormalized_address
instance Eq Issuing_card_shipping_address_validationNormalized_address
instance Data.Aeson.FromJSON Issuing_card_shipping_address_validationNormalized_address
instance Data.Aeson.ToJSON Issuing_card_shipping_address_validationNormalized_address
