module Stripe.CustomerSession.Types.LegalEntityCompany where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Legal_entity_company
instance Show Legal_entity_company
instance Eq Legal_entity_company
instance Data.Aeson.FromJSON Legal_entity_company
instance Data.Aeson.ToJSON Legal_entity_company
data Legal_entity_companyAddress_kana
instance Show Legal_entity_companyAddress_kana
instance Eq Legal_entity_companyAddress_kana
instance Data.Aeson.FromJSON Legal_entity_companyAddress_kana
instance Data.Aeson.ToJSON Legal_entity_companyAddress_kana
data Legal_entity_companyAddress_kanji
instance Show Legal_entity_companyAddress_kanji
instance Eq Legal_entity_companyAddress_kanji
instance Data.Aeson.FromJSON Legal_entity_companyAddress_kanji
instance Data.Aeson.ToJSON Legal_entity_companyAddress_kanji
data Legal_entity_companyDirectorship_declaration
instance Show Legal_entity_companyDirectorship_declaration
instance Eq Legal_entity_companyDirectorship_declaration
instance Data.Aeson.FromJSON Legal_entity_companyDirectorship_declaration
instance Data.Aeson.ToJSON Legal_entity_companyDirectorship_declaration
data Legal_entity_companyOwnership_declaration
instance Show Legal_entity_companyOwnership_declaration
instance Eq Legal_entity_companyOwnership_declaration
instance Data.Aeson.FromJSON Legal_entity_companyOwnership_declaration
instance Data.Aeson.ToJSON Legal_entity_companyOwnership_declaration
data Legal_entity_companyRepresentative_declaration
instance Show Legal_entity_companyRepresentative_declaration
instance Eq Legal_entity_companyRepresentative_declaration
instance Data.Aeson.FromJSON Legal_entity_companyRepresentative_declaration
instance Data.Aeson.ToJSON Legal_entity_companyRepresentative_declaration
data Legal_entity_companyVerification
instance Show Legal_entity_companyVerification
instance Eq Legal_entity_companyVerification
instance Data.Aeson.FromJSON Legal_entity_companyVerification
instance Data.Aeson.ToJSON Legal_entity_companyVerification
