module Stripe.CustomerSession.Types.LegalEntityCompanyVerificationDocument where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Legal_entity_company_verification_document
instance Show Legal_entity_company_verification_document
instance Eq Legal_entity_company_verification_document
instance Data.Aeson.FromJSON Legal_entity_company_verification_document
instance Data.Aeson.ToJSON Legal_entity_company_verification_document
data Legal_entity_company_verification_documentBackVariants
instance Show Legal_entity_company_verification_documentBackVariants
instance Eq Legal_entity_company_verification_documentBackVariants
instance Data.Aeson.FromJSON Legal_entity_company_verification_documentBackVariants
instance Data.Aeson.ToJSON Legal_entity_company_verification_documentBackVariants
data Legal_entity_company_verification_documentFrontVariants
instance Show Legal_entity_company_verification_documentFrontVariants
instance Eq Legal_entity_company_verification_documentFrontVariants
instance Data.Aeson.FromJSON Legal_entity_company_verification_documentFrontVariants
instance Data.Aeson.ToJSON Legal_entity_company_verification_documentFrontVariants
