module Stripe.CustomerSession.Types.LineItemsTaxAmount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Line_items_tax_amount
instance Show Line_items_tax_amount
instance Eq Line_items_tax_amount
instance Data.Aeson.FromJSON Line_items_tax_amount
instance Data.Aeson.ToJSON Line_items_tax_amount
