module Stripe.CustomerSession.Types.LineItem where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Line_item
instance Show Line_item
instance Eq Line_item
instance Data.Aeson.FromJSON Line_item
instance Data.Aeson.ToJSON Line_item
data Line_itemDiscountsVariants
instance Show Line_itemDiscountsVariants
instance Eq Line_itemDiscountsVariants
instance Data.Aeson.FromJSON Line_itemDiscountsVariants
instance Data.Aeson.ToJSON Line_itemDiscountsVariants
data Line_itemParent
instance Show Line_itemParent
instance Eq Line_itemParent
instance Data.Aeson.FromJSON Line_itemParent
instance Data.Aeson.ToJSON Line_itemParent
data Line_itemParentInvoice_item_details
instance Show Line_itemParentInvoice_item_details
instance Eq Line_itemParentInvoice_item_details
instance Data.Aeson.FromJSON Line_itemParentInvoice_item_details
instance Data.Aeson.ToJSON Line_itemParentInvoice_item_details
data Line_itemParentInvoice_item_detailsProration_details
instance Show Line_itemParentInvoice_item_detailsProration_details
instance Eq Line_itemParentInvoice_item_detailsProration_details
instance Data.Aeson.FromJSON Line_itemParentInvoice_item_detailsProration_details
instance Data.Aeson.ToJSON Line_itemParentInvoice_item_detailsProration_details
data Line_itemParentInvoice_item_detailsProration_detailsCredited_items
instance Show Line_itemParentInvoice_item_detailsProration_detailsCredited_items
instance Eq Line_itemParentInvoice_item_detailsProration_detailsCredited_items
instance Data.Aeson.FromJSON Line_itemParentInvoice_item_detailsProration_detailsCredited_items
instance Data.Aeson.ToJSON Line_itemParentInvoice_item_detailsProration_detailsCredited_items
data Line_itemParentSubscription_item_details
instance Show Line_itemParentSubscription_item_details
instance Eq Line_itemParentSubscription_item_details
instance Data.Aeson.FromJSON Line_itemParentSubscription_item_details
instance Data.Aeson.ToJSON Line_itemParentSubscription_item_details
data Line_itemParentSubscription_item_detailsProration_details
instance Show Line_itemParentSubscription_item_detailsProration_details
instance Eq Line_itemParentSubscription_item_detailsProration_details
instance Data.Aeson.FromJSON Line_itemParentSubscription_item_detailsProration_details
instance Data.Aeson.ToJSON Line_itemParentSubscription_item_detailsProration_details
data Line_itemParentSubscription_item_detailsProration_detailsCredited_items
instance Show Line_itemParentSubscription_item_detailsProration_detailsCredited_items
instance Eq Line_itemParentSubscription_item_detailsProration_detailsCredited_items
instance Data.Aeson.FromJSON Line_itemParentSubscription_item_detailsProration_detailsCredited_items
instance Data.Aeson.ToJSON Line_itemParentSubscription_item_detailsProration_detailsCredited_items
data Line_itemPricing
instance Show Line_itemPricing
instance Eq Line_itemPricing
instance Data.Aeson.FromJSON Line_itemPricing
instance Data.Aeson.ToJSON Line_itemPricing
data Line_itemSubscriptionVariants
instance Show Line_itemSubscriptionVariants
instance Eq Line_itemSubscriptionVariants
instance Data.Aeson.FromJSON Line_itemSubscriptionVariants
instance Data.Aeson.ToJSON Line_itemSubscriptionVariants
