module Stripe.CustomerSession.Types.LinkedAccountOptionsCommon where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Linked_account_options_common
instance Show Linked_account_options_common
instance Eq Linked_account_options_common
instance Data.Aeson.FromJSON Linked_account_options_common
instance Data.Aeson.ToJSON Linked_account_options_common
