module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordAfterpayClearpay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_afterpay_clearpay
instance Show Payment_method_details_payment_record_afterpay_clearpay
instance Eq Payment_method_details_payment_record_afterpay_clearpay
instance Data.Aeson.FromJSON Payment_method_details_payment_record_afterpay_clearpay
instance Data.Aeson.ToJSON Payment_method_details_payment_record_afterpay_clearpay
