module Stripe.CustomerSession.Types.PaymentMethodUsBankAccount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_us_bank_account
instance Show Payment_method_us_bank_account
instance Eq Payment_method_us_bank_account
instance Data.Aeson.FromJSON Payment_method_us_bank_account
instance Data.Aeson.ToJSON Payment_method_us_bank_account
data Payment_method_us_bank_accountNetworks
instance Show Payment_method_us_bank_accountNetworks
instance Eq Payment_method_us_bank_accountNetworks
instance Data.Aeson.FromJSON Payment_method_us_bank_accountNetworks
instance Data.Aeson.ToJSON Payment_method_us_bank_accountNetworks
data Payment_method_us_bank_accountStatus_details
instance Show Payment_method_us_bank_accountStatus_details
instance Eq Payment_method_us_bank_accountStatus_details
instance Data.Aeson.FromJSON Payment_method_us_bank_accountStatus_details
instance Data.Aeson.ToJSON Payment_method_us_bank_accountStatus_details
