module Stripe.CustomerSession.Types.PaymentIntentNextActionDisplayMultibancoDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_display_multibanco_details
instance Show Payment_intent_next_action_display_multibanco_details
instance Eq Payment_intent_next_action_display_multibanco_details
instance Data.Aeson.FromJSON Payment_intent_next_action_display_multibanco_details
instance Data.Aeson.ToJSON Payment_intent_next_action_display_multibanco_details
