module Stripe.CustomerSession.Types.PaymentMethodDetailsKonbini where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_konbini
instance Show Payment_method_details_konbini
instance Eq Payment_method_details_konbini
instance Data.Aeson.FromJSON Payment_method_details_konbini
instance Data.Aeson.ToJSON Payment_method_details_konbini
data Payment_method_details_konbiniStore
instance Show Payment_method_details_konbiniStore
instance Eq Payment_method_details_konbiniStore
instance Data.Aeson.FromJSON Payment_method_details_konbiniStore
instance Data.Aeson.ToJSON Payment_method_details_konbiniStore
