module Stripe.CustomerSession.Types.PaymentMethodDetailsPix where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_pix
instance Show Payment_method_details_pix
instance Eq Payment_method_details_pix
instance Data.Aeson.FromJSON Payment_method_details_pix
instance Data.Aeson.ToJSON Payment_method_details_pix
