module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourcePaymentMethodCardDetailsResourceInstallments where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payments_primitives_payment_records_resource_payment_method_card_details_resource_installments
instance Show Payments_primitives_payment_records_resource_payment_method_card_details_resource_installments
instance Eq Payments_primitives_payment_records_resource_payment_method_card_details_resource_installments
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_installments
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_installments
data Payments_primitives_payment_records_resource_payment_method_card_details_resource_installmentsPlan
instance Show Payments_primitives_payment_records_resource_payment_method_card_details_resource_installmentsPlan
instance Eq Payments_primitives_payment_records_resource_payment_method_card_details_resource_installmentsPlan
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_installmentsPlan
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_payment_method_card_details_resource_installmentsPlan
