module Stripe.CustomerSession.Types.PaymentMethodOptionsBancontact where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_bancontact
instance Show Payment_method_options_bancontact
instance Eq Payment_method_options_bancontact
instance Data.Aeson.FromJSON Payment_method_options_bancontact
instance Data.Aeson.ToJSON Payment_method_options_bancontact
