module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordBancontact where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_bancontact
instance Show Payment_method_details_payment_record_bancontact
instance Eq Payment_method_details_payment_record_bancontact
instance Data.Aeson.FromJSON Payment_method_details_payment_record_bancontact
instance Data.Aeson.ToJSON Payment_method_details_payment_record_bancontact
data Payment_method_details_payment_record_bancontactGenerated_sepa_debitVariants
instance Show Payment_method_details_payment_record_bancontactGenerated_sepa_debitVariants
instance Eq Payment_method_details_payment_record_bancontactGenerated_sepa_debitVariants
instance Data.Aeson.FromJSON Payment_method_details_payment_record_bancontactGenerated_sepa_debitVariants
instance Data.Aeson.ToJSON Payment_method_details_payment_record_bancontactGenerated_sepa_debitVariants
data Payment_method_details_payment_record_bancontactGenerated_sepa_debit_mandateVariants
instance Show Payment_method_details_payment_record_bancontactGenerated_sepa_debit_mandateVariants
instance Eq Payment_method_details_payment_record_bancontactGenerated_sepa_debit_mandateVariants
instance Data.Aeson.FromJSON Payment_method_details_payment_record_bancontactGenerated_sepa_debit_mandateVariants
instance Data.Aeson.ToJSON Payment_method_details_payment_record_bancontactGenerated_sepa_debit_mandateVariants
