module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordNaverPay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_naver_pay
instance Show Payment_method_details_payment_record_naver_pay
instance Eq Payment_method_details_payment_record_naver_pay
instance Data.Aeson.FromJSON Payment_method_details_payment_record_naver_pay
instance Data.Aeson.ToJSON Payment_method_details_payment_record_naver_pay
