module Stripe.CustomerSession.Types.PaymentMethodOptionsCardPresent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_card_present
instance Show Payment_method_options_card_present
instance Eq Payment_method_options_card_present
instance Data.Aeson.FromJSON Payment_method_options_card_present
instance Data.Aeson.ToJSON Payment_method_options_card_present
