module Stripe.CustomerSession.Types.PaymentMethodDetailsBillie where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_billie
instance Show Payment_method_details_billie
instance Eq Payment_method_details_billie
instance Data.Aeson.FromJSON Payment_method_details_billie
instance Data.Aeson.ToJSON Payment_method_details_billie
