module Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsPaycoPaymentMethodOptions where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_private_payment_methods_payco_payment_method_options
instance Show Payment_flows_private_payment_methods_payco_payment_method_options
instance Eq Payment_flows_private_payment_methods_payco_payment_method_options
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_payco_payment_method_options
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_payco_payment_method_options
