module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordPix where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_pix
instance Show Payment_method_details_payment_record_pix
instance Eq Payment_method_details_payment_record_pix
instance Data.Aeson.FromJSON Payment_method_details_payment_record_pix
instance Data.Aeson.ToJSON Payment_method_details_payment_record_pix
