module Stripe.CustomerSession.Types.PaymentMethodDetailsCardPresent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_card_present
instance Show Payment_method_details_card_present
instance Eq Payment_method_details_card_present
instance Data.Aeson.FromJSON Payment_method_details_card_present
instance Data.Aeson.ToJSON Payment_method_details_card_present
data Payment_method_details_card_presentOffline
instance Show Payment_method_details_card_presentOffline
instance Eq Payment_method_details_card_presentOffline
instance Data.Aeson.FromJSON Payment_method_details_card_presentOffline
instance Data.Aeson.ToJSON Payment_method_details_card_presentOffline
data Payment_method_details_card_presentReceipt
instance Show Payment_method_details_card_presentReceipt
instance Eq Payment_method_details_card_presentReceipt
instance Data.Aeson.FromJSON Payment_method_details_card_presentReceipt
instance Data.Aeson.ToJSON Payment_method_details_card_presentReceipt
