module Stripe.CustomerSession.Types.PaymentMethodDetailsOxxo where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_oxxo
instance Show Payment_method_details_oxxo
instance Eq Payment_method_details_oxxo
instance Data.Aeson.FromJSON Payment_method_details_oxxo
instance Data.Aeson.ToJSON Payment_method_details_oxxo
