module Stripe.CustomerSession.Types.PaymentMethodDetailsCardWalletMasterpass where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_card_wallet_masterpass
instance Show Payment_method_details_card_wallet_masterpass
instance Eq Payment_method_details_card_wallet_masterpass
instance Data.Aeson.FromJSON Payment_method_details_card_wallet_masterpass
instance Data.Aeson.ToJSON Payment_method_details_card_wallet_masterpass
data Payment_method_details_card_wallet_masterpassBilling_address
instance Show Payment_method_details_card_wallet_masterpassBilling_address
instance Eq Payment_method_details_card_wallet_masterpassBilling_address
instance Data.Aeson.FromJSON Payment_method_details_card_wallet_masterpassBilling_address
instance Data.Aeson.ToJSON Payment_method_details_card_wallet_masterpassBilling_address
data Payment_method_details_card_wallet_masterpassShipping_address
instance Show Payment_method_details_card_wallet_masterpassShipping_address
instance Eq Payment_method_details_card_wallet_masterpassShipping_address
instance Data.Aeson.FromJSON Payment_method_details_card_wallet_masterpassShipping_address
instance Data.Aeson.ToJSON Payment_method_details_card_wallet_masterpassShipping_address
