module Stripe.CustomerSession.Types.PaymentMethodDetailsPayco where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payco
instance Show Payment_method_details_payco
instance Eq Payment_method_details_payco
instance Data.Aeson.FromJSON Payment_method_details_payco
instance Data.Aeson.ToJSON Payment_method_details_payco
