module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordAffirm where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_affirm
instance Show Payment_method_details_payment_record_affirm
instance Eq Payment_method_details_payment_record_affirm
instance Data.Aeson.FromJSON Payment_method_details_payment_record_affirm
instance Data.Aeson.ToJSON Payment_method_details_payment_record_affirm
