module Stripe.CustomerSession.Types.PaymentMethodDetailsIdeal where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_ideal
instance Show Payment_method_details_ideal
instance Eq Payment_method_details_ideal
instance Data.Aeson.FromJSON Payment_method_details_ideal
instance Data.Aeson.ToJSON Payment_method_details_ideal
data Payment_method_details_idealGenerated_sepa_debitVariants
instance Show Payment_method_details_idealGenerated_sepa_debitVariants
instance Eq Payment_method_details_idealGenerated_sepa_debitVariants
instance Data.Aeson.FromJSON Payment_method_details_idealGenerated_sepa_debitVariants
instance Data.Aeson.ToJSON Payment_method_details_idealGenerated_sepa_debitVariants
data Payment_method_details_idealGenerated_sepa_debit_mandateVariants
instance Show Payment_method_details_idealGenerated_sepa_debit_mandateVariants
instance Eq Payment_method_details_idealGenerated_sepa_debit_mandateVariants
instance Data.Aeson.FromJSON Payment_method_details_idealGenerated_sepa_debit_mandateVariants
instance Data.Aeson.ToJSON Payment_method_details_idealGenerated_sepa_debit_mandateVariants
