module Stripe.CustomerSession.Types.PaymentMethodOptionsRevolutPay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_revolut_pay
instance Show Payment_method_options_revolut_pay
instance Eq Payment_method_options_revolut_pay
instance Data.Aeson.FromJSON Payment_method_options_revolut_pay
instance Data.Aeson.ToJSON Payment_method_options_revolut_pay
