module Stripe.CustomerSession.Types.PaymentMethodDetailsPaynow where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_paynow
instance Show Payment_method_details_paynow
instance Eq Payment_method_details_paynow
instance Data.Aeson.FromJSON Payment_method_details_paynow
instance Data.Aeson.ToJSON Payment_method_details_paynow
