module Stripe.CustomerSession.Types.PaymentMethodOptionsCardInstallments where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_card_installments
instance Show Payment_method_options_card_installments
instance Eq Payment_method_options_card_installments
instance Data.Aeson.FromJSON Payment_method_options_card_installments
instance Data.Aeson.ToJSON Payment_method_options_card_installments
data Payment_method_options_card_installmentsPlan
instance Show Payment_method_options_card_installmentsPlan
instance Eq Payment_method_options_card_installmentsPlan
instance Data.Aeson.FromJSON Payment_method_options_card_installmentsPlan
instance Data.Aeson.ToJSON Payment_method_options_card_installmentsPlan
