module Stripe.CustomerSession.Types.PaymentFlowsPaymentDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_payment_details
instance Show Payment_flows_payment_details
instance Eq Payment_flows_payment_details
instance Data.Aeson.FromJSON Payment_flows_payment_details
instance Data.Aeson.ToJSON Payment_flows_payment_details
