module Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsFinancialConnectionsCommonLinkedAccountOptionsFilters where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_private_payment_methods_financial_connections_common_linked_account_options_filters
instance Show Payment_flows_private_payment_methods_financial_connections_common_linked_account_options_filters
instance Eq Payment_flows_private_payment_methods_financial_connections_common_linked_account_options_filters
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_financial_connections_common_linked_account_options_filters
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_financial_connections_common_linked_account_options_filters
