module Stripe.CustomerSession.Types.PaymentMethodInteracPresent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_interac_present
instance Show Payment_method_interac_present
instance Eq Payment_method_interac_present
instance Data.Aeson.FromJSON Payment_method_interac_present
instance Data.Aeson.ToJSON Payment_method_interac_present
data Payment_method_interac_presentNetworks
instance Show Payment_method_interac_presentNetworks
instance Eq Payment_method_interac_presentNetworks
instance Data.Aeson.FromJSON Payment_method_interac_presentNetworks
instance Data.Aeson.ToJSON Payment_method_interac_presentNetworks
