module Stripe.CustomerSession.Types.PaymentMethodAcssDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_acss_debit
instance Show Payment_method_acss_debit
instance Eq Payment_method_acss_debit
instance Data.Aeson.FromJSON Payment_method_acss_debit
instance Data.Aeson.ToJSON Payment_method_acss_debit
