module Stripe.CustomerSession.Types.PaymentMethodDetailsCardInstallmentsPlan where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_card_installments_plan
instance Show Payment_method_details_card_installments_plan
instance Eq Payment_method_details_card_installments_plan
instance Data.Aeson.FromJSON Payment_method_details_card_installments_plan
instance Data.Aeson.ToJSON Payment_method_details_card_installments_plan
