module Stripe.CustomerSession.Types.PaymentMethodDetailsBancontact where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_bancontact
instance Show Payment_method_details_bancontact
instance Eq Payment_method_details_bancontact
instance Data.Aeson.FromJSON Payment_method_details_bancontact
instance Data.Aeson.ToJSON Payment_method_details_bancontact
data Payment_method_details_bancontactGenerated_sepa_debitVariants
instance Show Payment_method_details_bancontactGenerated_sepa_debitVariants
instance Eq Payment_method_details_bancontactGenerated_sepa_debitVariants
instance Data.Aeson.FromJSON Payment_method_details_bancontactGenerated_sepa_debitVariants
instance Data.Aeson.ToJSON Payment_method_details_bancontactGenerated_sepa_debitVariants
data Payment_method_details_bancontactGenerated_sepa_debit_mandateVariants
instance Show Payment_method_details_bancontactGenerated_sepa_debit_mandateVariants
instance Eq Payment_method_details_bancontactGenerated_sepa_debit_mandateVariants
instance Data.Aeson.FromJSON Payment_method_details_bancontactGenerated_sepa_debit_mandateVariants
instance Data.Aeson.ToJSON Payment_method_details_bancontactGenerated_sepa_debit_mandateVariants
