module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsAuBecsDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_au_becs_debit
instance Show Payment_intent_payment_method_options_au_becs_debit
instance Eq Payment_intent_payment_method_options_au_becs_debit
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_au_becs_debit
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_au_becs_debit
