module Stripe.CustomerSession.Types.PaymentMethodOptionsBoleto where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_options_boleto
instance Show Payment_method_options_boleto
instance Eq Payment_method_options_boleto
instance Data.Aeson.FromJSON Payment_method_options_boleto
instance Data.Aeson.ToJSON Payment_method_options_boleto
