module Stripe.CustomerSession.Types.PaymentMethodUsBankAccountBlocked where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_us_bank_account_blocked
instance Show Payment_method_us_bank_account_blocked
instance Eq Payment_method_us_bank_account_blocked
instance Data.Aeson.FromJSON Payment_method_us_bank_account_blocked
instance Data.Aeson.ToJSON Payment_method_us_bank_account_blocked
