module Stripe.CustomerSession.Types.PaymentMethod where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method
instance Show Payment_method
instance Eq Payment_method
instance Data.Aeson.FromJSON Payment_method
instance Data.Aeson.ToJSON Payment_method
data Payment_methodCustomerVariants
instance Show Payment_methodCustomerVariants
instance Eq Payment_methodCustomerVariants
instance Data.Aeson.FromJSON Payment_methodCustomerVariants
instance Data.Aeson.ToJSON Payment_methodCustomerVariants
