module Stripe.CustomerSession.Types.PaymentMethodCardPresent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_card_present
instance Show Payment_method_card_present
instance Eq Payment_method_card_present
instance Data.Aeson.FromJSON Payment_method_card_present
instance Data.Aeson.ToJSON Payment_method_card_present
data Payment_method_card_presentNetworks
instance Show Payment_method_card_presentNetworks
instance Eq Payment_method_card_presentNetworks
instance Data.Aeson.FromJSON Payment_method_card_presentNetworks
instance Data.Aeson.ToJSON Payment_method_card_presentNetworks
data Payment_method_card_presentOffline
instance Show Payment_method_card_presentOffline
instance Eq Payment_method_card_presentOffline
instance Data.Aeson.FromJSON Payment_method_card_presentOffline
instance Data.Aeson.ToJSON Payment_method_card_presentOffline
