module Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_private_payment_methods_card_present_common_wallet
instance Show Payment_flows_private_payment_methods_card_present_common_wallet
instance Eq Payment_flows_private_payment_methods_card_present_common_wallet
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_card_present_common_wallet
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_card_present_common_wallet
