module Stripe.CustomerSession.Types.PaymentMethodDetailsAffirm where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_affirm
instance Show Payment_method_details_affirm
instance Eq Payment_method_details_affirm
instance Data.Aeson.FromJSON Payment_method_details_affirm
instance Data.Aeson.ToJSON Payment_method_details_affirm
