module Stripe.CustomerSession.Types.PaymentIntentNextActionWechatPayRedirectToIosApp where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_wechat_pay_redirect_to_ios_app
instance Show Payment_intent_next_action_wechat_pay_redirect_to_ios_app
instance Eq Payment_intent_next_action_wechat_pay_redirect_to_ios_app
instance Data.Aeson.FromJSON Payment_intent_next_action_wechat_pay_redirect_to_ios_app
instance Data.Aeson.ToJSON Payment_intent_next_action_wechat_pay_redirect_to_ios_app
