module Stripe.CustomerSession.Types.PaymentIntentAmountDetailsLineItem where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_amount_details_line_item
instance Show Payment_intent_amount_details_line_item
instance Eq Payment_intent_amount_details_line_item
instance Data.Aeson.FromJSON Payment_intent_amount_details_line_item
instance Data.Aeson.ToJSON Payment_intent_amount_details_line_item
data Payment_intent_amount_details_line_itemPayment_method_options
instance Show Payment_intent_amount_details_line_itemPayment_method_options
instance Eq Payment_intent_amount_details_line_itemPayment_method_options
instance Data.Aeson.FromJSON Payment_intent_amount_details_line_itemPayment_method_options
instance Data.Aeson.ToJSON Payment_intent_amount_details_line_itemPayment_method_options
data Payment_intent_amount_details_line_itemTax
instance Show Payment_intent_amount_details_line_itemTax
instance Eq Payment_intent_amount_details_line_itemTax
instance Data.Aeson.FromJSON Payment_intent_amount_details_line_itemTax
instance Data.Aeson.ToJSON Payment_intent_amount_details_line_itemTax
