module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourceAddress where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payments_primitives_payment_records_resource_address
instance Show Payments_primitives_payment_records_resource_address
instance Eq Payments_primitives_payment_records_resource_address
instance Data.Aeson.FromJSON Payments_primitives_payment_records_resource_address
instance Data.Aeson.ToJSON Payments_primitives_payment_records_resource_address
