-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PaymentsPrimitivesPaymentRecordsResourceCustomerDetails
module Stripe.CustomerSession.Types.PaymentsPrimitivesPaymentRecordsResourceCustomerDetails where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Prelude as GHC.Internal.Maybe
import qualified Control.Monad.Fail
import qualified Control.Monad.Fail as GHC.Internal.Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString
import qualified Data.ByteString as Data.ByteString.Internal
import qualified Data.Foldable
import qualified Data.Foldable as GHC.Internal.Data.Foldable
import qualified Data.Functor
import qualified Data.Functor as GHC.Internal.Data.Functor
import qualified Data.Maybe
import qualified Data.Maybe as GHC.Internal.Data.Maybe
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text as Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Base as GHC.Internal.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Int as GHC.Internal.Int
import qualified GHC.Show
import qualified GHC.Show as GHC.Internal.Show
import qualified GHC.Types
import qualified Stripe.CustomerSession.Common
import Stripe.CustomerSession.TypeAlias

-- | Defines the object schema located at @components.schemas.payments_primitives_payment_records_resource_customer_details@ in the specification.
-- 
-- Information about the customer for this payment.
data Payments_primitives_payment_records_resource_customer_details = Payments_primitives_payment_records_resource_customer_details {
  -- | customer: ID of the Stripe Customer associated with this payment.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  payments_primitives_payment_records_resource_customer_detailsCustomer :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | email: The customer\'s email address.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , payments_primitives_payment_records_resource_customer_detailsEmail :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | name: The customer\'s name.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , payments_primitives_payment_records_resource_customer_detailsName :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | phone: The customer\'s phone number.
  -- 
  -- Constraints:
  -- 
  -- * Maximum length of 5000
  , payments_primitives_payment_records_resource_customer_detailsPhone :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON Payments_primitives_payment_records_resource_customer_details
    where {toJSON obj = Data.Aeson.Types.Internal.object (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("customer" Data.Aeson.Types.ToJSON..=)) (payments_primitives_payment_records_resource_customer_detailsCustomer obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("email" Data.Aeson.Types.ToJSON..=)) (payments_primitives_payment_records_resource_customer_detailsEmail obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (payments_primitives_payment_records_resource_customer_detailsName obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("phone" Data.Aeson.Types.ToJSON..=)) (payments_primitives_payment_records_resource_customer_detailsPhone obj) : GHC.Base.mempty));
           toEncoding obj = Data.Aeson.Encoding.Internal.pairs (GHC.Base.mconcat (Data.Foldable.concat (Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("customer" Data.Aeson.Types.ToJSON..=)) (payments_primitives_payment_records_resource_customer_detailsCustomer obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("email" Data.Aeson.Types.ToJSON..=)) (payments_primitives_payment_records_resource_customer_detailsEmail obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("name" Data.Aeson.Types.ToJSON..=)) (payments_primitives_payment_records_resource_customer_detailsName obj) : Data.Maybe.maybe GHC.Base.mempty (GHC.Base.pure GHC.Base.. ("phone" Data.Aeson.Types.ToJSON..=)) (payments_primitives_payment_records_resource_customer_detailsPhone obj) : GHC.Base.mempty)))}
instance Data.Aeson.Types.FromJSON.FromJSON Payments_primitives_payment_records_resource_customer_details
    where {parseJSON = Data.Aeson.Types.FromJSON.withObject "Payments_primitives_payment_records_resource_customer_details" (\obj -> (((GHC.Base.pure Payments_primitives_payment_records_resource_customer_details GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "customer")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "email")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "name")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..:! "phone"))}
-- | Create a new 'Payments_primitives_payment_records_resource_customer_details' with all required fields.
mkPayments_primitives_payment_records_resource_customer_details :: Payments_primitives_payment_records_resource_customer_details
mkPayments_primitives_payment_records_resource_customer_details = Payments_primitives_payment_records_resource_customer_details{payments_primitives_payment_records_resource_customer_detailsCustomer = GHC.Maybe.Nothing,
                                                                                                                                payments_primitives_payment_records_resource_customer_detailsEmail = GHC.Maybe.Nothing,
                                                                                                                                payments_primitives_payment_records_resource_customer_detailsName = GHC.Maybe.Nothing,
                                                                                                                                payments_primitives_payment_records_resource_customer_detailsPhone = GHC.Maybe.Nothing}
