module Stripe.CustomerSession.Types.PaymentIntentNextAction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action
instance Show Payment_intent_next_action
instance Eq Payment_intent_next_action
instance Data.Aeson.FromJSON Payment_intent_next_action
instance Data.Aeson.ToJSON Payment_intent_next_action
