module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordCashapp where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_cashapp
instance Show Payment_method_details_payment_record_cashapp
instance Eq Payment_method_details_payment_record_cashapp
instance Data.Aeson.FromJSON Payment_method_details_payment_record_cashapp
instance Data.Aeson.ToJSON Payment_method_details_payment_record_cashapp
