module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordMobilepay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_mobilepay
instance Show Payment_method_details_payment_record_mobilepay
instance Eq Payment_method_details_payment_record_mobilepay
instance Data.Aeson.FromJSON Payment_method_details_payment_record_mobilepay
instance Data.Aeson.ToJSON Payment_method_details_payment_record_mobilepay
data Payment_method_details_payment_record_mobilepayCard
instance Show Payment_method_details_payment_record_mobilepayCard
instance Eq Payment_method_details_payment_record_mobilepayCard
instance Data.Aeson.FromJSON Payment_method_details_payment_record_mobilepayCard
instance Data.Aeson.ToJSON Payment_method_details_payment_record_mobilepayCard
