module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordOxxo where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_oxxo
instance Show Payment_method_details_payment_record_oxxo
instance Eq Payment_method_details_payment_record_oxxo
instance Data.Aeson.FromJSON Payment_method_details_payment_record_oxxo
instance Data.Aeson.ToJSON Payment_method_details_payment_record_oxxo
