module Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsCardDetailsApiResourceMulticapture where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_private_payment_methods_card_details_api_resource_multicapture
instance Show Payment_flows_private_payment_methods_card_details_api_resource_multicapture
instance Eq Payment_flows_private_payment_methods_card_details_api_resource_multicapture
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_card_details_api_resource_multicapture
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_card_details_api_resource_multicapture
