module Stripe.CustomerSession.Types.PaymentMethodDetailsSofort where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_sofort
instance Show Payment_method_details_sofort
instance Eq Payment_method_details_sofort
instance Data.Aeson.FromJSON Payment_method_details_sofort
instance Data.Aeson.ToJSON Payment_method_details_sofort
data Payment_method_details_sofortGenerated_sepa_debitVariants
instance Show Payment_method_details_sofortGenerated_sepa_debitVariants
instance Eq Payment_method_details_sofortGenerated_sepa_debitVariants
instance Data.Aeson.FromJSON Payment_method_details_sofortGenerated_sepa_debitVariants
instance Data.Aeson.ToJSON Payment_method_details_sofortGenerated_sepa_debitVariants
data Payment_method_details_sofortGenerated_sepa_debit_mandateVariants
instance Show Payment_method_details_sofortGenerated_sepa_debit_mandateVariants
instance Eq Payment_method_details_sofortGenerated_sepa_debit_mandateVariants
instance Data.Aeson.FromJSON Payment_method_details_sofortGenerated_sepa_debit_mandateVariants
instance Data.Aeson.ToJSON Payment_method_details_sofortGenerated_sepa_debit_mandateVariants
