module Stripe.CustomerSession.Types.PaymentMethodDetailsCardPresentOffline where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_card_present_offline
instance Show Payment_method_details_card_present_offline
instance Eq Payment_method_details_card_present_offline
instance Data.Aeson.FromJSON Payment_method_details_card_present_offline
instance Data.Aeson.ToJSON Payment_method_details_card_present_offline
