module Stripe.CustomerSession.Types.PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_cashapp_handle_redirect_or_display_qr_code
instance Show Payment_intent_next_action_cashapp_handle_redirect_or_display_qr_code
instance Eq Payment_intent_next_action_cashapp_handle_redirect_or_display_qr_code
instance Data.Aeson.FromJSON Payment_intent_next_action_cashapp_handle_redirect_or_display_qr_code
instance Data.Aeson.ToJSON Payment_intent_next_action_cashapp_handle_redirect_or_display_qr_code
