module Stripe.CustomerSession.Types.PaymentFlowsPaymentIntentAsyncWorkflowsResourceInputs where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_payment_intent_async_workflows_resource_inputs
instance Show Payment_flows_payment_intent_async_workflows_resource_inputs
instance Eq Payment_flows_payment_intent_async_workflows_resource_inputs
instance Data.Aeson.FromJSON Payment_flows_payment_intent_async_workflows_resource_inputs
instance Data.Aeson.ToJSON Payment_flows_payment_intent_async_workflows_resource_inputs
