module Stripe.CustomerSession.Types.PaymentMethodDetailsPaymentRecordPaynow where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_payment_record_paynow
instance Show Payment_method_details_payment_record_paynow
instance Eq Payment_method_details_payment_record_paynow
instance Data.Aeson.FromJSON Payment_method_details_payment_record_paynow
instance Data.Aeson.ToJSON Payment_method_details_payment_record_paynow
