module Stripe.CustomerSession.Types.PaymentIntentNextActionKonbiniStores where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_konbini_stores
instance Show Payment_intent_next_action_konbini_stores
instance Eq Payment_intent_next_action_konbini_stores
instance Data.Aeson.FromJSON Payment_intent_next_action_konbini_stores
instance Data.Aeson.ToJSON Payment_intent_next_action_konbini_stores
data Payment_intent_next_action_konbini_storesFamilymart
instance Show Payment_intent_next_action_konbini_storesFamilymart
instance Eq Payment_intent_next_action_konbini_storesFamilymart
instance Data.Aeson.FromJSON Payment_intent_next_action_konbini_storesFamilymart
instance Data.Aeson.ToJSON Payment_intent_next_action_konbini_storesFamilymart
data Payment_intent_next_action_konbini_storesLawson
instance Show Payment_intent_next_action_konbini_storesLawson
instance Eq Payment_intent_next_action_konbini_storesLawson
instance Data.Aeson.FromJSON Payment_intent_next_action_konbini_storesLawson
instance Data.Aeson.ToJSON Payment_intent_next_action_konbini_storesLawson
data Payment_intent_next_action_konbini_storesMinistop
instance Show Payment_intent_next_action_konbini_storesMinistop
instance Eq Payment_intent_next_action_konbini_storesMinistop
instance Data.Aeson.FromJSON Payment_intent_next_action_konbini_storesMinistop
instance Data.Aeson.ToJSON Payment_intent_next_action_konbini_storesMinistop
data Payment_intent_next_action_konbini_storesSeicomart
instance Show Payment_intent_next_action_konbini_storesSeicomart
instance Eq Payment_intent_next_action_konbini_storesSeicomart
instance Data.Aeson.FromJSON Payment_intent_next_action_konbini_storesSeicomart
instance Data.Aeson.ToJSON Payment_intent_next_action_konbini_storesSeicomart
