module Stripe.CustomerSession.Types.PaymentMethodDetailsKlarna where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_klarna
instance Show Payment_method_details_klarna
instance Eq Payment_method_details_klarna
instance Data.Aeson.FromJSON Payment_method_details_klarna
instance Data.Aeson.ToJSON Payment_method_details_klarna
data Payment_method_details_klarnaPayer_details
instance Show Payment_method_details_klarnaPayer_details
instance Eq Payment_method_details_klarnaPayer_details
instance Data.Aeson.FromJSON Payment_method_details_klarnaPayer_details
instance Data.Aeson.ToJSON Payment_method_details_klarnaPayer_details
data Payment_method_details_klarnaPayer_detailsAddress
instance Show Payment_method_details_klarnaPayer_detailsAddress
instance Eq Payment_method_details_klarnaPayer_detailsAddress
instance Data.Aeson.FromJSON Payment_method_details_klarnaPayer_detailsAddress
instance Data.Aeson.ToJSON Payment_method_details_klarnaPayer_detailsAddress
