module Stripe.CustomerSession.Types.PaymentMethodDetailsPaypal where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_paypal
instance Show Payment_method_details_paypal
instance Eq Payment_method_details_paypal
instance Data.Aeson.FromJSON Payment_method_details_paypal
instance Data.Aeson.ToJSON Payment_method_details_paypal
data Payment_method_details_paypalSeller_protection
instance Show Payment_method_details_paypalSeller_protection
instance Eq Payment_method_details_paypalSeller_protection
instance Data.Aeson.FromJSON Payment_method_details_paypalSeller_protection
instance Data.Aeson.ToJSON Payment_method_details_paypalSeller_protection
