module Stripe.CustomerSession.Types.PaymentMethodDetailsKakaoPay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details_kakao_pay
instance Show Payment_method_details_kakao_pay
instance Eq Payment_method_details_kakao_pay
instance Data.Aeson.FromJSON Payment_method_details_kakao_pay
instance Data.Aeson.ToJSON Payment_method_details_kakao_pay
