module Stripe.CustomerSession.Types.PaymentMethodKlarna where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_klarna
instance Show Payment_method_klarna
instance Eq Payment_method_klarna
instance Data.Aeson.FromJSON Payment_method_klarna
instance Data.Aeson.ToJSON Payment_method_klarna
data Payment_method_klarnaDob
instance Show Payment_method_klarnaDob
instance Eq Payment_method_klarnaDob
instance Data.Aeson.FromJSON Payment_method_klarnaDob
instance Data.Aeson.ToJSON Payment_method_klarnaDob
