module Stripe.CustomerSession.Types.PaymentIntentNextActionBoleto where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_next_action_boleto
instance Show Payment_intent_next_action_boleto
instance Eq Payment_intent_next_action_boleto
instance Data.Aeson.FromJSON Payment_intent_next_action_boleto
instance Data.Aeson.ToJSON Payment_intent_next_action_boleto
