module Stripe.CustomerSession.Types.PaymentIntentTypeSpecificPaymentMethodOptionsClient where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_type_specific_payment_method_options_client
instance Show Payment_intent_type_specific_payment_method_options_client
instance Eq Payment_intent_type_specific_payment_method_options_client
instance Data.Aeson.FromJSON Payment_intent_type_specific_payment_method_options_client
instance Data.Aeson.ToJSON Payment_intent_type_specific_payment_method_options_client
