module Stripe.CustomerSession.Types.PaymentFlowsAmountDetailsResourceError where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_amount_details_resource_error
instance Show Payment_flows_amount_details_resource_error
instance Eq Payment_flows_amount_details_resource_error
instance Data.Aeson.FromJSON Payment_flows_amount_details_resource_error
instance Data.Aeson.ToJSON Payment_flows_amount_details_resource_error
