module Stripe.CustomerSession.Types.PaymentFlowsPrivatePaymentMethodsAlipayDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_private_payment_methods_alipay_details
instance Show Payment_flows_private_payment_methods_alipay_details
instance Eq Payment_flows_private_payment_methods_alipay_details
instance Data.Aeson.FromJSON Payment_flows_private_payment_methods_alipay_details
instance Data.Aeson.ToJSON Payment_flows_private_payment_methods_alipay_details
