module Stripe.CustomerSession.Types.PaymentMethodSofort where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_sofort
instance Show Payment_method_sofort
instance Eq Payment_method_sofort
instance Data.Aeson.FromJSON Payment_method_sofort
instance Data.Aeson.ToJSON Payment_method_sofort
