module Stripe.CustomerSession.Types.PaymentFlowsAutomaticPaymentMethodsPaymentIntent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_flows_automatic_payment_methods_payment_intent
instance Show Payment_flows_automatic_payment_methods_payment_intent
instance Eq Payment_flows_automatic_payment_methods_payment_intent
instance Data.Aeson.FromJSON Payment_flows_automatic_payment_methods_payment_intent
instance Data.Aeson.ToJSON Payment_flows_automatic_payment_methods_payment_intent
