module Stripe.CustomerSession.Types.PaymentIntentPaymentMethodOptionsMobilepay where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_intent_payment_method_options_mobilepay
instance Show Payment_intent_payment_method_options_mobilepay
instance Eq Payment_intent_payment_method_options_mobilepay
instance Data.Aeson.FromJSON Payment_intent_payment_method_options_mobilepay
instance Data.Aeson.ToJSON Payment_intent_payment_method_options_mobilepay
