module Stripe.CustomerSession.Types.PaymentMethodDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Payment_method_details
instance Show Payment_method_details
instance Eq Payment_method_details
instance Data.Aeson.FromJSON Payment_method_details
instance Data.Aeson.ToJSON Payment_method_details
