module Stripe.CustomerSession.Types.Person where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Person
instance Show Person
instance Eq Person
instance Data.Aeson.FromJSON Person
instance Data.Aeson.ToJSON Person
data PersonAddress_kana
instance Show PersonAddress_kana
instance Eq PersonAddress_kana
instance Data.Aeson.FromJSON PersonAddress_kana
instance Data.Aeson.ToJSON PersonAddress_kana
data PersonAddress_kanji
instance Show PersonAddress_kanji
instance Eq PersonAddress_kanji
instance Data.Aeson.FromJSON PersonAddress_kanji
instance Data.Aeson.ToJSON PersonAddress_kanji
data PersonFuture_requirements
instance Show PersonFuture_requirements
instance Eq PersonFuture_requirements
instance Data.Aeson.FromJSON PersonFuture_requirements
instance Data.Aeson.ToJSON PersonFuture_requirements
data PersonRequirements
instance Show PersonRequirements
instance Eq PersonRequirements
instance Data.Aeson.FromJSON PersonRequirements
instance Data.Aeson.ToJSON PersonRequirements
data PersonUs_cfpb_data
instance Show PersonUs_cfpb_data
instance Eq PersonUs_cfpb_data
instance Data.Aeson.FromJSON PersonUs_cfpb_data
instance Data.Aeson.ToJSON PersonUs_cfpb_data
data PersonUs_cfpb_dataEthnicity_details
instance Show PersonUs_cfpb_dataEthnicity_details
instance Eq PersonUs_cfpb_dataEthnicity_details
instance Data.Aeson.FromJSON PersonUs_cfpb_dataEthnicity_details
instance Data.Aeson.ToJSON PersonUs_cfpb_dataEthnicity_details
data PersonUs_cfpb_dataRace_details
instance Show PersonUs_cfpb_dataRace_details
instance Eq PersonUs_cfpb_dataRace_details
instance Data.Aeson.FromJSON PersonUs_cfpb_dataRace_details
instance Data.Aeson.ToJSON PersonUs_cfpb_dataRace_details
