module Stripe.CustomerSession.Types.PersonAdditionalTosAcceptances where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Person_additional_tos_acceptances
instance Show Person_additional_tos_acceptances
instance Eq Person_additional_tos_acceptances
instance Data.Aeson.FromJSON Person_additional_tos_acceptances
instance Data.Aeson.ToJSON Person_additional_tos_acceptances
data Person_additional_tos_acceptancesAccount
instance Show Person_additional_tos_acceptancesAccount
instance Eq Person_additional_tos_acceptancesAccount
instance Data.Aeson.FromJSON Person_additional_tos_acceptancesAccount
instance Data.Aeson.ToJSON Person_additional_tos_acceptancesAccount
