module Stripe.CustomerSession.Types.PersonUsCfpbData where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Person_us_cfpb_data
instance Show Person_us_cfpb_data
instance Eq Person_us_cfpb_data
instance Data.Aeson.FromJSON Person_us_cfpb_data
instance Data.Aeson.ToJSON Person_us_cfpb_data
data Person_us_cfpb_dataEthnicity_details
instance Show Person_us_cfpb_dataEthnicity_details
instance Eq Person_us_cfpb_dataEthnicity_details
instance Data.Aeson.FromJSON Person_us_cfpb_dataEthnicity_details
instance Data.Aeson.ToJSON Person_us_cfpb_dataEthnicity_details
data Person_us_cfpb_dataRace_details
instance Show Person_us_cfpb_dataRace_details
instance Eq Person_us_cfpb_dataRace_details
instance Data.Aeson.FromJSON Person_us_cfpb_dataRace_details
instance Data.Aeson.ToJSON Person_us_cfpb_dataRace_details
