module Stripe.CustomerSession.Types.Product where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Product
instance Show Product
instance Eq Product
instance Data.Aeson.FromJSON Product
instance Data.Aeson.ToJSON Product
data ProductDefault_priceVariants
instance Show ProductDefault_priceVariants
instance Eq ProductDefault_priceVariants
instance Data.Aeson.FromJSON ProductDefault_priceVariants
instance Data.Aeson.ToJSON ProductDefault_priceVariants
data ProductPackage_dimensions
instance Show ProductPackage_dimensions
instance Eq ProductPackage_dimensions
instance Data.Aeson.FromJSON ProductPackage_dimensions
instance Data.Aeson.ToJSON ProductPackage_dimensions
data ProductTax_codeVariants
instance Show ProductTax_codeVariants
instance Eq ProductTax_codeVariants
instance Data.Aeson.FromJSON ProductTax_codeVariants
instance Data.Aeson.ToJSON ProductTax_codeVariants
