module Stripe.CustomerSession.Types.RevolutPayUnderlyingPaymentMethodFundingDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Revolut_pay_underlying_payment_method_funding_details
instance Show Revolut_pay_underlying_payment_method_funding_details
instance Eq Revolut_pay_underlying_payment_method_funding_details
instance Data.Aeson.FromJSON Revolut_pay_underlying_payment_method_funding_details
instance Data.Aeson.ToJSON Revolut_pay_underlying_payment_method_funding_details
