module Stripe.CustomerSession.Types.SchedulesPhaseAutomaticTax where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Schedules_phase_automatic_tax
instance Show Schedules_phase_automatic_tax
instance Eq Schedules_phase_automatic_tax
instance Data.Aeson.FromJSON Schedules_phase_automatic_tax
instance Data.Aeson.ToJSON Schedules_phase_automatic_tax
data Schedules_phase_automatic_taxLiability
instance Show Schedules_phase_automatic_taxLiability
instance Eq Schedules_phase_automatic_taxLiability
instance Data.Aeson.FromJSON Schedules_phase_automatic_taxLiability
instance Data.Aeson.ToJSON Schedules_phase_automatic_taxLiability
data Schedules_phase_automatic_taxLiabilityAccountVariants
instance Show Schedules_phase_automatic_taxLiabilityAccountVariants
instance Eq Schedules_phase_automatic_taxLiabilityAccountVariants
instance Data.Aeson.FromJSON Schedules_phase_automatic_taxLiabilityAccountVariants
instance Data.Aeson.ToJSON Schedules_phase_automatic_taxLiabilityAccountVariants
