module Stripe.CustomerSession.Types.SepaDebitGeneratedFrom where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Sepa_debit_generated_from
instance Show Sepa_debit_generated_from
instance Eq Sepa_debit_generated_from
instance Data.Aeson.FromJSON Sepa_debit_generated_from
instance Data.Aeson.ToJSON Sepa_debit_generated_from
data Sepa_debit_generated_fromChargeVariants
instance Show Sepa_debit_generated_fromChargeVariants
instance Eq Sepa_debit_generated_fromChargeVariants
instance Data.Aeson.FromJSON Sepa_debit_generated_fromChargeVariants
instance Data.Aeson.ToJSON Sepa_debit_generated_fromChargeVariants
data Sepa_debit_generated_fromSetup_attemptVariants
instance Show Sepa_debit_generated_fromSetup_attemptVariants
instance Eq Sepa_debit_generated_fromSetup_attemptVariants
instance Data.Aeson.FromJSON Sepa_debit_generated_fromSetup_attemptVariants
instance Data.Aeson.ToJSON Sepa_debit_generated_fromSetup_attemptVariants
