module Stripe.CustomerSession.Types.SetupIntentNextAction where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_next_action
instance Show Setup_intent_next_action
instance Eq Setup_intent_next_action
instance Data.Aeson.FromJSON Setup_intent_next_action
instance Data.Aeson.ToJSON Setup_intent_next_action
