module Stripe.CustomerSession.Types.SetupAttemptPaymentMethodDetailsSofort where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_attempt_payment_method_details_sofort
instance Show Setup_attempt_payment_method_details_sofort
instance Eq Setup_attempt_payment_method_details_sofort
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_sofort
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_sofort
data Setup_attempt_payment_method_details_sofortGenerated_sepa_debitVariants
instance Show Setup_attempt_payment_method_details_sofortGenerated_sepa_debitVariants
instance Eq Setup_attempt_payment_method_details_sofortGenerated_sepa_debitVariants
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_sofortGenerated_sepa_debitVariants
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_sofortGenerated_sepa_debitVariants
data Setup_attempt_payment_method_details_sofortGenerated_sepa_debit_mandateVariants
instance Show Setup_attempt_payment_method_details_sofortGenerated_sepa_debit_mandateVariants
instance Eq Setup_attempt_payment_method_details_sofortGenerated_sepa_debit_mandateVariants
instance Data.Aeson.FromJSON Setup_attempt_payment_method_details_sofortGenerated_sepa_debit_mandateVariants
instance Data.Aeson.ToJSON Setup_attempt_payment_method_details_sofortGenerated_sepa_debit_mandateVariants
