module Stripe.CustomerSession.Types.SetupIntentPaymentMethodOptionsUsBankAccount where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_payment_method_options_us_bank_account
instance Show Setup_intent_payment_method_options_us_bank_account
instance Eq Setup_intent_payment_method_options_us_bank_account
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_us_bank_account
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_us_bank_account
