module Stripe.CustomerSession.Types.SetupIntentPaymentMethodOptionsCard where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_payment_method_options_card
instance Show Setup_intent_payment_method_options_card
instance Eq Setup_intent_payment_method_options_card
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_card
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_card
data Setup_intent_payment_method_options_cardMandate_options
instance Show Setup_intent_payment_method_options_cardMandate_options
instance Eq Setup_intent_payment_method_options_cardMandate_options
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_cardMandate_options
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_cardMandate_options
