module Stripe.CustomerSession.Types.SetupIntentPaymentMethodOptionsPaypal where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Setup_intent_payment_method_options_paypal
instance Show Setup_intent_payment_method_options_paypal
instance Eq Setup_intent_payment_method_options_paypal
instance Data.Aeson.FromJSON Setup_intent_payment_method_options_paypal
instance Data.Aeson.ToJSON Setup_intent_payment_method_options_paypal
