module Stripe.CustomerSession.Types.ShippingRateDeliveryEstimate where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Shipping_rate_delivery_estimate
instance Show Shipping_rate_delivery_estimate
instance Eq Shipping_rate_delivery_estimate
instance Data.Aeson.FromJSON Shipping_rate_delivery_estimate
instance Data.Aeson.ToJSON Shipping_rate_delivery_estimate
data Shipping_rate_delivery_estimateMaximum
instance Show Shipping_rate_delivery_estimateMaximum
instance Eq Shipping_rate_delivery_estimateMaximum
instance Data.Aeson.FromJSON Shipping_rate_delivery_estimateMaximum
instance Data.Aeson.ToJSON Shipping_rate_delivery_estimateMaximum
data Shipping_rate_delivery_estimateMinimum
instance Show Shipping_rate_delivery_estimateMinimum
instance Eq Shipping_rate_delivery_estimateMinimum
instance Data.Aeson.FromJSON Shipping_rate_delivery_estimateMinimum
instance Data.Aeson.ToJSON Shipping_rate_delivery_estimateMinimum
