module Stripe.CustomerSession.Types.SourceTypeSepaDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Source_type_sepa_debit
instance Show Source_type_sepa_debit
instance Eq Source_type_sepa_debit
instance Data.Aeson.FromJSON Source_type_sepa_debit
instance Data.Aeson.ToJSON Source_type_sepa_debit
