module Stripe.CustomerSession.Types.SourceOwner where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Source_owner
instance Show Source_owner
instance Eq Source_owner
instance Data.Aeson.FromJSON Source_owner
instance Data.Aeson.ToJSON Source_owner
data Source_ownerAddress
instance Show Source_ownerAddress
instance Eq Source_ownerAddress
instance Data.Aeson.FromJSON Source_ownerAddress
instance Data.Aeson.ToJSON Source_ownerAddress
data Source_ownerVerified_address
instance Show Source_ownerVerified_address
instance Eq Source_ownerVerified_address
instance Data.Aeson.FromJSON Source_ownerVerified_address
instance Data.Aeson.ToJSON Source_ownerVerified_address
