module Stripe.CustomerSession.Types.SourceTypeAuBecsDebit where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Source_type_au_becs_debit
instance Show Source_type_au_becs_debit
instance Eq Source_type_au_becs_debit
instance Data.Aeson.FromJSON Source_type_au_becs_debit
instance Data.Aeson.ToJSON Source_type_au_becs_debit
