module Stripe.CustomerSession.Types.SourceTypeCardPresent where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Source_type_card_present
instance Show Source_type_card_present
instance Eq Source_type_card_present
instance Data.Aeson.FromJSON Source_type_card_present
instance Data.Aeson.ToJSON Source_type_card_present
