module Stripe.CustomerSession.Types.SourceTypeBancontact where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Source_type_bancontact
instance Show Source_type_bancontact
instance Eq Source_type_bancontact
instance Data.Aeson.FromJSON Source_type_bancontact
instance Data.Aeson.ToJSON Source_type_bancontact
