module Stripe.CustomerSession.Types.StackableDiscountWithDiscountSettingsAndDiscountEnd where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Stackable_discount_with_discount_settings_and_discount_end
instance Show Stackable_discount_with_discount_settings_and_discount_end
instance Eq Stackable_discount_with_discount_settings_and_discount_end
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settings_and_discount_end
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settings_and_discount_end
data Stackable_discount_with_discount_settings_and_discount_endCouponVariants
instance Show Stackable_discount_with_discount_settings_and_discount_endCouponVariants
instance Eq Stackable_discount_with_discount_settings_and_discount_endCouponVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settings_and_discount_endCouponVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settings_and_discount_endCouponVariants
data Stackable_discount_with_discount_settings_and_discount_endDiscountVariants
instance Show Stackable_discount_with_discount_settings_and_discount_endDiscountVariants
instance Eq Stackable_discount_with_discount_settings_and_discount_endDiscountVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settings_and_discount_endDiscountVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settings_and_discount_endDiscountVariants
data Stackable_discount_with_discount_settings_and_discount_endPromotion_codeVariants
instance Show Stackable_discount_with_discount_settings_and_discount_endPromotion_codeVariants
instance Eq Stackable_discount_with_discount_settings_and_discount_endPromotion_codeVariants
instance Data.Aeson.FromJSON Stackable_discount_with_discount_settings_and_discount_endPromotion_codeVariants
instance Data.Aeson.ToJSON Stackable_discount_with_discount_settings_and_discount_endPromotion_codeVariants
