module Stripe.CustomerSession.Types.SubscriptionsResourceSubscriptionPresentmentDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscriptions_resource_subscription_presentment_details
instance Show Subscriptions_resource_subscription_presentment_details
instance Eq Subscriptions_resource_subscription_presentment_details
instance Data.Aeson.FromJSON Subscriptions_resource_subscription_presentment_details
instance Data.Aeson.ToJSON Subscriptions_resource_subscription_presentment_details
