module Stripe.CustomerSession.Types.SubscriptionAutomaticTax where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_automatic_tax
instance Show Subscription_automatic_tax
instance Eq Subscription_automatic_tax
instance Data.Aeson.FromJSON Subscription_automatic_tax
instance Data.Aeson.ToJSON Subscription_automatic_tax
data Subscription_automatic_taxLiability
instance Show Subscription_automatic_taxLiability
instance Eq Subscription_automatic_taxLiability
instance Data.Aeson.FromJSON Subscription_automatic_taxLiability
instance Data.Aeson.ToJSON Subscription_automatic_taxLiability
data Subscription_automatic_taxLiabilityAccountVariants
instance Show Subscription_automatic_taxLiabilityAccountVariants
instance Eq Subscription_automatic_taxLiabilityAccountVariants
instance Data.Aeson.FromJSON Subscription_automatic_taxLiabilityAccountVariants
instance Data.Aeson.ToJSON Subscription_automatic_taxLiabilityAccountVariants
