module Stripe.CustomerSession.Types.SubscriptionScheduleConfigurationItem where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_schedule_configuration_item
instance Show Subscription_schedule_configuration_item
instance Eq Subscription_schedule_configuration_item
instance Data.Aeson.FromJSON Subscription_schedule_configuration_item
instance Data.Aeson.ToJSON Subscription_schedule_configuration_item
data Subscription_schedule_configuration_itemBilling_thresholds
instance Show Subscription_schedule_configuration_itemBilling_thresholds
instance Eq Subscription_schedule_configuration_itemBilling_thresholds
instance Data.Aeson.FromJSON Subscription_schedule_configuration_itemBilling_thresholds
instance Data.Aeson.ToJSON Subscription_schedule_configuration_itemBilling_thresholds
data Subscription_schedule_configuration_itemPriceVariants
instance Show Subscription_schedule_configuration_itemPriceVariants
instance Eq Subscription_schedule_configuration_itemPriceVariants
instance Data.Aeson.FromJSON Subscription_schedule_configuration_itemPriceVariants
instance Data.Aeson.ToJSON Subscription_schedule_configuration_itemPriceVariants
