module Stripe.CustomerSession.Types.SubscriptionPaymentMethodOptionsCard where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_payment_method_options_card
instance Show Subscription_payment_method_options_card
instance Eq Subscription_payment_method_options_card
instance Data.Aeson.FromJSON Subscription_payment_method_options_card
instance Data.Aeson.ToJSON Subscription_payment_method_options_card
