module Stripe.CustomerSession.Types.SubscriptionsResourceTrialSettingsTrialSettings where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscriptions_resource_trial_settings_trial_settings
instance Show Subscriptions_resource_trial_settings_trial_settings
instance Eq Subscriptions_resource_trial_settings_trial_settings
instance Data.Aeson.FromJSON Subscriptions_resource_trial_settings_trial_settings
instance Data.Aeson.ToJSON Subscriptions_resource_trial_settings_trial_settings
