module Stripe.CustomerSession.Types.SubscriptionsResourceTrialSettingsEndBehavior where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscriptions_resource_trial_settings_end_behavior
instance Show Subscriptions_resource_trial_settings_end_behavior
instance Eq Subscriptions_resource_trial_settings_end_behavior
instance Data.Aeson.FromJSON Subscriptions_resource_trial_settings_end_behavior
instance Data.Aeson.ToJSON Subscriptions_resource_trial_settings_end_behavior
