module Stripe.CustomerSession.Types.SubscriptionScheduleAddInvoiceItem where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_schedule_add_invoice_item
instance Show Subscription_schedule_add_invoice_item
instance Eq Subscription_schedule_add_invoice_item
instance Data.Aeson.FromJSON Subscription_schedule_add_invoice_item
instance Data.Aeson.ToJSON Subscription_schedule_add_invoice_item
data Subscription_schedule_add_invoice_itemPriceVariants
instance Show Subscription_schedule_add_invoice_itemPriceVariants
instance Eq Subscription_schedule_add_invoice_itemPriceVariants
instance Data.Aeson.FromJSON Subscription_schedule_add_invoice_itemPriceVariants
instance Data.Aeson.ToJSON Subscription_schedule_add_invoice_itemPriceVariants
