module Stripe.CustomerSession.Types.SubscriptionSchedulesResourceInvoiceItemPeriodResourcePeriodEnd where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_schedules_resource_invoice_item_period_resource_period_end
instance Show Subscription_schedules_resource_invoice_item_period_resource_period_end
instance Eq Subscription_schedules_resource_invoice_item_period_resource_period_end
instance Data.Aeson.FromJSON Subscription_schedules_resource_invoice_item_period_resource_period_end
instance Data.Aeson.ToJSON Subscription_schedules_resource_invoice_item_period_resource_period_end
