module Stripe.CustomerSession.Types.SubscriptionSchedulePhaseConfiguration where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Subscription_schedule_phase_configuration
instance Show Subscription_schedule_phase_configuration
instance Eq Subscription_schedule_phase_configuration
instance Data.Aeson.FromJSON Subscription_schedule_phase_configuration
instance Data.Aeson.ToJSON Subscription_schedule_phase_configuration
data Subscription_schedule_phase_configurationBilling_thresholds
instance Show Subscription_schedule_phase_configurationBilling_thresholds
instance Eq Subscription_schedule_phase_configurationBilling_thresholds
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationBilling_thresholds
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationBilling_thresholds
data Subscription_schedule_phase_configurationDefault_payment_methodVariants
instance Show Subscription_schedule_phase_configurationDefault_payment_methodVariants
instance Eq Subscription_schedule_phase_configurationDefault_payment_methodVariants
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationDefault_payment_methodVariants
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationDefault_payment_methodVariants
data Subscription_schedule_phase_configurationInvoice_settings
instance Show Subscription_schedule_phase_configurationInvoice_settings
instance Eq Subscription_schedule_phase_configurationInvoice_settings
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationInvoice_settings
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationInvoice_settings
data Subscription_schedule_phase_configurationInvoice_settingsAccount_tax_idsVariants
instance Show Subscription_schedule_phase_configurationInvoice_settingsAccount_tax_idsVariants
instance Eq Subscription_schedule_phase_configurationInvoice_settingsAccount_tax_idsVariants
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationInvoice_settingsAccount_tax_idsVariants
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationInvoice_settingsAccount_tax_idsVariants
data Subscription_schedule_phase_configurationInvoice_settingsIssuer
instance Show Subscription_schedule_phase_configurationInvoice_settingsIssuer
instance Eq Subscription_schedule_phase_configurationInvoice_settingsIssuer
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationInvoice_settingsIssuer
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationInvoice_settingsIssuer
data Subscription_schedule_phase_configurationInvoice_settingsIssuerAccountVariants
instance Show Subscription_schedule_phase_configurationInvoice_settingsIssuerAccountVariants
instance Eq Subscription_schedule_phase_configurationInvoice_settingsIssuerAccountVariants
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationInvoice_settingsIssuerAccountVariants
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationInvoice_settingsIssuerAccountVariants
data Subscription_schedule_phase_configurationOn_behalf_ofVariants
instance Show Subscription_schedule_phase_configurationOn_behalf_ofVariants
instance Eq Subscription_schedule_phase_configurationOn_behalf_ofVariants
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationOn_behalf_ofVariants
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationOn_behalf_ofVariants
data Subscription_schedule_phase_configurationTransfer_data
instance Show Subscription_schedule_phase_configurationTransfer_data
instance Eq Subscription_schedule_phase_configurationTransfer_data
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationTransfer_data
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationTransfer_data
data Subscription_schedule_phase_configurationTransfer_dataDestinationVariants
instance Show Subscription_schedule_phase_configurationTransfer_dataDestinationVariants
instance Eq Subscription_schedule_phase_configurationTransfer_dataDestinationVariants
instance Data.Aeson.FromJSON Subscription_schedule_phase_configurationTransfer_dataDestinationVariants
instance Data.Aeson.ToJSON Subscription_schedule_phase_configurationTransfer_dataDestinationVariants
