module Stripe.CustomerSession.Types.TaxId where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Tax_id
instance Show Tax_id
instance Eq Tax_id
instance Data.Aeson.FromJSON Tax_id
instance Data.Aeson.ToJSON Tax_id
data Tax_idCustomerVariants
instance Show Tax_idCustomerVariants
instance Eq Tax_idCustomerVariants
instance Data.Aeson.FromJSON Tax_idCustomerVariants
instance Data.Aeson.ToJSON Tax_idCustomerVariants
data Tax_idOwner
instance Show Tax_idOwner
instance Eq Tax_idOwner
instance Data.Aeson.FromJSON Tax_idOwner
instance Data.Aeson.ToJSON Tax_idOwner
data Tax_idOwnerAccountVariants
instance Show Tax_idOwnerAccountVariants
instance Eq Tax_idOwnerAccountVariants
instance Data.Aeson.FromJSON Tax_idOwnerAccountVariants
instance Data.Aeson.ToJSON Tax_idOwnerAccountVariants
data Tax_idOwnerApplicationVariants
instance Show Tax_idOwnerApplicationVariants
instance Eq Tax_idOwnerApplicationVariants
instance Data.Aeson.FromJSON Tax_idOwnerApplicationVariants
instance Data.Aeson.ToJSON Tax_idOwnerApplicationVariants
data Tax_idOwnerCustomerVariants
instance Show Tax_idOwnerCustomerVariants
instance Eq Tax_idOwnerCustomerVariants
instance Data.Aeson.FromJSON Tax_idOwnerCustomerVariants
instance Data.Aeson.ToJSON Tax_idOwnerCustomerVariants
data Tax_idVerification
instance Show Tax_idVerification
instance Eq Tax_idVerification
instance Data.Aeson.FromJSON Tax_idVerification
instance Data.Aeson.ToJSON Tax_idVerification
