module Stripe.CustomerSession.Types.ThreeDSecureDetails where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Three_d_secure_details
instance Show Three_d_secure_details
instance Eq Three_d_secure_details
instance Data.Aeson.FromJSON Three_d_secure_details
instance Data.Aeson.ToJSON Three_d_secure_details
