module Stripe.CustomerSession.Types.Topup where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Topup
instance Show Topup
instance Eq Topup
instance Data.Aeson.FromJSON Topup
instance Data.Aeson.ToJSON Topup
data TopupBalance_transactionVariants
instance Show TopupBalance_transactionVariants
instance Eq TopupBalance_transactionVariants
instance Data.Aeson.FromJSON TopupBalance_transactionVariants
instance Data.Aeson.ToJSON TopupBalance_transactionVariants
data TopupSource
instance Show TopupSource
instance Eq TopupSource
instance Data.Aeson.FromJSON TopupSource
instance Data.Aeson.ToJSON TopupSource
data TopupSourceOwner
instance Show TopupSourceOwner
instance Eq TopupSourceOwner
instance Data.Aeson.FromJSON TopupSourceOwner
instance Data.Aeson.ToJSON TopupSourceOwner
data TopupSourceOwnerAddress
instance Show TopupSourceOwnerAddress
instance Eq TopupSourceOwnerAddress
instance Data.Aeson.FromJSON TopupSourceOwnerAddress
instance Data.Aeson.ToJSON TopupSourceOwnerAddress
data TopupSourceOwnerVerified_address
instance Show TopupSourceOwnerVerified_address
instance Eq TopupSourceOwnerVerified_address
instance Data.Aeson.FromJSON TopupSourceOwnerVerified_address
instance Data.Aeson.ToJSON TopupSourceOwnerVerified_address
