module Stripe.CustomerSession.Types.TransferReversal where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Transfer_reversal
instance Show Transfer_reversal
instance Eq Transfer_reversal
instance Data.Aeson.FromJSON Transfer_reversal
instance Data.Aeson.ToJSON Transfer_reversal
data Transfer_reversalBalance_transactionVariants
instance Show Transfer_reversalBalance_transactionVariants
instance Eq Transfer_reversalBalance_transactionVariants
instance Data.Aeson.FromJSON Transfer_reversalBalance_transactionVariants
instance Data.Aeson.ToJSON Transfer_reversalBalance_transactionVariants
data Transfer_reversalDestination_payment_refundVariants
instance Show Transfer_reversalDestination_payment_refundVariants
instance Eq Transfer_reversalDestination_payment_refundVariants
instance Data.Aeson.FromJSON Transfer_reversalDestination_payment_refundVariants
instance Data.Aeson.ToJSON Transfer_reversalDestination_payment_refundVariants
data Transfer_reversalSource_refundVariants
instance Show Transfer_reversalSource_refundVariants
instance Eq Transfer_reversalSource_refundVariants
instance Data.Aeson.FromJSON Transfer_reversalSource_refundVariants
instance Data.Aeson.ToJSON Transfer_reversalSource_refundVariants
data Transfer_reversalTransferVariants
instance Show Transfer_reversalTransferVariants
instance Eq Transfer_reversalTransferVariants
instance Data.Aeson.FromJSON Transfer_reversalTransferVariants
instance Data.Aeson.ToJSON Transfer_reversalTransferVariants
