module Stripe.CustomerSession.Types.Transfer where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Transfer
instance Show Transfer
instance Eq Transfer
instance Data.Aeson.FromJSON Transfer
instance Data.Aeson.ToJSON Transfer
data TransferBalance_transactionVariants
instance Show TransferBalance_transactionVariants
instance Eq TransferBalance_transactionVariants
instance Data.Aeson.FromJSON TransferBalance_transactionVariants
instance Data.Aeson.ToJSON TransferBalance_transactionVariants
data TransferDestinationVariants
instance Show TransferDestinationVariants
instance Eq TransferDestinationVariants
instance Data.Aeson.FromJSON TransferDestinationVariants
instance Data.Aeson.ToJSON TransferDestinationVariants
data TransferDestination_paymentVariants
instance Show TransferDestination_paymentVariants
instance Eq TransferDestination_paymentVariants
instance Data.Aeson.FromJSON TransferDestination_paymentVariants
instance Data.Aeson.ToJSON TransferDestination_paymentVariants
data TransferReversals
instance Show TransferReversals
instance Eq TransferReversals
instance Data.Aeson.FromJSON TransferReversals
instance Data.Aeson.ToJSON TransferReversals
data TransferSource_transactionVariants
instance Show TransferSource_transactionVariants
instance Eq TransferSource_transactionVariants
instance Data.Aeson.FromJSON TransferSource_transactionVariants
instance Data.Aeson.ToJSON TransferSource_transactionVariants
