module Stripe.CustomerSession.Types.UsBankAccountNetworks where
import qualified Data.Aeson
import qualified Stripe.CustomerSession.Common
data Us_bank_account_networks
instance Show Us_bank_account_networks
instance Eq Us_bank_account_networks
instance Data.Aeson.FromJSON Us_bank_account_networks
instance Data.Aeson.ToJSON Us_bank_account_networks
